### ISSUE TITLE
Support CoreOS Ignition for Flatcar Linux

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#1006]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Tracking issue for FlatCar Linux support

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

cc @dongsupark

**Comment by alexander-demichev** [comment]
Hi, I'm interested in implementing support for ignition files.
