### ISSUE TITLE
Machine stuck in Provisioning state

### ISSUE THREAD

**Issue by Emc1992** [kubernetes-sigs/cluster-api-provider-vsphere#1015]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The 'machine' never completes provisioning and remains in a "Provisioning" state for the master node and worker nodes never provision

`kind create cluster`
`clusterctl init --infrastructure vsphere:v0.7.0`
`clusterctl config cluster vsphere-quickstart \`
`    --infrastructure vsphere \`
`    --kubernetes-version v1.18.2 \`
`    --control-plane-machine-count 1 \`
`    --worker-machine-count 1 > cluster.yaml`
`kubectl apply -f cluster.yaml`
`kubectl get secret/vsphere-quickstart-kubeconfig -o json | jq -r .data.value | base64 --decode > ./vsphere-quickstart.kubeconfig`
`KUBECONFIG=vsphere-quickstart.kubeconfig kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml`
`KUBECONFIG=vsphere-quickstart.kubeconfig kubectl get nodes`
`kubectl get machine `

**What did you expect to happen:**
`kubectl get machine` should not stay in a "provisioning" state once `KUBECONFIG=vsphere-quickstart.kubeconfig kubectl get nodes` is in a "Ready" state 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
No errors in 
`kubectl logs -l control-plane=controller-manager -n capv-system -c manager `
prior to applying cni it states "Waiting for bootstrap data to be available"

clusterctl.yml:
`VSPHERE_USERNAME: "REDACTED"`                    
`VSPHERE_PASSWORD: "REDACTED" `                                

`VSPHERE_SERVER: "172.16.0.110"`
`VSPHERE_DATACENTER: "dc1"`
`VSPHERE_DATASTORE: "terraform-ds"`
`VSPHERE_NETWORK: "VM Network"`
`VSPHERE_RESOURCE_POOL: "Resources"`
`VSPHERE_FOLDER: ""`
`VSPHERE_TEMPLATE: "vm1"`
`CONTROL_PLANE_ENDPOINT_IP: "172.17.0.10"`
`EXP_CLUSTER_RESOURCE_SET: "true"`
`VSPHERE_SSH_AUTHORIZED_KEY: "REDACTED"`

**Environment:**

- Cluster-api-provider-vsphere version: v0.3.8 (clusterctl) v0.7.0 (CAPV)
- Kubernetes version: (use `kubectl version`): v1.18.2
- OS (e.g. from `/etc/os-release`): http://storage.googleapis.com/capv-images/release/v1.18.2/photon-3-kube-v1.18.2.ova as per https://github.com/kubernetes-sigs/cluster-api-provider-vsphere

**Comment by ncdc** [comment]
@Emc1992 could you please provide the core cluster-api logs? `kubectl -n capi-system logs deploy/capi-controller-manager`? This is what's responsible for changing the machine's state.

**Comment by Emc1992** [comment]
`kubectl get machines -w`:
`vsphere-quickstart-4cf8c                  vsphere://REDACTED   Provisioning`
`vsphere-quickstart-md-0-b8578fbf5-7sk24                Pending`
`vsphere-quickstart-md-0-b8578fbf5-s57t6                Pending`
`vsphere-quickstart-md-0-b8578fbf5-wgsbj                Pending`

` KUBECONFIG=vsphere-quickstart.kubeconfig kubectl get nodes`:
`vsphere-quickstart-4cf8c   Ready    master   8m8s   v1.18.2`

`kubectl -n capi-system logs deploy/capi-controller-manager`:
`I0824 16:19:48.205996       1 machine_controller_noderef.go:52] controllers/Machine "msg"="Machine doesn't have a valid ProviderID yet" "cluster"="vsphere-quickstart" "machine"="vsphere-quickstart-md-0-b8578fbf5-7sk24" "namespace"="default" 
E0824 16:19:48.206071       1 machine_controller.go:249] controllers/Machine "msg"="Reconciliation for Machine asked to requeue" "error"="Bootstrap provider for Machine \"vsphere-quickstart-md-0-b8578fbf5-7sk24\" in namespace \"default\" is not ready, requeuing: requeue in 30s" "cluster"="vsphere-quickstart" "machine"="vsphere-quickstart-md-0-b8578fbf5-7sk24" "namespace"="default" `

**Comment by ncdc** [comment]
If possible, could you please create gists of the full capi & kcp logs?

**Comment by Emc1992** [comment]
https://gist.github.com/Emc1992/6e86da7403dab4b973d80d87ab9c7388 <- is that ok?

**Comment by fabriziopandini** [comment]
might be this is related to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1011
@Emc1992 could you kindly test with vSphere provider v0.7.1?

**Comment by Emc1992** [comment]
> might be this is related to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1011
> @Emc1992 could you kindly test with vSphere provider v0.7.1?

Sure, give me 5

**Comment by Emc1992** [comment]
> > might be this is related to #1011
> > @Emc1992 could you kindly test with vSphere provider v0.7.1?
> 
> Sure, give me 5

Same errors unfortunately - will keep digging

**Comment by Emc1992** [comment]
Still digging but found this in capi-kubeadm-control-plane-system:

E0824 17:00:01.679395       1 controller.go:206] controllers/KubeadmControlPlane "msg"="Failed to patch KubeadmControlPlane" "error"="error patching conditions: The condition \"Ready\" was modified by a different process and this caused a merge/AddCondition conflict:   \u0026v1alpha3.Condition{\n  \tType:               \"Ready\",\n  \tStatus:             \"False\",\n  \tSeverity:           \"Info\",\n- \tLastTransitionTime: v1.Time{Time: s\"2020-08-24 16:59:53 +0000 UTC\"},\n+ \tLastTransitionTime: v1.Time{Time: s\"2020-08-24 16:59:59 +0000 UTC\"},\n- \tReason:             \"WaitingForKubeadmInit\",\n+ \tReason:             \"Cloning@Machine/vsphere-quickstart-fqgpb\",\n- \tMessage:            \"\",\n+ \tMessage:            \"0 of 1 completed\",\n  }\n" "cluster"="vsphere-quickstart" "kubeadmControlPlane"="vsphere-quickstart" "namespace"="default" 
E0824 17:00:01.679645       1 controller.go:248] controller-runtime/controller "msg"="Reconciler error" "error"="error patching conditions: **The condition \"Ready\" was modified by a different process and this caused a merge/AddCondition conflict:**   \u0026v1alpha3.Condition{\n  \tType:               \"Ready\",\n  \tStatus:             \"False\",\n  \tSeverity:           \"Info\",\n- \tLastTransitionTime: v1.Time{Time: s\"2020-08-24 16:59:53 +0000 UTC\"},\n+ \tLastTransitionTime: v1.Time{Time: s\"2020-08-24 16:59:59 +0000 UTC\"},\n- \tReason:             \"WaitingForKubeadmInit\",\n+ \tReason:             \"Cloning@Machine/vsphere-quickstart-fqgpb\",\n- \tMessage:            \"\",\n+ \tMessage:            \"0 of 1 completed\",\n  }\n" "controller"="kubeadmcontrolplane" "name"="vsphere-quickstart" "namespace"="default"

**Comment by ncdc** [comment]
Are you able to provide the complete log files (no grepping) for capi, kcp, and capv?

**Comment by Emc1992** [comment]
> Are you able to provide the complete log files (no grepping) for capi, kcp, and capv?

I don't believe I was grepping, iirc that was pretty much it but I'll recheck tomorrow

**Comment by ncdc** [comment]
Thanks (I would expect more than 10 lines per log)

**Comment by Emc1992** [comment]
> Thanks (I would expect more than 10 lines per log)

https://gist.github.com/Emc1992/0baf9f52a73354db9cb4573aa66554ec

**Comment by ncdc** [comment]
It looks like there is something wrong with the connectivity from the management cluster to the workload cluster's apiserver. Are you using the HAProxy load balancer VM, or kube-vip?

**Comment by Emc1992** [comment]
No however I think I'm on to something - it looks like the pod subnet is hardcoded in the cluster template to 192.168.0.0/16 and so assumes im on a class C network - is there a method I could use to override this?

**Comment by ncdc** [comment]
The pod CIDR needs to be a CIDR that is not already in use / conflicting with any existing subnet in your network. It's fine to be 192.168/16 if you aren't using that anywhere else. If you need to change it, you can edit your `cluster.yaml` file. You will probably need to adjust your Calico manifest too to match.

If 192.168/16 is not currently in use, you shouldn't need to make any changes.

I would continue to investigate connectivity issues to the workload cluster apiserver.

**Comment by Emc1992** [comment]
but if I can hit the api server to verify the manager node is in a ready state, doesn't that confirm connectivity?
i.e. KUBECONFIG=vsphere-quickstart.kubeconfig kubectl get nodes gives me an output

**Comment by ncdc** [comment]
Yes. I suppose the log lines that look like
```
I0825 17:58:44.554368       1 controller.go:186] controllers/KubeadmControlPlane "msg"="Could not connect to workload cluster to fetch status" "cluster"="vsphere-quickstart" "kubeadmControlPlane"="vsphere-quickstart" "namespace"="default" "err"={}
```
maybe aren't happening any more?

Can you share `kubectl get kubeadmcontrolplane -o yaml`?

**Comment by Emc1992** [comment]
https://gist.github.com/Emc1992/4b206a83aecd291d05ff1919629ff554

**Comment by ncdc** [comment]
```
    - lastTransitionTime: "2020-08-25T19:51:24Z"
      reason: WaitingForKubeadmInit
      severity: Info
      status: "False"
      type: Ready
    - lastTransitionTime: "2020-08-25T19:47:05Z"
      reason: WaitingForKubeadmInit
      severity: Info
      status: "False"
```

It looks like this is because the management cluster is having a problem running the equivalent of `kubectl -n kube-system get configmap/kubeadm-config` against the workload cluster. Are you able to do that?

**Comment by Emc1992** [comment]
sure let me check, however shouldn't we expect these to be false? i.e is isnt waiting waiting for kubeadminit(because its already kicked off) or did I miss read it that logic?

**Comment by ncdc** [comment]
I accidentally missed the last line (now fixed above) - you can see both the Ready and Available conditions are False, with the reason being WaitingForKubeadmInit.

**Comment by Emc1992** [comment]
Ah ha!! I missed that! Thank you - I'll play around with that once I get back to the laptop and let you know.

**Comment by yastij** [comment]
@Emc1992 - is this solved for you ?

**Comment by Emc1992** [comment]
It wasn't, trying with the latest capi at the moment

**Comment by Emc1992** [comment]
Looks to be working as of now, I played around with some ranges of the pod networks as well as bumping the versions and everything looks to be provisioning(apart from an issue with addons.cluster.x-k8s but doesn't appear to prevent deployment)

**Comment by yastij** [comment]
closing this, If this re-appears please feel free to re-open
