### ISSUE TITLE
Fail to shrink disk size while cloning VM template

### ISSUE THREAD

**Issue by Danil-Grigorev** [kubernetes-sigs/cluster-api-provider-vsphere#1030]
/kind bug

**What steps did you take and what happened:**

1) Clone VM from a template, and specify a lower `DiskGiB` then it's specified on the template
2) Cloning fails with an undescriptive error message: `Invalid operation for device '0'.`

**What did you expect to happen:**

Show an error on specifying an invalid user input, and do not attempt to clone the template.

**Anything else you would like to add:**

Full (almost) error output:
```json
   "Description": {
    "Key": "com.vmware.vim.vpxd.vpx.vmprov.ReconfigureVm",
    "Arg": null,
    "Message": "Reconfiguring Virtual Machine on destination host"
   },
   "Name": "CloneVM_Task",
   "DescriptionId": "VirtualMachine.clone",
   "Entity": {
    "Type": "VirtualMachine",
    "Value": "vm-1880"
   },
   "EntityName": "1909-template",
   "Locked": null,
   "State": "error",
   "Cancelled": false,
   "Cancelable": false,
   "Error": {
    "Fault": {
     "FaultCause": null,
     "FaultMessage": null,
     "Property": "virtualDeviceSpec.device",
     "DeviceIndex": 0,
     "BadOp": "edit",
     "BadFileOp": ""
    },
    "LocalizedMessage": "Invalid operation for device '0'."
   },
```
**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 1.19
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
Probably makes most sense to fail the machine (the other option would be at webhook validation, but feels wrong to be connecting to vcenter at that point).
