### ISSUE TITLE
Failure Domains support in CAPV

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api-provider-vsphere#1036]
/kind feature

**Describe the solution you'd like**

CAPV should be able to surface failure domains, so that machines are spread across these. 

The current proposal can be found [here](https://docs.google.com/document/d/1WBsNQofkoXeT_KVNehs5E7HJ89kbpf5YBgIEPT5UXO0/edit?usp=sharing)

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
@jzhoucliqr - I'm not able to assign it to you as you're not part of the kubernetes-sigs orgs yet, but consider it assigned to you

**Comment by embano1** [comment]
This proposal is great and implements most of the ideas in this old (in-tree) issue and relates PRs: https://github.com/kubernetes/kubernetes/issues/64021

The KEP is not specific about soft/hard DRS rules, and in case of soft how to deal with potential label drift (see issue above). Also, I'm curious why don't we propagate host group, eg "rack", failure domain labels for use case one? Any technical reason which speaks against it?
