### ISSUE TITLE
Failure domain support

### ISSUE THREAD

**Issue by jzhoucliqr** [kubernetes-sigs/cluster-api-provider-vsphere#1039]
/kind feature

**Describe the solution you'd like**
Add control plane failure domain support in CAPV.

**Anything else you would like to add:**
Design doc:  https://docs.google.com/document/d/1WBsNQofkoXeT_KVNehs5E7HJ89kbpf5YBgIEPT5UXO0/edit?ts=5f72090b#

If you have any use case for failure domain in capv, please leave a comment here or in the doc, about what kinds of topology that you are looking to support?  Mainly on the Zone mapping:  

zone -> Datacenter
zone -> Compute Cluster
zone -> Host
zone -> ? 

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
closing as a dupe of #1036

**Comment by jzhoucliqr** [comment]
Thanks @yastij .
