### ISSUE TITLE
Build the bootstrap OVA

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#104]
We need a bootstrap OVA that installs an initial kubernetes cluster, mainly just the master, that has the cluster api controllers running on startup.  Perhaps we can use a custom Yakkity OVA for this.

Requirement:

- [x] Create a cluster with a kubernetes master
- [ ] Has the ability to create VM templates from a cloud init image.  Perhaps we can use the VMDK that is packaged with the OVA.
- [x] Ability to get the kubeconfig from this bootstrap cluster.

**Comment by frapposelli** [comment]
Decided to have the user provide their own image, everything else is completed and fixed by #142
