### ISSUE TITLE
Generated CPI manifest has wrong toleration in K8S 1.19

### ISSUE THREAD

**Issue by jonkerj** [kubernetes-sigs/cluster-api-provider-vsphere#1056]
/kind bug

**What steps did you take and what happened:**
I am using CAPV to bootstrap Talos on vSphere (using CABPT and CACPPT), which mostly works fine. My workload cluster is based on K8S 1.19.3. At the final step, when the API endpoint becomes available, CAPV injects the CPI in the workload cluster. On my workload cluster, however, this consistently leads to a non working `DaemonSet`:

```
jorik@superbox:~$ kubectl get ds -n kube-system vsphere-cloud-controller-manager
NAME                               DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
vsphere-cloud-controller-manager   0         0         0       0            0           node-role.kubernetes.io/master=   32m
```
Note the 0 desired there.

**What did you expect to happen:**
I would expect the DaemonSet to get scheduled on all my masters.

**Anything else you would like to add:**
I did a little digging, and I noticed that on my workload cluster the taint on my master node does not match the toleration verbatim. When I change the toleration in the DS spec, it gets scheduled:

```
tolerations:
# omitted
- effect: NoSchedule
  key: node-role.kubernetes.io/master
  value: "true" #<--- I added this one
# omitted
```

I looked at the code, and the DaemonSet is directly constructed from Golang, and does not seem very tunable to fix this.

This probably needs fixing in the manifests at the CPI repo, which is filed under kubernetes/cloud-provider-vsphere#413

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.0
- Kubernetes version: v1.19.3 (both seed and target) 
- OS: Talos 0.7.0 (both seed and target)

**Comment by jonkerj** [comment]
There seems to be a proposed solution in kubernetes/cloud-provider-vsphere#392

**Comment by yastij** [comment]
@jonkerj - I checked quickly, default seems to be 

```
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
```

but adding exists would cover your use case, so I'm +1
