### ISSUE TITLE
Generate cluster config depending on bootstrap/controlplane providers

### ISSUE THREAD

**Issue by jonkerj** [kubernetes-sigs/cluster-api-provider-vsphere#1057]
/kind feature

Note: it could very well be that I am filing this request in the wrong GH repo, since I do not know which part of the x-api projects is responsible for this area. Feel free to correct me.

**Describe the solution you'd like**
I am using CAPV in conjunction with Talos' CABPT and CACPPT. In order to get a working `cluster.yaml` containing the right resources to fire up a cluster, I have to manually construct a config file, since `clusterctl -i vsphere` blindly assumes a kubeadm bootstrap/control plane. Needless to say, it's time consuming and failure prone. Moreover, I am considering of using a tool to template this for me, while `clusterctl` was designed to specifically do this for me.

Since the combination of CAPV+CABPT/CACPPT works fine, it would be great (and in the spirit of composable infrastructure) to be able to generate manifests for this (and other) combinations as well. 

**Anything else you would like to add:**
I am not sure if `clusterctl` allows for this and if I am barking up the right repo.

**Environment:**

- Cluster-api-provider-vsphere version: 0.7.0
- clusterctl version: 0.3.10
- Kubernetes version: 1.19.3 
- OS (e.g. from `/etc/os-release`): Talos 0.7.0

**Comment by fabriziopandini** [comment]
> In order to get a working cluster.yaml containing the right resources to fire up a cluster, I have to manually construct a config file

FYI clusterctl supports fetching cluster templates from other locations (different than the provider's repository) by using the `--from` flag; see [Alternative sources for cluster templates](https://cluster-api.sigs.k8s.io/clusterctl/commands/config-cluster.html#alternative-source-for-cluster-templates). This could avoid the need of creating a config file for providing an alternative source of artifacts.
Also [overrides](https://cluster-api.sigs.k8s.io/clusterctl/configuration.html#overrides-layer) could be an option here.
