### ISSUE TITLE
Support for complete control of Network section by IPAM controller in vSphereMachine(Templates)

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#1098]
/kind feature

**Describe the solution you'd like**
Currently the NetworkName is mandatory in the CRDs.
https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api-provider-vsphere/infrastructure.cluster.x-k8s.io/VSphereMachine/v1alpha3@v0.7.4#spec-network-devices-networkName
That causes a Problem if you want to outsource all Network config to an IPAM Controller, as you still need to add the necassesary NetworkNames into the Resource ontop of the work that the IPAM Controller will do.

**Comment by yastij** [comment]
we should probably use this issue to track the design for IPAM

**Comment by srm09** [comment]
@yastij Can you point me to some relevant document/issue for IPAM discussion? Would wanna catch up on this?

**Comment by srm09** [comment]
/assign @aartij17 
Since you are looking into supporting IPAM, good thought to think about this one as well.
