### ISSUE TITLE
VMware: support VM images that come with container runtime pre-installed

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes-sigs/cluster-api-provider-vsphere#11]
_From @rsdcastro on April 17, 2018 18:43_

_From @rsdcastro on April 14, 2018 1:46_

VM images provided by users might have the container runtime. This issue tracks verifying if the container runtime is already pre-installed and matches the version specified by the user.

_Copied from original issue: kubernetes/kube-deploy#687_

_Copied from original issue: kubernetes-sigs/cluster-api#79_

**Comment by roberthbailey** [comment]
_From @rsdcastro on May 29, 2018 21:51_

/cc @karan 

Karan - can you update this issue based on the current implementation using Ubuntu images?

**Comment by roberthbailey** [comment]
_From @karan on May 29, 2018 23:53_

Currently, we disregard user preference and install docker anyways - https://github.com/kubernetes-sigs/cluster-api/blob/master/cloud/terraform/templates.go#L251 (terraform) and https://github.com/kubernetes-sigs/cluster-api/blob/master/gcp-deployer/machine_setup_configs.yaml#L40 (gcp)

**Comment by sidharthsurana** [comment]
We already have the flag `preloaded` that the user can set to `True` in case the template used already has all the binaries pre-installed.
