### ISSUE TITLE
update CAPV to read informations from the failure domain spec to create vsphereVMs

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api-provider-vsphere#1101]
/kind feature

**Describe the solution you'd like**

when a `VSphereMachine` is created with `.spec.failureDomain` set, it should get it and read from it to generate `VSphereVMs`, this should enable spreading machine across the desired failure domains

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
Closing in favor of #1208 and #1219
/close
