### ISSUE TITLE
Add helper printer columns to CAPV resources

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#1119]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Add printer columns to help with troubleshooting.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
There is an open PR for a part of it, waiting for the author to squash the commits.
/remove-lifecycle stale
