### ISSUE TITLE
kube-vip BGP

### ISSUE THREAD

**Issue by kplimack** [kubernetes-sigs/cluster-api-provider-vsphere#1120]
/kind feature

I would like to be able to provide a kube-vip.yaml with bgp peering settings for kube-vip when creating a new cluster. 

In some topologies that span multiple subnets, ARP will not work for the api loadbalancer.  kube-vip has BGP mode which supports layer3
https://kube-vip.io/kubernetes/bgp/

**Comment by yastij** [comment]
@kplimack - the template we provide are quickstart ones. for the advanced use case, we recommend customizing your own through:

```
clusterctl config cluster  <cluster_name> --from /path/to/template.yaml
```
