### ISSUE TITLE
Storage policy applied before cloning causes clone to fail across datastores

### ISSUE THREAD

**Issue by bleech1** [kubernetes-sigs/cluster-api-provider-vsphere#1146]
/kind bug

**What steps did you take and what happened:**
Use a template that doesn't have a storage policy to spin up worker nodes on a different datastore with a storage policy.  The current code sets the new storage policy before cloning, and we receive the following logs in our vCenter logs:
`Changing or applying VM Storage Policies with Data Service capabilities during clone operations is disallowed. VM Storage Policies with Data Service capabilities can be assigned to the provisioned VM after the clone operation has been completed and before the VM has been powered on.`  Even though [this article](https://kb.vmware.com/s/article/78488) states that this occurs when the datastores have different settings, we verified that this occurs even when the datastores have all the same configuration settings (the only differences between our datastores are name and size) and the storage policy is compliant with both the source and destination datastore.  We also verified that this still happens when the template lives on the same datastore that the worker node would live on, which removes datastore differences from the equation.

**What did you expect to happen:**
I expected the template to be cloned to the new datastore with the storage policy applied.  One solution here, which is currently used by the terraform vsphere provider, is to clone the template without a storage policy and then switch to the new policy.  This does make the clone take longer, but solves this problem.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.6
- Kubernetes version: (use `kubectl version`): v1.18.12
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 machines
- vCenter: 6.7

**Comment by gab-satchi** [comment]
merged into master via #1168 

/close
