### ISSUE TITLE
kube-vip version should be v0.3.2

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/cluster-api-provider-vsphere#1148]
/kind bug

**What steps did you take and what happened:**
I had problems provisioning an Ubuntu based CAPV cluster where it wasn't responding to any requests from 6443 outside of the VM. I have worked with @gab-satchi and @yastij and upgrading to v0.3.2 for kube-vip fixed the problem.

**What did you expect to happen:**
The entire cluster should be stood up and provisioning should succeed.

**Anything else you would like to add:**
https://kubernetes.slack.com/archives/CKFGK3SSD/p1616003745040200?thread_ts=1615991574.014600&cid=CKFGK3SSD

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): v1.20.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04 using the pre-built image

**Comment by kbreit** [comment]
Looks like this was fixed in #1160. If it's fixed in the next release I'll close.

**Comment by srm09** [comment]
The kube-vip version was upgraded both in the main and release-0.7 branch. This should be fixed now. Will close it.

/close
