### ISSUE TITLE
Update MTU won't take effect

### ISSUE THREAD

**Issue by lynic** [kubernetes-sigs/cluster-api-provider-vsphere#1165]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
Update vsphereVM spec.mtu to 9000 for management interface, nothing changed.

**What did you expect to happen:**
eth0's mtu change to 9000 instead of 1500 by default.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 1.20.4
- OS (e.g. from `/etc/os-release`): photonOS

**Comment by gab-satchi** [comment]
Hey @lynic, 

>Update vsphereVM spec.mtu to 9000 for management interface, nothing changed.

you need to update the VsphereMachineTemplate.Spec.Template.Spec.Network.Devices[i].Mtu to 9000 prior to deployment for the vsphere vm to get created correctly. The network devices are allowed to be updated on the vsphereVM in order to support IPAMs that need to set the IP.

**Comment by lynic** [comment]
> Hey @lynic,
> 
> > Update vsphereVM spec.mtu to 9000 for management interface, nothing changed.
> 
> you need to update the VsphereMachineTemplate.Spec.Template.Spec.Network.Devices[i].Mtu to 9000 prior to deployment for the vsphere vm to get created correctly. The network devices are allowed to be updated on the vsphereVM in order to support IPAMs that need to set the IP.

Hi @gab-satchi , Could this value take effect after cluster deployment, if I want to change MTU after that?

**Comment by yastij** [comment]
@lynic - machines are immutable, so you'd have to create a new `VSphereMachineTemplate` with the desired value, then update the `MachineDeployment` to point to it. This should trigger a machine rollout

**Comment by gab-satchi** [comment]
hey @lynic closing this issue since the way to set MTU has been pointed out above. 

/close
