### ISSUE TITLE
OVA Image - Additional VMDKs

### ISSUE THREAD

**Issue by malikkal** [kubernetes-sigs/cluster-api-provider-vsphere#1166]
/kind bug

**What steps did you take and what happened:**
Add an additional virtual disk to the OVA image.
 Message:               error getting disk spec for "infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereVM default/guest1-control-plane-7qf4c": invalid disk count: 2
    Reason:                CloningFailed

**What did you expect to happen:**
Guest cluster to come up with additional scsi block devices.

**Anything else you would like to add:**
How do you add additional VMDKs to the node image during the custom image creation or post OVA import?

**Comment by gab-satchi** [comment]
That error is expected. We currently only support one disk per vsphere VM.

**Comment by malikkal** [comment]
@gab-satchi Could adding / allowing additional VMDKs as part of node image be considered as an enhancement? Thank you.
