### ISSUE TITLE
Documentation for VSPHERE_STORAGE_POLICY

### ISSUE THREAD

**Issue by TerryHowe** [kubernetes-sigs/cluster-api-provider-vsphere#1183]
/kind feature

**Describe the solution you'd like**
It'd be nice if VSPHERE_STORAGE_POLICY was mentioned in the documentation

**Anything else you would like to add:**
An example and where to find it for the not great vSphere person

**Environment:**

- Cluster-api-provider-vsphere version:  v0.7.7
- Kubernetes version: (use `kubectl version`):  1.19.6
- OS (e.g. from `/etc/os-release`):  ubuntu 1804

**Comment by gab-satchi** [comment]
should make the `VSPHERE_STORAGE_POLICY` optional and default it to ""
