### ISSUE TITLE
Placeholder: Update v1alpha4 types to use pointers instead of strings

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1184]
/kind feature

**Describe the solution you'd like**
Change string to string pointers, to ease out defaulting after Failure Domain is merged.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by geetikabatra** [comment]
@srm09 Can I take this up?
