### ISSUE TITLE
Migrate the yaml from the ci E2E test container to the provider repo

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#119]
Currently, the CI container has a copy of provider-components.yaml, machines.yaml, and cluster.yaml.  Every time the provider changes any of those, both the provider repo and the CI container repo must be updated.  If we moved it all to the provider repo, then only one repo needs to be updated.

---

- [ ] Remove all 3 yaml files from the CI container
- [ ] Add a kv file with infrastructure values for such fields as datacenter, datasource, etc.
- [ ] Use `make ci-yaml` to generate the yaml files
- [ ] Create scripts in this repo (perhaps, under hack), to modify the yaml with value from our kv file.
- [ ] Modify the makefile to generate the final yaml for E2E tests.

**Comment by frapposelli** [comment]
/assign @sflxn @figo

What's the status here? can this issue be closed?
