### ISSUE TITLE
Vspheremachinetemplate should support multiple disks

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/cluster-api-provider-vsphere#1196]
/kind feature

**Describe the solution you'd like**
The ability to have multiple disks attached to a VM could be very useful in situations where a block device is needed to be attached to a node VM. For instance, Ceph often likes internal disks in the same system. Right now I can only specify a single disk.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by vrabbi** [comment]
this would help with implementing things like ceph as well as portworx or other  SDS CSI drivers which we are seeing alot of adoption of these days in vSphere environments especially.

**Comment by srm09** [comment]
/reopen
Active PR open for this one #1236
