### ISSUE TITLE
VSphereClusterIdentity tries to update a secret when it doesn't exist

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api-provider-vsphere#1200]
/kind bug

**What steps did you take and what happened:**
Deploy a VSphereClusterIdentity that references a secret that doesn't exist

**What did you expect to happen:**
An error stating the secret can't be found and reflected in the status of the VSphereClusterIdentity

Instead, the VSphereClusterIdentity tries to update a non-existent secret and see errors like: `"error"="resource name may not be empty"`

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.8

**Comment by schrej** [comment]
The GitHub automation in the PR didn't trigger, so let's see if I'm allowed to do this.
/close

**Comment by gab-satchi** [comment]
thanks :)
