### ISSUE TITLE
Deletion process isn't reliable

### ISSUE THREAD

**Issue by kbreit** [kubernetes-sigs/cluster-api-provider-vsphere#1213]
/kind bug

**What steps did you take and what happened:**
I created a Helm chart to deploy CAPV based Kubernetes clusters. I believe it produces identical manifests to `clusterctl` generated manifests. I create a new `kind` cluster, install the required components (CNI, CAPV, etc) and use Helm to deploy the cluster. After the cluster is created and the Machine resources are up, I do a `helm uninstall`. The cluster never deletes as multiple resources don't appear to go away. In a conversation with @gab-satchi it appears the `vspherecluster` resource is deleted very quickly and the Machine objects do not get deleted. 

**What did you expect to happen:**
I would expect this to delete all objects in the proper order.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Please let me know what else I should provide.

**Environment:**

- Cluster-api-provider-vsphere version: 0.7.8
- Kubernetes version: (use `kubectl version`): 1.20.2
- OS (e.g. from `/etc/os-release`): kind

**Comment by yastij** [comment]
as per discussion in the CAPV office hours, this seems to be a mismatch on the cluster name. Closing
