### ISSUE TITLE
Change the controlPlaneEndpoint during kubernetes cluster running

### ISSUE THREAD

**Issue by haijianyang** [kubernetes-sigs/cluster-api-provider-vsphere#1218]
/kind feature

**Describe the solution you'd like**
I found that the documentation and code didn't mention update/change the controlPlaneEndpoint after setting.
As a user I want to change the controlPlaneEndpoint(kube-vip or haproxyloadbalancer IP) during kubernetes cluster running, can CAPV provide support?

**Environment:**

- Cluster-api-provider-vsphere version: v0.7.9
- Kubernetes version: v1.20.6
- OS : CentOS 7

**Comment by srm09** [comment]
Since kube-vip runs as a static pod on the nodes which is setup by `kubeadm`, not sure this is something that we can support in CAPV out of the box. Try using an external load balancer for this use case.
