### ISSUE TITLE
Design a method to get error feedback from a node running the init scripts

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#122]
Currently, once a node is initializing and running the init scripts, there is no feedback on error conditions until we ssh into the machines.  There are two problems with this.

1. it assumes the ssh server started up properly
2. it assumes we use ssh.  If we want to remove the ssh dependency, we need another mechanism for error feedback.

**Comment by moshloop** [comment]
I would close in favor of #176

**Comment by akutz** [comment]
Closing as related to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/45#issuecomment-500065308. Please see that comment for the prescribed conversation forward.

/close
