### ISSUE TITLE
README: Disambiguate cloud providers from capi providers 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#1224]
Somewhat unstructured notes to myself, on how we probably should clarify the intersection of cloud providers, the CAPI provider ID, and the CAPV provider ID implementation.... Id make a PR myself but im not sure i 100% understand it :)  

Today I asked a question in slack, @randomvariable helped me answer it, but in general its tricky for me to reconcile the difference between 

- cloud provider for vsphere 
- cluster api provider for vsphere 

Especially when it comes to the `vsphere-cloud-controller-manager` component (which lives in the cloud providers repository, https://github.com/kubernetes/cloud-provider-vsphere/blob/master/manifests/controller-manager/).

In general, running CAPV clusters i believe run the vsphere-cloud-controller-manager, which continually reconciles the providerID:

```
instances.NodeAddressesByProviderID() CACHED with 4208e34a-f0e0-b121-77e0-23807d98334d
```

And I believe at least in some CAPV variants.  In general, my understanding is that the notion of a `cloud provider id` is inherent to the cluster api datamodel, generically, but it is implemented differently by every cloud provider (again learned this from naadir in slack today).  

So, i figured id brain dump this into an issue, concretely, i think 

- having some info in the README.md and
- updating  https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine.html with some concrete examples of how these providerIDs look in the wild 

would be helpful

**Comment by randomvariable** [comment]
We should probably move this issue to the cluster api repo, but in terms of documentation, it makes sense, as there's been similar confusion in the comments of the recent MachinePool Machines CAEP. we're not going to be in a position to do a wholesale rename of projects though, that boat has long sailed.

@vincepri could you do the honours (of hitting transfer)?
