### ISSUE TITLE
Support datastore clusters in Datastore field

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api-provider-vsphere#1227]
/kind feature

**Describe the solution you'd like**
Currently if a user provides a `DatastoreCluster` in the `Datastore` field, CAPV will fail with a not-found error. ~~This issue is a request to expand the datastore reconciliation logic to also cover datastore clusters~~

This issue is to request a new field `DatastoreCluster` on the `VSphereMachineTemplate` to specify a datastore cluster to be used. Similar to storage policy, a user can still specify a datastore on top of specifying datastore cluster. In this use case, we should verify the datastore is part of the datastore cluster. 

There is a workaround where users can tag all of their datastores within the cluster and then target them through a storage policy.

**Comment by vrabbi** [comment]
this will be extremely useful especially now that CSI is planned to support Datastore Clusters and storage vmotion at least partially in 7.0u3 as indicated in the following issue https://github.com/kubernetes-sigs/vsphere-csi-driver/issues/1192

**Comment by AartiJivrajani** [comment]
The e2e tests are failing because of [this](https://github.com/kubernetes-sigs/cluster-api/issues/5283) issue

**Comment by s0uky** [comment]
Hello, 
is there any update about support DatastoreCluster in datastore field? This PR https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1240 is closed and I can't find any new information about this feature. 
Thank you

/cc  [srm09](https://github.com/srm09),

**Comment by polunox** [comment]
This issue is closed
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1244

Is there any plans to continue work for resolve this issue?
