### ISSUE TITLE
Bug: kubectl delete cluster doesn't delete the machines

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#123]
When I issue `kubectl delete cluster` on the bootstrap cluster, it deletes the cluster object without deleting the machines.  Once the cluster object is gone, it is not possible to delete the machines as the controller will complain the cluster does not exist.

In a way, allowing users to delete a whole cluster with a simple command that doesn't ask for verification is very dangerous.  Perhaps, we should not allow deletion of the cluster via kubectl.  Perhaps we should force using clusterctl to delete the objects?  We need the workflow to be designed out.

---

- [ ] Design a mechanism to verify deletion of a whole cluster
- [ ] Prevent the cluster object from orphaning the machines

**Comment by frapposelli** [comment]
@sflxn Is this still valid?

**Comment by sflxn** [comment]
still valid.  Some people are actually working on the same issue in the main cluster api repo.
