### ISSUE TITLE
Add e2e test that upgrades a cluster and runs the k8s conformance tests

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api-provider-vsphere#1235]
The CAPI test framework offers a way to run an upgrade followed by the Kubernetes conformance suite: https://github.com/kubernetes-sigs/cluster-api/blob/v0.4.2/test/e2e/cluster_upgrade.go#L48

This issue is to request adding a conformance test suite in e2e. These tests should then become part of the [periodic tests](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/cluster-api-provider-vsphere/cluster-api-provider-vsphere-ci.yaml) run. 

Note: the conformance tests should be omitted from our PR e2e test runs.

**Comment by srm09** [comment]
/assign @srm09 
Create a list of test cases to be supported in CAPV upstream jobs

**Comment by srm09** [comment]
/unassign @srm09
Can you use the same issue to run conformance tests on the cluster upgrade tests as well?

**Comment by srm09** [comment]
/close
This has been merged as part of the upgrade tests
