### ISSUE TITLE
Remove the terraform actuator code and dependencies

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#125]
The govmomi actuators have been implemented and all development work over the last 2 months have been focused on the govmomi code base.  Since no one is working on the terraform actuators, it is slowly getting out of date and there are no plans on updating it.  Terraform, itself, uses govmomi for vSphere.  There is no point in keeping the terraform actuators around.  It's time to remove this legacy code and all of it's dependencies.

**Comment by sidharthsurana** [comment]
There is some more clean up required beyond the PR #126 
Re-opening this for the moment so that we can resolve this issue once the clean up is complete
