### ISSUE TITLE
CAPV manager should refresh and use new credentials if the bootstrap secret is updated

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api-provider-vsphere#1275]
/kind feature

**Describe the solution you'd like**
If a user updates the `capv-manager-bootstrap-credentials` the manager won't pick up the new credentials. 
One way to get the manager to use the new credentials is to restart the pod. 

This feature request is for implementing a watch on that secret so the manager can use the most up-to-date credentials. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
Ref: https://github.com/kubernetes/cloud-provider-vsphere/pull/532
