### ISSUE TITLE
Exposed Prometheus metrics for unreachable workload clusters

### ISSUE THREAD

**Issue by perithompson** [kubernetes-sigs/cluster-api-provider-vsphere#1281]
/kind feature

**Describe the solution you'd like**
When a Management cluster cannot reach a Workload Cluster it may be necessary to pause reconciliation of that cluster until a time when cluster connectivity can be restored in order to prevent capi from constantly trying to reconcile something it can't.  There is an [issue(#5394)](https://github.com/kubernetes-sigs/cluster-api/issues/5394) that outlines some gaps in the documentation around this.

One problem operators will face is knowing when this state occurs.  A simple way to monitor for this state is a metric for monitoring workload clusters. Having `count of workload clusters`, `count of paused`  and `count of unreachable clusters` exposed to Prometheus would allow for an alert on a change to unreachable cluster count and then operators could implement some automation or SOPs to check and pause clusters that cannot reconcile for any reason.

**Anything else you would like to add:**

**Environment:**

**Comment by srm09** [comment]
@perithompson This seems like something that will sit in the CAPI repo. I am happy to keep this one around if CAPV would need to do something specifically, but I think the entire change will rest directly in CAPI.

**Comment by chrischdi** [comment]
Maybe gets resolved or partially resolved in #2061

**Comment by killianmuldoon** [comment]
I think this should be closed in favor of a solution on the CAPI side - there's a related issue here: https://github.com/kubernetes-sigs/cluster-api/issues/5510

**Comment by sbueringer** [comment]
+1

/close
