### ISSUE TITLE
Workaround the 15 character limit for AD in CAPV, temporarily (Cross linked issue to CAPI), until CAPI has a broader fix

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#1292]
/kind bug

we can't easily add machines for AD (active directory on windows nodes) bc of https://github.com/kubernetes-sigs/cluster-api/issues/2217 

Should we do a band aid similar to what is done in CAPZ? (ill try to dig up a link, but evidently CAPZ allows for smaller machine names by doing a provider specific fix for windows).
 
```
// Name returns the Azure Machine Pool Name.
func (m *MachinePoolScope) Name() string {
	// Windows Machine pools names cannot be longer than 9 chars
	if m.AzureMachinePool.Spec.Template.OSDisk.OSType == azure.WindowsOS && len(m.AzureMachinePool.Name) > 9 {
		return "win-" + m.AzureMachinePool.Name[len(m.AzureMachinePool.Name)-5:]
	}
	return m.AzureMachinePool.Name
}
``` (from machinepool.go)

**Comment by randomvariable** [comment]
there's no way of determining the OS is Windows on vSphere, so will need something explicit.

**Comment by vrabbi** [comment]
@randomvariable unless im misunderstanding,
you actually could tell the VMs OS from the vSphere API. for example
cmd: govc vm.info -json=true photon-3-kube-v1.19.8+vmware.3 | jq .VirtualMachines[0].Summary.Config.GuestId
returns: "vmwarePhoton64Guest"
cmd: govc vm.info -json=true Demo-EUC-WS1 | jq .VirtualMachines[0].Summary.Config.GuestId
returns: "windows9_64Guest"

the list of guestIds is in the vsphjere api docs. 
Its also possible to get The guest distro from the guestinfo.detailed.data property under the distroName key which would return "Windows."

**Comment by randomvariable** [comment]
> you actually could tell the VMs OS from the vSphere API. for example
> cmd: govc vm.info -json=true photon-3-kube-v1.19.8+vmware.3 | jq .VirtualMachines[0].Summary.Config.GuestId
> returns: "vmwarePhoton64Guest"

TIL

**Comment by srm09** [comment]
@jayunit100 How impactful is this fix? I am wary around making provider specific fixes when CAPI has a broader fix planned for all providers. Is this blocking some scenarios entirely for Windows adoption? Do you think this is something you might be able to work on?

@vrabbi From the example commands you posted, I can see that the VM info can be pulled from a live VM. But if we want to name the windows VM accordingly, we need to figure out the OS type before the VM is actually created. Is there a way to pull that info beforehand?

**Comment by vrabbi** [comment]
> @vrabbi From the example commands you posted, I can see that the VM info can be pulled from a live VM. But if we want to name the windows VM accordingly, we need to figure out the OS type before the VM is actually created. Is there a way to pull that info beforehand?

not sure if still relevant but if it is, the first example i gave is on a template so this could be run on the template before the clone. as its a vsphere property the VM doesnt need to be live to get the info.

**Comment by dimatha** [comment]
Hi Everyone, that's a problem for me as well now. For now I'm creating MachineSet directly to reduce the size of the Windows vm hostname. So it becomes MachineSetName-XXXXX.
