### ISSUE TITLE
Fix a broken link in the getting started doc

### ISSUE THREAD

**Issue by sayantani11** [kubernetes-sigs/cluster-api-provider-vsphere#1304]
/kind bug

https://cs.k8s.io/?q=cluster-api%2Fblob%2Fmaster&i=nope&files=&excludeFiles=&repos=
As the branch is changed to main in the cluster-api repo, we need to update that in files mentioned in the above link.

Change branch name from `master` to `main` here:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/9ea84f127c6430a258815e5632534c65e5755d6d/docs/getting_started.md#L219

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
there's no way this is a good first issue as it needs to be done by maintainers.

**Comment by randomvariable** [comment]
there's no way this is a good first issue as it needs to be done by maintainers.

**Comment by sayantani11** [comment]
@randomvariable I meant the file mentioned in the link not the branch of the project😅 Guess there's a little confusion there

**Comment by randomvariable** [comment]
Ah, ok. That makes sense.
