### ISSUE TITLE
Move kube-vip to new init routine

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#1314]
/kind feature

**Describe the solution you'd like**
The current template for new clusters still uses `start` as arg for kube-vip. Upstream moved their default to `manage` a while back.
IIRC new features only work with manage, not with start (  @thebsdbox pls correct me if im wrong)

**Anything else you would like to add:**
https://kubernetes.slack.com/archives/CKFGK3SSD/p1637609003082700

**Environment:**

- Cluster-api-provider-vsphere version: current
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by omniproc** [comment]
We already upgraded to kube-vip and all needed was editing the template. Am I correct to assume only the templates need to be changed?
