### ISSUE TITLE
docs/ demo on how to use tilt to make / run windows clusters

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#1320]
/kind feature

**Describe the solution you'd like**

- Would be nice to get `ClusterClass` prototypes working, and have docs for it.
- For now though, even regular YAML examples for how to test windows on CAPV would be good.
- We'd like to possibly use these docs to drive upstream CAPV continuous integration for windows tests.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
/kind documentation
@jayunit100 any chance you would like to drive this work and maybe drive some e2e tests for upstream CAPV + Windows support?
