### ISSUE TITLE
Re-enable LB network provider unit tests

### ISSUE THREAD

**Issue by gab-satchi** [kubernetes-sigs/cluster-api-provider-vsphere#1324]
**Describe the solution you'd like**
The supervisor [controller_test_suite](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/controllers/vmware/test/controllers_suite_test.go#L76-L84) attempts to run the same test suite twice while toggling the suite parameter `isLB` to provision the `dummyLBNetworkProvider`

This issue is to re-enable those tests. The old way of calling `RunSpecs` twice won't work with Ginkgo. A couple of options: 
- turn isLB into a flag and call the same suite twice
- setup and teardown the manager for each test. During setup, the appropriate loadBalancer can be set

**Comment by AectannArd** [comment]
@srm09, please checkout the provided PR
does this look like the change you requested here?
