### ISSUE TITLE
Tag vSphere VMs based on VSphereMachine labels/annotations.

### ISSUE THREAD

**Issue by josh-ferrell** [kubernetes-sigs/cluster-api-provider-vsphere#1340]
/kind feature

**Describe the solution you'd like**
As an end user I would like the ability to create and assign tags in vCenter based on a list provided at cluster creation time or reconciliation from node labels.

**Anything else you would like to add:**
This was a TKG customer request. The customer currently has a backup solution that excludes VMs based on a tag in vCenter. Tags can be manually added but scale or node recreation from failed MHC creates additional steps.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): v1.21.2+
- OS (e.g. from `/etc/os-release`):  Photon

**Comment by josh-ferrell** [comment]
I see tagIDs in the v1beta1 VirtualMachineCloneSpec so this may already be a planned enhancement. https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/8b1a3c7bc835e884f1e87ad94c189605061048bd/apis/v1beta1/types.go#L146

**Comment by josh-ferrell** [comment]
Yea they are currently using some YTT overlays to label certain resources during cluster creation time. Their goal is the be able to provide a label or in this instance maybe it's just a tag ID so that all VMs that get created have that tag assigned automatically. 

For ease of use I could see it being a tag array that was able to get the tag IDs if they existed and create the tag if not.

**Comment by srm09** [comment]
Digging up an older issue around tagging VMs https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/505
