### ISSUE TITLE
KCP manager role needs access to `vsphereMachineTemplates` and `vsphereMachines` 

### ISSUE THREAD

**Issue by aartij17** [kubernetes-sigs/cluster-api-provider-vsphere#1345]
**What steps did you take and what happened:**
KCP manager role needs access to `vsphereMachineTemplates` and `vsphereMachines` CRs in the `vmware.infrastructure.cluster.x-k8s.io` API group

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by AartiJivrajani** [comment]
\assign
