### ISSUE TITLE
"Network plugin returns error: cni plugin not initialized" on new cluster

### ISSUE THREAD

**Issue by ninlil** [kubernetes-sigs/cluster-api-provider-vsphere#1349]
/kind bug

**What steps did you take and what happened:**
Installed cluster according to quickstart template
After a lot of permission-troubles the nodes are actually getting created.
I can ssh into them just fine, and get the kubeconfig-secret..
but the nodes says
```
KubeletNotReady   runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized
```

coredns, csi-controller and csi-node wont start because the nodes are not Ready
```sh
$ kubectl get pod -A
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   coredns-74ff55c5b-7g5b8                   0/1     Pending             0          33m
kube-system   coredns-74ff55c5b-h7qjl                   0/1     Pending             0          33m
kube-system   etcd-k8mgmt-qqj24                         1/1     Running             0          33m
kube-system   kube-apiserver-k8mgmt-qqj24               1/1     Running             0          33m
kube-system   kube-controller-manager-k8mgmt-qqj24      1/1     Running             0          33m
kube-system   kube-proxy-qlms9                          1/1     Running             0          33m
kube-system   kube-proxy-qmv86                          1/1     Running             0          33m
kube-system   kube-scheduler-k8mgmt-qqj24               1/1     Running             0          33m
kube-system   kube-vip-k8mgmt-qqj24                     1/1     Running             0          33m
kube-system   vsphere-cloud-controller-manager-rndbz    1/1     Running             0          33m
kube-system   vsphere-cloud-controller-manager-t9rrd    1/1     Running             0          33m
kube-system   vsphere-csi-controller-5456544dd5-pgltv   0/5     Pending             0          33m
kube-system   vsphere-csi-node-2gc7k                    0/3     ContainerCreating   0          33m
kube-system   vsphere-csi-node-5c9gt                    0/3     ContainerCreating   0          33m
```

**What did you expect to happen:**
Working cluster

**Anything else you would like to add:**
According to the Tanzu documentation on v1.21.x (https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-releases/services/rn/vmware-tanzu-kubernetes-releases-release-notes/index.html) there is a fixed issue:
> **TKC creation stuck. Error: Network plugin returns error: cni plugin not initialized.**
> When creating a new cluster using TKr v1.21.2, the container runtime network is not ready and the cluster is not created. This is a regression in runc. This has been fixed in this release.

**Environment:**

- Cluster-api-provider-vsphere version: 1.0.2
- Kubernetes version: (use `kubectl version`): 1.21.1
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.3 LTS
- Template built using the "image builder cookbook" on vSphere 7.0.2.00500 using Ubuntu 20.04.3 LTS and k8 v1.20.10

**Comment by srm09** [comment]
From the CAPI book, follow the set of steps to deploy a CNI, the example in the book shows `calico`.
https://cluster-api.sigs.k8s.io/user/quick-start.html#deploy-a-cni-solution

Once the CNI solution is deployed, the cluster nodes should move to the `Ready` state.

**Comment by ninlil** [comment]
Thanks, my mistake.
The nodes got 'Ready' just fine after that.
I just stumbled upon the issue #1162 as well, but (temporarily changed that to "insecure-flag = true" during our testing.

/close
