### ISSUE TITLE
Deploying CAPV with Tilt is broken

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1352]
/kind bug

**What steps did you take and what happened:**
Deploying CAPV with the Tilt mentioned in the [CAPI book](https://cluster-api.sigs.k8s.io/developer/tilt.html) fails with the following error on the Tilt UI

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/8758225/149288693-ffc10f80-a78e-425d-8717-5a2ff671be72.png">

**What did you expect to happen:**
CAPI+KCP+CAPV controllers to be deployed successfully

**Anything else you would like to add:**
n/a

**Environment:**

- Cluster-api-provider-vsphere version: `master` branch
- Kubernetes version: (use `kubectl version`): 1.21
- OS (e.g. from `/etc/os-release`): n/a

**Comment by aartij17** [comment]
Resolved with PR - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1381
