### ISSUE TITLE
Reduce e2e execution time by allowing Docker to cache

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/cluster-api-provider-vsphere#1354]
We can reduce the execution time of the e2e tests by at least 30 seconds by allowing Docker to cache:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/3d8074ba7a46a82ccfa2fbd96e6de6e1308e6799/Makefile#L122-L124

The `e2e-image` Make target is executed every time `make e2e` is invoked. Passing `$(LDFLAGS)` to `e2e-image` causes `docker build` to always rebuild without using the Docker cache because `LDFLAGS` includes a date string which changes every second:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/3d8074ba7a46a82ccfa2fbd96e6de6e1308e6799/hack/version.sh#L92

I think it should be fine to remove `$(LDFLAGS)` from `e2e-image` because the commit which triggered the build can be viewed in Prow anyway, i.e. the traceability of the binary itself is important mainly in production builds.

I think it's worth considering since it enables quicker iterations when debugging e2e tests.

What do you guys think? Happy to open a PR with a fix.

**Comment by chrischdi** [comment]
We could change the line

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/3d8074ba7a46a82ccfa2fbd96e6de6e1308e6799/Makefile#L104

to use `?=` instead of `:=`.

Then a developer could set `export LDFLAGS=""` to set it to be empty.

**Comment by adityabhatia** [comment]
/close 
fixed via https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2312

**Comment by killianmuldoon** [comment]
/close

Thanks for pointing this out @adityabhatia
