### ISSUE TITLE
Broken e2e test case: storage policy

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/cluster-api-provider-vsphere#1355]
/kind bug

**What steps did you take and what happened:**

The `Cluster creation with vSphere validations` e2e test case is failing for me on `master`. Specifically, the test is failing here:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/3d8074ba7a46a82ccfa2fbd96e6de6e1308e6799/test/e2e/capv_quick_start_test.go#L96

The reason seems to be that `pbmClient.QueryAssociatedEntity()` is returning an empty slice because apparently my vSphere deployment doesn't have a matching **storage policy**.

Looking at #1141, it seems we're adding logic to create a storage policy in ec0c571de07fb1b52bfb8bbf33115a154e9ac666 but we're removing this logic in the following commit in the same PR - 4056faf6c29d8a4baaf7d70572f81284d7b96e9a.

That said, I'm wondering if the tests *assumes the existence* of a specific storage policy on the vSphere environment against which I run the tests. If it does, we may want to document this fact and possibly replace this logic with something more "portable". If it doesn't, I'm guessing the removal of this logic was a rebase error or something similar.

@gab-satchi looks like you're the author of the relevant test. In case you can shed some light on the matter - that would be great.

**What did you expect to happen:**

I expected one of the following:

- The test case should pass on `master`.
- There should be some mention of any "special" setup which has to be done in a vSphere environment for the test case to pass.

**Environment:**

- Cluster-api-provider-vsphere version: 3d8074ba
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04 LTS

**Comment by gab-satchi** [comment]
Hey @johananl, 

Thanks for raising the issue. Yes, the test does expect a storage policy already defined but it can be configured by setting `VSPHERE_STORAGE_POLICY` similar to what's being done for the [ci configuration](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/test/e2e/config/vsphere-ci.yaml#L165)

I think this can definitely be documented better in the [e2e instructions](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/master/test/e2e#environment-variables) as an extra required variable.

**Comment by johananl** [comment]
Thanks @gab-satchi.

I've set `VSPHERE_STORAGE_POLICY` to the name of a storage policy which exists in my vSphere environment and I can also see that the correct ID is stored in `spID` here:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/3d8074ba7a46a82ccfa2fbd96e6de6e1308e6799/test/e2e/capv_quick_start_test.go#L90

Still, I'm getting an empty response for `pbmClient.QueryAssociatedEntity()`. Any idea why that could happen?

>I think this can definitely be documented better in the e2e instructions as an extra required variable.

Yes, I'll open a PR for that.

**Comment by gab-satchi** [comment]
are you seeing VMs getting created on vsphere? Does the created vm have the correct storage policy attached to it?

**Comment by johananl** [comment]
Made some progress. When creating a VM **manually** and attaching an existing storage policy to it, `pbmClient.QueryAssociatedEntity()` returns a non-empty result. So, looks like the VMs which the test creates don't get the storage policy specified in `VSPHERE_STORAGE_POLICY` for some reason.

**Comment by johananl** [comment]
Update: Apparently the policies I've tried to use either had encryption or were incompatible with my chosen datastore. In both cases I couldn't create the VM via the web UI and apparently CAPV simply creates the VM without a storage policy in such cases.

**Comment by johananl** [comment]
> Hmm if a storage policy is defined and a compatible datastore isn't found, it should [block cloning the VM](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/pkg/services/govmomi/vcenter/clone.go#L212-L214). So that could be a new issue.

I'll double check and open an issue if necessary.

**Comment by johananl** [comment]
> > I think this can definitely be documented better in the e2e instructions as an extra required variable.
> 
> Yes, I'll open a PR for that.

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1358
