### ISSUE TITLE
Conversion is not completely implemented for all API types

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#1363]
/kind bug

Hey folks,
in core CAPI we have a tool called conversion-verifier which loops over all types and ensures the controller-runtime conversion interfaces are implemented correctly, i.e. it checks the types have the Hub / ConvertTo / ConvertFrom functions.

The results for CAPV are:
* type "infrastructure.cluster.x-k8s.io/VSphereClusterIdentity" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha4" marked as storage version but it's not convertible, missing Hub() method
* type "infrastructure.cluster.x-k8s.io/VSphereClusterIdentity" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/VSphereFailureDomain" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha4" marked as storage version but it's not convertible, missing Hub() method
* type "infrastructure.cluster.x-k8s.io/VSphereFailureDomain" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/VSphereClusterIdentityList" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha4" marked as storage version but it's not convertible, missing Hub() method
* type "infrastructure.cluster.x-k8s.io/VSphereClusterIdentityList" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/VSphereDeploymentZoneList" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha4" marked as storage version but it's not convertible, missing Hub() method
* type "infrastructure.cluster.x-k8s.io/VSphereDeploymentZoneList" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/VSphereFailureDomainList" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha4" marked as storage version but it's not convertible, missing Hub() method
* type "infrastructure.cluster.x-k8s.io/VSphereFailureDomainList" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods
* type "infrastructure.cluster.x-k8s.io/VSphereDeploymentZone" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha4" marked as storage version but it's not convertible, missing Hub() method
* type "infrastructure.cluster.x-k8s.io/VSphereDeploymentZone" in package "sigs.k8s.io/cluster-api-provider-vsphere/api/v1alpha3" it's not convertible, missing ConvertFrom() and ConvertTo() methods

I think it would be great to:
* implement the missing methods
* integrate the conversion-verifier in CI

The conversion-verifier can be found here:
* Code: https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/conversion-verifier
* Usage: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L339-L341 (core CAPI runs it as part of the verify job)

I can provide additional details if needed / if you want to implement this issue.

**Environment:**

- Cluster-api-provider-vsphere version: latest
- Kubernetes version: (use `kubectl version`):  -
- OS (e.g. from `/etc/os-release`):  -

**Comment by srm09** [comment]
Also, add a presubmit prow job which tests the same for every new PR raised.

**Comment by sbueringer** [comment]
@srm09 Just fyi in case you want to align, in core CAPI we only have one verify job which:
* runs scripts/ci-verify.sh, which then runs make verify
* make verify then runs all verify targets (https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L319)
