### ISSUE TITLE
Use controller-runtime setup-envtest instead of fetch_ext_bins.sh

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#1364]
/kind feature

Hey folks,

just wanted to make you aware of that there is a tool by controller-runtime which can be used to setup the controller-runtime envtest binaries (https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest).

It's already used in core CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L437-L441

I think this could be a good first issue, if you want to adopt setup-envtest.

**Environment:**

- Cluster-api-provider-vsphere version: latest
- Kubernetes version: (use `kubectl version`):  -
- OS (e.g. from `/etc/os-release`):  -

**Comment by geetikabatra** [comment]
@AartiJivrajani Can I take this up?

**Comment by AartiJivrajani** [comment]
Sure
