### ISSUE TITLE
Request-for-help on how to install ingress-nginx - LoadBalancer not getting external-ip

### ISSUE THREAD

**Issue by ninlil** [kubernetes-sigs/cluster-api-provider-vsphere#1373]
### Discussed in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/discussions/1368

<div type='discussions-op-text'>

<sup>Originally posted by **ninlil** January 24, 2022</sup>
I have created a vSphere-cluster in a VxRail vCenter (vSphere Client version 7.0.2.00500)
All nodes ready (3 master and 2 worker)

I'm running clusterctl and vsphere v1.0.2.

I then do
```sh
$ helm template ingress-nginx ingress-nginx/ingress-nginx > nginx.yaml
$ kubectl apply -f nginx.yaml
```
Everything starts fine, logs looks resonably ok, except regarding the loadbalancer-service...

then, (waiting 1+ hour) I still get:
```sh
$ kubectl get svc
NAMESPACE     NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
default       ingress-nginx-controller             LoadBalancer   10.103.209.60   <pending>     80:31925/TCP,443:30602/TCP   5h53m
default       ingress-nginx-controller-admission   ClusterIP      10.108.172.48   <none>        443/TCP                      5h53m
```

I dont know if I've missed something, if something is missing from my setup, if it's a bug, or missing feature... or what it could be.

The documentation regarding Tanzu is not helping me much either, since most of those pages talk about the "haproxy" (deprecated in cluster-api), which i'm not sure is even related to this issue (that seems to be regarding HA on the api-server)

I have tried creating a Calico-resource:
```yaml
apiVersion: crd.projectcalico.org/v1
kind: BGPConfiguration
metadata:
  name: default
spec:
  serviceLoadBalancerIPs:
  - cidr: 10.4.14.104/31
```
This didn't change anything, and the calico-controller dont log detecting a new LoadBalancer-service (annotated with matching IP)

I've also tried using MetalLB but that didn't help either.

Any help is appreciated.
</div>

**Comment by vrabbi** [comment]
Capv does not provide a solution for service type load balancer as vSphere does not offer such an API. You can use different tools like metallb,kubevip,nsx-alb, f5 etc. On top of a capv cluster to create lb services however that is out of the scope of capv itself. Haproxy was replaced by kubevip in capv a while ago but that is only for api server load balancing.
Metallb works great on capv clusters from my experience. If you are running into issues, i would suggest reaching out on the metallb channel in the k8s slack or in thier github repo as that would be a metallb issue

**Comment by ninlil** [comment]
Thanks for your answer. I've had a good talk with a colleague on this and I've changed the type from LoadBalancer to NodePort.
I will also create some tooling (kubernetes-operator) that detects the host-ip of all ingress-controllers and updates the extenal load-balancer on the correct endpoints.

/close
