### ISSUE TITLE
Add Calico flag to generate CNI resources for cluster templates

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1385]
/kind feature

**Describe the solution you'd like**
Currently, the cluster templates generated by CAPV do not deploy any CNI resources by default. This becomes a manual step when using the template to deploy clusters. Since, CAPV does not prescribe any particular CNI, but uses Calico in its e2e tests, it would make sense to include an extra flag during template generation `--calico` (just an example) to include the Calico resources as part of the CRS which is used to deploy CPI/CSI.

**Anything else you would like to add:**
As a first step, we can try to include this with the `vip` flavor and then extend it over to other flavors too.

**Environment:**

- Cluster-api-provider-vsphere version: `tip of main branch`
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

/help
/good-first-issue

**Comment by chrischdi** [comment]
/close

If this feature is still needed by someone feel free to reopen :-)

The CAPI quickstart includes deploying a CNI separately.
