### ISSUE TITLE
Add conversion-verifier to CI

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1394]
In reference to issue from [#3085](https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/3085) to track conversion-verifier addition separately.

Integrate the conversion-verifier in CI.

The conversion-verifier can be found here:

Code: https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/conversion-verifier
Usage: https://github.com/kubernetes-sigs/cluster-api/blob/main/Makefile#L339-L341 (core CAPI runs it as part of the verify job)

/good-first-issue
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by geetikabatra** [comment]
@srm09 Could you please put a label as a good first issue here. I am not allowed to do so for some reason.

**Comment by geetikabatra** [comment]
Covered by this one https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1393/files

**Comment by srm09** [comment]
/close
In response to the comment above
