### ISSUE TITLE
Update cluster-api bits to resolve the cert-manager issue

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1395]
/kind bug

**What steps did you take and what happened:**
Due to cert-manager moving repos, there is a failure in the E2E test jobs running in CAPV. Upstream CAPI has issued releases with fixes for this particular issue. We need to integrate those releases in our codebase to mitigate the failures

- [ ] Upgrade CAPI version to v1.1.0 in `default` branch and the `release-1.0` branch
- [ ] Upgrade CAPI version to v0.4.7 in the `release-0.8` branch

~Trying to figure out if any action is required for the `release-0.7` branch~

**What did you expect to happen:**
E2E tests should not be failing.

**Anything else you would like to add:**
n/a

**Environment:**

- Cluster-api-provider-vsphere version: `v1.1.0` and `v0.8.0`
- Kubernetes version: (use `kubectl version`):  n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by srm09** [comment]
/remove-kind bug
/kind feature

CAPI is cutting the new 1.1.0 release sometime this week, let's wait for that and then embark on the upgrade journey.

**Comment by srm09** [comment]
@geetikabatra Am gonna repurpose this issue to fix the failures that cert-manager repo move will bring to CAPV E2E tests

/retitle Update cluster-api bits to resolve the cert-manager issue
/remove-good-first-issue

**Comment by srm09** [comment]
Confirmed that the `release-0.7` branch does not have the cert-manager issue.
