### ISSUE TITLE
CAPV should be able to reconcile when `The vm was removed from infra`

### ISSUE THREAD

**Issue by joshrosso** [kubernetes-sigs/cluster-api-provider-vsphere#1396]
/kind feature

## Description

When a `vspheremachine` object no longer has a corresponding VM in the infrastructrue, it gets in a state where `capv-manager` will report `The vm was removed from infra`. As far as I can tell, this creates a deadlock where, attempting to delete the `Machine` object will get stuck in a `Deleting` state.

For example, consider a `Machine : wkload-ale-md-0-9747bd4d5-lrfbs`

`Machine : wkload-ale-md-0-9747bd4d5-lrfbs` : has an Infrastruct Ref to `vspheremachine: wkload-ale-worker-zw8m5`.

### Observations:

* `Machine : wkload-ale-md-0-9747bd4d5-lrfbs` is stuck in a `Deleting` state.
* `vspheremachine: wkload-ale-worker-zw8m5` has a failure message.
    ```
    Failure Message:         Unable to find VM by BIOS UUID 420c97cc-c09c-4684-45c1-ba607dac0b5a. The vm was removed from infra
    Failure Reason:          UpdateError
    ```
* `capv-manager` is reporting skipping reconcile.
    ```
    I0202 14:16:46.217370       1 vspheremachine_controller.go:313] capv-controller-manager/vspheremachine-controller/default/wkload-ale-worker-zw8m5 "msg"="Error state detected, skipping reconciliation"  
    ```
* After 24 hours, no progress is made.

### Workaround

1. Delete the vspheremachine object (the `machine` object will remain stuck!)
    ```
    kubectl delete vspheremachine wkload-ale-worker-zw8m5
    ```

1. Remove the finalizer from the corresponding machine

    ```
    kubectl patch machine/wkload-ale-md-0-9747bd4d5-lrfbs -p '{"metadata":{"finalizers":[]}}' --type=merge
    ```

1. Wait. In ~1 minute, the machine should finally be removed.

### Anything else you would like to add:

I was helping a user in [#tanzu-community-edition Kubernetes slack.](https://kubernetes.slack.com/archives/C02GY94A8KT/p1643736595699809). This project uses cluster-api vsphere under the hood.

cc @alescuderi

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
@joshrosso I might be missing the historical context, but in the past, we have always not allowed any direct modification on the underlying VM in the vCenter. This is a special case of VM modification wherein the VM might have gotten deleted/moved around. 

From the POV of the user, if the VM is gone, then no point keeping the objects around. Maybe replace it with a new VM/delete the CAPV object or some other operation. Let me think about what the resolution should be.

cc: @yastij @timmycarr looking for inputs here.

**Comment by srm09** [comment]
/assign @scdubey 
Can you think of a way that we could use to reconcile deletion of VSphereMachine objects if the VM is missing or does not exist?

**Comment by srm09** [comment]
Is there a way we could leverage MHC to get out of this state? Worth looking into that?
