### ISSUE TITLE
Run e2e and integration tests when changes are made to `go.mod` and `go.sum`

### ISSUE THREAD

**Issue by aartij17** [kubernetes-sigs/cluster-api-provider-vsphere#1400]
Currently, none of the pre-submit jobs run when changes are made to the `go.mod` and `go.sum` file. 
This might prove catastrophic in case where the `go.sum` is not updated correctly. 

We should run the `e2e` and `integration` tests as a pre-submit job when changes are made to these files

**Comment by srm09** [comment]
/close
https://github.com/kubernetes/test-infra/pull/25149 has been merged.
