### ISSUE TITLE
Move vsphere credentials from the Spec to k8s secrets

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#141]
Currently, the vsphere credentials are part of the Spec definition in plain text which is a huge security gap.
We need to move the credentials into k8s secrets to make a bit secure.

**Comment by sflxn** [comment]
@sidharthsurana This is a duplicate of issue #9.  Let's keep that issue and close this one since there are already some people on that issue and any updates we do there will ping them.
