### ISSUE TITLE
Clean up GC_KIND build variable

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/cluster-api-provider-vsphere#1415]
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/e1129cb1e676c778da495bb3f6d31190b59d0645/Makefile#L74

The `GC_KIND` variable used to control whether to tear down the Kind environment at the end of an e2e test run:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/cd5ed7f09871997e6f6eff6e30c59d1a7b6653ed/Makefile#L109

As of 7ed71271a183f72534541a8580bd3ef689f1c553 this variable is no longer used but is still defined.

We should consider doing one of the following:

1. Remove all references to the variable
2. Reintroduce the variable and ensure it works as intended

cc: @srm09 @geetikabatra

**Comment by geetikabatra** [comment]
Thanks @johananl for the issue.

**Comment by ditsuke** [comment]
@geetikabatra should this be closed now that #1446 is merged in?
