### ISSUE TITLE
Improving test coverage in pkg/identity

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1417]
/kind bug

This issue is to list out the files which are required to be tested in pkg/identity

```
sigs.k8s.io/cluster-api-provider-vsphere/pkg/identity/identity.go:42:				       GetCredentials				0.0%
sigs.k8s.io/cluster-api-provider-vsphere/pkg/identity/identity.go:115:				IsSecretIdentity			0.0%
sigs.k8s.io/cluster-api-provider-vsphere/pkg/identity/identity.go:123:				getData					0.0%
```

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
There are ginkgo tests around this package so am not sure if the coverage number that you are posting is absolutely correct. Moreover the more helpful approach to this task would be to list out the scenarios we would wanna test and list them out in the issue.

This approach of tracking the coverage for each of the functions will increase the overall number, but not sure if the tests that come outta it will be very helpful.

**Comment by srm09** [comment]
/close
This has been merged
