### ISSUE TITLE
Refactor method `GetCredentials` in the pkg/identity/identity.go file

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1441]
/kind feature

**Describe the solution you'd like**
Improve unit testing for `pkg/identity/identity.go`
This issue is a subtask of the https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1392

Individual tasks for this issue:

- [ ] Break down GetCredentials function to smaller functions `ValidatetIdentity`, `GetKey`, `GetNamespaceKey`, `MatchLabels`, `CreateSecretKey`
- [ ]  Add unit tests for each of the broken down functions

**Anything else you would like to add:**
n/a

/area testing
/help
/good-first-issue

**Comment by VibhorChinda** [comment]
Want to work on this.
