### ISSUE TITLE
Add kubescape security scanner in e2e tests 

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1442]
/kind feature

CAPV should run a Kubernetes job in e2e with the open source [kubescape](https://github.com/armosec/kubescape) security scanner and logs the results to stdout. 

Inspired by https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1793
Above should be followed by a prow job in test-infra which runs kubescanner in CI.

**Describe the solution you'd like**
n/a

**Anything else you would like to add:**
n/a

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
Instead of adding this as a CI job, let us start with having a custom doc on how to run a kubescape scan against a cluster created by CAPV.
The next logical step could be to augment the post-deploy job to run kubescape scanner after every successful merge and post the details in the job.
