### ISSUE TITLE
Add README about flavors

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1457]
/kind feature

There is no  README about what is the role of flavors in cluster-api-provider-vsphere and what all flavors are available.

This can be used as a reference.
https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/templates/flavors/README.md

/help
/good-first-issue

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by aartij17** [comment]
@sayantani11 If you want to talk about this issue, let me know! I can provide some more context 😄

**Comment by sayantani11** [comment]
> @sayantani11 If you want to talk about this issue, let me know! I can provide some more context 😄

Hey!! @aartij17 can we schedule a call for this one will be helpful

**Comment by geetikabatra** [comment]
@sayantani11 let us sync up to wind this up.
