### ISSUE TITLE
Add unit tests for vim machine reconciliation

### ISSUE THREAD

**Issue by Ankitasw** [kubernetes-sigs/cluster-api-provider-vsphere#1469]
/area testing

Add tests for below scenarios in vimmachine.go:

1. Successfully reconcile vim machine with following checks:
- Check if VSphereMachine status is Ready.
- Check if VsphereMachine status contains network details like mac address, ip addresses, whether connection established or not etc.
- Check if VSphereMachine spec contains provider ID
- Check if VMProvisionedCondition is set.
2. Should ignore reconciliation in below cases:
- if the ownerReferences is set in VsphereVM spec.
- if cluster and machine labels are set in VsphereVM spec.
- if bootstrap ref is set in VsphereVM spec.
- if vsphere machine's VM clone spec is set in VsphereVM spec.
- if failure domains(if present) are set in VsphereVM spec.
3. Reconcile failure scenarios:
- Failure in reconciling network, check if status and conditions corresponds to failed state.
- Failure in reconciling provider ID
(Can be thought of more error scenarios if time persists)
4. Successfully reconcile vim machine deletion:
- Check if VMProvisionedCondition is set to false.
- Check if vim machine is actually deleted by fetching the vim machine object.

**Comment by Ankitasw** [comment]
Subset of #1392

**Comment by geetikabatra** [comment]
I have closed the duplicate issue.

**Comment by srm09** [comment]
No work is planned on this one.
/close
