### ISSUE TITLE
Implement unit test cases for extra package

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1471]
/area testing

Implement unit tests for the public methods under the `pkg/services/govmomi/extra` package. This package is mainly used to set the cloud-init data which gets leveraged on VM startup.

/help
/good-first-issue

**Comment by DiptoChakrabarty** [comment]
hi @srm09 wanna take this up
/assign

**Comment by geetikabatra** [comment]
@DiptoChakrabarty Let us find you another good first issue. This will be worked upon by @ditsuke

**Comment by geetikabatra** [comment]
@DiptoChakrabarty My apologies! I was under the impression that this was created for Tushar, who is actively working on unit tests. Feel free to reach out to me over slack or here. I will help you pick up and work on an issue you feel is right for you.

**Comment by DiptoChakrabarty** [comment]
> @DiptoChakrabarty Really sorry for the mid-communication. You were correct in assuming that any unassigned issues with the help wanted label can be worked upon. We highly appreciate you wanting to be involved with the project.
> 
> Feel free to go through the list of issues and pick up anything that you might find interesting.

No problem @srm09 I understand

**Comment by DiptoChakrabarty** [comment]
> @DiptoChakrabarty Would you like to pick up this one #1478 ?

yes sure thank you @geetikabatra
