### ISSUE TITLE
Implement unit test cases for metadata package

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1472]
/area testing

Implement unit tests for the public methods under the pkg/services/govmomi/metadata package. This package is mainly used to create tag/categories used when using the auto-tagging feature for `VSphereFailureDomain` objects.

/help
/good-first-issue

**Comment by geetikabatra** [comment]
@ditsuke You might want to take a look at this one.

**Comment by ditsuke** [comment]
@geetikabatra thanks for tagging. Would like to be assigned to this.
