### ISSUE TITLE
[Refactor] Move CAPI related E2E tests to one place.

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1476]
/kind bug

**What steps did you take and what happened:**

Currently, all CAPI related E2E tests are written in different files. The idea is to consolidate all the CAPI related E2E tests in one place. This will bring more structure to the code base.

**What did you expect to happen:**
N/A

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
Like we talked about, let us keep the refactoring for a later point in time until we have stable E2E tests running for a period of time.
/lifecycle frozen
/remove-kind bug
/kind cleanup
/area testing

**Comment by killianmuldoon** [comment]
/close

I'm taking a look at restructuring some of the test directory - starting with https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2251. Will take this into account when thinking about consolidating existing tests.
