### ISSUE TITLE
Add unit test case for the package vimmachine

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1478]
/area testing
/help
/good-first-issue

There are missing tests for the following methods in `pkg/services/vimmachine.go`
The package is primarily used for vsphere VM lifecycle and syncing with VSphereMachine types.

- [ ] ReconcileNormal
- [ ] ReconcileDelete

**What steps did you take and what happened:**
N/A

**What did you expect to happen:**
N/A

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by Ankitasw** [comment]
@geetikabatra i think there might be some confusion, there is already an issue for the same https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1469

**Comment by geetikabatra** [comment]
Closing this, as this is duplicate. https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1469
