### ISSUE TITLE
Add legacy `capw` labels to VirtualMachine for backward compatibility

### ISSUE THREAD

**Issue by lubronzhan** [kubernetes-sigs/cluster-api-provider-vsphere#1483]
/kind feature

**Describe the solution you'd like**
The label [clusterSelectorKey](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/fae6ef88467e608665e2902e2bb0aaeb4cee67ed/pkg/services/vmoperator/control_plane_endpoint.go#L40) is added to the Machine Object. The label used to be `capw.vmware.com` instead of `capv.vmware.com`. This label, as well as `nodeSelectorKey` are consumed by other components.
Directly replacing the key name of the label could cause disruption during upgrade.
In order to provide a smooth upgrade experience, we should have a deprecating policy about this `capw` label instead of directly replacing it.

**Proposal:**
* Add `capw` and  `capv` labels to Machine for 1 or 2 major releases.
* Remove this `capw` release once most customers are using new CAPV, and other component that consumes `capv` flag.

**Updates:**
* While waiting for PM's input on Deprecation process, start the code change first

**Anything else you would like to add:**
Cloud Provider vSphere also [added capw labels ](https://github.com/kubernetes/cloud-provider-vsphere/blob/d5f062858935b9c50b0e8e53463b6985ca34494c/pkg/cloudprovider/vsphereparavirtual/vmservice/vmservice.go#L41-L44). But it's for label selectors. So Cloud Provider vSphere should directly change the capw to capv label.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
@aartij17 Pinging you in case Lubron needs an assist.

**Comment by srm09** [comment]
/close
Merged via https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1489
