### ISSUE TITLE
Refactor provisioner templates into discrete files

### ISSUE THREAD

**Issue by frapposelli** [kubernetes-sigs/cluster-api-provider-vsphere#149]
Currently, all the templates are declared as raw string literals under `pkg/cloud/vsphere/provisioner/common/templates.go`, for better readability and code hygiene, we should refactor those into discrete files.

**Comment by moshloop** [comment]
I am happy to submit a PR for this using [konfigadm](https://github.com/moshloop/konfigadm) to generate the cloud-init ?

**Comment by akutz** [comment]
Hi @moshloop,

I am going to close this issue as literally all those templates are going away as we pull in bits from CAPA. Thank you though!
