### ISSUE TITLE
Add legacy capw labels to default network for backward compatibility

### ISSUE THREAD

**Issue by lzhanghe** [kubernetes-sigs/cluster-api-provider-vsphere#1493]
/kind feature

**Describe the solution you'd like**
Currently, CAPV is using "capv.vmware.com/is-default-network" label [https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/8dd957d665c0aceca8be9be1f9aa916ff8a9fcc5/pkg/services/network/network.go#L45](url) to find the default network. During an upgrade where legacy components are still running, "capvw.vmware.com/is-default-network" is still in use. CAPV only looks for "capv.vmware.com/is-default-network" label  could cause disruption during an upgrade since CAPV would not be able to find the network with "capw.vmware.com/is-default-network" label. 

Proposal:
CAPV is able to discover both "capv.vmware.com/is-default-network" labeled  and "capw.vmware.com/is-default-network" labeled network for 1 or 2 major releases.
Remove the ability to find capw.vmware.com/is-default-network" labeled network once the network is "capv.vmware.com/is-default-network" labeled only. 

**Anything else you would like to add:**
The deprecation of the "capw.vmware.com/is-default-network" label will most likely be the same to the https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1483 issue.

**Comment by srm09** [comment]
@srm09 Add more description around the use case and the solution needed for this one.

**Comment by lzhanghe** [comment]
@srm09 thanks for the comments. Updated the issue. Please let me know if anything is unclear. Thanks!

**Comment by srm09** [comment]
Following the same deprecation policy outlined in #1483
