### ISSUE TITLE
Investigate why the description of all the tests are not logged

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1496]
/kind bug

Currently, there is a lot of unevenness in logging. Some unit tests show descriptions of the tests, while others go completely unnoticed.
```

Please refer to the following.
=== RUN   TestIdentity
Running Suite: Identity Suite
=============================
Random Seed: 1648482245
Will run 9 of 9 specs.

•••••••••
```

```
--- PASS: TestIdentity (9.39s)
PASS
ok  	sigs.k8s.io/cluster-api-provider-vsphere/pkg/identity	12.629s
=== RUN   TestOptions_GetCredentials
=== RUN   TestOptions_GetCredentials/username_&_password_with_no_special_characters
=== RUN   TestOptions_GetCredentials/username_with_UPN_
--- PASS: TestOptions_GetCredentials (0.00s)
    --- PASS: TestOptions_GetCredentials/username_&_password_with_no_special_characters (0.00s)
    --- PASS: TestOptions_GetCredentials/username_with_UPN_ (0.00s)
PASS
ok  	sigs.k8s.io/cluster-api-provider-vsphere/pkg/manager	1.333s
```

There is a lot of ambiguity in finding out which one is the `pkg/Identity` test. The first example logs that it ran nine specs without any description of what test ran, and the second example logs TestIdentity even though it is not exactly a test of pkg/identity; it is a test to check the functionality of `pkg/manager`

**What steps did you take and what happened:**

Above can be observed in logs after running the `make test`

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Further investigation is required to understand why this behaviour happens and take measures to rectify it.
This is a follow up of the discussion happened in CAPV office hours.
**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by geetikabatra** [comment]
@ditsuke Can you comment on this one, so that bot assigns it to you.

**Comment by ditsuke** [comment]
@geetikabatra 
After some investigation it appears these inconsistencies are due to our mixed usage of vanilla Go `testing` and `ginkgo` tests. As an example:
- `go test -v ./...` on my [PR](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1475) for the metadata package (uses `ginkgo`):
	<details>
	  <summary>Visual</summary>

	![image](https://user-images.githubusercontent.com/72784348/161092571-113b29af-5907-4377-bedd-2349e84bb4a1.png)
	</details>

	```
	=== RUN   TestMetadata
	Running Suite: Metadata Suite
	=============================
	Random Seed: 1648739658
	Will run 4 of 4 specs

	2022/03/31 20:44:20 tag not found: testTag
	++++
	Ran 4 of 4 Specs in 1.898 seconds
	SUCCESS! -- 4 Passed | 0 Failed | 0 Pending | 0 Skipped
	--- PASS: TestMetadata (1.90s)
	PASS
	ok      sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/metadata  2.020s
	```

- `go test -v ./...` on `pkg/services/govmomi/net` (vanilla Go `testing`):
	<details>
	<summary>Visual</summary>

	![image](https://user-images.githubusercontent.com/72784348/161092125-6a24bf04-b06d-4274-8a2f-512205400283.png)
	</details>

	```
	=== RUN   TestErrOnLocalOnlyIPAddr
	=== RUN   TestErrOnLocalOnlyIPAddr/valid-ipv4
	=== RUN   TestErrOnLocalOnlyIPAddr/valid-ipv6
	=== RUN   TestErrOnLocalOnlyIPAddr/localhost
		net_test.go:71: failed to validate ip addr=127.0.0.1: loopback
	=== RUN   TestErrOnLocalOnlyIPAddr/link-local-unicast-ipv4
		net_test.go:71: failed to validate ip addr=169.254.2.3: link-local-unicast
	=== RUN   TestErrOnLocalOnlyIPAddr/link-local-unicast-ipv6
		net_test.go:71: failed to validate ip addr=fe80::250:56ff:feb0:345d: link-local-unicast
	=== RUN   TestErrOnLocalOnlyIPAddr/link-local-multicast-ipv4
		net_test.go:71: failed to validate ip addr=224.0.0.252: link-local-mutlicast
	=== RUN   TestErrOnLocalOnlyIPAddr/link-local-multicast-ipv6
		net_test.go:71: failed to validate ip addr=FF02:0:0:0:0:0:1:3: link-local-mutlicast
	--- PASS: TestErrOnLocalOnlyIPAddr (0.00s)
		--- PASS: TestErrOnLocalOnlyIPAddr/valid-ipv4 (0.00s)
		--- PASS: TestErrOnLocalOnlyIPAddr/valid-ipv6 (0.00s)
		--- PASS: TestErrOnLocalOnlyIPAddr/localhost (0.00s)
		--- PASS: TestErrOnLocalOnlyIPAddr/link-local-unicast-ipv4 (0.00s)
		--- PASS: TestErrOnLocalOnlyIPAddr/link-local-unicast-ipv6 (0.00s)
		--- PASS: TestErrOnLocalOnlyIPAddr/link-local-multicast-ipv4 (0.00s)
		--- PASS: TestErrOnLocalOnlyIPAddr/link-local-multicast-ipv6 (0.00s)
	PASS
	ok      sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/net       0.061s
	```

**Comment by geetikabatra** [comment]
I believe we should be using any one of those. This topic requires a broader discussion. From the visuals above, I am more in favour of `vanilla go testing`. Since it provides a detailed output. 
@ditsuke Could you also investigate how can we have more information if we use ginkgo. Try looking into other providers as well as core cluster api.
