### ISSUE TITLE
Wrongly committed file

### ISSUE THREAD

**Issue by lubronzhan** [kubernetes-sigs/cluster-api-provider-vsphere#1498]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
This file should be removed 
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/github.com/lubronzhan/cluster-api-provider-vsphere/apis/v1alpha3/zz_generated.conversion.go

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by geetikabatra** [comment]
We should close this as the referenced PR is merged.
