### ISSUE TITLE
`Make modules` throw error with Go 1.17 

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1509]
/kind bug

With Go version 1.17. Make modules throw a compatibility error.

```
go mod tidy
go mod tidy: error loading go 1.16 module graph: sigs.k8s.io/cluster-api/test@v1.1.3 requires
	sigs.k8s.io/cluster-api@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000

If reproducibility with go 1.16 is not needed:
	go mod tidy -compat=1.17
For other options, see:
	https://golang.org/doc/modules/pruning
make: *** [modules] Error 1
```

Quick fix in Make file

```
.PHONY: modules
modules: ## Runs go mod to ensure proper vendoring
	go mod tidy -compat=1.17
	cd $(TOOLS_DIR); go mod tidy

```
**What steps did you take and what happened:**
N/A

**What did you expect to happen:**

**Anything else you would like to add:**
N/A

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by geetikabatra** [comment]
@ditsuke, could you investigate and validate this issue. You could change go versions and check if this stands true for you.

**Comment by ditsuke** [comment]
> @ditsuke, could you investigate and validate this issue. You could change go versions and check if this stands true for you.
> 

@geetikabatra thanks for creating this! Just recently I encountered this issue while setting up CAPV on a remote development environment with go 1.17, so I was contemplating discussing this. I'll investigate and report back.

**Comment by ditsuke** [comment]
@geetikabatra it appears we need a `replace` directive for CAPI in our `go.mod`. For reference, [here's a similar issue (#1590)](https://github.com/vmware-tanzu/tanzu-framework/issues/1590) in Tanzu Framework.

/assign
