### ISSUE TITLE
Published OVAs are obsolete

### ISSUE THREAD

**Issue by sathieu** [kubernetes-sigs/cluster-api-provider-vsphere#1511]
/kind bug

(this is also a security bug, and also an enhancement request 😀 )

**What steps did you take and what happened:**

Go to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/README.md#kubernetes-versions-with-published-ovas. Currently shows:

> Kubernetes | CentOS 7 | Ubuntu 18.04 | Photon 3
> -- | -- | -- | --
> v1.17.16 | ova, sha256 | ova, sha256 | ova, sha256
> v1.18.14 | ova, sha256 | ova, sha256 | ova, sha256
> v1.19.6 | ova, sha256 | ova, sha256 | ova, sha256
> v1.20.1 | ova, sha256 | ova, sha256 | ova, sha256

Those versions are outdated and have security flaws.

**What did you expect to happen:**

Images to be updated when new k8s are released.

**Anything else you would like to add:**

There are more up to date OVAs from tanzu-community-edition: [Tanzu Community Edition 0.11.0 product page](https://customerconnect.vmware.com/downloads/get-download?downloadGroup=TCE-0110). NB: those require a VMware account.

**Comment by codenrhoden** [comment]
@kkeshavamurthy let's chat this week and get you set up to build/publish these. We should set up a pipeline to do them regularly.

**Comment by codenrhoden** [comment]
I'll go ahead and rebuild these now with the latest patch releases.

I can also add Ubuntu 20.04 images. Should we drop CentOS 7? Does anyone use those? What about Ubuntu 18.04?

**Comment by MaxRink** [comment]
I would add 20.04, given that april 21st is the release date for 22.04 (which will need some work in the image builder, as the installer changes )
