### ISSUE TITLE
Enforce some standards for PR titles

### ISSUE THREAD

**Issue by ditsuke** [kubernetes-sigs/cluster-api-provider-vsphere#1548]
/kind feature

**Describe the solution you'd like**
CAPI uses the [kubernetes-sigs/kubebuilder-release-tools](https://github.com/kubernetes-sigs/kubebuilder-release-tools) action to enforce some standards in PR titles. These standards require emoji prefixes to PR titles, which make release note generation and visually scanning through PRs convenient.

**Anything else you would like to add:**
This should be a really straightforward addition (a single workflow), happy to take this up myself or have a new contributor work on it once the issue is validated.

**Comment by AectannArd** [comment]
Hi @ditsuke 
Could you please assign the issues to me please. It should be quite straightforward to handle

**Comment by ditsuke** [comment]
@AectannArd unfortunately not, I'll give it a look for you but we'll need a maintainer for approval.
