### ISSUE TITLE
[Refactor] Use pointer values for fields.

### ISSUE THREAD

**Issue by geetikabatra** [kubernetes-sigs/cluster-api-provider-vsphere#1549]
All the fields defined in `types.go` should be of pointer type, unless it is very much necessary to keep it as is.
This would help in better error handling. It is adopted across cluster api wide and should be adopted by CAPV also.

This will for example solve the problem of nil values in `int32`. the nil and the zero values (by Go standards) have semantic differences. Hence if the field of type `int32` is not present, it is not passed as nil and hence cannot be compared. 

https://cluster-api.sigs.k8s.io/contributing?highlight=optional#optional-vs-required

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
Do you mind listing out the API types, and we could discuss and tackle them as part of separate PRs?
