### ISSUE TITLE
e2e test enhancement, support parallel job running

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/cluster-api-provider-vsphere#155]
the current e2e test only support 1 Prow and 1 debug job running at the same time.
because the bootstrap cluster is based on vm snapshot.

we can use clone method to avoid this limitation.

note: although ideally we also want to use clusterapi delete to properly do clean up.
so we can move away from deleting VM by e2e.sh (which is a workaround)

**Comment by frapposelli** [comment]
maybe consider pulling this into `v1alpha1` as opportunistic
