### ISSUE TITLE
IPAM support for CAPV

### ISSUE THREAD

**Issue by aartij17** [kubernetes-sigs/cluster-api-provider-vsphere#1550]
Umbrella issue for all tasks required to implement IPAM support for CAPV
This issue will be updated over time

- [ ] IPAM Contract implementation - https://github.com/kubernetes-sigs/cluster-api/pull/6313

**Comment by schrej** [comment]
Implementation is merged and part of 1.2.0-rc.0
API types are located at `sigs.k8s.io/cluster-api/exp/ipam/api/v1alpha1`.
