### ISSUE TITLE
Helm to manage cluster deployments

### ISSUE THREAD

**Issue by ugiraud** [kubernetes-sigs/cluster-api-provider-vsphere#1553]
/kind feature

**Describe the solution you'd like**

A helm chart to manage the created clusters, to simplify the usage of the cluster api and capv CRDs

**Anything else you would like to add:**

We are maintaining a helm chart to do this and more, like deploying calico-cni with the clusterresourceset, and opening some clusterApi features through the chart values.yaml, and we would like to propose it to the community.

The helm chart can be found there :
- https://artifacthub.io/packages/helm/cluster-api-vsphere/cluster-api-vsphere
- https://gitlab.com/labo-pe/capv-helm-chart/

What do you think about telling capv users that they could use a helm chart to manage the creation/update/rollouts of their clusters?
Should/could we add a section in the capv project's README.md file pointing to this and explaining the usage?

**Comment by srm09** [comment]
@srm09 to post a reply on this one.
