### ISSUE TITLE
Bad vCenter Credentials seems to cause lots of idle connection

### ISSUE THREAD

**Issue by ninlil** [kubernetes-sigs/cluster-api-provider-vsphere#1569]
If your vCenter-account doesn't have enough access to "Sessions" you might end up with a lot of idle connections in vCenter, eventually causing service-outage.

Please add a link to the "Required Permissions for the vSphere Account" section in https://tanzucommunityedition.io/docs/v0.10/ref-vsphere/

This is especially important when Keep-Alive is active (default since last(?) version)

Seems to be caused in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/177c0bb52bd805588308af0bbcba6e5bfeb39670/pkg/session/session.go#L228
If the "SessionIsActive" is denied (by not being authorized) it seems to stay active and not getting it's "Logout"

**Comment by srm09** [comment]
Although the symptom is different, this seems to be a similar problem as https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1552
