### ISSUE TITLE
Add a test to verify scaling issues with sessions

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1578]
/kind feature

**Describe the solution you'd like**
We have recently received a couple of bugs around sessions not being cleaned up and a large number of sessions lying around causing vCenter failures. This issue is to track the activity for implementing a test to verify this behavior and possibly reduce this friction in the future.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by geetikabatra** [comment]
@srm09 How can I replicate this issue with basic Shepherd env?

**Comment by srm09** [comment]
With a fully functional vCenter you could let the session expire and see if a new one gets created in its place, and what happens to the older one. You could create multiple username/password combinations to correctly identify the sessions created for each cluster.

**Comment by srm09** [comment]
Removing this one for now, I could not figure out a better way to add a meaningful scale e2e test for this one. Also, we have addressed the issues of leaking vCenter sessions in #1767 so this is not a pressing issue anymore.
/close
