### ISSUE TITLE
capv-controller-manager crashes randomly and webhook becomes unavailable

### ISSUE THREAD

**Issue by RnkeZ** [kubernetes-sigs/cluster-api-provider-vsphere#1588]
/kind bug

**What steps did you take and what happened:**
Have a provider deployed in AKS cluster and try to increase the number of replicas for a MachineDeployment 

**What did you expect to happen:**
New VM is provisioned and joined to the cluster

**Anything else you would like to add:**
We are running our management cluster in AKS and it's deploying a cluster to vSphere (on-premises). We are not using DHCP so we developed a small controller that patches the VSphereMachine ipAddrs field, so Machines are initially stuck in "Waiting for static IP" status until our controller sets the static IP. This is the error our controller receives:
```
Internal error occurred: failed calling webhook "default.vspheremachine.infrastructure.cluster.x-k8s.io": failed to call webhook: Post "[https://capv-webhook-service.capv-system.svc:443/mutate-infrastructure-cluster-x-k8s-io-v1beta1-vspheremachine?timeout=10s](https://capv-webhook-service.capv-system.svc/mutate-infrastructure-cluster-x-k8s-io-v1beta1-vspheremachine?timeout=10s)": no endpoints available for service "capv-webhook-service"
```
Error log in the capv-controller-manager, the reason why webhook is unavailable:
[capv-controller-manager-6fdfb7977c-k2lfq.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/9220980/capv-controller-manager-6fdfb7977c-k2lfq.log)

**Environment:**

- Cluster-api-provider-vsphere version: v1.3.1
- Kubernetes version: (use `kubectl version`): 1.23.8
- OS (e.g. from `/etc/os-release`): Linux Mint

**Comment by srm09** [comment]
We recently pushed a change to the `main` branch in the PR #1583 which changed the logic around the failing line. My thought is that this change should mitigate the above failure, which originally was occurring in a logger statement since an incorrect object was being returned.
We are on track to release the newer version before the end of this month which should fix this error. Thanks!

**Comment by RnkeZ** [comment]
Great, looking forward to check out the new version.

**Comment by srm09** [comment]
Actually this is the PR that has the fix https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1622
It was a race condition that was causing this failure. Will cut a release today which has the fix.

**Comment by srm09** [comment]
This is a part of the 1.4.0 and 1.4.1 release for CAPV.
/close
