### ISSUE TITLE
VMs wouldn't power on when using a storage policy

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/cluster-api-provider-vsphere#1601]
/kind bug

**What steps did you take and what happened:**
I tried running an e2e test using `GINKGO_FOCUS="\[PR-Blocking\]" make e2e` and the test timed out because the controller VM gets created but stays powered off. Further investigation showed that the CAPV controller never progresses past the following line:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/a7b6edc14ebc13053cac82a6d458c5eaa6eebfc7/pkg/services/govmomi/service.go#L131

This in turns is caused by the fact that the following call never returns:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/a7b6edc14ebc13053cac82a6d458c5eaa6eebfc7/pkg/services/govmomi/service.go#L322

**What did you expect to happen:**
I expected the VM to power on and the test to proceed.

**Anything else you would like to add:**
I was able to isolate the bug and it's either a problem in `govmomi` or a problem on the vSphere server side. I've opened an upstream issue: https://github.com/vmware/govmomi/issues/2929

Workaround: Setting the `VSPHERE_STORAGE_POLICY` variable to an empty string makes the test converge.

The bug seems to occur also when creating clusters manually, i.e. it isn't an e2e-specific thing.

**Environment:**

- Cluster-api-provider-vsphere version: `main` at d2494c3c
- Kubernetes version: (use `kubectl version`): n/a
- OS (e.g. from `/etc/os-release`): n/a

**Comment by srm09** [comment]
Since there has been no movement on the govmomi issue that's linked above, this would save you from re-adding the label over and over.
/lifecycle frozen

**Comment by chrischdi** [comment]
Is the root-cause here that the used file https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/test/e2e/config/vsphere-dev.yaml#L153 or https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/test/e2e/config/vsphere-ci.yaml#L147 did refer a storage policy which did not exist in the environment?

So there would be two issues:

* Document better how to run the E2E tests on a custom environment (especially about the storage policy variable)
* Check handling / reproduce the issue of setting a storage policy which does not exist

**Comment by johananl** [comment]
I'd say the root cause is the upstream issue https://github.com/vmware/govmomi/issues/2929, but still I opened this issue here because the upstream issue affects CAPV developers and it isn't obvious right away what is causing the problem.

Both of your suggested points make sense to me @chrischdi.

**Comment by sbueringer** [comment]
@johananl Wondering if this PR potentially solves/changes the issue: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2467

**Comment by johananl** [comment]
@sbueringer the govmomi bug was never addressed and at some point I got tired of doing `remove-lifecycle stale`...

Looking at #2467, we no longer call the problematic govmomi function, however since we don't know the root cause I can't be certain the problem is gone.

Unfortunately, I don't have access to a vSphere environment on which I can try to reproduce this right now. As far as I'm concerned we can close this, especially given that there seems to be no traction here nor on the govmomi issue.

**Comment by sbueringer** [comment]
Hm yeah. It's hard to tell without being able to reproduce it what the problem is.

Is your environment simila to what is described on 2467?
> we have figured out this call is too expensive for environments with a lot of resources, like more than 10k resources.

**Comment by johananl** [comment]
Maybe, I'm not sure what "resource" means in this context. I also don't have full visibility over the environment since it's managed by my employer for multiple purposes and therefore I didn't have admin privileges.

**Comment by sbueringer** [comment]
Alright!  Let's close this issue for now. Please re-open in case you (or anyone else seeing this in the future) observes this behavior with a CAPV version including #2467

**Comment by johananl** [comment]
SGTM, thanks for consistently being a very reliable maintainer @sbueringer 🙏

**Comment by sbueringer** [comment]
Thank you! :)
