### ISSUE TITLE
calico-node pods are crashlooping in e2e tests

### ISSUE THREAD

**Issue by johananl** [kubernetes-sigs/cluster-api-provider-vsphere#1605]
/kind bug

**What steps did you take and what happened:**

Run the e2e tests while skipping resource cleanup as follows:

```
SKIP_RESOURCE_CLEANUP=true GINKGO_FOCUS="\[PR-Blocking\]" make e2e
```

Get the kubeconfig of the management cluster:

```
kind get kubeconfig --name $(kind get clusters | head -n 1) > /tmp/kind-kubeconfig
```

Get the kubeconfig of the workload cluster:

```
export KUBECONFIG=/tmp/kind-kubeconfig
clusterctl get kubeconfig quick-start-gf4dbv -n quick-start-x9uf43 > /tmp/workload-kubeconfig
```

Wait for the workload cluster to converge on vSphere, then check the pod status on the workload cluster:

```
export KUBECONFIG=/tmp/workload-kubeconfig
kubectl get pods -A
```

Output:

```
NAMESPACE     NAME                                               READY   STATUS              RESTARTS        AGE
kube-system   calico-kube-controllers-56d67c99f7-6v2g8           0/1     ContainerCreating   0               54m
kube-system   calico-node-d6bqg                                  0/1     CrashLoopBackOff    15 (27s ago)    53m
kube-system   calico-node-n846s                                  0/1     CrashLoopBackOff    15 (2m7s ago)   54m
kube-system   coredns-64897985d-pfnd4                            0/1     ContainerCreating   0               55m
kube-system   coredns-64897985d-qm7gd                            0/1     ContainerCreating   0               55m
kube-system   etcd-quick-start-gf4dbv-vwc76                      1/1     Running             0               55m
kube-system   kube-apiserver-quick-start-gf4dbv-vwc76            1/1     Running             0               55m
kube-system   kube-controller-manager-quick-start-gf4dbv-vwc76   1/1     Running             0               55m
kube-system   kube-proxy-755z7                                   1/1     Running             0               55m
kube-system   kube-proxy-n5qgv                                   1/1     Running             0               53m
kube-system   kube-scheduler-quick-start-gf4dbv-vwc76            1/1     Running             0               55m
kube-system   kube-vip-quick-start-gf4dbv-vwc76                  1/1     Running             0               55m
kube-system   vsphere-cloud-controller-manager-h9zvb             1/1     Running             0               53m
kube-system   vsphere-cloud-controller-manager-rhfxm             1/1     Running             0               54m
kube-system   vsphere-csi-controller-bc4676cd9-8wp4g             0/5     ContainerCreating   0               54m
kube-system   vsphere-csi-node-2qfd2                             0/3     ContainerCreating   0               53m
kube-system   vsphere-csi-node-mlvhs                             0/3     ContainerCreating   0               54m
```

**What did you expect to happen:**
I expected the workload cluster pods to be ready.

**Anything else you would like to add:**
Note that this issue **isn't** failing the test because the test doesn't validate pod status, it only checks for a successful cluster creation.

**Environment:**

- Cluster-api-provider-vsphere version: `main` as of `9ffa6d8f6a606fe1457317b235551c7a5c74850f`.
- Kubernetes version: (use `kubectl version`): `v1.23.5`
- OS (e.g. from `/etc/os-release`): `Ubuntu 20.04 LTS`

**Comment by johananl** [comment]
Replacing https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/test/e2e/data/cni/calico/calico.yaml with https://github.com/projectcalico/calico/blob/v3.24.0/manifests/calico.yaml seems to solve the problem.

**Comment by srm09** [comment]
The current e2e suite has been passing for all existing and new PRs, am unsure if this has something to do with the calico version in use.

**Comment by johananl** [comment]
> The current e2e suite has been passing for all existing and new PRs, am unsure if this has something to do with the calico version in use.

Hey @srm09 🙂 That's right, the tests are passing because AFAICT they don't check pod status. See my comment in the description:

>Note that this issue isn't failing the test because the test doesn't validate pod status, it only checks for a successful cluster creation.

Do you think we should ignore the pod status in the e2e tests?

**Comment by srm09** [comment]
CAPV concerns itself with making sure that operational Kubernetes clusters can be deployed with vSphere. Without an operational CNI, the cluster never moves into a workable state,  so maybe we should consider adding verification of pod status in our tests as well.

**Comment by johananl** [comment]
Yes, that makes sense to me. Let me take a quick look into it and/or open an issue to track this.
