### ISSUE TITLE
Where to execute "kubectl apply -f infrastructure-components-supervisor.yaml "

### ISSUE THREAD

**Issue by ruifaling** [kubernetes-sigs/cluster-api-provider-vsphere#1631]
I just started to contact this project and want to build my own environment. In release, I found two deployed yaml files (infrastructure components supervisor. yaml

And infrastructure-components.yaml

）Where are the two files executed respectively (there is no public network environment, and the environment cannot be deployed through clusterctl)

**Comment by srm09** [comment]
Hi @ruifaling welcome to the CAPV community and thanks for raising this issue. 
The 2 infrastructure components yaml are to be used separately. The `infrastructure-components.yaml` deploys the CRDs and controllers responsible for interaction with the classical CAPV resources under the `infrastructure.cluster-x.k8s.io` API group. It is responsible for creating CAPI clusters with the classic govmomi based vCenter APIs.

Whereas the `infrastructure-components.yaml` deploys the CRDs and controllers responsible for interaction with the CAPV resources under the `vmware.infrastructure.cluster-x.k8s.io` API group. These are responsible for creating [Supervisor cluster](https://docs.vmware.com/en/VMware-vSphere/7.0/vmware-vsphere-with-tanzu/GUID-21ABC792-0A23-40EF-8D37-0367B483585E.html) based CAPI clusters.

**Comment by srm09** [comment]
To deploy classic CAPV through `clusterctl`, follow the guide https://cluster-api.sigs.k8s.io/user/quick-start.html
You will need access to a vCenter environment and CAPV based images, [example](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/#kubernetes-versions-with-published-ovas)

**Comment by ruifaling** [comment]
> Reference

Thanks

**Comment by srm09** [comment]
/close
Feel free to open another one in case of other questions.
