### ISSUE TITLE
Feature: support to inject custom trusted certs into the nodes

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#165]
Often, we need the ability to inject custom CA certs into the machines so that the non-standard CA signed certs can be trusted on the created machines for various reasons.

The proposal is as follows:
- Add a new optional field named `TrustedCerts` to the `MachineSpec`. This field would be a list of base64 encoded custom certs that would be added to the instance's trusted CA certificates for SSL/TLS trust establishment.

This value if present in the spec is then passed on the cloud-init to distribute the certs on the instance

**Comment by craigtracey** [comment]
Has consideration been given to other means of accomplishing this? I think there could be two alternatives that would, perhaps, remove the need for an implementation-specific modification to the current API types.  

The first would be to support immutable images that may be provided by the user. (This would obviate the need for runtime OS configuration, and provide for support beyond just Debian/Ubuntu). In the case of user-provided images, CA certs could be added at the time. (I would be happy to help with this effort, and can point at existing work to get us there.)

Alternatively, there may be opportunity for allowing a full cloud-init template. Users may want to additional runtime configurations (ie. additional users, keys, etc.), and a `CloudInit` attribute in the `Machine` and/or `Cluster` specs could be used to provide broader access than just `TrustedCerts`.

**Comment by sidharthsurana** [comment]
@craigtracey thanks for the comment. Apologies for the late reply.
> Has consideration been given to other means of accomplishing this? I think there could be two alternatives that would, perhaps, remove the need for an implementation-specific modification to the current API types.

Not that I am aware of other than your comment here.
 
> The first would be to support immutable images that may be provided by the user. (This would obviate the need for runtime OS configuration, and provide for support beyond just Debian/Ubuntu). In the case of user-provided images, CA certs could be added at the time. (I would be happy to help with this effort, and can point at existing work to get us there.)

The immutable image is kind of possible in the current implementation by setting the property `preloaded: true` in the spec. With this the script run on the machines only include the configuration part and not the install parts. The generation of these  I think there are 2 cases where a CA cert might be backed into the image itself, but there may very well be certs that are generated in some other part of the system that needs to be injected into the nodes

> Alternatively, there may be opportunity for allowing a full cloud-init template. Users may want to additional runtime configurations (ie. additional users, keys, etc.), and a `CloudInit` attribute in the `Machine` and/or `Cluster` specs could be used to provide broader access than just `TrustedCerts`.

In general I like the idea, of maybe exposing the full cloud-init template as that would provide a lot of flexibility. However, I have few concerns in doing so. First it may be too much flexibility that may lead to unreliable results. Second, today the script responsible for bringing up the environment is delivered as part of the user-data in cloud-init, thus it will be difficult to reconcile the user input of the cloud-init template and the part that the controllers want to inject.

**Comment by lelvisl** [comment]
what about this feature in 2020?
