### ISSUE TITLE
Automated versioned builds

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#166]
Currently, we tag the git repo and build and push release containers manually.  Even the makefile does not have the updated version.  We need to automate this.

**Comment by chuckha** [comment]
cc

**Comment by chuckha** [comment]
Interested to learn how this project is releasing. I'm working on unifying (if possible) or at least adding tooling to cluster-api for providers to use with regards to automated releases.

See https://docs.google.com/document/d/17tY88ysZPDH2rZ9BkewPxETViqivdWDJPrVl_P1TpLg/edit for more detail

**Comment by codenrhoden** [comment]
This has been automated for quite some time... If any unification with CAPA later on, i'd say take that on as a separate issue.

/close
