### ISSUE TITLE
CAPV controllers should keep ownerRefs on the current apiVersion

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1683]
/kind feature

**Describe the solution you'd like**
This issue stems from the [CAPI issue #7224](https://github.com/kubernetes-sigs/cluster-api/issues/7224). This is to investigate the owner references of the CAPV objects created pre-v1beta1 versions. Currently, there is no provision to update the owner reference api version to the latest served by CAPV, which might cause garbage collection by the api server of some resources to be impacted. 

**Anything else you would like to add:**
If any such issues are found, lets use this issue to create a task list and resolve those as follow up PRs.

**Environment:**

- Cluster-api-provider-vsphere version: `1.4.1`

/good-first-issue
/help

**Comment by geetikabatra** [comment]
The way to replicate this issue is, I create a CAPV cluster with v1alpha3 and look for owner references in MD, MS, and M. They all should reflect v1alpha3. Now I upgrade it to v1beta1 and see that owner references in MD-> v1beta1, but MS and M is v1alpha3. Please correct me if I am wrong @srm09

**Comment by sbueringer** [comment]
/assign @killianmuldoon 
Please take a closer look. I think this is ~ the same as [@killianmuldoon](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2075). Feel free to handle as you see fit

**Comment by sbueringer** [comment]
I would probably close #1683 as #2075 includes a bit more

**Comment by killianmuldoon** [comment]
/close

In favor of #2075
