### ISSUE TITLE
Have some trouble about cluster api on vmware, if anyone can help?

### ISSUE THREAD

**Issue by andyzheung** [kubernetes-sigs/cluster-api-provider-vsphere#1699]
from cluster api sig to there.
https://github.com/kubernetes-sigs/cluster-api/issues/7588

**Comment by andyzheung** [comment]
i search from internet, but only find two, i seem not the same to me:
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/828
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/808

**Comment by srm09** [comment]
Answered in the CAPI issue.

**Comment by andyzheung** [comment]
yes, I can close this issue. thank you. @srm09
