### ISSUE TITLE
Remove HAProxy refs from CAPV codebase

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1723]
/kind feature

**Describe the solution you'd like**
Support for HAProxy has been deprecated from CAPV since `release-0.8` and removed entirely from the 1.x release line. We should cleanup the related code and docs from the CAPV repo as well.

**Anything else you would like to add:**
Following are a few references:
- [ ] `contrib/haproxy`
- [ ] `config/default/crd/bases`
- [ ] `README.md`

The above is by no means an exhaustive list, there could be other references which should be removed as well.

/help
/good-first-issue

**Comment by ShivamTyagi12345** [comment]
Hey, a New contributor here, just so that i get it right. We are supposed to remove all the code and documentation related to HAProxy in this repository?

**Comment by srm09** [comment]
It is fine to delete the `contrib/haproxy` directory entirely and the haproxy related files from the `crd/bases` directory.

**Comment by ShivamTyagi12345** [comment]
Thanks for clarifying, implemented all the suggestions

**Comment by Sajiyah-Salat** [comment]
please close this issue if this is sovled.

**Comment by srm09** [comment]
This issue is still open since the raised PR was stale and could not be merged in its current state.
