### ISSUE TITLE
Error while using OS type as Windows

### ISSUE THREAD

**Issue by sachinphogat** [kubernetes-sigs/cluster-api-provider-vsphere#1725]
/kind bug

**What steps did you take and what happened:**
When we use OS type as Windows in vspheremachinetemplate, capv-controller-manager unable to reconcile vspherevm with vspheremachine post creation.

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachine
metadata:
  annotations:
    cluster.x-k8s.io/cloned-from-groupkind: VSphereMachineTemplate.infrastructure.cluster.x-k8s.io
    cluster.x-k8s.io/cloned-from-name: capi-cluster-worker-windows-tngrh
  creationTimestamp: "2022-12-11T13:30:14Z"
  finalizers:
  - vspheremachine.infrastructure.cluster.x-k8s.io
  generation: 2
  labels:
    cluster.x-k8s.io/cluster-name: capi-cluster
    cluster.x-k8s.io/deployment-name: capi-cluster-workerpool-2
    cluster.x-k8s.io/set-name: capi-cluster-workerpool-2-5f6b588cc
    machine-template-hash: "192614477"
  name: capi-cluster-worker-windows-tngrh-55ns7
  namespace: default
  ownerReferences:
  - apiVersion: cluster.x-k8s.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: Machine
    name: capi-cluster-workerpool-2-5f6b588cc-kmjpz
    uid: f7906a85-411b-4652-a54d-a50ac4ce5804
  resourceVersion: "2143525"
  selfLink: /apis/infrastructure.cluster.x-k8s.io/v1beta1/namespaces/default/vspheremachines/capi-cluster-worker-windows-tngrh-55ns7
  uid: 05acf43a-3aa7-4330-a87b-073156fcb3e2
spec:
  additionalDisksGiB:
  - 250
  cloneMode: linkedClone
  datacenter: DC01
  diskGiB: 250
  memoryMiB: 8192
  network:
    devices:
    - gateway4: 100.65.160.97
      ipAddrs:
      - 100.65.160.110/27
      nameservers:
      - 8.8.8.8
      networkName: P_CAPI_836
  numCPUs: 8
  os: Windows
  resourcePool: MGM
  storagePolicyName: MGM_Storage_Policy
  template: rhel-7-kube-v1.22.15
status:
  conditions:
  - lastTransitionTime: "2022-12-11T13:30:15Z"
    reason: WaitingForBootstrapData
    severity: Info
    status: "False"
    type: Ready
  - lastTransitionTime: "2022-12-11T13:30:15Z"
    reason: WaitingForBootstrapData
    severity: Info
    status: "False"
    type: VMProvisioned

**Corresponding vspherevm:**
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereVM
metadata:
  creationTimestamp: "2022-12-11T13:30:15Z"
  finalizers:
  - vspherevm.infrastructure.cluster.x-k8s.io
  generation: 3
  labels:
    cluster.x-k8s.io/cluster-name: capi-cluster
  name: capi-clu-kmjpz
  namespace: default
  ownerReferences:
  - apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: VSphereMachine
    name: capi-cluster-worker-windows-tngrh-55ns7
    uid: 05acf43a-3aa7-4330-a87b-073156fcb3e2
  resourceVersion: "2144104"
  uid: 2b7bc728-70c7-4419-80ce-478edf89b641
spec:
  additionalDisksGiB:
  - 250
  biosUUID: 421dbd92-1050-ce10-0163-6a4590acccfd
  bootstrapRef:
    apiVersion: v1
    kind: Secret
    name: capi-cluster-worker-fr9wx-6jxmc
    namespace: default
  cloneMode: linkedClone
  datacenter: DC01
  diskGiB: 250
  memoryMiB: 8192
  network:
    devices:
    - gateway4: 100.65.160.97
      ipAddrs:
      - 100.65.160.110/27
      nameservers:
      - 8.8.8.8
      networkName: P_CAPI_836
  numCPUs: 8
  os: Windows
  resourcePool: MGM
  server: 100.65.250.66
  storagePolicyName: MGM_Storage_Policy
  template: rhel-7-kube-v1.22.15
  thumbprint: BA:02:31:29:7B:0A:91:9C:07:15:86:15:19:FB:F7:3F:BE:0F:52:3F
status:
  addresses:
  - 100.65.160.110
  cloneMode: fullClone
  conditions:
  - lastTransitionTime: "2022-12-11T13:32:13Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2022-12-11T13:30:15Z"
    status: "True"
    type: VCenterAvailable
  - lastTransitionTime: "2022-12-11T13:32:13Z"
    status: "True"
    type: VMProvisioned
  host: esx99
  network:
  - connected: true
    ipAddrs:
    - 100.65.160.110
    macAddr: 00:50:56:9d:a6:25
    networkName: P_CAPI_836
  ready: true

**LOGS:**
E1211 13:31:09.240508       1 vimmachine.go:407] "capv-controller-manager/vspheremachine-controller/default/capi-cluster-worker-windows-tngrh-55ns7: failed to CreateOrPatch VSphereVM" err="vspherevms.infrastructure.cluster.x-k8s.io \"capi-clus-kmjpz\" already exists" namespace="default" name="capi-cluster-workerpool-2-5f6b588cc-kmjpz"
E1211 13:31:09.240538       1 vimmachine.go:125] "capv-controller-manager/vspheremachine-controller/default/capi-cluster-worker-windows-tngrh-55ns7: error creating or patching VM" err="vspherevms.infrastructure.cluster.x-k8s.io \"capi-clus-kmjpz\" already exists" vsphereVM=<nil>
E1211 13:31:09.240913       1 controller.go:326] "Reconciler error" err="vspherevms.infrastructure.cluster.x-k8s.io \"capi-clus-kmjpz\" already exists" controller="vspheremachine" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="VSphereMachine" vSphereMachine="default/capi-cluster-worker-windows-tngrh-55ns7" namespace="default" name="capi-cluster-worker-windows-tngrh-55ns7" reconcileID=1768024b-5a14-4ea5-845e-e30726eb5891

**What did you expect to happen:**
capv-controller should use the vspherevm name based on os field and try to relate appropriate vspherevm rather than full name of vspheremachine in case of windows

**Environment:**

- Cluster-api-provider-vsphere version:  1.5.1
- Kubernetes version: (use `kubectl version`): 1.22.15

**Comment by srm09** [comment]
I notice that the template in use is a `rhel` template, please use a windows OVA to create a windows based workload cluster.

**Comment by srm09** [comment]
Since there have been no updates, am gonna close this one. Feel free to reopen this if there are any questions.
/close
