### ISSUE TITLE
Published OVAs are obsolete

### ISSUE THREAD

**Issue by sathieu** [kubernetes-sigs/cluster-api-provider-vsphere#1727]
/kind bug

(this is also a security bug, and also an enhancement request 😀 )

This is #1511, again.

**What steps did you take and what happened:**

Go to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/README.md#kubernetes-versions-with-published-ovas. Currently shows:

| Kubernetes | CentOS 7 | Ubuntu 18.04 | Ubuntu 20.04 | Photon 3 |
| :--------: | :------: | :----------: | :----------: | :------: |
|  v1.21.11   |   [ova](https://storage.googleapis.com/capv-images/release/v1.21.11/centos-7-kube-v1.21.11.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.21.11/centos-7-kube-v1.21.11.ova.sha256)   |   [ova](https://storage.googleapis.com/capv-images/release/v1.21.11/ubuntu-1804-kube-v1.21.11.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.21.11/ubuntu-1804-kube-v1.21.11.ova.sha256)   |   [ova](https://storage.googleapis.com/capv-images/release/v1.21.11/ubuntu-2004-kube-v1.21.11.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.21.11/ubuntu-2004-kube-v1.21.11.ova.sha256)| [ova](https://storage.googleapis.com/capv-images/release/v1.21.11/photon-3-kube-v1.21.11.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.21.11/photon-3-1804-kube-v1.21.11.ova.sha256) |
|  v1.22.8  | [ova](https://storage.googleapis.com/capv-images/release/v1.22.8/centos-7-kube-v1.22.8.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.22.8/centos-7-kube-v1.22.8.ova.sha256) | [ova](https://storage.googleapis.com/capv-images/release/v1.22.8/ubuntu-1804-kube-v1.22.8.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.22.8/ubuntu-1804-kube-v1.22.8.ova.sha256) | [ova](https://storage.googleapis.com/capv-images/release/v1.22.8/ubuntu-2004-kube-v1.22.8.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.22.8/ubuntu-2004-kube-v1.22.8.ova.sha256)| [ova](https://storage.googleapis.com/capv-images/release/v1.22.8/photon-3-kube-v1.22.8.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.22.8/photon-3-kube-v1.22.8.ova.sha256)  |
|  v1.23.5   |   [ova](https://storage.googleapis.com/capv-images/release/v1.23.5/centos-7-kube-v1.23.5.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.23.5/centos-7-kube-v1.23.5.ova.sha256)   |   [ova](https://storage.googleapis.com/capv-images/release/v1.23.5/ubuntu-1804-kube-v1.23.5.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.23.5/ubuntu-1804-kube-v1.23.5.ova.sha256)   |   [ova](https://storage.googleapis.com/capv-images/release/v1.23.5/ubuntu-2004-kube-v1.23.5.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.23.5/ubuntu-2004-kube-v1.23.5.ova.sha256)|   [ova](https://storage.googleapis.com/capv-images/release/v1.23.5/photon-3-kube-v1.23.5.ova), [sha256](https://storage.googleapis.com/capv-images/release/v1.23.5/photon-3-kube-v1.23.5.ova.sha256)    |

Those versions are outdated and have security flaws.

**What did you expect to happen:**

- Having up to date images
- Images to be updated when new k8s are released (or regularly).

**Anything else you would like to add:**

There are more up to date OVAs from tanzu-community-edition: [Tanzu Community Edition 0.12.0 product page](https://customerconnect.vmware.com/downloads/get-download?downloadGroup=TCE-0121). NB: those require a VMware account.

**Comment by paokrab** [comment]
+1

**Comment by sathieu** [comment]
Thanks @srm09. Could this be automated somewhat? I've created https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1738.

**Comment by paokrab** [comment]
Thanks, @srm09 . Can you suggest how to build this one? 
I have built it from https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi with make build-node-ova-vsphere-ubuntu-2004 and the size of the image is 9GB but I see your image is just 2GB.
