### ISSUE TITLE
Publish OVAs regularly

### ISSUE THREAD

**Issue by sathieu** [kubernetes-sigs/cluster-api-provider-vsphere#1738]
/kind feature

**Describe the solution you'd like**

This was done manually (in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1511 and https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1727). Could it be done regularly (at least monthly, or when a new release is done)?

**Comment by srm09** [comment]
Plan is to release once every month manually for 3 kurerentes releases, usually around the 2nd week of the month.

**Comment by sathieu** [comment]
Thanks @srm09 :pray: !

**Comment by paokrab** [comment]
@srm09  It seem lastest ova is 2023-03. Cloud you help to provide updated version 🙏
