### ISSUE TITLE
[Feature] Support for anti-affinity/affinity rules for the created machines

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#175]
vsphere DRS supports defining anti-affinity / affinity rules for VMs. This feature is to add support for the user to specify affinity/anti-affinity grouping for the VMs.

Use case: User created 3 Machine object, and want all 3 VMs to run on different hosts to improve resiliency from host failures. This can easily be realized by creating the anti-affinity rule for the 3 VMs

**Comment by sflxn** [comment]
This potentially can get done for v1alpha1, but it isn't a feature that's absolutely needs to go in for this release.  If it gets done in time and the PR has been reviewed, we can make a judgement call at that time.

**Comment by moshloop** [comment]
Any reason why this can't be supported without DRS? Not sure DRS works across multiple clusters, and scheduling aross multiple clusters in a vcenter seems like a reasonable thing todo?

**Comment by akutz** [comment]
This may need to be punted to v1alpha2. If not we need to resource this work yesterday.

cc @frapposelli

**Comment by frapposelli** [comment]
@moshloop affinity/anti-affinity rules are defined within a DRS-enabled cluster, a cluster is also a fault-domain boundary for vSphere. Deploying across multiple clusters should be possible today using `MachineSets`.

@akutz this is potentially a noop (see kubernetes/cloud-provider-vsphere#179), but even if not, definitely needs to be punted to v1alpha2.

**Comment by sujeet-banerjee** [comment]
> Any reason why this can't be supported without DRS? Not sure DRS works across multiple clusters, and scheduling across multiple clusters in a vcenter seems like a reasonable thing todo?

Short Answer: No. Without-DRS, it won't be effective.

Long Answer:
#1 One may use VM-Host rules without the "DRS enabled" on a vShpere cluster. However, the worker nodes will not be auto-migrated (or vMotioned) to support a balanced spread of the nodes across Hosts (i.e. HA in true sense). And CRDs do not expose Host details.
#2 That also means "vMotion" must be enabled for the Hosts. 
More Details: https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.resmgmt.doc/GUID-7D3ABD21-4524-42E9-B7FE-6AAF6766433B.html


I have been working on a design-proposal for supporting Antiafinity/Affinity. Attached.
[Spec_changes_for_AntiAffinity.docx](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/3471305/Spec_changes_for_AntiAffinity.docx)
[Test_n_Demo.pdf](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/3471306/Test_n_Demo.pdf)

**Comment by moshloop** [comment]
@sujeet-banerjee Can you create a google doc for commenting and review? 

vMotion is something I believe should be turned off for kubernetes clusters as it conflicts with kubernetes view of the system. If a host fails then kubernetes should reschedule the pods that become not ready, cluster-api machineset should then detect unresponsive nodes, and create new ones. 

Same applies to DRS, it should be turned off and kubernetes native components like descheduler used to move and rebalance workloads. 

Without DRS or vMotion, machine affinity/antiAffinity can easily be implemented when creating a machine by listing all available hosts/clusters and running through rules list in the same way pod affinity is implemented.

**Comment by andrewsykim** [comment]
> Can you create a google doc for commenting and review?

+1 to this, please use Google docs so we can comment/review :)

**Comment by sujeet-banerjee** [comment]
Could you point me to the shared location where I could add the doc?

**Comment by sujeet-banerjee** [comment]
Proposal Doc: https://docs.google.com/document/d/1fNm53l5K0OfPrGc3zhjNDYzVQNBEc85uEJfNwtiDQrY

I would invite folks to review the proposal and add suggestions (if any).

Thanks,
Sujeet

**Comment by davidopp** [comment]
I believe
https://github.com/kubernetes/enhancements/pull/997
https://github.com/kubernetes/enhancements/pull/1127
are related?

**Comment by brysonshepherd** [comment]
@moshloop
Wouldn't it be better to vmotion, rather than build a whole new node on another vhost? To me that would lead longer time with pending pods.

**Comment by moshloop** [comment]
@brysonshepherd vMotion requires shared storage which is really expensive, slow and unreliable (when compared to just starting a new vm)

**Comment by moshloop** [comment]
> , it's not a good idea to tie/specify host-details in the affinity-definition 

antiAffinity using a topology key would work as new hosts, clusters and datancenters are added and removed:

e.g.
```yaml
    vmAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: 
            topologyKey: "vmware.io/hostname"
```
and to distribute nodes across multiple clusters
```yaml
    vmAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: 
            topologyKey: "vmware.io/clustername"
```

**Comment by brysonshepherd** [comment]
@moshloop

Some users may pay for that higher level of service for higher uptime. 

In our current use case, drs and vmotion are needed.

**Comment by moshloop** [comment]
> higher uptime

Shared storage is much more likely to reduce uptime than it is to increase it, especially when your application is stateless and doesn't need persistent storage. Even when an application requires clustered or replicated storage, the control plane (kubernetes) should not share the same shared fault domain.

vMotion has it's advantages and is often the easiest solution from an operational overhead, but if you want to achieve the highest levels of resilience and uptime your kubernetes nodes shouldn't be using it.

**Comment by brysonshepherd** [comment]
@moshloop I'm not saying that vmotion is what I want, it is just faster than making a new node.  If making a new node (along with rescheduling/starting up the pods) was faster, then that is what I would do. But it isn't. At least not that I'm aware of.

**Comment by moshloop** [comment]
The time to recover a pod doesn't need to be instant, just reasonable - You should be running multiple pods with enough headroom to survive the loss of one pod,  If you lose a physical ESXi host than the VM doesn't get vMotion'ed, it gets booted on a different host, potentially goes through disk crash recovery and rejoins the cluster - in the meantime the pods running on the node may have already been detected as down and rescheduled.

**Comment by sujeet-banerjee** [comment]
The discussion moved to: https://docs.google.com/document/d/1fNm53l5K0OfPrGc3zhjNDYzVQNBEc85uEJfNwtiDQrY/edit#

**Comment by akutz** [comment]
ping @pdaigle

**Comment by jayunit100** [comment]
naively looking at this, and wondering, 

Since @srm09 added https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1182/files , would it be possibly to hijack the `VerifyAffinityRule(ctx computeClusterContext, clusterName, hostGroupName, vmGroupName string) (Rule, error) {` somehow, to do some kind of affinity/anti-affinity VM Spreading at a non-regional, but rather at just an ESXi'ish level ?

**Comment by srm09** [comment]
@jayunit100 I am not sure I quite understand what you are looking for here? Currently multi AZ allows you to attach VMs to specific hosts, if the host groups are setup to point to a particular host. 
Can you elaborate on this ask?

**Comment by srm09** [comment]
/close
This has been implemented as the multi AZ feature using `VSphereDeploymnetZone` and `VSphereFailureDomain` CRDs.

**Comment by sujeet-banerjee** [comment]
Does VSphereDeploymnetZone tie the machines (VMs) to specific ESXi hosts? As I understand, ESXi hosts may be added/taken down at the will of the end-users, within a vSphere cluster. Not sure if it's a good idea to tie/specify host details in the affinity definition (machine/machine-set CRDs).
