### ISSUE TITLE
datastoreCluster field

### ISSUE THREAD

**Issue by s0uky** [kubernetes-sigs/cluster-api-provider-vsphere#1751]
/kind feature

Instead of definition specific `datastore` in `VSphereMachineTemplate` configuration should be `datastoreCluster`, because only one specific `datastore` does not have to be persistent from VMware POV and it can breaks reconciliation. 
  
**Describe the solution you'd like**

Ability to define VMware `datastoreCluster` in `datastore` field.

**Environment:**

- Cluster-api-provider-vsphere version:  v1.3.5
- Kubernetes version: (use `kubectl version`): v1.22.12
- OS (e.g. from `/etc/os-release`):  Ubuntu 22

**Comment by srm09** [comment]
Thanks for creating this one, CAPV provides a way to target all the datastores in a datastore cluster via a storage policy.
- Tag all the datastores within the datastore cluster with a particular tag+category combo
- Create a tag based storage policy following [these](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-D025AA68-BF00-4FC2-9C7E-863E5787E743.html) instructions
- Set the storage policy on the `VSphereMachineTemplate` to leverage this.

This being said, am curious to know if there is a particular use case that cannot be attained using this. Would love to hear your thoughts? @s0uky @heavenly999 @beneso @michalcila @Zafael

**Comment by s0uky** [comment]
Thank you @srm09 I tried it and it works like a charm. 
We decide to not use `datastore` field anymore. It was  replaced with `storagePolicyName` field. I testing it right now, but it simply works. :)

**Comment by cloudmaniac** [comment]
Based on comment below, I'm wondering if that would be working for an existing deployed cluster? The datastore is set within the fault domain CRD, which is immutable. Is there any way to switch an existing cluster from a datastore to a VM storage policy?

> Thanks for creating this one, CAPV provides a way to target all the datastores in a datastore cluster via a storage policy.
> 
> * Tag all the datastores within the datastore cluster with a particular tag+category combo
> * Create a tag based storage policy following [these](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.storage.doc/GUID-D025AA68-BF00-4FC2-9C7E-863E5787E743.html) instructions
> * Set the storage policy on the `VSphereMachineTemplate` to leverage this.

**Comment by chrischdi** [comment]
Is it maybe possible to create a new fault domain CRD and move the machines over?
