### ISSUE TITLE
`verify-crds` test is flaky

### ISSUE THREAD

**Issue by ntoofu** [kubernetes-sigs/cluster-api-provider-vsphere#1757]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

`hack/verify-crds.sh`, which is used by `pull-cluster-api-provider-vsphere-verify-crds` prow job or `make verify-crds`, is flaky. The script occasionally returns errors, but it will run successfully when retried. For example, please see [this PR](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1739#issuecomment-1407443719).

**What did you expect to happen:**

Even if the script is executed several times, the results are the same.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

An example of a failed test: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/1739/pull-cluster-api-provider-vsphere-verify-crds/1619032549575626752

**Environment:**

- Cluster-api-provider-vsphere version: I confirmed this issue on 4aafab65d5cfcde29026d01b70ca3065124cd019
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by ntoofu** [comment]
It might be a bug of `controller-gen`. Even when I called `controller-gen` directly, the same issue still occurred.

```
$ while true; do ./hack/tools/bin/controller-gen paths=./apis/v1alpha3 paths=./apis/v1alpha4 paths=./apis/v1beta1 crd:crdVersions=v1 output:stdout | sha256sum; sleep 3; done
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
9a2448e120cb9da054283686b468f268e53914b350bcdefda56b16ee31e46d8a  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
c950fae07ee79d98cc5e1d84f83c6c503c6bcadadcfeea98dd787e128e9e152f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
c950fae07ee79d98cc5e1d84f83c6c503c6bcadadcfeea98dd787e128e9e152f  -
c950fae07ee79d98cc5e1d84f83c6c503c6bcadadcfeea98dd787e128e9e152f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -
0ca33b5ac647051dde8e233cd0c324d5581a27cf167b690bb7b67a8854fccf9f  -                                                              
```

**Comment by srm09** [comment]
Thanks for the analysis, this makes sense. Do you want to raise a PR to address this flake? We'd need to bump the version in the file you mentioned above.

**Comment by srm09** [comment]
Ran a small experiment after upgrading to `v0.11.0`, seeing the same issue

```zsh
cluster-api-provider-vsphere [$!?] via 🏎💨 v1.19
at 13:33:45 ❯ while true; do ./hack/tools/bin/controller-gen paths=./apis/v1alpha3 paths=./apis/v1alpha4 paths=./apis/v1beta1 paths=./controllers crd:crdVersions=v1 output:dir=/tmp/test; shasum -a 256 /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml; sleep 1; rm -rf /tmp/test/*.yaml; done
d55bfc60d02e0033c923f52a74657922b192f2161abf79488f033513848e0a18  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
d55bfc60d02e0033c923f52a74657922b192f2161abf79488f033513848e0a18  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
88dd033a7d8a459c5d3ca50d6c903ea7e0e63ba639868f0195a4dc09064e38d4  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
d55bfc60d02e0033c923f52a74657922b192f2161abf79488f033513848e0a18  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
d55bfc60d02e0033c923f52a74657922b192f2161abf79488f033513848e0a18  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
88dd033a7d8a459c5d3ca50d6c903ea7e0e63ba639868f0195a4dc09064e38d4  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
d55bfc60d02e0033c923f52a74657922b192f2161abf79488f033513848e0a18  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
d55bfc60d02e0033c923f52a74657922b192f2161abf79488f033513848e0a18  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
88dd033a7d8a459c5d3ca50d6c903ea7e0e63ba639868f0195a4dc09064e38d4  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
d55bfc60d02e0033c923f52a74657922b192f2161abf79488f033513848e0a18  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
d55bfc60d02e0033c923f52a74657922b192f2161abf79488f033513848e0a18  /tmp/test/infrastructure.cluster.x-k8s.io_vsphereclusters.yaml
^C%

cluster-api-provider-vsphere [$!?] via 🏎💨 v1.19 took 43s
at 13:34:33 ❯ ./hack/tools/bin/controller-gen --version
Version: v0.11.0
```

**Comment by ntoofu** [comment]
I'm sorry for the late reply and the typo in my previous comment. I wrote I had used `v0.11.4` but such a version was not released yet.

I have tried the same experiment with `v0.11.3` (the current latest version) again, and I also confirmed the issue still occurs. Probably because of the random nature, I could not see the same issue when I tested previously.

Since the latest release of `controller-gen` shows this flakiness, I will report this issue to https://github.com/kubernetes-sigs/controller-tools/ later.

**Comment by ntoofu** [comment]
I might have found a workaround while trying to discover the root cause. This issue occurs only when multiple `paths` options are specified, and I could not reproduce this issue when using `paths=./apis/...`.

```
$ while true; do hack/tools/bin/controller-gen paths=./apis/... crd:crdVersions=v1 output:stdout | sha256sum; done    
68cf04e037e83f7c52210ac3aa030caf7c9b1584211baa1c7576457457b5c8f8  -
68cf04e037e83f7c52210ac3aa030caf7c9b1584211baa1c7576457457b5c8f8  -
68cf04e037e83f7c52210ac3aa030caf7c9b1584211baa1c7576457457b5c8f8  -
68cf04e037e83f7c52210ac3aa030caf7c9b1584211baa1c7576457457b5c8f8  -
...
```

However, this workaround also generates manifests from `./apis/vmware`, which are not generated in the original way.
