### ISSUE TITLE
OVA: Add a webserver to get logs and status

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#176]
We've used this pattern in the past with great success.  We should develop a webserver for the OVA to get various information about management server.

- [ ] Logs
- [ ] kubeconfig
- [ ] Status of the management cluster
- [ ] List of created target clusters

**Comment by moshloop** [comment]
Why did we close this issue?

`kubectl logs machine` streaming the system logs off the machine would be nice to have for troubleshooting
