### ISSUE TITLE
Dependabot PR pre-submit fail with error

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1787]
/kind bug

**What steps did you take and what happened:**
Here a few examples of the failed jobs on the PRs:
For PR #1784, all jobs exercising the `lint` Makefile target fail with the error:
```
level=error msg="Running error: 1 error occurred:\n\t* can't run linter goanalysis_metalinter: buildir: failed to load package : could not load export data: no export data for \"sigs.k8s.io/cluster-api/internal/util/kubeadm\"\n\n"
```
The job URL for the above failure: [pull-cluster-api-provider-vsphere-test](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/1784/pull-cluster-api-provider-vsphere-test/1625243304008355840)

**What did you expect to happen:**
Dependabot PR pre-submit jobs should pass successfully.

**Anything else you would like to add:**
Other examples of failing dependabot PRs:
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1783
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1782
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1781

/kind failing-test
/priority important-longterm

**Comment by sbueringer** [comment]
@srm09 I think this works at the moment (on recent dependabot PRs). WDYT can we close this issue?

**Comment by sbueringer** [comment]
/close

Let's open a new issue if this becomes a problem (we'll notice pretty quickly)
