### ISSUE TITLE
Setup trivy for vulnerability scanning

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1789]
/kind feature

**Describe the solution you'd like**
CAPI has trivy to get an early signal on CVE vulnerabilities:
kubernetes-sigs/cluster-api#7604 related issue in the CAPI repo
kubernetes-sigs/cluster-api#7632 has links to other similar issues for some other providers

We should have a similar setup for CAPV PRs and make it not required, so even if it fails we could get the PR merged and open a follow up PR to remediate the issue.

**Anything else you would like to add:**
n/a

/priority important-soon
/lifecycle active

**Comment by PatrickLaabs** [comment]
Seems like CAPI and the AWS-Provider do run the scans with a cron defined in the GitHub action yaml.

I like the idea of having a scan on new releases as soon as the pr kicks off, and also on we weekly basis.
Maybe both ways are good to have?

Which images should be included from https://console.cloud.google.com/gcr/images/cluster-api-provider-vsphere ?
Only the ones inside the release-folder?

Best
Patrick

**Comment by killianmuldoon** [comment]
@zhanggbj I think this should be done now and closed with a few PRs that merged yesterday - e.g. https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1978, https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1909, https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1908.

We could close this now IMO.

**Comment by sbueringer** [comment]
Yup looks good. @zhanggbj Sorry wasn't aware of this issue when we did the PRs.

I'll follow-up with some PRs to fix the found CVE's:
* https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1989
* https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1988
