### ISSUE TITLE
recurring reconcile loop for the cluster and machine objects not happening

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#179]
Prior to moving to CRDs the controller behavior was that it would have a recurring reconcile loop resulting in the actuators `update` method getting called in a recurring pattern. After moving to CRDs, the recurring behavior has stopped. This causes the Machine/Cluster objects to not be able to reconcile the state with the underlying infrastructure. For instance if a VM resulted from a Machine object, is deleted from the vsphere directly. Then the cluster-API controller would never re-create the missing node, as the call to actuator never gets called for the Machine object.

**Comment by sflxn** [comment]
I tested this issue with the self-service workflow and found the cluster would eventually recover and stand up a new node to replace the deleted one.  This happened whether I was using a machineset or just machine for the worker nodes.  The only problem is that it is taking hours to recover.  It may just be a matter of how often the reconcile is run.

**Comment by figo** [comment]
my test with a management cluster shows:
deleting a master node, in a few minutes, it been re-created automatically.
deleting machineset node (worker node), waited 30 minutes, did not come back.

**Comment by sidharthsurana** [comment]
The root cause for this issue has been identified now. It seems like after me move to CRD the default `SyncPeriod` is set to 10 Hrs instead of previous timeout of few sec/min.

See https://github.com/kubernetes-sigs/cluster-api/issues/748 for more details.

FYI I am still verifying the fix, and will post a PR shorty after verifying it works.

**Comment by sflxn** [comment]
@sidharthsurana has a fix in his internal repo.  Just needs a PR open.
