### ISSUE TITLE
Failure during clone VM operations does not log errors in CAPV logs

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1797]
/kind bug

**What steps did you take and what happened:**
During VM creation, when an error occurs, say incorrect OVA template path gets passed into the spec, the CAPV logs should report an error. Instead the error just gets set as a message on the `VSphereVM` condition, but no error gets propagated back to the controller.

**What did you expect to happen:**
The error also gets propagated back to the controller and shows up in the CAPV logs.

**Anything else you would like to add:**
History of the change: [commit SHA](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/09c48147234394fff35e78f682121921171d908d#diff-67aa981986e8e4940cfb755b4020310d5e8754bccfe3efd7d4b653eff8efc57c)
Slack thread: https://kubernetes.slack.com/archives/CKFGK3SSD/p1677068417306739

**Environment:**

- Cluster-api-provider-vsphere version: `v1.5.3`

**Comment by agtogna** [comment]
The problem seem to be in
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/09c48147234394fff35e78f682121921171d908d/pkg/services/govmomi/service.go#L100-L104
i.e. if the `createVM` fails only the condition is set, but no error is returned

**Comment by agtogna** [comment]
I think a good solution would be to have a
```go
return vm, err
```
just below the `conditions.MarkFalse` (inside the {}) so the error gets passed on, as is done just above
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/09c48147234394fff35e78f682121921171d908d/pkg/services/govmomi/service.go#L93-L97

**Comment by agtogna** [comment]
BTW, this whole if
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/09c48147234394fff35e78f682121921171d908d/pkg/services/govmomi/service.go#L72-L105
i caused by an error, so why does it have a `return vm, nil` at the end?
