### ISSUE TITLE
Draft - Ready the CI infrastructure for node IPAM e2e test runs

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1798]
/kind feature

**Describe the solution you'd like**
Currently the e2e tests rely on the DHCP server to get IP addresses assigned to the VMs. We want to start testing the node IPAM feature and eventually pivot all the tests to use the node IPAM feature.
This would require the following tasks:

- [ ] IP address pools to be used by the various test runs
- [ ] Deploying the IPAM provider when setting up the e2e tests
- [ ] Picking a particular IP address pool for one run

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
/assign

to keep an eye on it

**Comment by killianmuldoon** [comment]
An additional subtask to keep an eye on when implementing these tests. From https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2075 


- Ensure Node IPAM ownerReferences are re-reconciled and their API Version kept up to date

**Comment by sbueringer** [comment]
@chrischdi WDYD. Can we close this issue, given #2757?
