### ISSUE TITLE
Content Library Support

### ISSUE THREAD

**Issue by adam-jian-zhang** [kubernetes-sigs/cluster-api-provider-vsphere#1838]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We support clone from vSphere template in current CAPV implementation. In some cases, user might wish to use content library as the source of the OVA/templates for better managbility and consistency. For example if user have multiple vCenter environments, content library can help manage propagation of the VM templates, and ensure consistencies of the OVAs/templates.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
/lifecycle active

proposal PR is open

**Comment by sathieu** [comment]
Can we reopen this issue? This is still usefull I think.

**Comment by chrischdi** [comment]
Happy to reopen it if someone wants to volunteer on the work involved :-)

**Comment by douvryf** [comment]
Can we reopen this issue?

**Comment by fabriziopandini** [comment]
> > Happy to reopen it if someone wants to volunteer on the work involved :-)

> Can we reopen this issue?

@douvryf are you planning to work on this issue? that would be great!
Otherwise I fear the "The Kubernetes project currently lacks enough active contributors to adequately respond to all issues and PRs." still applies

**Comment by TrevorBenson** [comment]
[This prior comment](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1838#issuecomment-1683846329) makes it sound like there was a PR at one point, but no ID was referenced.

Is the participation required to get this over the finish line testing and reviewing this unknown PR's work, or inplementing a design it proposes?
