### ISSUE TITLE
docs: fix errors in self service quickstart

### ISSUE THREAD

**Issue by tkrausjr** [kubernetes-sigs/cluster-api-provider-vsphere#184]
Proposing two documentation changes to Quickstart.

In  cluster-api-provider-vsphere/docs/self-service/README.md  from my testing, there are two syntactical mistakes in CLI commands I believe.

In “Create a target cluster” section below:

` - $> clusterctl create cluster --provider vsphere --bootstrap-type minikube --bootstrap-flags "--vm-driver,vmware" -c cluster.yaml -m machines.yaml -p provider-components.yaml`

Should read:

`$ clusterctl create cluster --provider vsphere --bootstrap-type minikube --bootstrap-flags "vm-driver=vmware" -c cluster.yaml -m machines.yaml -p provider-components.yaml`

In Create a Target Cluster using an initial existing cluster  section below:

```
// Create a cluster using the kubeconfig created by minikube above
$> clusterctl create cluster -c cluster.yaml -m machines.yaml -p provider-components.yaml --provider vsphere -e $HOME/.kube/kubeconfig
```

SHOULD READ -

```
// Create a cluster using the kubeconfig created by minikube above
$> clusterctl create cluster -c cluster.yaml -m machines.yaml -p provider-components.yaml --provider vsphere -e $HOME/.kube/config
```

**Comment by frapposelli** [comment]
@tkrausjr would you mind opening a PR for this?

/kind documentation

**Comment by sflxn** [comment]
Hey @tkrausjr, just a tip.  If you follow the standard git message standard, your PR merges will trigger closing of the issue.  The standard is as follows,

Title
<newline>
Small description
<newline>
Resolves/Fixes [issue number]

The last part is what causes the closing of the issue.
