### ISSUE TITLE
clusterctl create cluster fails because IP is never assigned to master

### ISSUE THREAD

**Issue by tkrausjr** [kubernetes-sigs/cluster-api-provider-vsphere#185]
Already looked at [issue-63](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/163) and this is a little different.

Using clusterctl to create a cluster results in an inability for the Provisioned Master node on vSphere to obtain an IP Address as specified in machines.yaml.
```
root@ubu01-jumphost:~/go/src/sigs.k8s.io/cluster-api-provider-vsphere/out# clusterctl create cluster -c cluster.yaml -m machines.yaml -p provider-components.yaml --provider vsphere -e clusterapi.kubeconfig
I0131 16:01:17.160850   13163 createbootstrapcluster.go:27] Creating bootstrap cluster
I0131 16:01:17.359537   13163 clusterdeployer.go:95] Applying Cluster API stack to bootstrap cluster
I0131 16:01:17.359768   13163 applyclusterapicomponents.go:26] Applying Cluster API Provider Components
I0131 16:01:18.915083   13163 clusterdeployer.go:100] Provisioning target cluster via bootstrap cluster
I0131 16:01:19.222835   13163 applycluster.go:36] Creating cluster object clean in namespace "default"
I0131 16:01:19.240740   13163 clusterdeployer.go:109] Creating control plane  in namespace "default"
I0131 16:01:19.253416   13163 applymachines.go:36] Creating machines in namespace "default"
I0131 16:03:19.335935   13163 clusterdeployer.go:114] Updating bootstrap cluster object for cluster clean in namespace "default" with control plane endpoint running on
I0131 16:03:19.386404   13163 clusterdeployer.go:119] Creating target cluster
I0131 16:03:19.402618   13163 utils.go:162] pulling kubeconfig (using ssh) from fe80::250:56ff:fea4:9bb1
I0131 16:03:19.408945   13163 utils.go:175] ssh failed with error = exit status 255
I0131 16:03:29.409134   13163 utils.go:162] pulling kubeconfig (using ssh) from fe80::250:56ff:fea4:9bb1
I0131 16:03:29.414860   13163 utils.go:175] ssh failed with error = exit status 255
I0131 16:03:39.409188   13163 utils.go:162] pulling kubeconfig (using ssh) from fe80::250:56ff:fea4:9bb1
I0131 16:03:39.416291   13163 utils.go:175] ssh failed with error = exit status 255
I0131 16:03:49.409166   13163 utils.go:162] pulling kubeconfig (using ssh) from fe80::250:56ff:fea4:9bb1
```
It appears that the only address returned is an IPv6 address.   

[addons.yaml.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/2819589/addons.yaml.txt)
[cluster.yaml.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/2819590/cluster.yaml.txt)
[machines.yaml.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/2819591/machines.yaml.txt)
machines.yaml, cluster.yaml, addons.yaml are attached.

**Comment by sidharthsurana** [comment]
@tkrausjr This is happening because the image you are using does not have the `VMware GuestInfo` cloud-init datasource. The pre-packaged version of the cloud-init inside the ubuntu cloud image does not support static IP. I think we probably need to add documentation around the static IP support to make it more explicit for the users.
(see https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/72)

**Comment by tkrausjr** [comment]
thanks @sidharthsurana .  Going to rebuild the vsphere VM / Template I am using with the VMware Guestinfo datasource. After that maybe I will see about putting something in the documentation.
