### ISSUE TITLE
reconciler error "nodes ... not found" in a cluster during creation

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#1851]
/kind bug

**What steps did you take and what happened:**

During cluster creation, checking the logs, theres a cryptic error message about nodes not being found... but it appears to me like the machine and vspheremachine objects which it might be looking for are there.... (see screenshot, where we can see the `tkg-mgmt-vc-9pjqm-xmxx8` machine)

```
E0330 19:14:53.934128       1 controller.go:326] "Reconciler error" 

 err="nodes \"tkg-mgmt-vc-9pjqm-xmxx8\" not found" 
 controller="machine" controllerGroup="cluster.x-k8s.io" 
 controllerKind="Machine" 
 machine="tkg-system/tkg-mgmt-vc-9pjqm-xmxx8" 
 namespace="tkg-system" 
 name="tkg-mgmt-vc-9pjqm-xmxx8" 

reconcileID=bb2b294e-d4b6-432e-8af9-d8549c760164

E0330 19:15:34.931792       1 node_controller.go:157] 

"capv-controller-manager/node-label-controller/tkg-system/tkg-mgmt-vc-9pjqm-xmxx8: unable to get node object" err="nodes \"tkg-mgmt-vc-9pjqm-xmxx8\" not found" cluster="tkg-mgmt-vc" machine="tkg-mgmt-vc-9pjqm-xmxx8" node="tkg-mgmt-vc-9pjqm-xmxx8" 

```

But its not clear why it is that a node object should exist given that, CAPV is running inside of my bootstrap cluster, and the migration hasnt occured into VSphere yet (i.e. `kubectl get nodes` should only be returning CAPI nodes).

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/826111/228941036-dd6f87b9-f2bd-4131-9574-f2e72539ffdc.png">

**What did you expect to happen:**

I would like it if CAPV is more precise about specifically how it is attempting to look up this node, and why it expectes it to be there.  I can understand if this is reconcilatory, but it seems like its calling it an "error" as opposed to a "waiting for node to be up" issue. 

If this *is* an error, maybe it is an actual bug (i.e. CAPV is failing bc a "node" doesnt exist yet), and that might be due to other logic in CAPV which has not properly run.  However, I suspect that this "error" is maybe just a logging statement for some kind of reconcilation that is failing. 

But really, im just guessing here. 

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: cluster-api-vsphere-controller:v1.5.3 
- Kubernetes version: (use `kubectl version`): 1.24

**Comment by srm09** [comment]
This message is for labeling the nodes with the ESXi host info that the node VM (VM which corresponds to the Kubernetes node) resides on. The way this is achieved is by labeling the machine with the prefixed label and have the node-label-controller propagate the label to the node. This is a stop gap functionality implemented by CAPV, but is natively available in CAPI from v1.4.0.

From the scenario you mentioned, the node is not yet Ready (Machine in **Provisioning** state) which might cause these error logs to show up intermittently. These would eventually get resolved once the node is reported as Ready on the Cluster.

**Comment by srm09** [comment]
Feel free to close this issue if the explanation makes sense.

**Comment by sbueringer** [comment]
As the controller has also been removed with v1.7

Let's close this issue

/close
