### ISSUE TITLE
Unblock CI for the `main` branch

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#1859]
/kind bug

**What steps did you take and what happened:**
After a scheduled maintenance of the vCenter infra, the e2e tests have been failing consistently. 

**What did you expect to happen:**
The e2e tests should be passing after the maintenance window ends.

**Anything else you would like to add:**
The reason for this is that the certificate for the vCenter (used by the CI) was updated which led to the thumbprint be changed. This thumbprint value gets used by the e2e tests. This value gets supplied to the tests via [an ExternalSecret CR](https://github.com/kubernetes/test-infra/blob/89944e7c3e0ea94d36ce633c186233d514e257c8/config/prow/cluster/build/build_kubernetes-external-secrets_customresource.yaml#L79-L99) which then gets used [in the prow jobs](https://github.com/kubernetes/test-infra/blob/89944e7c3e0ea94d36ce633c186233d514e257c8/config/jobs/kubernetes-sigs/cluster-api-provider-vsphere/cluster-api-provider-vsphere-presubmits.yaml#L5-L24).

The idea is to update the secret value in the GCP project, which gets reconciled by the prow test cluster which hosts the e2e test jobs. In repeated test runs, the stale value (of the thumbprint) is being used which is causing failures.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): 

/priority critical-urgent

**Comment by srm09** [comment]
To unblock CI runs, we will fall back to consuming this variable from the `vsphere-ci.yaml` which was removed in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1600

The longer term fix is to get the `ExternalSecret` updated to pick the latest value.

**Comment by killianmuldoon** [comment]
@chrischdi @sbueringer  - is there anything left to do to unblock the CI now?

**Comment by sbueringer** [comment]
I think it's unblocked for now. I don't see a good way to fully automate this. I'll make sure to document what we have to do if it occurs again (update the thumbprint secret in the Google cloud secret manager)
