### ISSUE TITLE
Move documentation to Gitbook or similar

### ISSUE THREAD

**Issue by frapposelli** [kubernetes-sigs/cluster-api-provider-vsphere#186]
Current documentation for `cluster-api-provider-vsphere` is living in this repo as markdown documents. These are fine for consumption by developers working on the project, but we need a proper documentation website that we can point users to.

- [ ] Evaluate platform for documentation
- [ ] Start moving existing documentation

/priority important-longterm
/kind documentation
/assign @sflxn @frapposelli

**Comment by sflxn** [comment]
I moved this to v1alpha1.  I already have one in progress but haven't finished it since I was asked to lower the priority on documentation.

**Comment by moshloop** [comment]
/remove-lifecycle rotten 
Note changes in gitbooks business model don't make it a good fit anymore 

https://github.com/kubernetes-sigs/cluster-api/issues/1122
