### ISSUE TITLE
template/kubeadm support for k8s versions > 1.11

### ISSUE THREAD

**Issue by ntfrnzn** [kubernetes-sigs/cluster-api-provider-vsphere#188]
The boot scripts in _pkg/cloud/vsphere/provisioner/common/templates.go_ use kubeadm v1alpha2 which is incompatible with k8s 1.13, and uses a flag (--skip-preflight-checks) incompatible with k8s/kubeadm 1.12.

Only k8s versions 1.11 and below are currently buildable.

**Comment by ntfrnzn** [comment]
I have a functioning code change at https://github.com/StackPointCloud/cluster-api-provider-vsphere/pull/1 available.

My change merely enables the newer versions of k8s, within the existing codebase.  It does not

- refactor the templates into separate files
- extend the kubeadm templating to enable more configuration options
- do away with the templating entirely and replace versioning/configuration with a library of quick-starting OVAs :)

**Comment by sflxn** [comment]
Thanks @ntfrnzn.  You're also welcome to submit PRs for issues.

I am going to add the other items you listed in the next upcoming meeting notes for discussion.  We'll either add issues to this repo or the main repo.

**Comment by sflxn** [comment]
Closing.  PR #190 fixed it, but @ntfrnzn didn't put in 'fix' or 'resolve' in the description so the issue wasn't closed automatically.
