### ISSUE TITLE
add unit tests for get.go

### ISSUE THREAD

**Issue by khareyash05** [kubernetes-sigs/cluster-api-provider-vsphere#1895]
/kind feature

**Describe the solution you'd like**
I would like to add unit tests for `pkg/taggable/get.go`

**Anything else you would like to add:**
NA

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by srm09** [comment]
/assign @khareyash05 
Feel free to raise a PR and tag me on it.

**Comment by chrischdi** [comment]
cc @laozc FYI

**Comment by sbueringer** [comment]
Just talked about it. I think this code will be covered by unit tests on other higher-level functions

/close
