### ISSUE TITLE
capv should filter out non-datastores when using storage policy

### ISSUE THREAD

**Issue by tommasopozzetti** [kubernetes-sigs/cluster-api-provider-vsphere#1914]
/kind bug

**What steps did you take and what happened:**
When using a storage policy to create VMs, if vsphere returns objects that are not datastores but are compatible with the storage policy, capv tries to use them as datastores, generating an error in VM provisioning.

**What did you expect to happen:**
Since the API used for cloning the VM only accepts datastores, capv controller should ensure that only datastore object references are passed to it by filtering out any other object.

**Anything else you would like to add:**
This issue is easily reproducible by creating a datastore cluster with multiple datastores inside and tagging all datastores with a common tag. A policy can then be created to target storage matching that tag. If all datastores in a datastore cluster match the policy, the returned set [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/v1.6.0/pkg/services/govmomi/vcenter/clone.go#L228) contains all the datastores plus the datastorecluster (vsphere considers a datastorecluster matching the policy if all its datastores match it). Since one result is picked at random, we were seeing random failures where every so often one VM would fail being provisioned and then after a random amount of retries it would succeed. Adding some logs pointed out that the failures were happening when the datastorecluster was chosen among the results as it cannot be used as datastore reference. Unfortunately, capv does not directly support datastore clusters and based on [this](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1751#issuecomment-1433757485) comment, this system is the advised replacement, but it introduces this bug.

My temporary workaround has been to add an extra small datastore to the datastorecluster and not tag it as usable by the policy. This way not all datastores in the cluster match the policy and the result is that vsphere no longer returns the datastorecluster itself as a match. This has neutralized the errors completely, but I do think that there should be some code in the controller to filter these out so that this workaround is not needed.

**Environment:**

- Cluster-api-provider-vsphere version: 1.6.0
- Kubernetes version: 1.25.7

**Comment by zhanggbj** [comment]
I can reproduce what @tommasopozzetti mentioned above, that CAPV will get all the datastores and also the datastore cluster as below through result.CompatibleDatastores(), and then pick one randomly to move forward.

HubType:StoragePod means the datastore cluster.
```
[{DynamicData:{} HubType:StoragePod HubId:group-p60} {DynamicData:{} HubType:Datastore HubId:datastore-36} {DynamicData:{} HubType:Datastore HubId:datastore-35}]
```

I would like to work on this.
/assign

**Comment by zhanggbj** [comment]
Hi @tommasopozzetti, the fix is merged and this could be closed.

**Comment by tommasopozzetti** [comment]
Fantastic! 🎉 
Thanks for fixing!
