### ISSUE TITLE
Network Requirements 

### ISSUE THREAD

**Issue by NaivePa** [kubernetes-sigs/cluster-api-provider-vsphere#1939]
I am Looking for Network Recommendations for K8s Cluster Deployment using CAPV Project ( like for network segmentations, placement of Virtual IP's).

Can some one help me with any documentation or recommendations.

**Comment by lubronzhan** [comment]
That depends on what kind of use case you want to support. Like if you don't care about security, you can just put all VM on the same network. 
Or you want to isolate the network between different cluster, you can use different network. But make sure you management cluster is able to reach the controlplaneendpoint/apiserverloadbalancer of workload cluster
