### ISSUE TITLE
404 on the calico.yaml url for the Accessing the workload cluster step

### ISSUE THREAD

**Issue by colinrippeyfinarne** [kubernetes-sigs/cluster-api-provider-vsphere#1948]
On this page:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/getting_started.md#accessing-the-workload-cluster

The step:

KUBECONFIG=vsphere-quickstart.kubeconfig kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

Has an invalid url for https://docs.projectcalico.org/manifests/calico.yaml

I'm very much a noob on all things k8s so would be great if anyone can provide an alternative url?

**Comment by lubronzhan** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/test/e2e/data/cni/calico/calico.yaml
this is the one got used in the test or  you can find it here https://github.com/projectcalico/calico/blob/master/manifests/calico.yaml

**Comment by colinrippeyfinarne** [comment]
> https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/test/e2e/data/cni/calico/calico.yaml this is the one got used in the test or you can find it here https://github.com/projectcalico/calico/blob/master/manifests/calico.yaml

Thanks, I'll try that.
