### ISSUE TITLE
Use a SAML token to log in to vCenter

### ISSUE THREAD

**Issue by rgcostea** [kubernetes-sigs/cluster-api-provider-vsphere#1959]
/kind feature

**Describe the solution you'd like**
We would like to be able to use a SAML token to establish a session with vCenter rather than having to specify a username and password.

**Anything else you would like to add:**
This is currently supported by govmomi per the examples here:

- https://github.com/vmware/govmomi/blob/main/session/example_test.go
- https://github.com/vmware/govmomi/blob/main/govc/session/login.go

**Environment:**

- Cluster-api-provider-vsphere version: 1.6.1
- Kubernetes version: (use `kubectl version`): 1.26.2
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by lubronzhan** [comment]
Just to clarify, you want to input for example vsphere key/cert instead of the real token, and the CAPV should get token through that and kept refreshing token if necessary for authentication

**Comment by rgcostea** [comment]
Yes.  That is correct.

**Comment by lubronzhan** [comment]
Ok, I can look into it. CPI already has that function. Should be non trivial to move it here as well

**Comment by sbueringer** [comment]
/assign @lubronzhan 
/lifecycle active
given the open WIP PR
