### ISSUE TITLE
V1.7.0 image is no longer mulit-arch

### ISSUE THREAD

**Issue by dkoshkin** [kubernetes-sigs/cluster-api-provider-vsphere#1963]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

`v1.7.0` image is not multi-arch:
```
➜  ~ docker buildx imagetools inspect gcr.io/cluster-api-provider-vsphere/release/manager:v1.7.0
Name:      gcr.io/cluster-api-provider-vsphere/release/manager:v1.7.0
MediaType: application/vnd.docker.distribution.manifest.v2+json
Digest:    sha256:8e319e8437f6125f13deb5bee789ae9fcbfa6cba29d8dc9294f956c4ebd7c118
```

`v1.6.1` is multi-arch:
```
➜  ~ docker buildx imagetools inspect gcr.io/cluster-api-provider-vsphere/release/manager:v1.6.1
Name:      gcr.io/cluster-api-provider-vsphere/release/manager:v1.6.1
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:6433fd3137a0d3cec8d6fda25c7b05638dc5d75ac15c7b59b0573e10329aa771

Manifests:
  Name:      gcr.io/cluster-api-provider-vsphere/release/manager:v1.6.1@sha256:d2b39b5115979d1c8ac96e7591cb3d6abe4a78abed364f827ddd0e73b1eb22a4
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      gcr.io/cluster-api-provider-vsphere/release/manager:v1.6.1@sha256:cb48e4d20404f1e2a49f60453ed5dfbc6a33d8a507165b45624e257afc67e1c7
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64
```

The individual `amd64` and `arm64` images were also pushed, but maybe something overwrote the main image?
```
REPOSITORY                                                  TAG                                                                      IMAGE ID       CREATED         SIZE
gcr.io/cluster-api-provider-vsphere/release/manager-amd64   v1.7.0                                                                   bfcc0a82eda5   3 days ago      80.5MB
gcr.io/cluster-api-provider-vsphere/release/manager         v1.7.0                                                                   bfcc0a82eda5   3 days ago      80.5MB
gcr.io/cluster-api-provider-vsphere/release/manager-arm64   v1.7.0                                                                   0117f75a3650   3 days ago      78.4MB
```

**What did you expect to happen:**
The `v1.7.0` should be multi-arch and return `MediaType: application/vnd.docker.distribution.manifest.list.v2+json`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The release script hasn't changed since the multi-arch support has been added - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/hack/release.sh, did the release process change somewhere else?

**Environment:**

- Cluster-api-provider-vsphere version: 
`v1.7.0`
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by chrischdi** [comment]
v1.7.1 is back on multi-arch.

I'm curious about what happened for v1.7.0.
At least there is an arm64 image for v1.7.0 via: `gcr.io/cluster-api-provider-vsphere/release/manager-arm64:v1.7.0`

However, normally the post-submit prowjob should run run:

https://github.com/kubernetes/test-infra/blob/bc698d6da5df2f25fac89774d0f9fbc63cc3a008/config/jobs/kubernetes-sigs/cluster-api-provider-vsphere/cluster-api-provider-vsphere-ci.yaml#L37-L65

Then this one should run `hack/release.sh` including `-p` which leads to running the following code for pushing as multiarch:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/9f2cb807b17e62a62909a71017d829e9b694f787/hack/release.sh#L154-L158

Looks like some manual process was done for v1.7.0.

cc @sbueringer as you are currently looking into automating things for the release process further :-).

**Comment by sbueringer** [comment]
Yup. Don't have an answer for v1.7.0. If everything goes well I'll have a PR up today to automate our release process further which should eliminate a few steps that might have gone wrong here with v1.7.0.

**Comment by sbueringer** [comment]
Release automation has been merged. Let's close this once we have a first release created with the new automation and everything is fine

**Comment by sbueringer** [comment]
Should be good now:
```bash
 docker buildx imagetools inspect registry.k8s.io/cluster-api-vsphere/cluster-api-vsphere-controller:v1.8.0
Name:      registry.k8s.io/cluster-api-vsphere/cluster-api-vsphere-controller:v1.8.0
MediaType: application/vnd.docker.distribution.manifest.list.v2+json
Digest:    sha256:71db51cfd7301aba9fa75665e169704a06f401577450ed5190ae5c1db3908f3e

Manifests:
  Name:      registry.k8s.io/cluster-api-vsphere/cluster-api-vsphere-controller:v1.8.0@sha256:df3f8015a0eb56c69f83f0b882bbce89a9112111dd6e394d4c785017ffca29f2
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/amd64

  Name:      registry.k8s.io/cluster-api-vsphere/cluster-api-vsphere-controller:v1.8.0@sha256:0ce2be5e26423ca204c8e8dcd726823a9a905d6f1c521d2ea4a7ba0022cf4edc
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm/v7

  Name:      registry.k8s.io/cluster-api-vsphere/cluster-api-vsphere-controller:v1.8.0@sha256:6ee609358061a03d13c689bf5747dde7b36d8779ac6d19348ea37c759d585858
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/arm64

  Name:      registry.k8s.io/cluster-api-vsphere/cluster-api-vsphere-controller:v1.8.0@sha256:4e70c0f7383bf9c5fb90f2daf551ee6ba0e94fa97773e7129c9e457561273e65
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/ppc64le

  Name:      registry.k8s.io/cluster-api-vsphere/cluster-api-vsphere-controller:v1.8.0@sha256:508747dcb0f2f8edd01b68ab848c97e375ced7ded1096ac4ceb5320757e45f70
  MediaType: application/vnd.docker.distribution.manifest.v2+json
  Platform:  linux/s390x
```

/close
