### ISSUE TITLE
Failure Domain network configuration should support similar fields of VMTemplate network config

### ISSUE THREAD

**Issue by rikatz** [kubernetes-sigs/cluster-api-provider-vsphere#1964]
/kind feature

**Describe the solution you'd like**
Per [API](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/apis/v1beta1/types.go#L256) there is a set of configurations that can be applied for a Network device, not only the portgroup name.

When working on different failure domains, there may be different IP Pools (eg.: AWS you create subnetworks per a VPC region). 

Other configurations may differ as well, like DNS Server.

The original [Failure domain design proposal](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/docs/proposal/20201103-failure-domain.md#api-design) also proposed that the Network placement was added to the DeploymentZone (although today it is on failure domain, which is fine).

In fact, this API was [implemented](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/c77f5fb7dc6f8244c5d3d2adf1ea19825a14cabe/apis/v1beta1/vspheredeploymentzone_types.go#L63) but never used. There is no reference for it 

This feature request is to move forward with the implementation of per-failure domain network configuration

# Use cases
## Use case 1 - Different nameservers per Zone
Acme Ltd runs their Kubernetes clusters over a vSphere environment. This vSphere manages a set of clusters within the same datacenter. The concept of cluster, for Acme Ltd is an isolated room on the same datacenter, containing its own network resources: different network switches, different DNS servers

This way, Acme Ltd needs to be able to define different network configurations (DNS Server, routes, even NTP servers) per cluster/deployment zone

## Use case 2 - Different network requirements per zone
Acme Ltd is migrating its networking model. They understand that running Kubernetes control plane nodes with dynamic IPv4 addressing via DHCP may be risky for their operations, so they decided to establish IP pools per zones/clusters. As an example, nodes in zone 1 should receive the IPs 10.10.1.0/24, while in zone 2 should receive IPs 10.10.2.0/24. 
This migration needs to be nondisruptive, which means zone1 may already have IP Pool configured, but zone 2 may be still operating on DHCP, and at the proper moment, a new zone definition will be made with the right IP Pool, and the nodes on that zone migrated to this new zone definition.

This way, Acme Ltd needs to be able to define different Network models (DHCP vs IPAM/IPPool) per zone definition within the same datacenter

**Comment by rikatz** [comment]
![image](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/7182341/9e18fa4e-eccf-4ea9-800a-47a54bc7fc0a)
Credits to @chrischdi on the picture

**Comment by rikatz** [comment]
A public document to discuss the API evolutions is available at https://docs.google.com/document/d/1Mm8CUVP5ydjP1Uc247uoPHHRatqsBXU3C_jYHQEdVWg/edit?usp=sharing

**Comment by randomvariable** [comment]
@lubronzhan can you take a look at the doc above ^

**Comment by sbueringer** [comment]
/assign @rikatz 
given open doc & PR
