### ISSUE TITLE
`Guestinfo.hostname` field in vCenter not set when using ignition for VMs

### ISSUE THREAD

**Issue by odvarkadaniel** [kubernetes-sigs/cluster-api-provider-vsphere#2013]
/kind feature

I am using `DHCP4`  within my vSphereMachineTemplate and the vSphereVM does not have a DNSName set in the vCenter (has localhost.localdomain) and I have to override that myself.

**What did you expect to happen:**

I expect my newly created VM to have a DNSName set in the vCenter dashboard - the name of the machine itself.

I thought it might be appropriate to set the `guestinfo.hostname` extraConfig while reconciling the metadata here:
 - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/services/govmomi/extra/config.go#L55

The necessary information is already present in the metadata under field `local-hostname`.

**Environment:**

- Cluster-api-provider-vsphere version: v1.7.0
- Kubernetes version: (use `kubectl version`): --- 
- OS (e.g. from `/etc/os-release`):  ---

**Comment by odvarkadaniel** [comment]
With the DNSName being set, we should then also append this value as an `InternalDNS` to `machineAddresses`.

**Comment by randomvariable** [comment]
I think that makes sense, if you want to give it a go. I know @akutz and @ahrkrak had some conversations on converging on a common host metadata standard across cloud-init and Ignition

**Comment by odvarkadaniel** [comment]
The PR contains changes that I used to overcome this issue so I could run MachineSets in downstream OpenShift version of this repository. If there is a better place to set this field, please let me know - I just found it convenient to do it while reconciling the metadata as we need them to set guestinfo.hostname field anyway.

**Comment by chrischdi** [comment]
To circle back on the original issue:

Is it about having this `DNS Name` set inside vsphere?

![image](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/417870/8f5f8874-bf73-4b16-9b29-b3b8c8acc20d)

If yes: this seems to work already for me using the templates we also use for CI.

**Comment by chrischdi** [comment]
In case of our CI, this works because the following file and systemd service get added as `additionalConfig`:

The file/script:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/8332c4272e6351d60502efc4dd9d511a6d9684c2/templates/cluster-template-ignition.yaml#L237-L248

and the systemd service which runs the script:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/8332c4272e6351d60502efc4dd9d511a6d9684c2/templates/cluster-template-ignition.yaml#L265-L277

**Comment by odvarkadaniel** [comment]
Thank you both for looking into this. Thinking about this a little bit more, I see, that this is not even upstream issue. It is something we need to handle downstream.

**Comment by odvarkadaniel** [comment]
Would you be ok with proceeding with setting the internalDNS for a machine with its name as proposed in the PR and scrape the rest?

**Comment by chrischdi** [comment]
I'm currently not sure about that.

To gather some facts:

The `InternalDNS` type originally comes from CAPI:

https://github.com/kubernetes-sigs/cluster-api/blob/4ac1964f13cb50ed8ead9efb40e0fc6000c3b35c/api/v1beta1/common_types.go#L256

The only providers I currently see setting this CAPA and CAPK:

https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/7e3d2cd9fb328559e044446f19cd6a0a98484675/pkg/cloud/services/ec2/instances.go#L869-L876

https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/044d4110bfdb7615e261b76843d904d3e4538ea8/controllers/kubevirtmachine_controller.go#L322-L338

The field I think originally is inspired by the corev1.Node type: 

https://github.com/kubernetes/kubernetes/blob/1c651cf7398f612124297dbb47f30a6825337759/staging/src/k8s.io/api/core/v1/types.go#L5673-L5676

**Comment by odvarkadaniel** [comment]
We don't really care about the `NodeInternalDNS`, we want to set `MachineInternalDNS` from [here](https://github.com/kubernetes-sigs/cluster-api/blob/main/api/v1alpha4/common_types.go#L135-L151) - technically the same thing I guess. We are dependant on setting it due to our [machine-approver-operator](https://github.com/openshift/cluster-machine-approver/blob/master/pkg/machinehandler/machinehandler.go#L130-L139). I don't see any other good place to set this value and we don't really want to diverge from upstream either. Changing the code for the machine approver would be breaking machine-api, which is also something we don't want to do.

**Comment by chrischdi** [comment]
Yes, `NodeInternalDNS` is basically the same as `MachineInternalDNS` (the one is the name of the go const for `corev1.Node`, the other is the go const for CAPI's `v1beta1.Machine`). Both have the string `InternalDNS` as value.

Question @odvarkadaniel : which component does set the `Machine.status.addresses` entry with `InternalDNS` for your other providers where you use the `machine-approver-operator`?

Happy to hear other opinions on this :-)

**Comment by chrischdi** [comment]
The field `Machine.status.nodeRef.name` may be more accurate in this case and should work for all providers.

**Comment by odvarkadaniel** [comment]
> Question: which component does set the `Machine.status.addresses` entry with `InternalDNS` for your other providers where you use the machine approver?
> 

This is something that is being done by cluster-api itself. Other providers such as AWS or GCP both set the `internalDNS` on their cloud instances and then it gets reconciled all the way to the generic machines. It can be seen [here](https://github.com/kubernetes-sigs/cluster-api/blob/ef16a057319ff9d48076025450552bd39d35d4fa/internal/controllers/machine/machine_controller_phases.go#L304-L308).

[CAPA](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/ec2/instances.go#L870-L873) setting the internalDNS value.
[CAPG](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/main/cloud/services/compute/instances/reconcile.go#L67-L82) setting the internalDNS value.

**Comment by chrischdi** [comment]
To clarify: I'm not against the proposal to add the name, I just want to be clear about the use case why we would introduce it and why this is the right thing to do.

The main difference between your proposal (to set `Machine.metadata.name` as `InternalDNS` address) and the approaches for CAPG and CAPA is:

* CAPA: the source of information here is not the `machine` object, it is the actual instance object in AWS. The equivalent for CAPV may be to read the information from vSphere from the `DNS Name` information.
* CAPG: The code there explicitly states that they provide search paths and the name will be resolvable:
  ```go
  	// Add the machine's name as a known NodeInternalDNS because GCP platform
  	// provides search paths to resolve those.
  	// https://cloud.google.com/compute/docs/internal-dns#resolv.conf
  ```

From reading the machine approver code:
* The input is a list of `machines` and a `nodeName`
* The code returns the machine (if found) which has an `InternalDNS` address entry which matches the nodeName.

The proposal is to add the `Machine.metadata.name` as address entry of type `InternalDNS` to the `VSphereVM.status.addresses`.

Although this works on the happy path, it may not work all the time. There could be scripts injected which set a different hostname at the VM and because of that the `nodeName` inside the machine approver would be different.

**Comment by odvarkadaniel** [comment]
Thank you for getting back to me. I have to admit that the approach I proposed originally does not really make sense.

What I think would be better idea to do (don't know the vSphere details):

- We know that the vCenter instance should have correctly assigned `guestinfo.hostname`
- Therefore we could take the instance's hostname at the creation of the instance and add the `MachineInternalDNS` (as that should be resolvable path) to the infrastructure Machine.
- From the infra machine, the cluster-api would take the values and assign them to generic Machines.

This would mean that we would take CAPA's approach in this issue. Am I missing something crucial in here?

**Comment by odvarkadaniel** [comment]
Is this even the good place to do insert the InternalDNS? https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/services/vimmachine.go#L261-L268

As far as I understand, we could take `vm.Name` as that is the actual name of the vm, which should be resolvable and append it as `clusterv1.MachineInternalDNS` to `machineAddresses` and move all these addresses to the infrastructure Machine. From there, CAPI would take over and copy the `Status.Addresses` to the generic Machine. It would look like so:

```go
for _, addr := range addresses {
        machineAddresses = append(machineAddresses, clusterv1.MachineAddress{
		Type:    clusterv1.MachineExternalIP,
		Address: addr,
	})
}
machineAddresses = append(machineAddresses, clusterv1.MachineAddress{
	Type:    clusterv1.MachineInternalDNS,
	Address: vm.Name,
})
vimMachineCtx.VSphereMachine.Status.Addresses = machineAddresses
```

I am not so familiar with CAPV yet, so I am not sure where else would be a good place to handle that. Could you please point me to a better location if one exists?

Other changes of the current PR would be scrapped as they are not needed - currently, this is for us only about the `internalDNS` address.

Thank you, @chrischdi!

**Comment by odvarkadaniel** [comment]
Proposed in a new PR what I said in the last comment. @chrischdi @randomvariable. PTAL, thank you!

**Comment by chrischdi** [comment]
This seems to make sense to me and matches the behaviour of the [kubevirt provider](https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/blob/c2cd191dd363aed8cd7653206b44ff0f96c46abd/controllers/kubevirtmachine_controller.go#L335), for the [openstack provider](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/821a1a2ef25ac615db5fb26379eb0c4b947ad284/controllers/openstackmachine_controller.go#L355-L358) and also about what [CAPA does](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/pkg/cloud/services/ec2/instances.go#L870-L873) (but having a different source for the value).

@sbueringer wdyt?

**Comment by sbueringer** [comment]
Seems okay to me. Although still not clear to me if the MachineInternalDNS name is actually resolvable via DNS.
