### ISSUE TITLE
Multiple ssh keys

### ISSUE THREAD

**Issue by sverrirsig** [kubernetes-sigs/cluster-api-provider-vsphere#202]
There is currently only support for a [single public key](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/a5ec7eace875047cf17d3a29ccce980a05747dae/pkg/cloud/vsphere/provisioner/common/templates.go#L220). This public key is by default the one that is used to fetch kubeconfig.

Having the option of more public keys seems sensible. Which would however only be an option if [this condition is met](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/01b174eec2016a246dea216abb686660303fa368/pkg/cloud/vsphere/provisioner/govmomi/create.go#L191) since the properties only support a single ssh key.

Anyways, it seems relatively trivial to implement and I'm up for doing that. But I just wanted to get some conversation going beforehand.

- Is there anything that opposes the idea of multiple ssh public keys
- Other than simply changing the template to support a slice, should we propagate the extra public keys down through the cluster or machine - Since they are both neatly available [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/01b174eec2016a246dea216abb686660303fa368/pkg/cloud/vsphere/provisioner/govmomi/create.go#L410).

I think cluster makes more sense, at least if the plan is to have the public keys identical for all machines in the cluster.

**Comment by sflxn** [comment]
@sverrirsig Go for it.  I don't have any opposition to it.  If you make the change, please also update the files in /config and cmd/clusterctl/examples/vsphere/generate-yaml.sh to get the keys in.  Also, if you can add those key files to the .gitignore file so we don't accidentally check them into the repo.

btw, there is an upcoming PR that updates the repo to use Kustomize v2.

I'm marking this as milestone next, but if you get it in soon, we can review and merge it.

@frapposelli @sidharthsurana @dougm @figo Any of you have any opposition to this?  I'll bring this topic up in the sig-vmware public slack channel to see if anyone have any opposition.

**Comment by frapposelli** [comment]
👍 go for it

**Comment by sidharthsurana** [comment]
👍 I like the idea.

However, few things to keep in mind (note these are open concerns that still need to be deal with in the current implementation)
- LCM of user provided ssh keys
  - Do we want to support adding user defined ssh keys only as a day-0 operation or can we have a day-2 support as well?
    - When the user creates the cluster, they specify a set of user defined ssh key/s. With the help of cloud-init we can easily inject that in the new VM supporting the day-0 operation.
    - If the use adds a new key after provisioning the cluster, does that show up in the already created nodes, should we even support that?  The new nodes provisioned after the change will get these keys for sure. (may be that's the only behavior we document and support)
  - How about revocation of these ssh keys? would we support that by the means of the user editing the cluster object and removing the user defined ssh key? ( Same concern how does this affect the already provisioned nodes?)

Thoughts?

**Comment by sflxn** [comment]
Sidharth, you bring up good points.  I'll reply with my usual reply to these deeper design questions and add another wrinkle to your points.

If we like what Sverrir is proposing and believe there is a utility here, we can go ahead and add this now.  Long term, we do need an epic that thinks this through.  Unfortunately, cluster api and many open source projects I've seen tend to code before requirements & design so we're left with a "feature" like this that's not well thought out.  My proposal for a future epic is that we think more about this and design how we actually want it to function.

We should also take into consideration the management cluster model when gathering the requirements and designing this feature out in a future epic.  What triggered this for me is that you mentioned editing the cluster object.  Live edit was a "cool" feature for a project that started off focused on developers, but I'm not sure live editing is something we should allow for enterprises.  This is why I mentioned requirements.

In case anyone reading don't understand what I mean by epic, we use a feature in zenhub that allows us to add the scrum idea of an epic to group upcoming issues related to a big feature.

**Comment by moshloop** [comment]
0.3.0 does support multiple keys
/close
