### ISSUE TITLE
Audit GitHub labels

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2043]
I think we should take a closer look at the GitHub labels we have and compare them with core Cluster API and what we have defined in test-infra.

Once we did that we can suggest to add/remove labels accordingly.

**Comment by sbueringer** [comment]
In general this is a low-priority issue, but it would be good if we can create one label manually in the meantime:
![image](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/4662360/02dac053-72f5-4436-8b9b-64844ddaac8b)

I would like to be able to track release blocking issues as soon as possible.


P.S. I propose to do this manually now because we should make all the label changes we want within one PR in test-infra. There's only very few folks who can approve PRs to the label sync config and it usually takes a while to get those PRs approved

@randomvariable @srm09 @yastij You should have the rights to create labels

**Comment by randomvariable** [comment]
This is done.

**Comment by sbueringer** [comment]
@randomvariable Are you sure? I can't find it :)

**Comment by chrischdi** [comment]
Just compared CAPI and CAPV labels:

List of labels CAPI has, CAPV does not:

```
area/bootstrap
area/ci
area/clustercachetracker
area/clusterclass
area/clusterctl
area/clusterresourceset
area/control-plane
area/devtools
area/documentation
area/e2e-testing
area/ipam
area/logging
area/machine
area/machinedeployment
area/machinehealthcheck
area/machinepool
area/machineset
area/metrics
area/networking
area/provider/bootstrap-kubeadm
area/provider/control-plane-kubeadm
area/provider/core
area/provider/infrastructure-docker
area/provider/infrastructure-in-memory
area/runtime-sdk
area/security
area/upgrades
area/util
do-not-merge/needs-area
kind/proposal
```

List of labels CAPV has, CAPI does not:

```
sig/service-catalog
wg/cluster-api
wg/component-standard
wg/lts
wg/machine-learning
wg/security-audit
```

There are other labels in CAPV which I think don't make sense to have, e.g. `area/provider/aws` and others which are refering other providers.

Full list of CAPV labels (via `gh label list --sort name -L 500 | awk '{print $1}'`):

<details>

```
api-review
approved
area/api
area/community-meeting
area/dependency
area/provider/aws
area/provider/azure
area/provider/digitalocean
area/provider/gcp
area/provider/ibmcloud
area/provider/openstack
area/provider/vmware
area/release
area/testing
cherry-pick-approved
cncf-cla:
cncf-cla:
committee/code-of-conduct
committee/security-response
committee/steering
do-not-merge
do-not-merge/blocked-paths
do-not-merge/cherry-pick-not-approved
do-not-merge/hold
do-not-merge/invalid-commit-message
do-not-merge/invalid-owners-file
do-not-merge/release-note-label-needed
do-not-merge/work-in-progress
good
help
kind/api-change
kind/bug
kind/cleanup
kind/deprecation
kind/design
kind/documentation
kind/failing-test
kind/feature
kind/flake
kind/regression
kind/release-blocking
kind/support
lgtm
lifecycle/active
lifecycle/frozen
lifecycle/rotten
lifecycle/stale
needs-kind
needs-ok-to-test
needs-rebase
needs-sig
needs-triage
ok-to-test
priority/awaiting-more-evidence
priority/backlog
priority/critical-urgent
priority/important-longterm
priority/important-soon
release-note
release-note-action-required
release-note-none
sig/api-machinery
sig/apps
sig/architecture
sig/auth
sig/autoscaling
sig/cli
sig/cloud-provider
sig/cluster-lifecycle
sig/contributor-experience
sig/docs
sig/etcd
sig/instrumentation
sig/k8s-infra
sig/multicluster
sig/network
sig/node
sig/release
sig/scalability
sig/scheduling
sig/security
sig/service-catalog
sig/storage
sig/testing
sig/ui
sig/usability
sig/windows
size/L
size/M
size/S
size/XL
size/XS
size/XXL
tide/merge-blocker
tide/merge-method-merge
tide/merge-method-rebase
tide/merge-method-squash
triage/accepted
triage/duplicate
triage/needs-information
triage/not-reproducible
triage/unresolved
ug/big-data
ug/vmware
wg/api-expression
wg/batch
wg/cluster-api
wg/component-standard
wg/data-protection
wg/iot-edge
wg/lts
wg/machine-learning
wg/multitenancy
wg/naming
wg/policy
wg/reliability
wg/security-audit
wg/structured-logging
¯\_(ツ)_/¯
```

</details>

**Comment by sbueringer** [comment]
CAPV doesn't have a specific label config in test-infra. So we only have the labels that everyone has + some leftovers

* List of labels CAPV has, CAPI does not:
  *  => Ieftover, not specified in test-infra => manually deleted now
* There are other labels in CAPV which I think don't make sense to have, e.g. area/provider/aws and others which are refering other providers.
  * => no easy way to get rid of them as they come from the common config => I would just ignore them

I would just ignore the missing labels for now, considering that we're not really using labels much in CAPV.

/close

(feel free to reopen if you think we should do more)
