### ISSUE TITLE
Wire up E2E to VMware infrastructure to be able to test VM Operator and GPU integrations

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#2049]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

This is a tracking issue since some things will need to be dealt with internally, but we need to be able to wire in VMware owned infrastructure to E2E tests to test features like GPU support as well as have E2E coverage for VM operator.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
cc @fabriziopandini

**Comment by sbueringer** [comment]
I think this is not realistic nowadays. In general the trend is towards community-owned infrastructure.

**Comment by chrischdi** [comment]
One approach fur such scenarios for upstream testing may be based on vcsim if possible in future.
