### ISSUE TITLE
Consider to stop pushing latest tags in post-submit

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2052]
Today we are pushing latest tags in post-submit jobs: https://github.com/kubernetes/test-infra/blob/e2eaeb8aca492f645454281cc4131dda712d1211/config/jobs/kubernetes-sigs/cluster-api-provider-vsphere/cluster-api-provider-vsphere-ci.yaml#L1

(the -l in /hack/release.sh -l -p)

I think we should stop pushing the latest tag and also delete the current latest tag we have.

The problem is that whenever one of those two jobs runs the latest tag is overwritten.

So for users it's pretty random if latest is:
* the last commit from main
* the last published releases (v1.5.5, v1.7.0, ... doesn't matter what is actually the "highest")

**Comment by sbueringer** [comment]
@randomvariable @srm09 @yastij WDYT?

**Comment by randomvariable** [comment]
Yeah, makes sense

**Comment by sbueringer** [comment]
PR: https://github.com/kubernetes/test-infra/pull/30205

**Comment by sbueringer** [comment]
@randomvariable Do you think it's okay to just delete the latest tags from the registry as a cleanup? They were pretty useless anyway as they were overwritten all the time

**Comment by randomvariable** [comment]
Probably.

**Comment by sbueringer** [comment]
We can also just ignore the existing tag. We will move to an entirely different registry anyway.

I'm fine either way

**Comment by sbueringer** [comment]
Let's just keep the latest flag. So we don't break "whoever runs with a random CAPV image"

/close
