### ISSUE TITLE
Consider using ClusterCacheTracker instead of remote.NewClusterClient

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2053]
I think we should consider using the ClusterCacheTracker from core CAPI which caches Clients and RESTConfig for a cluster across reconciles. The main advantage is that we don't have to construct a client on each reconcile.

Currently we have a few places where we are using remote.NewClusterClient instead:

![image](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/4662360/d9418401-5457-4b99-86b6-8178712cb333)

An example on how to setup the ClusterCacheTracker can be seen here: https://github.com/kubernetes-sigs/cluster-api/blob/main/main.go#L372-L395

**Comment by laozc** [comment]
I can take over this issue.

**Comment by sbueringer** [comment]
Perfect, thx!

/assign @laozc
