### ISSUE TITLE
Remove handling of orphaned Machines in reconcileDelete of vspherecluster_controller

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2054]
We have to take another closer look, but I think we can now remove this code: (We should check if there is more in other places) 
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/7f09896fe4099c09c8b78796910558b69b6d3eea/controllers/vspherecluster_reconciler.go#L138-L171

Because the corresponding issue in core ClusterAPI has been fixed a while back (xref: https://github.com/kubernetes-sigs/cluster-api/issues/5483)

**Comment by srm09** [comment]
Yes, this was a stop gap that was introduced to make sure that no orphaned resources are left over. This should be ready fro removal, we should also think about removing the logic to set the VSphereCluster as one of the ownerRefs for the VSphereMachine. It was done to facilitate this deletion.

**Comment by sbueringer** [comment]
Sounds good. Needs some careful reviews but I agree we should be able to remove this and get rid of some significant complexity
