### ISSUE TITLE
Migrate Makefile to use go install wherever possible

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2060]
I think we should continue the refactoring we already started to build binaries via go install instead of hack/tools/go.mod. IIRC it's not possible for the binaries we consume from core CAPI but it should work for everything else.

**Comment by sbueringer** [comment]
cc @chrischdi (maybe one for you to finish the work you already started)

**Comment by chrischdi** [comment]
/reopen

We want to cherry-pick back to v1.5, let's close once all is done
