### ISSUE TITLE
Create kube-state-metrics configuration for CRD metrics

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2061]
We recently created configuration to expose state metrics for core CAPI CRDs in core CAPI.

We should do the same in CAPV for CRDs for which it makes sense.

Then we should find a pragmatic way how we can use CAPI + CAPV state-metrics via core CAPI `tilt up` at the same time (currently kube-state-metrics only supports a single metrics config

The generated crd-config of core CAPI can be seen here: https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/observability/kube-state-metrics/crd-config.yaml

**Comment by chrischdi** [comment]
/close

fixed via #2345
