### ISSUE TITLE
Discuss if we want to remove PreferredAPIServerCIDR

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2092]
In the v1alpha4 roadmap we had the following item:
* remove `PreferredAPIServerCIDR`

I don't know why we wanted to remove this field, but apparently it was neither deprected nor removed.

@srm09 @yastij Should we still consider deprecating/removing it?

**Comment by chrischdi** [comment]
We have validation in-place so it cannot get used anymore: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/internal/webhooks/vspherevm.go#L75-L77

**Comment by sbueringer** [comment]
Very nice catch. Do you want to open a PR to properly deprecate the field in the API? (cf. https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/653d6e9196b1a5e67003da6c5e8850dd7690dd83/apis/v1beta1/vspherefailuredomain_types.go#L60-L63)
