### ISSUE TITLE
Ability to use FQDN to access workload clusters, rather than ip address

### ISSUE THREAD

**Issue by lknite** [kubernetes-sigs/cluster-api-provider-vsphere#2098]
/kind feature

**Describe the solution you'd like**
How can I set things up such that I can access a workload cluster kubeapi via FQDN rather than ip address?

For example:  Access the new cluster using something like https://clustername.k.home.net/ rather than something like https://10.0.1.25:6443/ .

What I've been doing is editing the kubeconfig file after the fact, changing the ip to be an fqdn and add 'insecure-skip-tls-verify: true', but this is of course insecure (and incompatible w/ pinniped).  The insecure flag is needed because when the certificates were generated the fqdn was not included.  I set the fqdn by annotating the loadbalancer ip in such a way that external-dns will manage the fqdn record automatically.

What I think needs to happen is for an option to exist to enable using an fqdn & specify the domain to use, then:
1. the fqdn is generated on the fly and used:
    - when generating the kubernetes cluster certs
    - when adding url to kubeconfig
    - when adding external-dns style fqdn annotation to the kubeapi loadbalancer service
      - e.g. external-dns.alpha.kubernetes.io/hostname: clustername.k.home.net

**Important:**
To work the user would be required to setup external-dns themselves so the fqdn is registered automatically.

**Configuration would look something like this:**
\# Enable this to use an fqdn instead of an ip address to access the workload cluster kubeapi, this feature will:
\# (external-dns must be installed and configured in order for this to work)
\# 1. add an external-dns style annotation to the workload cluster loadbalancer ip service
\# 2. generate an fqdn to be used in the kubeconfig instead of the ipaddress
\# specify domain to use with external-dns e.g. \<clustername\>.\<domain\>
use-external-dns-domain: k.home.net

**Otherwise, the work-around to do this manually is time consuming, and not very gitops:**
https://devops.stackexchange.com/questions/9483/how-can-i-add-an-additional-ip-hostname-to-my-kubernetes-certificate

**Comment by randomvariable** [comment]
Additional SANs can be added under /spec/template/spec/kubeadmConfigSpec/clusterConfiguration/apiServer/certSANs in KubeadmControlPlane.

In terms of changing the kubeconfig, this is a core CAPI concern and doesn't involve CAPV.

cc @sbueringer

**Comment by lknite** [comment]
Thank you

**Comment by lknite** [comment]
Note, i created a controller-based solution which accomplishes this use case without needing an fqdn by instead targeting applications via the cluster name instead of fqdn:
https://github.com/lknite/daytwo
