### ISSUE TITLE
Migrate to vm-operator v1alpha2 APIs

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2118]
CAPV today is using [vm-operator](https://github.com/vmware-tanzu/vm-operator) v1alpha1 APIs. There is ongoing work on v1alpha2 APIs.

v1alpha2 APIs are not ready yet, so for now there is nothing to do. Also when v1alpha2 is the default in vm-operator v1alpha1 will continue to work for some time.

One reason to migrate earlier could be if CAPV needs any new functionalities which are only available via v1alpha2.

**Comment by sbueringer** [comment]
cc @srm09 @randomvariable

**Comment by chrischdi** [comment]
Also depends on which versions we need to support + how far it needs to be backwards compatible :-)

**Comment by randomvariable** [comment]
When we do this, let's make sure we're exposing all of the options like boot device size, etc...

**Comment by randomvariable** [comment]
Also, v1alpha2 is ready now, so i guess we can upgrade the description.

**Comment by chrischdi** [comment]
Let's split this into two PRs:

- [ ] migrating the controller and main go module
  - #3029
- [ ] migrating the e2e test part

**Comment by chrischdi** [comment]
/close

🎉
