### ISSUE TITLE
Cloning from template with snapshot and simultaneous disk expansion fails

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#212]
Currently, if the source template used has snapshots and the in the target machine spec the disk is requested to be expanded the clone operation fails.

**Comment by sflxn** [comment]
@sidharthsurana Your solution appears to be a workaround.  I think it's reasonable, but you should write up a bug in our internal bugzilla for this issue.
