### ISSUE TITLE
Migrate from static shellcheck docker container to the shellcheck script used in other k repos

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#2125]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

We currently hard pin a shellcheck docker image stored in a VMware owned GCP repository. This should be migrated to something more regularly updated and community owned.

https://github.com/kubernetes/kubernetes/blob/master/hack/verify-shellcheck.sh is a good example.

This will also affect Cloud provider vSphere and vsphere CSI repositories.

cc @lubronzhan 
cc @xing-yang 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
Let's check if we can use the same as core CAPI: https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/verify-shellcheck.sh

**Comment by sbueringer** [comment]
@chrischdi Done? (for all branches?)
