### ISSUE TITLE
Stop using outdated mdlint docker container

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#2126]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The mdlint image has been static for several years and is in a VMware owned GCP project. We should migrate to something more readily maintained.

This will also affect Cloud provider vSphere and vsphere CSI repositories.

cc @lubronzhan
cc @xing-yang

There's an example here:

https://github.com/kubernetes-sigs/node-feature-discovery-operator/blob/master/Makefile#L154

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by chrischdi** [comment]
Instead we could use the GH action as CAPI does: https://github.com/kubernetes-sigs/cluster-api/blob/44530a5ae2163f277d904a2e629fe793d6fbbdd8/.github/workflows/lint-docs-pr.yaml

**Comment by sbueringer** [comment]
I think mdlint and link checker is not the same.

Whatever we end up doing here. Let's consider adding the same to core CAPI if it's worth it

**Comment by chrischdi** [comment]
Oh, that one only does link checking for the book :-( maybe there's an alternative action doing what we want 👍

**Comment by sbueringer** [comment]
If possible I think I would prefer makefile targets for linters etc over adding more and more GitHub actions

**Comment by chrischdi** [comment]
> If possible I think I would prefer makefile targets for linters etc over adding more and more GitHub actions

ack, I think then there will be no way around using a container image because [markdownlint](https://github.com/DavidAnson/markdownlint) is npm based.

**Comment by sbueringer** [comment]
Agree!

**Comment by chrischdi** [comment]
Note: the author of markdownlint provides a cli in a docker image via https://github.com/DavidAnson/markdownlint-cli2

**Comment by randomvariable** [comment]
There's a golang implementation down in https://fuchsia.googlesource.com/fuchsia/+/refs/heads/main/tools/mdlint/ which is go.fuchsia.dev/fuchsia/tools 

not tried it. Also, license seems a bit weird: "// Use of this source code is governed by a BSD-style license"

**Comment by chrischdi** [comment]
Installation of the fuchsia one is also a bit hard :-) does not work via `go install`.

```
❯ wget https://fuchsia.googlesource.com/fuchsia/+archive/refs/heads/main/tools/mdlint.tar.gz
❯ tar -xvzf mdlint.tar.gz
❯ go mod init go.fuchsia.dev/fuchsia/tools/mdlint
❯ go build ./
❯ ./mdlint -h
Usage: mdlint [flags]

Markdown linter.

Flags:
  -enable value
        Enable a rule. Valid rules are 'bad-headers', 'bad-lists', 'casing-of-anchors', 'newline-before-fenced-code-block', 'no-extra-space-at-start-of-doc', 'no-extra-space-on-right', 'respect-col-length', 'respectful-code', 'simple-utf8-chars', 'verify-internal-links'. To enable all rules, use the special 'all' name
  -filter-filenames string
        Regex to filter warnings by their filenames
  -json
        Enable JSON output
  -root-dir value
        (required) Path to root directory containing Markdown files
```

But the code seems to be still under maintenance (last change in mdlint directory was 13 days ago)

**Comment by chrischdi** [comment]
Idea:
* Use the gh action https://github.com/DavidAnson/markdownlint-cli2 (which uses the same as our current markdown linter)
* For local usage, add `act -W .github/path/to/gh-action.yml`

🤔 

The fuchsia one would want us to do a lot of changes.

**Comment by chrischdi** [comment]
Note: the current image we use is not even runnable on arm64...

**Comment by sbueringer** [comment]
Yup, but that would be fixable by publishing the image properly

**Comment by sbueringer** [comment]
Wondering if it is an option to simply sync the image into our CAPV staging repo and use it from there

**Comment by chrischdi** [comment]
I gave it a try: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/compare/main...chrischdi:cluster-api-provider-vsphere:pr-mdlint-upstream-image?expand=1

Testable via:
```sh
MARKDOWNLINT_CLI2_IMAGE_NAME=davidanson/markdownlint-cli2 make lint-markdown
```

(variable is required because I did not push/sync the image).

**Comment by sbueringer** [comment]
Discussed yesterday, current idea would be to now just get rid of the linter

/assign @chrischdi 
(I assume that's fine as you're already familiar with it)

**Comment by sbueringer** [comment]
@chrischdi can be closed?

**Comment by chrischdi** [comment]
/close

Jep.
