### ISSUE TITLE
Split and test clone operation results

### ISSUE THREAD

**Issue by rikatz** [kubernetes-sigs/cluster-api-provider-vsphere#2135]
While changing [clone.go](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/services/govmomi/vcenter/clone.go) I've figured out it is a bit hard to test its results, as the whole function ends up with the clone request.

My proposal is to split the function on this file into smaller functions, in a way that we can test the clone spec output before really calling the clone operation.

**Comment by sbueringer** [comment]
Sounds good, thank you!
