### ISSUE TITLE
Importing API types pulls in lots of dependencies

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api-provider-vsphere#2159]
Inspired by https://github.com/kubernetes-sigs/cluster-api/issues/9011

We should mirror the work to reduce the number of dependencies brought in from importing API types that has been done in the core Cluster API repository at https://github.com/kubernetes-sigs/cluster-api/issues/9011

This will require:
- Moving webhooks out of the API packages
- Dropping  `controller-runtime/pkg/scheme` in the API packages

**Comment by killianmuldoon** [comment]
Credit to @JoelSpeed who championed this work in the CAPI repo

**Comment by sbueringer** [comment]
@laozc Please take a look at the linked issue for context. It should ~ come down to something like this:
* https://github.com/kubernetes-sigs/cluster-api/pull/9045
* https://github.com/kubernetes-sigs/cluster-api/pull/9047

We already have consensus on how to do #9045. I'll try to review #9047 so we have an established pattern to follow

**Comment by sbueringer** [comment]
/assign @laozc 
/unassing @killianmuldoon 
(IIRC based on offline discussion)

**Comment by sbueringer** [comment]
@laozc
Can you assign the issue to yourself? Unfortunately I can't do it > https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2159#issuecomment-1683836520

**Comment by sbueringer** [comment]
@laozc If you have time, the next thing we can do is the equivalent of https://github.com/kubernetes-sigs/cluster-api/pull/9047

Maybe just do it for one webhook first to get a first review and then we can do the same for all

**Comment by sbueringer** [comment]
Thx @laozc. I think the only remaining part is "Add import-boss to prevent regressions" (xref: https://github.com/kubernetes-sigs/cluster-api/issues/9011#issuecomment-1672582845)

If you have some time, I think we can already explore how to use it in CAPV without waiting for CAPI.
