### ISSUE TITLE
Feature: Support creating linked clone from snapshots

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#216]
Today we are doing a full clone of the template when creating the nodes.
We should support doing a linked clone as well. That would tremendously help speed up the VM
creation. Linked clone should be presented as an option for the user creating the `Machine` if they want to use it.

**Comment by figo** [comment]
will be great to cover this topic here:

disk consolidation for every clone can be expensive, we should try to avoid it,
we can discuss snapshots use case here:

1) if user trying to use snapshot to create multiple versions of template, could user use multiple templates instead?
2) we are not restricting snapshot, but we can detect snapshot, potentially give a warning.
