### ISSUE TITLE
Removing v1alpha3 & v1alpha4 apiVersions

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api-provider-vsphere#2165]
Cluster API has decided to remove apiVersions v1alpha3 and v1alpha4 in upcoming releases. These versions have been end of life for more than a year and are scheduled to be fully removed from  in CAPI v1.6 - scheduled for around the end of March next year. 

These API types are already deprecated in CAPV since they are no longer the latest apiVersions. 

The removal of the API types in core CAPI necessitates that CAPV is ready to remove those API versions in order to adopt CAPI release 1.6.

I'm proposing the following set of tasks with a necessary completion date of March next year: 

#### v1.8
- [x] Signal deprecation of v1alpha3 and v1alpha4 API versions in code and OpenAPI definitions https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2166
- [x] Clearly signal the deprecation and plan in the release notes and in other places in the community.

#### v1.9
- [x] #2075 to ensure Clusters created on an older apiVersion are still fully functional
- [x] Ensure any other apiVersions referenced in objects are always bumped (I'm not sure if there are any - this will need investigation and possible backporting like the above). 
- [x] Drop all code related to v1alpha3 & v1alpha4 (API types, conversion, …) #2414 
- [ ] Clearly signal the removal in the release notes and in other places in the community.

(Note this is essentially a simplified version of the process being followed in upstream Cluster API at https://github.com/kubernetes-sigs/cluster-api/issues/8038)

The above schedule should leave us in a good state ahead of the release of CAPI v1.7 if we more or less follow the recent CAPV release cadence of ~2 minor releases per CAPI minor releases.

**Comment by sbueringer** [comment]
Thx for opening this issue.

Just to emphasize. The steps for deprecation we do is just to make the deprecation we already have more visible. v1alpha3/v1alpha4 have been basically deprecated at the time when they haven't been the latest apiVersion anymore.

**Comment by killianmuldoon** [comment]
Updated the wording to be more clear about the current status of the apiVersions and the wording of that task - thanks for the clarification.

**Comment by killianmuldoon** [comment]
Updated to have the code removals take place as part of the 1.9 release. This is necessary as 1.9 will import CAPI 1.6, removing the v1alpha3 APIVersions.

**Comment by chrischdi** [comment]
/reopen

There's one more open point: `Clearly signal the removal in the release notes and in other places in the community.`

**Comment by killianmuldoon** [comment]
- This will show up as a breaking change by default in the release notes 
- We've already broadcast it on the slack channels and in the community meeting (as far as possible :sweat_smile:)


What more do you think we should do?

**Comment by chrischdi** [comment]
Should be good enough, just wanted to verify that we did :-)

❓ : when upgrading CAPV: it is a must to run `v1.8.2` at least once to get all owner references fixed, before upgrading to the v1.9 series, right?

**Comment by killianmuldoon** [comment]
You're right - we should add that to the release notes for 1.9. 

Let's leave this open for now to track that - good catch!

**Comment by sbueringer** [comment]
WDYT about opening an issue for 1.6.0 (if we don't have one already) and add this there as a sub-task?

**Comment by killianmuldoon** [comment]
> WDYT about opening an issue for the v1.6.0 release (if we don't have one already) and add this there as a sub-task? 

Will do (assuming you meant v1.9.0)

**Comment by killianmuldoon** [comment]
Should be covered now in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2474

Closing this issue.

/close
