### ISSUE TITLE
Feature: Support specifying a particular snapshot for cloning purpose

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#217]
In vsphere the users can create number of snapshots on a VM, giving them the ability to use the VM through it various stages of evolution. Currently, we only take the template name. Ideally we should be able to specify the particular snapshot if available to clone

**Comment by akutz** [comment]
Please see #289

**Comment by frapposelli** [comment]
Is this a prereq for linked clones?
