### ISSUE TITLE
Consider using dependabot dependency groups

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2202]
Dependabot has an option to bump dependencies in groups:

> By default, Dependabot raises a single pull request for each dependency that needs to be updated to a newer version. You can use groups to create sets of dependencies (per package manager), so that Dependabot opens a single pull request to update multiple dependencies at the same time.
> https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

As we're bumping k8s.io/* patch versions in CAPV it might be worth using this feature. If I got it right the k8s.io PRs in the following screenshot could have been just one PR

<img width="756" alt="image" src="https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/4662360/db22b246-86c5-43ae-9456-62f5d24230c6">

**Comment by killianmuldoon** [comment]
/assign

I have this one on my radar - plus doing the same for CAPI.
