### ISSUE TITLE
Expose minimum hardware version on the VSphereVM spec

### ISSUE THREAD

**Issue by srm09** [kubernetes-sigs/cluster-api-provider-vsphere#2212]
/kind feature

**Describe the solution you'd like**
Similar to the [hardware version field](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/2bf748d66f951fb1dc518bbdd81e2ff0611240f1/apis/v1beta1/types.go#L206) on the `infrastructure.cluster.x-k8s.io` VSphereVM API types, we'd like to introduce a similar field on the API types under the `vmware.infrastructure.cluster.x-k8s.io` API group as well.

**Anything else you would like to add:**
With some recent updates to the underlying VMOperator provisioner used in vCenter Workload Management, the hardware version of the VirtualMachine now gets inferred from the VMClass instead of being calculated from the hardware version set in the OVA. If the hardware version is not set on the VMClass, then it defaults to the vCenter datacenter/cluster/host compatibility version defaults.
Since hardware version dictates the hardware compatibility of VMs, CAPV users should have the ability to be able to prescribe the minimum hardware version that a VM should adhere to.

This would require pulling in the updated VMOp APIs which expose setting this field on the Spec.

**Comment by sbueringer** [comment]
Sounds good!

**Comment by chrischdi** [comment]
I think its not even part of v1alpha2. I was only able to find it for the `VirtualMachineImage` object in v1alpha2: https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha1/virtualmachineimage_types.go#L103

**Comment by srm09** [comment]
/retitle Expose minimum hardware version on the VSphereVM spec

**Comment by srm09** [comment]
VM-operator https://github.com/vmware-tanzu/vm-operator/pull/205 exposes a new field to set the minimum h/w version on the VirtualMachine Spec. This issue is to track the uptake of this field in the VSphereVM spec in the `vmware.infra.cluster.x-k8s.io` API group.
