### ISSUE TITLE
Enable clusterctl upgrade tests

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2247]
Once we're done with the re-structuring of the e2e test folder structure we should enable the clusterctl upgrade tests again.

I would propose that we run two tests. Example: (on main)
* 1.8.x => main
* 1.7.x => main

**Comment by killianmuldoon** [comment]
/unassign

I'm not going to get to this any time soon :sweat_smile:. There's a WIP PR open at https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2463 if someone wants to pick it up.

**Comment by sbueringer** [comment]
No worries, thx for linking the WIP PR

**Comment by chrischdi** [comment]
Taking over this work

/assign

/unassign sbueringer
