### ISSUE TITLE
Restructure test folder for multiversion support

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api-provider-vsphere#2251]
Currently Cluster API Provider vSphere holds all of the templates used for testing in a single folder. This makes it more difficult to test upgrades between versions. Templates for those tests, which are currently being skipped on main, are held in a different folder.

We should move the `test/e2e/data/infrastructure-vsphere` to a model that more closely represents the core CAPI structure for templates i.e:

```
test/e2e/data/infrastructure-docker/
├── main
├── README.md
├── v0.4
├── v1.0
├── v1.3
├── v1.4
└── v1.5
``` 

We need to do the following steps:
1. Move existing templates into a `main` folder under  `test/e2e/data/infrastructure-vsphere`
2. Add versioned files required for upgrade tests. 3
    - Initial idea - test n-2 on `release- 1.8`, `release-1.7` and `main. n-1` on `release-1.6` and none on `release-1.5`. This is similar to  CAPI's n-2 testing, but that is directly related to CAPI's support policy.
    - We could feasibly try to do upgrade tests for all supported versions.
    - Related to #2247
3. Figure out testing strategy for Cluster API v1alpha4 upgrades. We could support these reasonably up until `release-1.7`. Support for serving v1alpha4 objects is stopped as of CAPI v1.5.0. These versions will be removed soon, but we should have a tested upgrade path for CAPV objects.

**Comment by sbueringer** [comment]
Sounds good. Let's get n-2 coverage in place for main / release-1.8 / release-1.7 and then let's see how much we can pragmatically backport (your proposal sounds fine)

**Comment by sbueringer** [comment]
Not sure if it's worth to now invest in 4. to be honest

**Comment by killianmuldoon** [comment]
> Not sure if it's worth to now invest in 3. to be honest (I think we're now at the 9th minor release which uses v1beta1)

I think you might be right - Let's get the first two points done for sure and then revisit.

**Comment by sbueringer** [comment]
/assign @killianmuldoon 
/lifecycle active
(as far as I can tell :))

**Comment by killianmuldoon** [comment]
Let's close this issue now that this is cherry-picked on all branches. The clusterctl version upgrade is tracked in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2247 and I don't think we need to cover over v1alpha4 upgrades in our e2e tests.
