### ISSUE TITLE
Reconsider the OVA images we build and use for testing

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api-provider-vsphere#2252]
We currently build the following OVA images for new kubernetes releases:

- Ubuntu 18.04
- Ubuntu 20.04 (Used in tests)
- Ubuntu 22.04
- Photon 3
- Flatcar Stable (Used in tests)

At least Ubuntu 18.04 is already very old and not used in CI.

At some point we should maybe switch over to use Ubuntu 22.04 in CI, especially with upcoming changes which may require cgroupv2 support.

**Comment by sbueringer** [comment]
I would be in favor of dropping Ubuntu 18.04 going forward and switching our CI on main to use Ubuntu 22.04

**Comment by killianmuldoon** [comment]
All sounds good to me

**Comment by sbueringer** [comment]
/close

Let's just keep 18.04 in mind when building new OVAs
