### ISSUE TITLE
Environment value "${VIP_NETWORK_INTERFACE=\"\"}" may not be set appropriately.

### ISSUE THREAD

**Issue by MrDXY** [kubernetes-sigs/cluster-api-provider-vsphere#2279]
/kind bug

**What steps did you take and what happened:**
Hi, team, 
I came across an issue while attempting to generate a cluster manifest by running the command `make dev-manifests`. And when I checked the generated yaml files, it appears that the environment variable `${VIP_NETWORK_INTERFACE=""}` will not be replaced. And I checked the `/templates` directory, it's the same. Also, I have checked the source code [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/ea5331de4e27665aa712f1fa52b16aa905308bb5/packaging/flavorgen/flavors/env/envsubts_consts.go#L48C1-L49C64): It says: `Set the default to an empty string to let kube-vip autodetect the interface`. But still, I do not quite get it.

If anyone has insight into why this environment variable is set to its current value, please kindly provide me with some hints. If that is unexpected, then I can try to submit a pr to fix this.

<img width="406" alt="image" src="https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/18511096/5bc84e2f-a70a-46c6-bf60-b20a2b91226b">

**What did you expect to happen:**
The variable should be set to something like: 
`VipNetworkInterfaceVar       = "${VIP_NETWORK_INTERFACE}"`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 1.8
- Kubernetes version: (use `kubectl version`): 1.27.3
- OS (e.g. from `/etc/os-release`): mac-os

**Comment by sbueringer** [comment]
Nice catch.

I think: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/059376968c7d5dbd94547dbc76927ca1a6aba3a9/packaging/flavorgen/flavors/env/envsubts_consts.go#L45

Should be 
```go
	// Set the default to an empty string to let kube-vip autodetect the interface.
	VipNetworkInterfaceVar       = "${VIP_NETWORK_INTERFACE:=\"\"}"
```

Without the colon it's just broken, with the colon it will default to an empty string if VIP_NETWORK_INTERFACE is not set

**Comment by MrDXY** [comment]
I reviewed the `envsubst` tool that I utilize and discovered that my macOS version differs from the one utilized in the Makefile. My macOS version is `(GNU gettext-runtime 0.21.1)`, while the Makefile uses `github.com/drone/envsubst/v2/cmd/envsubst`.

I tested the `github.com/drone/envsubst/v2/cmd/envsubst` version and it worked perfectly for both `"${VIP_NETWORK_INTERFACE=\"\"}" ` and `"${VIP_NETWORK_INTERFACE:=\"\"}"`.

So, no modifications are required in this situation I think. Maybe this could serve as a helpful reminder for others who may experience a similar issue, and hopefully, it will assist them. 😄

**Comment by sbueringer** [comment]
I think I would still change it. `:=` seems to be the correct syntax as far as I can tell (I"m seeing the `=` for the first time)

(cc @killianmuldoon @chrischdi)
