### ISSUE TITLE
CAPV, vSphere CPI, and vSphere CSI use different schemas for the vCenter server address

### ISSUE THREAD

**Issue by dlipovetsky** [kubernetes-sigs/cluster-api-provider-vsphere#2301]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
cluster-api-provider-vsphere accepts the vCenter server address in host:port concatenated form, e.g. `1.2.3.4:5678`, or as a URL, e.g. `https://example.com:5678`.

On the other hand, both [cloud-provider-vsphere](https://github.com/kubernetes/cloud-provider-vsphere//blob/5c6e6e5a16f88d6cd36dc09076b9b102119137f4/pkg/common/config/types_yaml.go#L88-L91), and [vsphere-csi](https://github.com/kubernetes-sigs/vsphere-csi-driver//blob/f6baaa76f8ddfb7500dcf61b2629950bcdc06ccf/pkg/common/config/types.go#L141-L142) expect the vCenter server address as separate host and port values, and do not support the URL. 

The CAPV user has to generate configuration for cloud-provider-vsphere and vsphere-csi, so they need to be informed about this difference. Right now, the difference is not documented.

In fact, the current cluster templates generate invalid cloud-provider-vsphere and vsphere-csi configuration if `VSPHERE_SERVER` is in host:port concatenated form, or is a URL. CAPV deploys the cluster, and the user remains unaware that that CPI and CSI are misconfigured.

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/9cfdc84c51cfb8f10777036c0a17d772625ebb34/templates/cluster-template.yaml#L35

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/9cfdc84c51cfb8f10777036c0a17d772625ebb34/templates/cluster-template.yaml#L454

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/9cfdc84c51cfb8f10777036c0a17d772625ebb34/templates/cluster-template.yaml#L773

**What did you expect to happen:**
One or more of the following:
(a) Clearly document this difference between the projects for CAPV end users.
(b) Change cloud-provider-vsphere and vsphere-csi to accept a concatenated or URL form. (I'm not sure why the projects don't already do this; internally, they create a URL from the separate host and port fields. See [here](https://github.com/kubernetes/cloud-provider-vsphere//blob/bfd472106fa9de36abae1ca20353cff955add25c/pkg/common/vclib/connection.go#L158), and [here](https://github.com/kubernetes-sigs/vsphere-csi-driver//blob/f6675be1f8a3e8c0fa9e0d0d1c02cbfa33bb6771/pkg/common/cns-lib/vsphere/virtualcenter.go#L141).)  
(c) Change CAPV to accept separate fields for host and port. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: v1.8.0 (or master)
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`): N/A

**Comment by sbueringer** [comment]
cc @lubronzhan @wyike

**Comment by lubronzhan** [comment]
Yeah if you tried to deploy CPI and CSI through cluster-template in CAPV, you will run into issues. 
I think the cluster-template.yaml is just a starting point if customer wants to deploy cluster on very basic use case.
Maybe we can document more about when the customer wants to use the cluster-template. Also link to the official doc in Cloud-provider-vsphere.

CPI and CSI still use that form probably it used to have the legacy ini form of configuration. CPI could be deployed as a process.

**Comment by sbueringer** [comment]
@lubronzhan WDYT would it make sense to support the same url field as in CAPV in CSI & CPI as well?

I don't think it makes much sense to add two additional fields to CAPV in all places where we have the URL today

**Comment by sbueringer** [comment]
> WDYT would it make sense to support the same url field as in CAPV in CSI & CPI as well?

@xing-yang What do you think about it from a CPI perspective?
