### ISSUE TITLE
Increase code coverage

### ISSUE THREAD

**Issue by laozc** [kubernetes-sigs/cluster-api-provider-vsphere#2308]
/kind feature

**Describe the solution you'd like**
A few codes are not covered by unit test and we would like to increase the code coverage.

There are some improvements we could make to ensure the code quality in the workflow, including
1. Better report to understand the code coverage summary more intuitively (than the current go coverage report)
2. Generate the report regularly to observe the trends
3. Enable the coverage check against each PR (for gating in the future)
5. More test cases
...

**Anything else you would like to add:**
All the progress related to code coverage may be tracked with this issue.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by laozc** [comment]
Package | Coverage | Details
-- | -- | --
sigs.k8s.io/cluster-api-provider-vsphere/apis/v1alpha3 | 69.3% | 190/274
sigs.k8s.io/cluster-api-provider-vsphere/controllers | 69.6% | 1062/1526
sigs.k8s.io/cluster-api-provider-vsphere/controllers/vmware | 18.4% | 25/136
sigs.k8s.io/cluster-api-provider-vsphere/internal/webhooks | 74.7% | 162/217
sigs.k8s.io/cluster-api-provider-vsphere/pkg/clustermodule | 34.4% | 43/125
sigs.k8s.io/cluster-api-provider-vsphere/pkg/identity | 86.8% | 46/53
sigs.k8s.io/cluster-api-provider-vsphere/pkg/manager | 46.2% | 37/80
sigs.k8s.io/cluster-api-provider-vsphere/pkg/record | 100.0% | 10/10
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services | 33.7% | 69/205
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi | 9.5% | 58/608
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/cluster | 84.6% | 44/52
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/extra | 86.7% | 13/15
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/find | 83.3% | 15/18
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/ipam | 93.8% | 91/97
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/metadata | 75.9% | 22/29
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/net | 31.0% | 9/29
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/pci | 96.3% | 26/27
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/vcenter | 12.9% | 24/186
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/network | 79.8% | 83/104
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/vmoperator | 71.4% | 215/301
sigs.k8s.io/cluster-api-provider-vsphere/pkg/session | 55.8% | 67/120
sigs.k8s.io/cluster-api-provider-vsphere/pkg/util | 55.3% | 145/262

**Comment by sbueringer** [comment]
Let's definitely not invest in `sigs.k8s.io/cluster-api-provider-vsphere/apis/v1alpha3`. This package will be gone in a few months.

WDYT, let's take a look at the low coverage packages (maybe start with <50%) and see if we can add some useful unit tests there? (useful in the sense of we're actually testing code with logic and not just super-straightforward code without any logic/branching)

**Comment by laozc** [comment]
This is the latest coverage after we enabled collecting all packages.

Package | Coverage | Details
-- | -- | --
sigs.k8s.io/cluster-api-provider-vsphere/apis/v1alpha3 | 69.3% | 190/274
sigs.k8s.io/cluster-api-provider-vsphere/apis/v1alpha4 | 6.8% | 11/162
sigs.k8s.io/cluster-api-provider-vsphere/apis/v1beta1 | 95.8% | 23/24
sigs.k8s.io/cluster-api-provider-vsphere/apis/vmware/v1beta1 | 100.0% | 12/12
sigs.k8s.io/cluster-api-provider-vsphere/controllers | 73.0% | 1114/1526
sigs.k8s.io/cluster-api-provider-vsphere/controllers/vmware | 78.7% | 107/136
sigs.k8s.io/cluster-api-provider-vsphere/feature | 100.0% | 1/1
sigs.k8s.io/cluster-api-provider-vsphere/internal/webhooks | 80.2% | 174/217
sigs.k8s.io/cluster-api-provider-vsphere/pkg/clustermodule | 42.4% | 53/125
sigs.k8s.io/cluster-api-provider-vsphere/pkg/clustermodule/fake | 100.0% | 6/6
sigs.k8s.io/cluster-api-provider-vsphere/pkg/context | 88.5% | 23/26
sigs.k8s.io/cluster-api-provider-vsphere/pkg/context/fake | 78.9% | 45/57
sigs.k8s.io/cluster-api-provider-vsphere/pkg/context/vmware | 80.0% | 8/10
sigs.k8s.io/cluster-api-provider-vsphere/pkg/identity | 86.8% | 46/53
sigs.k8s.io/cluster-api-provider-vsphere/pkg/manager | 82.5% | 66/80
sigs.k8s.io/cluster-api-provider-vsphere/pkg/record | 100.0% | 10/10
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services | 60.5% | 124/205
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/fake | 100.0% | 4/4
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi | 9.5% | 58/608
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/cluster | 84.6% | 44/52
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/clustermodules | 0.0% | 0/46
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/extra | 86.7% | 13/15
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/find | 83.3% | 15/18
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/ipam | 93.8% | 91/97
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/metadata | 82.8% | 24/29
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/net | 31.0% | 9/29
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/pci | 96.3% | 26/27
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/template | 54.5% | 12/22
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/vcenter | 61.3% | 114/186
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/network | 84.6% | 88/104
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/vmoperator | 77.4% | 233/301
sigs.k8s.io/cluster-api-provider-vsphere/pkg/session | 67.5% | 81/120
sigs.k8s.io/cluster-api-provider-vsphere/pkg/taggable | 84.2% | 16/19
sigs.k8s.io/cluster-api-provider-vsphere/pkg/util | 87.8% | 230/262
sigs.k8s.io/cluster-api-provider-vsphere/pkg/util/vmware | 100.0% | 1/1
sigs.k8s.io/cluster-api-provider-vsphere/test/helpers | 55.5% | 91/164
sigs.k8s.io/cluster-api-provider-vsphere/test/helpers/vcsim | 92.7% | 38/41
sigs.k8s.io/cluster-api-provider-vsphere/test/helpers/vmware | 98.5% | 66/67

**Comment by sbueringer** [comment]
To make this slightly more actionable I filtered out the ones with relatively high coverage.

I think we can start looking into the following packages, check if there are more useful unit tests to be added and then open PRs to add them.

Package | Coverage | Details
-- | -- | --
sigs.k8s.io/cluster-api-provider-vsphere/pkg/clustermodule | 42.4% | 53/125
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services | 60.5% | 124/205
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi | 9.5% | 58/608
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/clustermodules | 0.0% | 0/46
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/net | 31.0% | 9/29
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/template | 54.5% | 12/22
sigs.k8s.io/cluster-api-provider-vsphere/pkg/services/govmomi/vcenter | 61.3% | 114/186
sigs.k8s.io/cluster-api-provider-vsphere/test/helpers | 55.5% | 91/164

**Comment by MrDXY** [comment]
I can take a look at `sigs.k8s.io/cluster-api-provider-vsphere/pkg/clustermodule`, and try to add more unit tests for it.

**Comment by laozc** [comment]
I will take `sigs.k8s.io/cluster-api-provider-vsphere/pkg/services`
