### ISSUE TITLE
Add metric to track vCenter sessions

### ISSUE THREAD

**Issue by laozc** [kubernetes-sigs/cluster-api-provider-vsphere#2329]
/kind feature

**Describe the solution you'd like**
It's essential to track vCenter sessions metrics
so we could understand better on the vCenter load in stress or scale test.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
Sounds good. Initial thoughts, maybe the following makes sense:
* current cached sessions
* session created
* not sure if we have something that removes a session

**Comment by sbueringer** [comment]
If someone wants to take this up. We have a lot of prior art and feedback on this PR: #2472
