### ISSUE TITLE
Run e2e tests with higher concurrency

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2342]
Currently all our e2e tests are run sequentially which is pretty slow.

We should improve them so they can run in parallel.

I tried to run with higher concurrency here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2340

But this failed apparently because we only get one control plane IP in our e2e.sh and then cannot use it for multiple clusters of course.

I would suggest to try to move the IP allocation to a BeforeEach step.

Notes:
* I think for folks running the e2e tests outside of our VMC env we should still make it possible to run the tests sequentially as of today (i.e. that the IP is allocated up-front)
* We could also migrate to the CAPI IPAM controller when we do this

**Comment by sbueringer** [comment]
cc @chrischdi @killianmuldoon

**Comment by sbueringer** [comment]
Slightly related. Could it be that today we are only using CONTROL_PLANE_ENDPOINT_IP and WORKLOAD_CONTROL_PLANE_ENDPOINT_IP is unused?

If yes, let's open a PR to drop WORKLOAD_CONTROL_PLANE_ENDPOINT_IP

**Comment by chrischdi** [comment]
Exact. `WORKLOAD_CONTROL_PLANE_ENDPOINT_IP` was used in the capi-upgrades test which was removed in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/96f02b71067d3256a2a08b4386d13ecd589eca56#diff-61bca8c1f7684aa0ca1217356780f3a83bae890d4cce0ec850918edb54e7cb26

**Comment by sbueringer** [comment]
Ah I see. I didn't look at the old templates... . Then let's try to preserve this behavior (that we can also get this IP).
