### ISSUE TITLE
Bump to CR v0.16

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2356]
Just a tracking issue to collect things we should implement after the bump to CR v0.16

Most of them will be probably already documented in the migration doc (https://main.cluster-api.sigs.k8s.io/developer/providers/migrations/v1.5-to-v1.6)

Tasks:
* [ ] https://github.com/kubernetes-sigs/cluster-api/pull/9264

**Comment by killianmuldoon** [comment]
I think this should be closed with #2463.


/close

**Comment by sbueringer** [comment]
/reopen

Did a diff, we missed a few things
