### ISSUE TITLE
After k8s 1.14 was release, installation of kubeadm and kubelet failing because it wants kubernetes-cni 0.6.0

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#238]
With the latest k8s 1.14 update,  CAPV is failing on node bootstrap.  This is a known issue.  There is a work around by pinning kubernetes-cni=0.6.0-00.  This issue is here to track our resolution for v1alpha1.

Issue 75683 on the kubernetes repo.

**Comment by sflxn** [comment]
On the main issue page, @neolit123 suggested we try to pin this package to 0.7.5, but the repo's release page doesn't even show this version.  https://github.com/containernetworking/cni/releases

**Comment by neolit123** [comment]
just download from here:
https://packages.cloud.google.com/apt/pool/kubernetes-cni_0.7.5-00_amd64_b38a324bb34f923d353203adf0e048f3b911f49fa32f1d82051a71ecfe2cd184.deb

i can also give you a link from the GCS buckets, but it's pretty much the same DEB.

**Comment by sflxn** [comment]
I need to note that this issue exist with ubuntu 16.04 and 18.04, the two versions I tested.
