### ISSUE TITLE
Review use of `nolint` directives across code

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api-provider-vsphere#2384]
CAPV uses many linters from golangci-lint, but many of these linters are skipped in some packages due to the use of `nolint` directives. The usage of these should be reviewed and as many as possible should be removed. This work should be tackled as a follow-on from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2058

Some initial findings:

- [x] godot: 
  - Should only be used in old APIVersions. Should be removed everywhere else.
    - #2383 
  - [x] gosec: 8 usages. @Ankitasw 
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2406
- Allowed in test code.
  - [x] staticcheck: 	8  @xiujuanx 
  - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2427
  - [x] nestif: 	6  @adityabhatia 
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2410
  - [x]  gocritic: 	3  @MrDXY 
    - #2399
  - [x]  gocyclo: 	2 @Ankitasw 
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2407
  - [x] errcheck: 2 @Ankitasw
    - #2409
  - [x] gocognit: 	2 @Ankitasw 
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2407
  - [x] revive: 	2 @Ankitasw
    - #2409
  - [x] parallelltest: 	1  @Ankitasw 
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2407
  - [x] wrapcheck: 	1 @Ankitasw 
    - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2407
  - [x] prealloc: 	1 @Ankitasw
    - #2409
  - [x] containedctx @zhanggbj 
    - #2297 
- related to https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/2295
  - [x] goconst:	 	1 @Ankitasw
    - #2409
  - [x] ineffassign: 	1 @Ankitasw
    - #2409

The above usages should be investigated and we should remove where possible. Where not possible we should add comments beside the lint ignore directives explaining why these linters are ignored.

**Comment by zhanggbj** [comment]
- [ ]  containedctx
I'll pick up this, will remove `nolint` during the refactoring work.

Also CC @MrDXY @xiujuanx，if you have some bandwidth :-)

**Comment by MrDXY** [comment]
I can take this task as I have done similar work previously. 😄 
- [ ] gocritic

**Comment by xiujuanx** [comment]
I can pick this one:
- [ ] staticcheck: 8

**Comment by adityabhatia** [comment]
I can pickup `nestif` cases

**Comment by Ankitasw** [comment]
I can pick `gosec`

**Comment by Ankitasw** [comment]
Will pick `gocyclo`

**Comment by Ankitasw** [comment]
@killianmuldoon Also I see other linters have only occurrences <=2, can we combine them in same PR? Since the changes wont be significant.

**Comment by Ankitasw** [comment]
Will pick rest of the linters:
 errcheck: 2
 revive: 2
 prealloc: 1
 goconst: 1
 ineffassign: 1

**Comment by adityabhatia** [comment]
@killianmuldoon `nestif` was also disabled, so the `nolint:nestif `directives were unused.

**Comment by chrischdi** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2399 seems to be the last open PR for this 🎉

**Comment by killianmuldoon** [comment]
Looks like we've ticked everything off the list here - thanks a lot for all the effort folks!
