### ISSUE TITLE
IPAddress Gateway should be concidered optional

### ISSUE THREAD

**Issue by ekarlso** [kubernetes-sigs/cluster-api-provider-vsphere#2396]
/kind feature

**Describe the solution you'd like**
It was decided in previous discussions that Gateway should be optional so you can have interfaces without defualt gw here
https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/pull/118
https://github.com/kubernetes-sigs/cluster-api/issues/8536
https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/issues/70

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
1.8.x

**Comment by christianang** [comment]
This is fine with me. There was a lot of back and forth on this across various repos and it seem like it was made optional everywhere, but CAPV. So this make sense to me to remove the restriction from CAPV.

cc @schrej @srm09

**Comment by chrischdi** [comment]
Fore more context also see the discussion at https://kubernetes.slack.com/archives/CKFGK3SSD/p1695731228748929

As of today it is already okay for CAPV to have no gateway set for ipv6. With this use case we should do the same for ipv4 propably inside the `parseGateway` function:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/pkg/services/govmomi/ipam/parse.go#L57-L59

```go
	if ipamAddress.Spec.Gateway == "" {
		return nil, nil
	}
```

/triage accepted
