### ISSUE TITLE
Use CAPI's `namingStrategy` in end-to-end testing

### ISSUE THREAD

**Issue by killianmuldoon** [kubernetes-sigs/cluster-api-provider-vsphere#2428]
Upstream Cluster API has added a namingStrategy field in topology managed clusters in order to allow customization of the names of CAPI objects.

We should use this feature - [documented here](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/write-clusterclass#defining-a-custom-naming-strategy-for-controlplane-objects) - in CAPV e2e tests to ensure it plays well with other components, for example the VSphere Cloud Provider, which have their own assumptions about the names of Kubernetes objects.

**Comment by sbueringer** [comment]
@killianmuldoon Let me know if someone should take this one over

**Comment by killianmuldoon** [comment]
/unassign

Probably not getting to this any time soon.

/help
