### ISSUE TITLE
Remove immutable fields when patching VM Service VMs after creation

### ISSUE THREAD

**Issue by dilyar85** [kubernetes-sigs/cluster-api-provider-vsphere#2430]
/kind feature

**Describe the solution you'd like**
Currently, the following fields are immutable after a VM Service VM resource is created ([related code in vmop repo](https://github.com/vmware-tanzu/vm-operator/blob/main/webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go#L143-L148)):
- ImageName
- ClassName
- StorageClass
- ResourcePolicyName

Therefore, patching these fields after a VM Service VM is created could potentially be denied, as they might be updated during the VM creation by a mutation webhook.

**Anything else you would like to add:**
For example, in the latest VMOP version, `vm.spec.imageName` can be mutated from a friendly image name to a "vmi-" name if there is a single VM image that can be resolved. If CAPV continues patching such VM with the previous friendly image name, the request would be denied as the imageName is an immutable field, leading to reconciliation errors for TKG VMs.

**Environment:**
N/A.

**Comment by chrischdi** [comment]
Question: does VM Operator only mutate the `vm.spec.imageName` for Creation?

If it also mutates the same on Update there should not be a patching issue.

**Comment by dilyar85** [comment]
> Question: does VM Operator only mutate the `vm.spec.imageName` for Creation?

Yes. Once a VM is created, its imageName field cannot be changed which is enforced by the VM validation webhook.

**Comment by akutz** [comment]
To be clear, the validation webhook to prevent mutating the `spec.imageName` field always existed. It's just that before it didn't result in an error since CAPV would patch the same value back in, thus resulting in a no-op, not triggering the webhook.

**Comment by akutz** [comment]
> If it also mutates the same on Update there should not be a patching issue.

Also, the reason we do not do this is because the `vmi-xxx` unique ID should be resolved exactly once, as early as possible. If CAPV later changes the value to a friendly name that must be resovled again, there's a chance (small, but one that does exist) that it could resolve to a _different_ image.

**Comment by sbueringer** [comment]
Sounds like we should make the corresponding fields on the VSphereMachine immutable in CAPV (currently we don't have any webhooks on this type)

**Comment by chrischdi** [comment]
> Sounds like we should make the corresponding fields on the VSphereMachine immutable in CAPV (currently we don't have any webhooks on this type)

Ack, but as addition: don't try to patch it on an existing object / ignore if it is already set.

**Comment by sbueringer** [comment]
It's just pretty confusing to have a field which is then just not applied without any sort of error

**Comment by chrischdi** [comment]
I think all we can do is:

* Add a comment on the relevant fields that they only get used when creating a VM
* Adjust the code to not try to update the fields after creation of the vm (to match the above then documented behaviour)
* Add a webhook to make these fields immutable on CAPV side too.

**Comment by sbueringer** [comment]
We could also return errors in some condition theoretically if the desired state cannot be applied

**Comment by sbueringer** [comment]
Okay I think now I got the ask
* CAPV set the image name on creation of a vmoprv1.VirtualMachine
* vmoperator resolves the image name and sets the spec field to something else
* CAPV continues to try to write the original image name (which then fails because the imageName is immutable)

So the ideal way to address this is probably:
* Ensure we don't update the imageName after creation of vmoprv1.VirtualMachine
* Also make the field immutable on the vmware.VSphereMachine

**Comment by fabriziopandini** [comment]
I think we should fix, but this vm-operator behavior of mutating a spec value provided by something else is sort of unusual and unexpected.
IMO, long term, If the VM operator should resolve the value provided to internal names or IDs it should store the resolved value on different fields.

**Comment by chrischdi** [comment]
Cherry-picks:

- #2579
- #2580

We will publish releases for 1.7 and 1.8 after merging.

**Comment by chrischdi** [comment]
/reopen

The fix did not include `ResourcePolicyName` but `MinHardwareRevision` instead (which is ok according to https://github.com/vmware-tanzu/vm-operator/blob/main/webhooks/virtualmachine/v1alpha1/validation/virtualmachine_validator.go#L143-L149).

We should file another PR which also adds the same behaviour for the `ResourcePolicyName`.

**Comment by chrischdi** [comment]
I think we can close this.

resourcePolicyName was also implemented:

* https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2597
* https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2602
* https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2603
