### ISSUE TITLE
Run upstream tests currently using kube-up on top of CAPV

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api-provider-vsphere#2452]
**Describe the solution you'd like**

The plan is to setup the same tests as:

- ci-kubernetes-gce-conformance-latest
- ci-kubernetes-e2e-gci-gce-alpha-features
- ci-kubernetes-e2e-gci-gce-serial
- ci-kubernetes-e2e-gci-gce-slow
- ci-kubernetes-e2e-gci-gce

But run them on top of CAPV.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Mailinglist:
https://groups.google.com/g/kubernetes-sig-cluster-lifecycle/c/igg420CDQJg/m/z55dW2WDBQAJ 

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
/assign @chrischdi 
(just to make it visible that you're currently working on it)

**Comment by chrischdi** [comment]
Action plan:
- [ ] Merge PR which adds configuration file for all cases for kubetest
- [ ] Create test-infra PR to add periodic jobs which make use of them via the `KUBETEST_CONFIGURATION` env var
- [ ] Compare a run of the jobs with the original ones
  - which cases got skipped but run upstream, ...

**Comment by zhanggbj** [comment]
I assume this is still in progress based on the comments above.
/remove-lifecycle rotten

**Comment by chrischdi** [comment]
I still have to summarise how the state is. We have the periodics running, but they fail on some tests (which was somewhat expected):

* https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-e2e-exp-kk
* https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-e2e-exp-kk-alpha-features
* https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-e2e-exp-kk-serial
* https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-vsphere#periodic-e2e-exp-kk-slow
