### ISSUE TITLE
Add ability to set label for dynamic passthrough devices

### ISSUE THREAD

**Issue by maximsnezhkov** [kubernetes-sigs/cluster-api-provider-vsphere#2470]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
As an operator I would like to use hardware label to differentiate PCI device of the same deviceID/VendorID.
It might be useful to separate device between different workload clusters.

**Anything else you would like to add:**
Nothing else.

**Environment:**

- Cluster-api-provider-vsphere version: v1.6.0
- Kubernetes version: (use `kubectl version`): v1.22.17
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.6 LTS

**Comment by chrischdi** [comment]
I think this makes sense.

This does not need an additional implementation for vm operator mode.
VM operator mode seems to already support it via `VirtualMachineClass`:

https://github.com/vmware-tanzu/vm-operator/blob/main/api/v1alpha1/virtualmachineclass_types.go#L23
