### ISSUE TITLE
[Feature] support vCenter Clusters and Host Groups

### ISSUE THREAD

**Issue by frodenas** [kubernetes-sigs/cluster-api-provider-vsphere#252]
When deploying a machine, we would like to specify a VC Cluster or a DRS Host Group. This will allow deploying master and worker machines in different fault domains. Right now, we can only specify a Resource Pool.

**Comment by ksemele** [comment]
/reopen
Any updates here?

**Comment by movergan** [comment]
We can benefit from that feature too. Can it be reopened?

**Comment by chrischdi** [comment]
Did you consider using VSphereDeploymentZone + VSphereFailureDomain for this?
Or does it lack support for your use-case?

**Comment by ksemele** [comment]
@chrischdi It seems that this is not suitable...
we have several vSphere clusters, for example, cluster_A, cluster_B, cluster_C, and we want the control plane of 3 replicas to be created immediately distributed among these clusters...
But maybe it's not applicable to ClusterAPI by its design itself.

**Comment by chrischdi** [comment]
If I get it right, exactly that should be possible via VSphereDeploymentZone + VSphereFailureDomain

You can define 3 times VSphereDeploymentZone + VSphereFailureDomain which refers e.g. different HostGroups or computeClusters or even VCenters (requires same user + password across the vCenters).

**Comment by ksemele** [comment]
Oh, it seems I understand now... yes, that's roughly what we need, it seems this is not sufficiently documented, as it is very unclear that capi will automatically use all the created VSphereDeploymentZones and I don't need to manage it manually.
