### ISSUE TITLE
Flaky tests umbrella issue

### ISSUE THREAD

**Issue by chrischdi** [kubernetes-sigs/cluster-api-provider-vsphere#2536]
/kind bug

**What steps did you take and what happened:**

Run tests or created a PR where the tests or coverage failed.

**What did you expect to happen:**

The tests to succeed.

**Anything else you would like to add:**

Target of this issue is to collect test cases and information so we can get rid of the flakiness.

* `sigs.k8s.io/cluster-api-provider-vsphere/controllers/vmware/test` [link](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/actions/runs/7146022081/job/19462872633?pr=2535)
  * `fatal error: concurrent map read and map write`
  * <details>

    ```
    2023-12-08T20:37:22.6873626Z [38;5;10m•[0mE1208 20:35:08.815675    3204 options.go:127] "error opening credentials file" err="open : no such file or directory"
    2023-12-08T20:37:22.6873785Z fatal error: concurrent map read and map write
    2023-12-08T20:37:22.6873797Z 
    2023-12-08T20:37:22.6873910Z goroutine 1800 [running]:
    ...
    2023-12-08T20:37:22.7306001Z FAIL	sigs.k8s.io/cluster-api-provider-vsphere/controllers/vmware/test	11.532s
    ```
    </details>

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2537 will make collecting flaky tests easier

**Comment by sbueringer** [comment]
@chrischdi Are we good, given the recent fixes?

**Comment by chrischdi** [comment]
It's currently not 100% good (but it propably will never be)

Current state is https://storage.googleapis.com/k8s-triage/index.html?job=.*-cluster-api-provider-vsphere.*

<img width="1094" alt="image" src="https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/assets/417870/43a22ddc-bb61-472f-95f0-66bfe24cd3ea">

which is pretty good.

/close
