### ISSUE TITLE
Node not removed when Machine is deleted

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#256]
The default behavior observed in k8s 1.11.x was that when one deletes the Machine object, the node associated with the machine would automatically get removed from the node list in a couple of minutes. This behavior got changed soon after 1.11.6 or so. Thus with k8s 1.12.x or newer, the node object is left behind even after the Machine object and the underlying VM is deleted.

**Comment by ncdc** [comment]
@sidharthsurana do you know which PR or commit changed this behavior in Kubernetes?

**Comment by sidharthsurana** [comment]
@ncdc I don't really know which PR introduced that changed behavior, but I got to know about that when I was chasing some other issue with PVs created with VCP.
@gnufied may have some idea about this behavior, as he was the one who told me about it.

**Comment by gnufied** [comment]
In 1.12 branch - https://github.com/kubernetes/kubernetes/pull/66619 the commit that introduced that behaviour (there is a small chance I could be wrong but commit should be in vicinity of this stuff). This also brings vsphere in-line with other cloudproviders where node object is kept around when a node is shutdown. 

In 1.11 series then to fix detach issue from shutdown nodes on vSphere, I intentionally changed behaviour of shutdown nodes to be kept in apiserver - https://github.com/kubernetes/kubernetes/pull/70291
