### ISSUE TITLE
Proposal - Add go-deadlock detection on places we use mutexes

### ISSUE THREAD

**Issue by rikatz** [kubernetes-sigs/cluster-api-provider-vsphere#2611]
Recently, we have implemented a feature to [force Logouts](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2530/files) on vSphere sessions.

This was due to a heavy usage of vsphere sessions and no logout after errors on session or reconciliation.

But a new problem arrived: govmomi has a [deadlock risk ](https://github.com/vmware/govmomi/issues/3240) on keepalive handler that, when calling Logout, can happen, getting all of the reconciliation process that relies on [session.GetOrCreate](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/3559ab28072c163796a58af6e2ef5d83680324e0/pkg/session/session.go#L125)

Because now we may be calling Logout multiple times, and this can get deadlocked if using keepalive, we need a way to detect this situation and restart in case of it. (actually we need to fix the deadlock, but we should have a way to avoid it on the future as well).

Some other projects have been using https://github.com/sasha-s/go-deadlock as a inplace replacement for the builtin sync package, so the proposal here is that at least on this specific part of the code where this deadlock may be happening (down to govmomi), we detect and restart CAPV.

The usage of this library seems like a low risk, as it can be easily reverted to use builtin `sync` package again, and it is being used on some other big projects.

Based on its usage, we can either flag it with options like:
* Should deadlock detection be enabled?
* What's a lock timeout before considering the process deadlocked?

Also we need to define if we should panic in case of deadlocks, so this allows the pod / container to restart? What would be the deadlock dealing callback?

@berlin-ab tagging you as well as we did had some discussions about it

**Comment by sbueringer** [comment]
Overall sounds good to me

> Should deadlock detection be enabled?

I think overall we can enable it. The question is what do we do if we find one:
* panic/kill the controller?
* log something?

> What's a lock timeout before considering the process deadlocked?
I guess we can pick some timeout which is higher than whatever is reasonable for the code we cover with the mutex + some buffer. I guess if we pick something >= 1m we should be okay?

**Comment by berlin-ab** [comment]
> The question is what do we do if a deadlock occurs as you said

I think ideally the system heals itself rather than remain in a deadlocked state. I guess your question is "is it always safe to panic?"

**Comment by sbueringer** [comment]
Yeah and also. If we are panic'ing does this improve the situation or are we just directly panic'ing again and ending up in CrashLoopBackoff.

But I think in this case it actually helps and improves uptime as the sessions are recreated from scratch on the client-side and if we're stuck in this mutex everything is blocked anyway.
