### ISSUE TITLE
Unable to pull kubeconfig

### ISSUE THREAD

**Issue by derryos** [kubernetes-sigs/cluster-api-provider-vsphere#263]
Testing out the vsphere cluster api provider - the following is the output from my clusterctl call:

```
clusterctl create cluster --provider vsphere --bootstrap-type kind -c cluster.yaml -m machines.yaml -p provider-components.yaml
I0515 14:44:00.573102   48124 createbootstrapcluster.go:27] Creating bootstrap cluster
I0515 14:44:45.045965   48124 clusterdeployer.go:79] Applying Cluster API stack to bootstrap cluster
I0515 14:44:45.046228   48124 applyclusterapicomponents.go:26] Applying Cluster API Provider Components
I0515 14:44:46.315146   48124 clusterdeployer.go:84] Provisioning target cluster via bootstrap cluster
I0515 14:44:46.338963   48124 applycluster.go:36] Creating cluster object test1 in namespace "default"
I0515 14:44:46.351680   48124 clusterdeployer.go:93] Creating control plane  in namespace "default"
I0515 14:44:46.359685   48124 applymachines.go:36] Creating machines in namespace "default"
I0515 14:46:36.393932   48124 clusterdeployer.go:98] Updating bootstrap cluster object for cluster test1 in namespace "default" with control plane endpoint running on
I0515 14:46:36.445029   48124 clusterdeployer.go:103] Creating target cluster
I0515 14:46:36.458291   48124 utils.go:170] pulling kubeconfig (using ssh) from 10.******.49
I0515 14:46:38.261425   48124 utils.go:183] ssh failed with error = exit status 255
```

I've tried ssh-ing in manually using the laid down key:
```
ssh -i ~/.ssh/vsphere_tmp 10.****.49
<first.last>@10.***.49: Permission denied (publickey).
```

Is it correct that the key in provider-components.yaml should be laid down in my .ssh and also on the booted master? I just ran make prod-yaml and then customised the settings. I'm using the ubuntu 16.04 ova (converted from a vm to a template) as my template.

**Comment by figo** [comment]
@derryos could you confirm that ssh keys in `.ssh` (where you run `clusterctl`) and provider-components.yaml matched?   (it was not clear to me by reading your description)

**Comment by derryos** [comment]
Yes, they are present:
```
ll ~/.ssh/vsphere_tmp*
-rw-------  1  1.8K 15 May 14:39 /Users/derryos/.ssh/vsphere_tmp
-rw-r--r--  1    430B 15 May 14:39 /Users/derryos/.ssh/vsphere_tmp.pub

**Comment by figo** [comment]
looks like the ssh key is not the issue, then it most likely the OVA image, could you clarify where is your ubuntu 16.04 ova download from? we need to make sure it support cloud-init.

**Comment by derryos** [comment]
For reference, i'm running local bootstrap cluster on macos using kind:
```
$ kind version
0.2.1
$ kustomize version
Version: {KustomizeVersion:v2.0.3 GitCommit:a6f65144121d1955266b0cd836ce954c04122dc8
$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"1.0.8", KubernetesVendor:"1.13.1", GitCommit:"1adf50ed107f5042d7472ba5ab50d5e1d357169d", BuildDate:"2019-01-25T23:14:29Z", GoOs:"unknown", GoArch:"unknown"}
$ go version
go version go1.12.5 darwin/amd64

```
I'm using a recent commit from master (e1a0555411eee447fa0321f32cad4edb3d90e093)

I've also downloaded https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64.ova as per the docs....i assumed this had cloud-init already on it as the steps are:
1 download https://cloud-images.ubuntu.com/releases/16.04/release/ubuntu-16.04-server-cloudimg-amd64.ova
2. deploy the ova
3. create a template for this vm

I had tried to use an existing template that i had and got the error
```
E0513 20:39:34.992365       1 machineactuator.go:66] this source VM lacks a vApp configuration and cannot have vApp properties set on it
W0513 20:39:34.992409       1 controller.go:220] Failed to create machine "vs-master-2v266": this source VM lacks a vApp configuration and cannot have vApp properties set on it
```

**Comment by figo** [comment]
@derryos  the best way to move forward right now is: please send the controller manager log as a link here, for example: you can use gist.

you can get controller manager log by:
```
kubectl logs vsphere-provider-controller-manager-0 -n vsphere-provider-system
```

**Comment by sflxn** [comment]
@derryos I'm not sure if you wrote the full ssh command or not, but when you ssh, you need to also to specify the default user name, which is ubuntu.  If you've changed that in the scripts in templates.go (which is not recommended and only for dev), then the user name will be different.

**Comment by sflxn** [comment]
@derryos @figo As further debugging assist, you can bump up the log level in provider-components.yaml.

```
      containers:
      - args:
        - --logtostderr
        - --v=6
        command:
        - /root/manager
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: gcr.io/cnx-cluster-api/vsphere-cluster-api-provider:0.2.0
```

**Comment by derryos** [comment]
Am away from laptop until tomorrow (GMT here!) - but i'll add those logs in the AM. I haven't edited any go code (e.g. changed usernames etc) and tried with ubuntu user (same result).

**Comment by derryos** [comment]
Added gist with requested output to https://gist.github.com/derryos/2ed5a3d9e8515673dbb0d4420ad07762 (I removed some username/internal info)

**Comment by derryos** [comment]
Also
```
ssh  -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -i ~/.ssh/vsphere_tmp ubuntu@10.***.46
Warning: Permanently added '10.128.47.46' (ECDSA) to the list of known hosts.
ubuntu@10.***.46: Permission denied (publickey).
```

**Comment by derryos** [comment]
Is it possible that there is an issue with the key?
```
openssl rsa -in ~/.ssh/vsphere_tmp -check
unable to load Private Key
4448298604:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.250.1/libressl-2.6/crypto/pem/pem_lib.c:683:Expecting: ANY PRIVATE KEY
```

Also: https://github.com/net-ssh/net-ssh/issues/633 https://github.com/net-ssh/net-ssh/issues/638#issuecomment-441189002

```
ssh -V
OpenSSH_7.9p1, LibreSSL 2.7.3
```

**Comment by derryos** [comment]
This also seems relevant https://serverfault.com/a/941893
I'm on mojave 10.4.4 for reference:

Generating a key the old and new way and validating after...
```
$ ssh-keygen -t rsa -f /tmp/key-default -N ""
Generating public/private rsa key pair.
Your identification has been saved in /tmp/key-default.
Your public key has been saved in /tmp/key-default.pub.
.....

➜  ~ ssh-keygen -t rsa -f /tmp/key-new -N "" -m PEM
Generating public/private rsa key pair.
Your identification has been saved in /tmp/key-new.
Your public key has been saved in /tmp/key-new.pub.
....
$ openssl rsa -in /tmp/key-default -check
unable to load Private Key
4472022636:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-22.250.1/libressl-2.6/crypto/pem/pem_lib.c:683:Expecting: ANY PRIVATE KEY
$ openssl rsa -in /tmp/key-new -check
RSA key ok
writing RSA key
...
```

**Comment by derryos** [comment]
Unfortunately, same error even after adding the -m PEM to the generate-yaml.sh script:

```
➜  ~ openssl rsa -in ~/.ssh/vsphere_tmp -check -noout
RSA key ok
➜  ~ ssh ubuntu@10.***.45
ubuntu@10.****.45: Permission denied (publickey).
```

**Comment by derryos** [comment]
@figo  / @sflxn  - any idea how to progress on the above?

**Comment by figo** [comment]
@derryos from the log you linked, it is able to ssh into VM, but the kubeconfig was not ready.

```
I0516 06:14:35.665331       1 round_trippers.go:438] GET https://10.96.0.1:443/api/v1/namespaces/default/secrets/92746ed1-77a1-11e9-9c20-02428d4a563e-kubeconfig 404 Not Found in 6 milliseconds
I0516 06:14:35.665818       1 clusteractuator.go:109] could not pull secrets for kubeconfig
I0516 06:14:35.666176       1 utils.go:170] pulling kubeconfig (using ssh) from 10.****.46
I0516 06:14:36.952471       1 utils.go:183] ssh failed with error = exit status 255
I0516 06:14:36.952898       1 clusteractuator.go:118] [cluster-actuator] error retrieving kubeconfig for target cluster, will requeue
I0516 06:14:36.953161       1 clusteractuator.go:96] ClusterActuator failed to get cluster status: requeue in: 20s
I0516 06:14:36.953421       1 controller.go:131] Actuator returned requeue after error: requeue in: 20s
I0516 06:14:55.624645       1 controller.go:89] Running reconcile Cluster for test1
I0516 06:14:55.624752       1 controller.go:127] reconciling cluster object test1 triggers idempotent reconcile.
I0516 06:14:55.624994       1 clusteractuator.go:60] Attempting to reconcile cluster test1
I0516 06:14:55.625268       1 clusteractuator.go:106] attempting to fetch kubeconfig
I0516 06:14:55.634851       1 round_trippers.go:438] GET https://10.96.0.1:443/api/v1/namespaces/default/secrets/92746ed1-77a1-11e9-9c20-02428d4a563e-kubeconfig 404 Not Found in 8 milliseconds
I0516 06:14:55.635060       1 clusteractuator.go:109] could not pull secrets for kubeconfig
```
it suppose to say: SSH error if it is not able to ssh into VM.
and you can not SSH into VM for debugging is a separate issue (let discuss it a bit later).

now could you share your cluster.yaml, machine.yaml, or machineset.yaml?  if yaml has non-valid configuration, it could result in cloud-init failure. ( although if we confirm all yaml configurations are valid, we will need to ssh into VM to get logs to move the debugging forward.)

**Comment by derryos** [comment]
@figo thanks for responding. I'm not sure if i really understand your comment - i thought i should be able to ssh into the machine?

As said earlier, i can't log into the machine manually using the pub file:
```
ssh -vvv -i ~/.ssh/vsphere_tmp ubuntu@10.128.46.134
OpenSSH_7.9p1, LibreSSL 2.7.3
....
debug1: Offering public key: .ssh/vsphere_tmp RSA SHA256:dYVeg*****tsxM explicit
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 51
....
debug1: Authentications that can continue: publickey
debug2: we did not send a packet, disable method
debug1: No more authentication methods to try.
ubuntu@10.128.46.134: Permission denied (publickey).
```

I'll anonymise the config files and add a gist. I agree that we need to SSH into vm to debug fully - the template that we are using is used in other (terraform) scripts to boot images with cloud init data fyi

**Comment by derryos** [comment]
BTW, made some 'related' progress on this. I think the issue is with the template.

As i was saying previously, i could not use our existing templates (that we use with terraform vsphere provider - also govnomi) but tried again with 
```
vSphereCloudInit: true 
```
in my machines and machineset.yaml

This now allows me to ssh into an instance using the ubuntu user/keys:
```
ssh -i ~/.ssh/vsphere_tmp ubuntu@10.***.133
[ubuntu@vs-master-h5jtw ~]$
```

Does that flag need to be set for the ubuntu ova? I noticed in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/72 that it says:
```
For usual upstream version of
ubuntu cloud image that has been used so far, this flag need not be set at all and the
controller will utilize the OVF properties available on the ubuntu cloud image to inject
the cloud-init data.
```

I'm now at a new error but think this is an issue on my side:
```
I0528 09:03:39.223929   16532 getkubeconfig.go:60] Waiting for kubeconfig on vs-master-h5jtw to become ready...
I0528 09:03:39.223950   16532 utils.go:170] pulling kubeconfig (using ssh) from 10.1***.133
cat: /etc/kubernetes/admin.conf: No such file or directory
I0528 09:04:02.027327   16532 utils.go:183] ssh failed with error = exit status 1
```

**Comment by figo** [comment]
> @figo thanks for responding. I'm not sure if i really understand your comment - i thought i should be able to ssh into the machine?

yes, you should able to ssh into VM manually, but that is a separate issue (debugging issue), 
clusterctl was able to ssh into VM based on log you provided.
> 
> As said earlier, i can't log into the machine manually using the pub file:
> 
> ```
> ssh -vvv -i ~/.ssh/vsphere_tmp ubuntu@10.***.134
> OpenSSH_7.9p1, LibreSSL 2.7.3
> ....
> debug1: Offering public key: .ssh/vsphere_tmp RSA SHA256:dYVeg*****tsxM explicit
> debug3: send packet: type 50
> debug2: we sent a publickey packet, wait for reply
> debug3: receive packet: type 51
> ....
> debug1: Authentications that can continue: publickey
> debug2: we did not send a packet, disable method
> debug1: No more authentication methods to try.
> ubuntu@10.***.134: Permission denied (publickey).
> ```
> 
> I'll anonymise the config files and add a gist ( three files are in https://gist.github.com/derryos/87c43c9a35cfb858977484ce0beb0873 ). I agree that we need to SSH into vm to debug fully - the template that we are using is the standard ubuntu 16.04 ova linked from doc.

**Comment by derryos** [comment]
clusterctl was able to ssh into the newer vm I spun up (based on our own template vs the documented ubuntu ova template). 

Unfortunately, i now have a vm i can log into but no way of knowing why kubernetes components will not start (i see content in //etc/kubernetes/cloud-config/cloud-config.yaml )

How do i debug that part of the process (e.g. what components are installed on the booted master vm and how are they configured?)

**Comment by figo** [comment]
> clusterctl was able to ssh into the newer vm I spun up (based on our own template vs the documented ubuntu ova template).
> 
> Unfortunately, i now have a vm i can log into but no way of knowing why kubernetes components will not start (i see content in //etc/kubernetes/cloud-config/cloud-config.yaml )
> 
> How do i debug that part of the process (e.g. what components are installed on the booted master vm and how are they configured?)

could you check a few log files if you have access to VM?
/var/log/cloud-init*.log
/var/log/startup.log
please paste the logs file here if possible, thx

**Comment by figo** [comment]
also, please link the yaml file (cluster.yaml, machine.yaml etc) as well, just want to make sure the configurations are valid.

**Comment by derryos** [comment]
The only difference to the previous yaml inputs was replacing the existing template reference with our own template (vs the ova one) and setting vsphereCloudInit to true:
```
template: "vmTemplateController230519"
vsphereCloudInit: true
```

This template is a centos 7.6 image with the cloud init/vmware datasource configured.

This makes a lot of sense now:
```
# cat /var/log/startup.log
+ KUBELET_VERSION=1.11.3
+ curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg
+ apt-key add -
/tmp/boot.sh: line 9: apt-key: command not found

# grep -v DEBUG /var/log/cloud-init*.log
2019-05-28 08:52:36,143 - stages.py[INFO]: Loaded datasource DataSourceVMwareGuestInfo - DataSourceVMwareGuestInfo
2019-05-28 08:52:36,286 - stages.py[INFO]: Applying network configuration from ds bringup=False: {'version': 1, 'config': [{'subnets': [{'type': 'dhcp'}], 'type': 'physical', 'name': 'eth0'}]}
2019-05-28 08:52:43,028 - __init__.py[INFO]: /var/lib/cloud/data/previous-hostname differs from /etc/hostname, assuming user maintained hostname.
2019-05-28 08:52:43,117 - __init__.py[INFO]: Created new group sudo
2019-05-28 08:54:51,860 - util.py[WARNING]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 793, in _run_modules
    freq=freq)
  File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py", line 109, in handle
    key_entries, hash_meth)
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py", line 95, in _pprint_key_entries
    stderr=False, console=True)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 524, in multi_log
    wfh.flush()
IOError: [Errno 5] Input/output error
2019-05-28 08:54:51,936 - cc_keys_to_console.py[WARNING]: Writing keys to the system console failed!
2019-05-28 08:54:51,938 - util.py[WARNING]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_keys_to_console.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 793, in _run_modules
    freq=freq)
  File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run
    results = functor(*args)
  File "/usr/lib/python2.7/site-packages/cloudinit/config/cc_keys_to_console.py", line 69, in handle
    stderr=False, console=True)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 524, in multi_log
    wfh.flush()
IOError: [Errno 5] Input/output error
```

Is it possible to download all external requirements and place on the template vs downloading at startup?

**Comment by sidharthsurana** [comment]
Yes, there is. You can preload all the binary artifacts (like kubelet, kubeadm, docker, etc.) in the image and then set the `preloaded: true` flag in the `MachineSpec`. This will then only trigger the configuration aspect of the scripts.

**Comment by derryos** [comment]
Thanks - i got to the point where it complained about kubeadm not being installed, once i solved that, its failing on some pre flight checks which are all issues on my side.

I think the only issue outstanding is why i can't ssh into the ubuntu 16.04 ova?

**Comment by sidharthsurana** [comment]
you should be able to ssh into the VM via ssh keys
try `ssh -i ~/.ssh/vsphere_tmp ubunutu@<IP of VM >`

**Comment by derryos** [comment]
@sidharthsurana thanks - see earlier comments (from https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/263#issuecomment-492938595 onwards), i was not able to login using the ubuntu user/key on the ubuntu 16.04 ova included in documentation (but could do so with my own centos template)

**Comment by sidharthsurana** [comment]
I think the issue might be because you are using the OVA as the template itself. I have never tried that personally, and I doubt if it will work since that OVA most likely has some other boot scripts set to run. Can you try using the Ubuntu cloud image directly from the internet [https://cloud-images.ubuntu.com](https://cloud-images.ubuntu.com)
The only catch is that since these images do not have the vsphere cloud-init datasource in them, thus static IP functionality will not work.  Also, note that when using this upstream image, please remove the `vSphereCloudInit: true` property or set it to false in the `machineSpec`

**Comment by derryos** [comment]
@sidharthsurana thanks

What exactly do you mean by 'using the ova as the template'? Is there something to be done between booting the OVA and creating the template?

I just assumed that i needed to create a template from the ova and i used ovftool to do this:
```
$ ovftool --noSSLVerify -n=test-ova01 --acceptAllEulas --allowExtraConfig --vmFolder=<x> --datastore=<x> -nw=<x> --ipAllocationPolicy=dhcpPolicy --powerOn ubuntu-16.04-server-cloudimg-amd64.ova "vi://<vsphere creds>"
```
(and then created a template from that vm)

I'm using DHCP for all my testing and i only set the vsphereCloudInit: true when i moved to the non OVA image

**Comment by moshloop** [comment]
@derryos you can try create a new vmTemplate using this OVA: https://storage.googleapis.com/capv-images/release/v1.13.6/ubuntu-1804-kube-v1.13.6.ova

The next release changes the mechanism for getting the kubeconfig,  it is no longer pulled via SSH, but generated from the CA that is injected into the master node. The need for the bootstrap OVA has also been removed (note that the bootstrap OVA is different to the vmTemplate used for the cluster nodes)

/close
