### ISSUE TITLE
🐛 kube-vip-prepare.sh - return does not work

### ISSUE THREAD

**Issue by PatrickLaabs** [kubernetes-sigs/cluster-api-provider-vsphere#2659]
Hey everyone,

we encountered the issue, that the script below does not work as one might expect.
Running flatcar with Kubernetes v1.28.6, the script failes to run, since a return is only valid inside a function.

We tried to modify it by replacing the "return" with "exit 0", which then starts to work.

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/d4e07cd3ec58d85645fd63faf2d835ba6649a31e/packaging/flavorgen/flavors/kubevip/kube-vip-prepare.sh#L22-L26

Here is our change:

```
KUBEADM_MINOR="$(kubeadm version -o short | cut -d '.' -f 2)"
if [[ "$KUBEADM_MINOR" -lt "29" ]]; then
  exit 0
fi
```

What you guys think?

**Comment by chrischdi** [comment]
Sounds good. Thanks for bringing this up!

**Comment by sbueringer** [comment]
Same as on the other PR. Any ideas why our e2e tests didn't capture it?
