### ISSUE TITLE
[question] secret cloud-provider-vsphere-e2e-config how to create and keep private

### ISSUE THREAD

**Issue by jichenjc** [kubernetes-sigs/cluster-api-provider-vsphere#268]
cluster-api-provider-ibmcloud is trying to build e2e and encounter some issue, 
we found vsphere uses secret cloud-provider-vsphere-e2e-config to store the credential for login before push. but we are not sure how to create and keep credential private.

https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/154 has more info ..

**Comment by figo** [comment]
@jichenjc the secret `cloud-provider-vsphere-e2e-config` need be set on Prow(https://github.com/kubernetes/test-infra/tree/master/prow), in a short answer: you need to talk to sig-testing to setup secret for your provider.

**Comment by jichenjc** [comment]
@figo thanks a lot, we will switch to sig-testing for more info~
