### ISSUE TITLE
Ignition does not set the vm ip address

### ISSUE THREAD

**Issue by xsen84** [kubernetes-sigs/cluster-api-provider-vsphere#2684]
/kind bug

**What steps did you take and what happened:**
Deploying flatcar vm and configuring via ignition does not set the ip address as passed through the guestinfo.metadata. 
Image used: flatcar-stable-3510.2.4-kube-v1.27.3

**What did you expect to happen:**
Set the ip as defined in guestinfo.metadata > network. 

**Anything else you would like to add:**
This works if using ubuntu with cloud-init.
Image used: ubuntu-1804-kube-v1.17.3

**Environment:**

- Cluster-api-provider-vsphere version: v1.9.0
- Kubernetes version: (use `kubectl version`): v1.27.3
- OS (e.g. from `/etc/os-release`): flatcar/coreos 3510.2.4

**Comment by chrischdi** [comment]
Could you please provide details about the yaml's you are using? How are you setting the ip address?

**Comment by chrischdi** [comment]
First idea: ignition may not support the format we use when providing the `guestinfo.metadata` information.

**Comment by chrischdi** [comment]
Would be awesome to see the relevant logs for ignition.

**Comment by chrischdi** [comment]
Note: flatcar does not seem to support the guestinfo.metadata format in the flatcar version you are referencing above.

It may be worth to try the latest verison of flatcar (https://www.flatcar.org/releases#release-3760.2.0) which includes `afterburn` in `v5.5.0` which should include this implementation of support for the format: https://github.com/coreos/afterburn/pull/888 .

**Comment by vgromanov** [comment]
We also ran into this issue and as a workaround had to use a crude shell script which parses netplan yaml into a systemd network unit:
```
#!/bin/bash
PATH=$PATH:/bin
function yaml_to_vars {
   # find input file
   for f in "$1" "$1.yay" "$1.yml"
   do
     [[ -f "$f" ]] && input="$f" && break
   done
   [[ -z "$input" ]] && exit 1

   # use given dataset prefix or imply from file name
   [[ -n "$2" ]] && local prefix="$2" || {
     local prefix=$(basename "$input"); prefix=${prefix%.*}; prefix="${prefix//-/_}_";
   }

   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|,$s\]$s\$|]|" \
        -e ":1;s|^\($s\)\($w\)$s:$s\[$s\(.*\)$s,$s\(.*\)$s\]|\1\2: [\3]\n\1  - \4|;t1" \
        -e "s|^\($s\)\($w\)$s:$s\[$s\(.*\)$s\]|\1\2:\n\1  - \3|;p" $1 | \
   sed -ne "s|,$s}$s\$|}|" \
        -e ":1;s|^\($s\)-$s{$s\(.*\)$s,$s\($w\)$s:$s\(.*\)$s}|\1- {\2}\n\1  \3: \4|;t1" \
        -e    "s|^\($s\)-$s{$s\(.*\)$s}|\1-\n\1  \2|;p" | \
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)-$s[\"']\(.*\)[\"']$s\$|\1$fs$fs\2|p" \
        -e "s|^\($s\)-$s\(.*\)$s\$|\1$fs$fs\2|p" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" | \
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]; idx[i]=0}}
      if(length($2)== 0){  vname[indent]= ++idx[indent] };
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) { vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, vname[indent], $3);
      }
   }'
}

/usr/share/oem/bin/vmtoolsd --cmd "info-get guestinfo.metadata" | /bin/base64 --decode > /tmp/netplan.yaml
cat /tmp/netplan.yaml
yaml_to_vars /tmp/netplan.yaml
eval $(yaml_to_vars /tmp/netplan.yaml)
/bin/cat > /etc/systemd/network/10-ipam.network << EOF
[Match]
MACAddress=$netplan_network_ethernets_id0_match_macaddress

[Network]
DHCP=no
DNS=$netplan_network_ethernets_id0_nameservers_1
DNS=$netplan_network_ethernets_id0_nameservers_2
DNS=$netplan_network_ethernets_id0_nameservers_3
Address=$netplan_network_ethernets_id0_1
Gateway=$netplan_network_ethernets_id0_gateway4
EOF
```
Yeah. It is ugly.

**Comment by xsen84** [comment]
> We also ran into this issue and as a workaround had to use a crude shell script which parses netplan yaml into a systemd network unit:
> 
> ```
> #!/bin/bash
> PATH=$PATH:/bin
> function yaml_to_vars {
>    # find input file
>    for f in "$1" "$1.yay" "$1.yml"
>    do
>      [[ -f "$f" ]] && input="$f" && break
>    done
>    [[ -z "$input" ]] && exit 1
> 
>    # use given dataset prefix or imply from file name
>    [[ -n "$2" ]] && local prefix="$2" || {
>      local prefix=$(basename "$input"); prefix=${prefix%.*}; prefix="${prefix//-/_}_";
>    }
> 
>    local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
>    sed -ne "s|,$s\]$s\$|]|" \
>         -e ":1;s|^\($s\)\($w\)$s:$s\[$s\(.*\)$s,$s\(.*\)$s\]|\1\2: [\3]\n\1  - \4|;t1" \
>         -e "s|^\($s\)\($w\)$s:$s\[$s\(.*\)$s\]|\1\2:\n\1  - \3|;p" $1 | \
>    sed -ne "s|,$s}$s\$|}|" \
>         -e ":1;s|^\($s\)-$s{$s\(.*\)$s,$s\($w\)$s:$s\(.*\)$s}|\1- {\2}\n\1  \3: \4|;t1" \
>         -e    "s|^\($s\)-$s{$s\(.*\)$s}|\1-\n\1  \2|;p" | \
>    sed -ne "s|^\($s\):|\1|" \
>         -e "s|^\($s\)-$s[\"']\(.*\)[\"']$s\$|\1$fs$fs\2|p" \
>         -e "s|^\($s\)-$s\(.*\)$s\$|\1$fs$fs\2|p" \
>         -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
>         -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" | \
>    awk -F$fs '{
>       indent = length($1)/2;
>       vname[indent] = $2;
>       for (i in vname) {if (i > indent) {delete vname[i]; idx[i]=0}}
>       if(length($2)== 0){  vname[indent]= ++idx[indent] };
>       if (length($3) > 0) {
>          vn=""; for (i=0; i<indent; i++) { vn=(vn)(vname[i])("_")}
>          printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, vname[indent], $3);
>       }
>    }'
> }
> 
> /usr/share/oem/bin/vmtoolsd --cmd "info-get guestinfo.metadata" | /bin/base64 --decode > /tmp/netplan.yaml
> cat /tmp/netplan.yaml
> yaml_to_vars /tmp/netplan.yaml
> eval $(yaml_to_vars /tmp/netplan.yaml)
> /bin/cat > /etc/systemd/network/10-ipam.network << EOF
> [Match]
> MACAddress=$netplan_network_ethernets_id0_match_macaddress
> 
> [Network]
> DHCP=no
> DNS=$netplan_network_ethernets_id0_nameservers_1
> DNS=$netplan_network_ethernets_id0_nameservers_2
> DNS=$netplan_network_ethernets_id0_nameservers_3
> Address=$netplan_network_ethernets_id0_1
> Gateway=$netplan_network_ethernets_id0_gateway4
> EOF
> ```
> 
> Yeah. It is ugly.
> 
> Update: as for `afterburn` in latest flatcar version - it is pretty much useless. It is only capable of burping out netplan config which makes no point.

Thanks a lot. It worked. I ended up using only this, as it looks a little better:
```
address=$(echo $encoded | base64 -d | awk -F'"' '/addresses:/{getline; gsub(/^[ \t"-]+|[ \t"-]+$/,""); print}')
gateway=$(echo $encoded | base64 -d | awk -F'"' '/gateway4:/{gsub(/^[ \t"-]+|[ \t"-]+$/,""); print $2}')
macaddr=$(echo $encoded | base64 -d | awk -F'"' '/macaddress:/{gsub(/^[ \t"-]+|[ \t"-]+$/,""); print $2}')
```
