### ISSUE TITLE
Build fails in an environment with a proxy

### ISSUE THREAD

**Issue by kisanth88** [kubernetes-sigs/cluster-api-provider-vsphere#270]
The below scripts fail when executed in an environment with a proxy server.

package_provisioning.sh
provision_govc.sh
provision_kubernetes.sh

Workaround was to declare -x http_proxy="x.x.x.x:yy" and declare -x https_proxy="x.x.x.x:yy" directly in the scripts, this is not an extensible solution however. Need a mechanism for passing proxy information into the scripts from farther upstream.

Thanks,
JB

**Comment by kisanth88** [comment]
This is also an issue in system_settings.sh 
We declared proxy in this file at the top as well.

Error was not intuitive:  curl#7: Couldn't connect to server
(breadcrumbs for searchers)

This may be an issue with build-disks.sh - however, we pre-emptively declared proxy in function setup_grub

**Comment by kisanth88** [comment]
And build-app.sh :-)

**Comment by figo** [comment]
@kisanth88 you are right, the current build scripts has the assumption of direct internet access.
but you are encouraged to add proxy support with PULL request.

cc @frapposelli
