### ISSUE TITLE
Please create the branch "feature/capa-parity-phase-one"

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#275]
Please create the topic branch `feature/capa-parity-phase-one` in order to facilitate contributors working on this effort to open pull requests to a shared branch that is not `master`. Thank you!

cc @frapposelli @andrewsykim

**Comment by frapposelli** [comment]
done! [`feature/capa-parity-phase-one`](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/feature/capa-parity-phase-one)
