### ISSUE TITLE
CAPV should support SHA-256 thumbprints when connecting to the vSphere API

### ISSUE THREAD

**Issue by rgcostea** [kubernetes-sigs/cluster-api-provider-vsphere#2805]
/kind feature

**Describe the solution you'd like**
Currently, CAPV only supports SHA-1 thumbprints when creating VSphereClusters.  We would like to see support for SHA-256 thumbprints as well.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: v1.9.2
- Kubernetes version: (use `kubectl version`): 1.26.8
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by neolit123** [comment]
cc @yastij @dougm @chrischdi 

@rgcostea pinged the VMware slack about this. my findings are:
- the CAPV session client to a VC seems to have two modes, insecure (without a SHA1 thumbprint) and secure using a SHA1 thumbprint
- the code is here https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/26932c883d37edeeba32b09ed8d91a46581328dc/pkg/session/session.go#L241-L259
- cannot find a way to feed standard cert, key, CA cert - i.e. for mTLS.
- without a thumbprint what happens is that the new client is created here with InsecureSkipVerify as Doug said https://github.com/vmware/govmomi/blob/main/vim25/soap/client.go#L136-L163
- CAPV seems transparent to what type the SHA is, but govmomi expects SHA1.
https://github.com/vmware/govmomi/blob/main/vim25/soap/client.go#L421

**Comment by neolit123** [comment]
i assume next step is to just phase out SHA1 in all places in CAPV, update API comments and docs too?
i can just send a PR for the main branch, but perhaps there is a need for a better plan + discussion.

- https://github.com/kubernetes/kubernetes/issues/125689

**Comment by chrischdi** [comment]
Documented sha256 and using it in code now since merging:

- #3076

However, not yet using it completely in CI, because it would currently break old CAPV branches and also CPI.

Action plan:

- [ ] merge govmomi bump PRs for release branches:
  - #3078
  - #3079
  - #3080
- [ ] wait for the next round of patch releases
- [ ] ensure CPI is also ok with start using sha256 thumbprints
- [ ] configure CI to use sha256 thumbprint

**Comment by sbueringer** [comment]
@chrischdi Assigned the issue to you, please update accordingly once done :)

**Comment by chrischdi** [comment]
/close

This is done and CI still green
