### ISSUE TITLE
Bug: Fetching kubeconfig via ssh poses problems in certain cases

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#282]
In cases where the template used say has an ssh banner or message of the day enabled then the way currently we fetch the kubeconfig does not work.
More specifically, we are using the `stdout` of the remote command `cat /etc/kubernetes/admin.conf` which in cases like the above and some more will contain extra text which makes the fetched kubeconfig incorrect, causing failures in the provider controllers.

We need to change the mechanism of how we are fetching the kubeconfig to a better alternative than using `ssh + remote command execution`

**Comment by moshloop** [comment]
One approach to this would be to generate the CA's first, and then pass them to the machines on boot (via cloud-init, iso, server, etc..)

The advantage is that SSH would not be required on the nodes at all.
