### ISSUE TITLE
Ensure reconcileLoadBalancedEndpoint Function Gets Called Despite Setting of ControlPlaneEndpoint

### ISSUE THREAD

**Issue by silvery1622** [kubernetes-sigs/cluster-api-provider-vsphere#2872]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
The current functionality of CAPV bypasses the reconcileLoadBalancedEndpoint if the ControlPlaneEndpoint is set in either the cluster or vspherecluster. Nonetheless, undesirable scenarios may arise, such as the accidental deletion of the virtualmachineservice corresponding to the cluster control plane service, which disables the ControlPlaneEndpoint.

**What did you expect to happen:**
When reconciling the vspherecluster, CAPV should execute reconcileLoadBalancedEndpoint so it could create the virtualmachineservice if necessary.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Related code link
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/controllers/vmware/vspherecluster_reconciler.go#L203

**Environment:**

- Cluster-api-provider-vsphere version: v1.4.2
- Kubernetes version: (use `kubectl version`):  v1.26.4
- OS (e.g. from `/etc/os-release`): photon 3.0

**Comment by sbueringer** [comment]
Sounds good! Feel free to open a PR

**Comment by sbueringer** [comment]
Wait, doesn't this change the controlplane endpoint? Does this actually recover the cluster? Aren't all our kubelets using this endpoint?

**Comment by zhanggbj** [comment]
Sorry please ignore this... it works in local env as the LoadBalance IP doesn't change...

**Comment by silvery1622** [comment]
Yeah, after discussion with @zhanggbj, we feel we 'd better block the deletion instead of creation.

**Comment by sbueringer** [comment]
Yup makes sense. I'm wondering how exactly :)

As this is a CRD of another controller, maybe it makes sense to add a finalizer? To make sure the service is not deleted while we still need/use it?

(we should probably talk to the vm-operator folks, IIRC that the CRD is from there)

**Comment by chrischdi** [comment]
A different approach would be to make it more easy to discover this issue / bring up a condition or so at the VSphereCluster object, that the object does not exist anymore and for this first iteration still require manually fixing it.

**Comment by silvery1622** [comment]
From what I understand, the vm-operator isn't currently set up to handle VirtualMachineService deletions in its webhook. https://github.com/vmware-tanzu/vm-operator/blob/main/webhooks/virtualmachineservice/v1alpha2/validation/virtualmachineservice_validator.go#L103
Since CAPV is already in charge of the creation of VirtualMachineService for the TKG control plane, what if we also let CAPV handle safeguards against accidental deletions using use a webhook in ValidatingWebhookConfiguration. 

Also, @chrischdi’s idea about using a condition inside VSphereCluster objects could work well in parallel, giving us an extra layer of visibility into this issue.

**Comment by sbueringer** [comment]
> The tricky part is how to distinguish between an intended and an accidental delete.

(independent of how implements the webhook)

**Comment by zhanggbj** [comment]
Considering the cluster has a dependency on VirtualMachineService, VSphereCluster created VirtualMachineService but it's vm-operator who manages VirtualMachineService, I'm thinking in CAPV side:

1. Add a finalizer when VSphereCluster to create VirtualMachineService.
2. Remove the finalizer when deleting VSphereCluster. 
3. We should reach out to the vm-operator team to inform them about this finalizer.

Regarding the ValidationWebhook, I think it's more appropriate for the controller who manages the CR to implement one. In this case, it's vm-operator, but validation needs the cluster context to check whether to prevent deletion, so I prefer using finalizer.

**Comment by sbueringer** [comment]
I think the idea of finalizers is to signal "oh there is some cleanup work to do for **me** here", not to block other controllers from doing there deletion.

**Comment by zhanggbj** [comment]
Yes, I agree, that should indeed be the intention of the finalizer. However, I think it could be beneficial in this scenario to prevent the deletion of the VirtualMachineService until the VsphereCluster is deleted.

Another option is adding a ValidationWebhook within CAPV to reject delete requests for VirtualMachineService, as previously discussed.

I don't have strong opinions on either of these options. It appears to me that both options are trying to interfere with a CR managed by a separate controller, and both would require coordination with the vm-operator team.

**Comment by chrischdi** [comment]
Just adding a finaliser could still lead to users deleting the `VirtualMachineService`. They still can use `kubectl delete --force --grace-period=0` to delete the object, or `kubectl delete` + remove the finaliser.

Also: blocking the final deletion of the object with a finaliser may just lead to "the object is still around", but the `VirtualMachineService` may already be deprovisioned or we may have other side effects.

I think the scope for CAPV for this issue ("`VirtualMachineService` is gone" without CAPV having delete dit) should be to be able to handle all scenarios well:

* If the intent is to delete the Cluster: should still be able to delete it (user has to trigger it via `kubectl delete cluster`, if that's not already the case)
* If the intent is to keep the cluster: Signal the issue and let the user manually fix the case (because there is no automatic way to solve this?!)

**Comment by sbueringer** [comment]
> Also: blocking the final deletion of the object with a finaliser may just lead to "the object is still around", but the VirtualMachineService may already be deprovisioned or we may have other side effects.

Yup that's the point I was trying to make. We can keep the object around, but vm-operator will still go through the deletion. And it would be a strange dependency if the vm-operator skips deletion if our finalizer is present

**Comment by sbueringer** [comment]
Yup, that would be the difference.
