### ISSUE TITLE
Use vm-operator 1.8.6 for E2E testing

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-provider-vsphere#2883]
/kind feature

**Describe the solution you'd like**
We should upgrade the version of vm-operator used for E2E testing to v1.8.5, commit 1ff5180e (final commit will probably change)

**Anything else you would like to add:**
Going forward we should probably be able to test more versions of vm-operator for each version of CAPV, but let's get there incrementally...

**Comment by sbueringer** [comment]
Just a heads-up. Upstream vm-operator has a v1.8.6 tag since 3 days. (fine with using v1.8.5 for now)
