### ISSUE TITLE
Use bigger machines for install on bootstrap conformance tests

### ISSUE THREAD

**Issue by fabriziopandini** [kubernetes-sigs/cluster-api-provider-vsphere#2898]
/kind feature

**Describe the solution you'd like**
Conformance tests are using bigger machines to increase speed/reduce flakes, but install on bootstrap conformance tests are not.

We should start using bigger machines for install on bootstrap conformance tests too

**Anything else you would like to add:**

The existing patch cannot be used (it applies to legacy clusters. install on bootstrap uses a classy cluster)
Also, this is a problem that exists for both govimomi and supervisor templates.

**Comment by sbueringer** [comment]
I'm fine with doing that. But I'm a bit confused why this was never an issue with govmomi

**Comment by fabriziopandini** [comment]
> are we already using bigger machines there? (in the govmomi test) 

AFAIK no

> why this was never a problem with govmomi (tests are absolutely stable there afaik)

I don't have historical context, I'm just assuming the two conformance test have the same requirements.
We can also put this on hold and wait for when we have data about actual resource consumption (I know we have those data for the jobs migrated to the eks cluster, I'm not sure if there is something similar for the jobs running on the google cluster)

**Comment by sbueringer** [comment]
I think we're talking about different resources. Wasn't the idea to change the size of the VMs created in VMC? Not the resources for the ProwJob?

**Comment by fabriziopandini** [comment]
It is the VM size, rif https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/test/e2e/data/infrastructure-vsphere-govmomi/main/conformance/worker-node-size.yaml

**Comment by sbueringer** [comment]
I'm fine either way. I think we can either wait to see if the conformance tests are flaky or fix it directly

**Comment by fabriziopandini** [comment]
/close 

This doesn't seem to be an issue and we are in the process of migrating to a different infrastructure (this means we should probably re-assess resource usage after migration)
