### ISSUE TITLE
periodic-cluster-api-provider-vsphere-test-release-1-7 is flaky

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#2929]
periodic-cluster-api-provider-vsphere-test-release-1-7 is flaky since at least 2 weeks

See:
* testgrid: https://testgrid.k8s.io/vmware-cluster-api-provider-vsphere#periodic-test-release-1-7
* one example https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-vsphere-test-release-1-7/1782415855628324864

Slightly wondering if we forgot to cherry-pick some of our fixes (@chrischdi do you remember with which PRs we improved stability of this test on main?)

**Comment by chrischdi** [comment]
All green since https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/2983 + cherry-picks got merged 🎉 

/close
