### ISSUE TITLE
enable-keep-alive is not disabled in version cluster-api-vsphere-controller:v1.10.0.

### ISSUE THREAD

**Issue by hrbasic** [kubernetes-sigs/cluster-api-provider-vsphere#2946]
/kind bug

**What steps did you take and what happened:**
- Deployed capv-controller-manager v1.10.0 with cluster-api-operator

**What did you expect to happen:**
- `--enable-keep-alive` option should be disabled as mentioned in #2896

**Anything else you would like to add:**

According to the discussion related to the mentioned PR (#2896), when KeepAlive is enabled, a deadlock issue occurs during session logout, causing the controller to hang. This issue also impacts our environment.

 capv-controller-manager args:  
```
  Containers:
   manager:
    Image:       registry.k8s.io/cluster-api-vsphere/cluster-api-vsphere-controller:v1.10.0
    Ports:       9443/TCP, 9440/TCP, 8443/TCP
    Host Ports:  0/TCP, 0/TCP, 0/TCP
    Args:
      --leader-elect
      --diagnostics-address=:8443
      --insecure-diagnostics=false
      --v=4
      --enable-keep-alive
      --feature-gates=NodeAntiAffinity=false
      --metrics-bind-addr=:8080
```
Logs: 
```
Flag --enable-keep-alive has been deprecated, This flag has been deprecated and will be removed in a future release. Note: This feature has been disabled per default because we determined that we already keep alive sessions just by our regular reconciles. So we don't need an additional keep alive handler. Enabling this feature may lead to a deadlock in controllers communicating with vCenter.
```

It seems like option is not removed from the template: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/fdf3d46ae1cb070c5f7196dd2edb21c76bb69302/config/manager/manager.yaml#L24

If it's needed I can create small PR with the fix.

**Environment:**

- Cluster-api-provider-vsphere version: v1.10.0
- Kubernetes version: (use `kubectl version`): v1.27.9
- OS (e.g. from `/etc/os-release`): 
```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by chrischdi** [comment]
That's a great catch, thanks for reporting this.
