### ISSUE TITLE
Use vSphere projects from Boskos

### ISSUE THREAD

**Issue by sbueringer** [kubernetes-sigs/cluster-api-provider-vsphere#3040]
This is an umbrella issue for the migration to use vSphere projects only from Boskos.

For more context, see: https://github.com/kubernetes/k8s.io/issues/6877

### Prerequisites

* [x] Setup Boskos in VMC
  * Done, configuration used can be seen here: https://github.com/sbueringer/k8s.io/pull/1

### Migration

* [x] CAPV
  * [x] PR to update test-infra to set BOSKOS_HOST: https://github.com/kubernetes/test-infra/pull/32727
  * [x] PR for main: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3034
  * [x] cherry-pick to all branches with CI
    * [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3053
    * [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3054
    * [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3055
    * [x] https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3056
* [x] CPI
  * [x] PR to update test-infra to set BOSKOS_HOST: https://github.com/kubernetes/test-infra/pull/32727
  * [x] PR for main: https://github.com/kubernetes/cloud-provider-vsphere/pull/1067
  * [x] cherry-pick to all branches with CI (delegated to CPI folks)
* [x] image-builder
  * [x] PR to update test-infra to set BOSKOS_HOST: https://github.com/kubernetes/test-infra/pull/32727
  * [x] PR for main: https://github.com/kubernetes-sigs/image-builder/pull/1487
  * [x] no release branches => no cherry-picks necessary

### Misc

* [x] Increase # of CAPV projects to 40 (verify state "initializing" works)

### Cleanup

* [x] Cleanup janitor: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3057
* [x] Remove IPAM controller and corresponding objects from CAPV services cluster in VMC
* [x] Remove old resource pools and folders in VMC (+ corresponding permissions) (also audit & cleanup the Google doc)
* [x] Cleanup secrets:
  * [x] Cleanup presets: https://github.com/kubernetes/test-infra/pull/32771
  * [x] Clean up ExternalSecrets: https://github.com/kubernetes/test-infra/pull/32688
    * ~capv-gcs-keyfile_json & vmc-capv-services_kubeconfig (TODO)~
  * [x] Cleanup the same in GCP secrets manager (check that they are unused)
    * Deleted `vmc-capv-services_kubeconfig` and `capv-gcs-keyfile_json`
* [x] Rollout janitor user:
  * [x] Secret PR for janitor creds: https://github.com/kubernetes/test-infra/pull/32688
  * [x] Update presets to point to janitor creds: https://github.com/kubernetes/test-infra/pull/32824
  * [x] Remove CAPV user from janitor group

**Comment by sbueringer** [comment]
cc @chrischdi @fabriziopandini

**Comment by chrischdi** [comment]
Finished the cleanup 🎉 

/close
