### ISSUE TITLE
clusterctl binary release

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/cluster-api-provider-vsphere#312]
As a cluster operator I want to install the `clusterctl` binary and deploy I shouldn't need to checkout out a git repo and build a binary

**Comment by codenrhoden** [comment]
With the 0.2.x series of CAPI, this has been taken care of.

`clusterctl` is available for Darwin and Linux on the CAPI releases page: https://github.com/kubernetes-sigs/cluster-api/releases

/close
