### ISSUE TITLE
Should kube-vip be a DaemonSet instead of a Pod at KubeadmControlPlane?

### ISSUE THREAD

**Issue by jisnardo** [kubernetes-sigs/cluster-api-provider-vsphere#3183]
/kind feature

We were discussing about why kube-vip is a Pod instead of a DaemonSet at templates.

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/download/v1.11.0/cluster-template.yaml

We prefere to setup as DaemonSet because it should be always up to provide api-server and ingress high availabilty.

https://kube-vip.io/docs/installation/daemonset/

**Environment:**

- Cluster-api-provider-vsphere version: v1.11.0
- Kubernetes version: (use `kubectl version`): v1.30
- OS (e.g. from `/etc/os-release`): Ubuntu 24.04 LTS

Greetings.

**Comment by chrischdi** [comment]
We use kube-vip as a control-plane load-balancer.

The load-balanced endpoint needs to get available during `kubeadm init` of the first control-plane node for the process to finish. At this point in time it is simply not possible to deploy a daemonset yet.

May I ask for your underlying use-case?

**Comment by jisnardo** [comment]
We use kube-vip as control-plane and ingress load-balancer but we do not have experienced any issue with the fisrt control-plane node.

Maybe because we tested with rke2 instead of kubeadm?

**Comment by chrischdi** [comment]
I don't know how rke2 deploys their control-plane load balancer.

Kube-vip in the existing templates for CAPV exists for load balancing the control plane endpoint. Having the ability for using it for services of type loadBalancer is more an side-effect.

**Comment by chrischdi** [comment]
AFAIK, for the control-plane load balancer in the setup we have in CI, using only a daemonset does not work. I'm happy to see how this works in your case :-) maybe we can improve something here.

**Comment by jisnardo** [comment]
Thanks @chrischdi.
