### ISSUE TITLE
Add data disks not present in VM template to VM during cloning

### ISSUE THREAD

**Issue by vr4manta** [kubernetes-sigs/cluster-api-provider-vsphere#3213]
/kind feature

**Describe the solution you'd like**
As a cluster admin, I would like to create machines with additional data disks so that I can have dedicated disks for such things as etcd, container runtime, image storage, swap, etc.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The idea here is to add new disks to a VM during the clone process that are not part of the vSphere VM Template.  This way we can share one template across multiple machine sets but tweak the additional data disks across each machine set based on the needs of that group.

Initial goal is to support the govmomi mode.

Currently most vSphere VM Templates have a single defined disk for the OS.  This feature should still check to see if any other disks are present in template and make sure new data disks are added.

There currently is a property `additionalDisksGiB` that will change the size of existing disks found in the vSphere VM Template, but is not related to adding disks not present in the template.  This may cause confusion.  Current proposal is to have a new field that will start simple and grow over time w/ additional capabilities.  One example would be to have new disks only use same controller (usually scsi controller) as the primary disk.

**Environment:**

- Cluster-api-provider-vsphere version: 1.11
- Kubernetes version: (use `kubectl version`): 1.30.3
- OS (e.g. from `/etc/os-release`):  Red Hat Enterprise Linux CoreOS 418

**Comment by chrischdi** [comment]
Note: one thing we should check at least once manually or in an e2e test: make sure that deletion does also delete the additional disk, so we don't leak data/vmdk's.

**Comment by chrischdi** [comment]
CC @lubronzhan , @neolit123 , this one might be interesting to you folks :-)

**Comment by neolit123** [comment]
i'm not aware of related FR but happy to help with review on any PRs.
@vr4manta is this something your will be working on/

**Comment by chrischdi** [comment]
It is WIP by @vr4manta at: 
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/3214

👍

**Comment by vr4manta** [comment]
> i'm not aware of related FR but happy to help with review on any PRs. @vr4manta is this something your will be working on?

Yes.  I'm working this one as a feature we are needing.  I've done a first pass at this and all is working so far.  I've fixed some tests to make sure the conversion works properly.  I've also verified that when the VM is deleted, the disks are also cleaned up.  Thanks!
