### ISSUE TITLE
CPI Daemonset image 401 Unauthorized (version v1.24.6)

### ISSUE THREAD

**Issue by avivlev98** [kubernetes-sigs/cluster-api-provider-vsphere#3216]
/kind bug

Following the vmware offical docs - https://docs.vmware.com/en/VMware-vSphere-Container-Storage-Plug-in/3.0/vmware-vsphere-csp-getting-started/GUID-0AB6E692-AA47-4B6A-8CEA-38B754E16567.html

After running the following lines :  

1. VERSION=1.24

2. wget https://raw.githubusercontent.com/kubernetes/cloud-provider-vsphere/release-$VERSION/releases/v$VERSION/vsphere-cloud-controller-manager.yaml

3. kubectl apply -f vsphere-cloud-controller-manager.yaml

I get the following error in pod describe:

"Failed to pull image "gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.24.6": rpc error: code = Unknown desc = failed to pull and unpack image "gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.24.6": failed to resolve reference "gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.24.6": failed to authorize: failed to fetch anonymous token: unexpected status: 401 Unauthorized"

As I noticed the image in higher kubernetes version for example(https://github.com/kubernetes/cloud-provider-vsphere/blob/master/releases/v1.31/vsphere-cloud-controller-manager.yaml) moved to:
registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere:v1.31.0

I tried to pull the same image tag from: registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere:v1.24.6 , but seems that the image is not exists

Can you please advice on this ? 

**Environment:**

- Kubernetes version: (use `kubectl version`): v1.24.17
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.4 LTS

**Comment by fabriziopandini** [comment]
For availability of images for old versions of the CPI you should ask in https://github.com/kubernetes/cloud-provider-vsphere

**Comment by chrischdi** [comment]
The oldest version provided at registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere is v1.28.0 .

The docker mirror at `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager` from the rancher folks also provides some older verisons.

Otherwise you may need to build and push the image on your own.

**Comment by avivlev98** [comment]
> For availability of images for old versions of the CPI you should ask in https://github.com/kubernetes/cloud-provider-vsphere



> The oldest version provided at `registry.k8s.io/cloud-pv-vsphere/cloud-provider-vsphere` is v1.28.0 .
> 
> The docker mirror at `rancher/mirrored-cloud-provider-vsphere-cpi-release-manager` from the rancher folks also provides some older verisons.
> 
> Otherwise you may need to build and push the image on your own.

Ok thanks you for the quick replay guys ,I will check upgrading my k8s to 1.28+ or  I will open kind/support in  https://github.com/kubernetes/cloud-provider-vsphere with the same error described So that they might upload the old images to the new registry .
