### ISSUE TITLE
Logging Conventions

### ISSUE THREAD

**Issue by moshloop** [kubernetes-sigs/cluster-api-provider-vsphere#329]
We need to standardize on how we use the different logging levels, these are conventions that I would propose:

## Logging

**Error (1)**
*Hard Errors that a user will likely need to fix*

Failed to connect, no hostname specified

**Warning (2)**
Soft Errors that a retry might fix

Failed to connect, connection refused

**Change (3)**
Machine created, updated

POST /api/v1/namespaces/default/events

PUT /apis/cluster.k8s.io/v1alpha1/namespaces/default/machines/capv-mgmt-example

**Info  (4)**
Finding machine=host1

GET /apis/cluster.k8s.io/v1alpha1/namespaces/default/machines

caches populated

**Trace Header (5)**
Found machine=host1 id=123

**Trace Detail (6)**
Machine JSON, Request,Response Body

I think we should also perhaps consider introducing Error and Warning so that they can be colored on interactive consoles - it is really hard to scan a wall of colorless text.

https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

**Comment by moshloop** [comment]
@akutz @andrewsykim @figo @ @frapposelli @sflxn @sidharthsurana

**Comment by akutz** [comment]
Hi @moshloop,

First of all, thank you for doing this!

We're using the standard K8s logging facility. Also, trace is level 8 I believe. Can you please update #328's description with the template and link to this issue? 

Please use the template where possible. Thanks.

Also, the link you provided would move CAPV to being **far** more verbose. Please rephrase this proposal to be in sync with the linked, community standards, and give examples of each change based on the current code (where applicable).

**Comment by akutz** [comment]
Hi @moshloop,

Is there anything you need to move forward on this?
