### ISSUE TITLE
Clusterctl built through clusterctl-in-docker isn't cross-compiled

### ISSUE THREAD

**Issue by mylesagray** [kubernetes-sigs/cluster-api-provider-vsphere#338]
/kind bug

`clusterctl` needs to be compiled to run on whatever hostOS is running the `clusterctl-in-docker` container.

**What steps did you take and what happened:**
On macOS:
* Clone repo and run `make clusterctl-in-docker`
* Try to execute `/bin/clusterctl`

**What did you expect to happen:**
`clusterctl` runs

**Anything else you would like to add:**
`clusterctl` from make command:

```sh
file bin/clusterctl 
bin/clusterctl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, not stripped
> bin/clusterctl    
zsh: exec format error: bin/clusterctl
```

`clusterctl` compiled using `go build && go install`:
```sh
> file $GOPATH/bin/clusterctl 
/Users/mylesgray/Documents/Programming/Go/bin/clusterctl: Mach-O 64-bit executable x86_64
> clusterctl          
Simple kubernetes cluster management
```
**Environment:**
 macOS 10.14

- Cluster-api-provider-vsphere version:  master/ToT

**Comment by akutz** [comment]
FWIW, `GOHOSTOS=$(go env GOHOSTOS) make clusterctl-in-docker` should work.

**Comment by mylesagray** [comment]
FYI - didn't work with the above, had to run `GOOS=$(go env GOOS) make clusterctl-in-docker`.

**Comment by akutz** [comment]
Fixed

/close
