### ISSUE TITLE
Create missing resource pools/folders

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#341]
/kind feature

**Describe the solution you'd like**
PR #339 removed the capability for CAPV to resource pools or folders that were present in the machine spec but missing on the target vSphere platform. This was removed on purpose because any of the resource pools or folders created were not tracked, and therefore could not be safely removed upon a machine/cluster being deleted.

This issue tracks the reintroduction of creating missing resource pools/folders, but with the caveat that any such item created as part of `Reconcile`, `Create`, or `Update` should be removed upon `Delete` when said item contains no more children.

**Anything else you would like to add:** NA

**Environment:** NA

**Comment by mylesagray** [comment]
+1 - would very much like to see this reintroduced, rather than having to pre-create each item.

**Comment by Jellyfrog** [comment]
We'd also like to see automatic folder creation

**Comment by hexchen** [comment]
This feature would be very useful to organise multiple clusters in VSphere without requiring manual intervention to create folders.

/remove-lifecycle rotten

**Comment by chrischdi** [comment]
/reopen

to see if someone has time to assign and work on this.

This would first require a proposal to agree upon because we don't want to delete resource pools or folders if we cannot be sure that we also created them and they are empty.
