### ISSUE TITLE
OVF Spec on CAPV images fail to deploy when using Distributed Switches

### ISSUE THREAD

**Issue by mylesagray** [kubernetes-sigs/cluster-api-provider-vsphere#346]
/kind bug

**What steps did you take and what happened:**
Download one of the CAPV images:
```sh
wget https://storage.googleapis.com/capv-images/release/v1.14.3/ubuntu-1804-kube-v1.14.3.ova
```

Set up govc env vars:
```sh
export GOVC_INSECURE=1
export GOVC_URL="vc-here"
export GOVC_USERNAME=administrator@vsphere.local
export GOVC_PASSWORD="pw-here"
export GOVC_DATASTORE=vsanDatastore
export GOVC_NETWORK="Cluster01-LAN-1-Routable"
export GOVC_RESOURCE_POOL='cluster01/Resources'
export GOVC_DATACENTER=DC01
```

Attempt to import the OVA:
```sh
$ govc import.ova ~/Downloads/ubuntu-1804-kube-v1.14.3.ova
govc: Host did not have any virtual network defined.
```

When exporting the ova spec and overriding the network in JSON and deploying with that, it works:

```sh
govc import.spec ~/Downloads/ubuntu-1804-kube-v1.14.3.ova | python -m json.tool > ~/Downloads/ubuntu.json
```

ubuntu.json:
```json
{
    "DiskProvisioning": "thin",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "NetworkMapping": [
        {
            "Name": "nic0",
            "Network": "Cluster01-LAN-1-Routable"
        }
    ],
    "Annotation": "Ubuntu 18.04 + Kubernetes",
    "MarkAsTemplate": false,
    "PowerOn": false,
    "InjectOvfEnv": false,
    "WaitForIP": false,
    "Name": null
}
```

Deploy ova:
```sh
$ govc import.ova -options ~/Downloads/ubuntu.json ~/Downloads/ubuntu-1804-kube-v1.14.3.ova
[25-06-19 10:00:12] Uploading ubuntu-1804.ova.vmdk... (55%, 2.1MiB/s)
```

**What did you expect to happen:**
OVA should be deployed with the network set as env var `$GOVC_NETWORK`.

**Anything else you would like to add:**
This environment has zero vSphere Standard Switches - it only uses vSphere Distributed Switches and NSX-T Distributed Switches, it would appear the error message `Host did not have any virtual network defined.` is propagated from vSphere and is common in environments with no VSS or Port Group named `VM Network` - this seems hacky.

We should work around this limitation and allow users to deploy to vDS or any Port Group, regardless - when populating the `ubuntu.json` as above with the vDS/N-VDS Port Group deployment works as expected.

**Environment:**

- Cluster-api-provider-vsphere version: N/A
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`):  macOS 10.14

**Comment by akutz** [comment]
Hi @mylesagray,

Can you explain how to fix this? FWIW, I'm literally building the OVA from an OVF template I always use, which was originally generated off of VMC. You can see how it works [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/hack/image-build-ova.py). Thanks!

**Comment by mylesagray** [comment]
Yeah, seems this was a me problem after all @akutz:

```sh
govc import.ova ~/Downloads/ubuntu-18.04-server-cloudimg-amd64.ova                           
govc: Host did not have any virtual network defined.
```

You absolutely have to define `Network` and pass it in via `-options ubuntu.json` or similar, just exposing the env var `export GOVC_NETWORK="Cluster01-LAN-1-Routable"` doesn't make `import.ova` use that network for OVA deployment. 

Maybe a FR to raise against `govc`.
