### ISSUE TITLE
CAPV image template changes

### ISSUE THREAD

**Issue by mylesagray** [kubernetes-sigs/cluster-api-provider-vsphere#347]
/kind feature

**Describe the solution you'd like**
CAPV images when deployed without any customisation (probably the standard) are all deployed with the same name, that is non-specific and requires quotes because of special characters.

I would propose that the VM name matches the OVA name when deployed.

Additionally, the annotation that is added could be a little more verbose (documented below)

The images are also deployed as VMs and not templates, when the ultimate goal is to have them as template - adding another step to the deployment that can be worked around easily, also documented below.

**Anything else you would like to add:**
Current OVA options json (for 18.04, 1.14.3 image):
```json
{
    "DiskProvisioning": "thin",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "NetworkMapping": [
        {
            "Name": "nic0",
            "Network": ""
        }
    ],
    "Annotation": "Ubuntu 18.04 + Kubernetes",
    "MarkAsTemplate": false,
    "PowerOn": false,
    "InjectOvfEnv": false,
    "WaitForIP": false,
    "Name": null
}
```

Proposed OVA options json (for 18.04, 1.14.3 image):
```json
{
    "DiskProvisioning": "thin",
    "IPAllocationPolicy": "dhcpPolicy",
    "IPProtocol": "IPv4",
    "NetworkMapping": [
        {
            "Name": "nic0",
            "Network": ""
        }
    ],
    "Annotation": "Cluster API vSphere image - Ubuntu 18.04 and Kubernetes - https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/machine_images.md",
    "MarkAsTemplate": true,
    "PowerOn": false,
    "InjectOvfEnv": false,
    "WaitForIP": false,
    "Name": "ubuntu-18.04-kube-1.14.3"
}

```

**Comment by akutz** [comment]
Hi @mylesagray,

Where were you when I was writing this stuff, huh? Huh? HUH?! :) Thanks for the info. I'll work on this ASAP!

**Comment by akutz** [comment]
Hi @mylesagray,

Aren't these the options when importing the OVA with something like `govc`? I think `govc` reads this file and acts on the options. I'm not sure how to actually build these into the actual OVF.

**Comment by dougm** [comment]
The govc specific options are `MarkAsTemplate`, `PowerOn` and `WaitForIp`.  Currently not possible to set using the .ovf.  I suppose we could have govc look for a specific Property ovf:key to support this, not sure what other options there might be.

**Comment by akutz** [comment]
FWIW, I do intend to add a feature that automatically imports the OVA into the content lib and deploys it as a template If the template is missing.

**Comment by mylesagray** [comment]
Okay, well in the vein of your plans @akutz and what we chatted about on zoom, simple changes to Annotation and Name on deploy would close this one off for me :)
