### ISSUE TITLE
Add vcsim tests for the machine actuator's create workflow

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#35]
We can use vc sim (simulator) to run unit tests for the machine actuator.  We need unit tests for the existing machine actuator.  There may be some problems running Terraform against vc sim.  We need to identify those issues and raise them in the vcsim repo.

**Comment by dougm** [comment]
@zpratt thanks, I'll have a PR for that issue soon.

**Comment by sflxn** [comment]
I'm revising this issue to focus only on the create workflow.  The issue was too broad.  It was more like an epic.  I will open up new issues for further work around vcsim.
