### ISSUE TITLE
E2E test continues even if "make test" fails

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/cluster-api-provider-vsphere#353]
/kind bug

**What steps did you take and what happened:**
I noticed on one of my PRs with a flaky test that the e2e test continues on, even after `make test` has failed. here is an example log: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/352/pull-cluster-api-provider-vsphere-e2e/1143588252314243072

Even after the test failure, it continues to build and push images, and run E2E, which takes a long amount of item. 

**What did you expect to happen:**
This should fail immediately after the make test fails.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by codenrhoden** [comment]
This might warrant a separate issue, but in [this](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api-provider-vsphere/388/pull-cluster-api-provider-vsphere-e2e/1144662693072867328), the E2E test reported success when it actually failed.

**Comment by akutz** [comment]
Given that the PR executes the test job separately, even if it fails here because etcd is missing, I think that’s okay.

Ideally we don’t execute the test target in the e2e job at all.
