### ISSUE TITLE
QoL: Have addons.yaml set up a StorageClass for the defined Datastore

### ISSUE THREAD

**Issue by mylesagray** [kubernetes-sigs/cluster-api-provider-vsphere#360]
/kind feature

**Describe the solution you'd like**
`addons.yaml` has a StorageClass at the very top called `standard` - this currently has no `datastore` value or `storagePolicyName` value applied, meaning it's useless to the VCP.

I would propose that we populate this using the `storagePolicyName` method:

Add an ENV VAR for `VSPHERE_STORAGE_POLICY` that would define the SPBM policy that the VMs and the volumes for the `standard` StorageClass are provisioned with. This is compatible with vSAN, VMFS and NFS datastores (as long as VMFS and NFS are using tag-based SPBM policies).

An example vSAN SC:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
    storagePolicyName: "vSAN Default Storage Policy"
    datastore: vsanDatastore
```

An example VMFS/NFS SC:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/vsphere-volume
parameters:
    storagePolicyName: "Tag-Based-Storage"
```

**Comment by mylesagray** [comment]
It appears that `addons.yaml` now does this - however, it creates a SC that is VCP specific, even when deploying the CSI plugin - SC created is as such:

```sh
$ kubectl get sc -o yaml
apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"standard"},"parameters":{"datastore":""},"provisioner":"kubernetes.io/vsphere-volume"}
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2019-10-07T15:49:45Z"
    name: standard
    resourceVersion: "1531"
    selfLink: /apis/storage.k8s.io/v1/storageclasses/standard
    uid: dcecb8e9-e6c4-4f05-8036-0c8b57beb961
  parameters:
    datastore: ""
  provisioner: kubernetes.io/vsphere-volume
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

The `provisioner` needs to change from VCP to CSI, a valid CSI SC would look like this:

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "vSAN Default Storage Policy"
```

Storage Policy Name would ideally be added as a env var export before creating the YAML files, `provisioner` should change based on whether the `-u` flag is set on the container or not.

**Comment by akutz** [comment]
Hi @mylesagray,

Did you remove the stale marker due to something related to the CNI work in the upcoming v0.5.2 release?

cc @andrewsykim

**Comment by andrewsykim** [comment]
I assumed that the StorageClass should be applied on a per-cluster basis in the same way we do for CNI and others. With that said though, I wouldn't be opposed to deploying a default storage class for convenience. @mylesagray we can probably get the `datastoreurl` in there but is the storage policy name mandatory?

**Comment by mylesagray** [comment]
@andrewsykim Yeah, SPBM name is mandatory in CSI - and highly recommended in VCP, to simplify deployment we should assume SPBM name will be used for both - so it'd need to be a setup Env var too.

**Comment by andrewsykim** [comment]
One alternative we can do here is remove `StorageClass` entirely from `addons.yaml`, that way it's clear to users they need to create a StorageClass themselves. I'm not sure if it's making things better or worse though, thoughts @mylesagray @akutz?

**Comment by voor** [comment]
As someone coming into this space, the new CSI stuff is pretty overwhelming at first.  You listed several acronyms I have no clue about -- SPBM and VCP for example.  Those are largely irrelevant to the Cluster API, since you're storing everything as CRDs in etcd.  So I would +1 removing it from the addons.yaml entirely.

**Comment by mylesagray** [comment]
@andrewsykim - maybe removing it simplifies things, and doesn’t make the assumption to know about the underlying VC SPBM names.

SGTM if @akutz is okay with it

**Comment by akutz** [comment]
I agree. I've been thinking about this, and I think with CNS in play we should start to consider a separate add-ons file for the initial management cluster and future, worker clusters. The initial management cluster doesn't need or require CNS, and should be as brain-dead and simple as possible IMO.
