### ISSUE TITLE
Support taking a `Machine` temporarily offline

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#369]
/kind feature

**Describe the solution you'd like**
In vsphere env, there are cases when an admin might want to power off some VMs in order to do routine software/hardware maintenance . The current behavior for CAPV actuator is to power ON the VM if it is not already powered on. This means even if the admin intentionally powered OFF a VM it would automatically be powered on by the actuator.
This we need a way for the user to express their intent on the `Machine` object so that the controller would not automatically change the state of the VM for the time being. 

I suggest we could define a special annotation for the `Machine` object that could express that intent.
e.g. `capv.sigs.k8s.io/offline` 
The intent would be for the actuator to sort of skip reconciling the `Machine` object temporarily.

**Comment by akutz** [comment]
Thank you @sidharthsurana, I agree, this is definitely a worthwhile feature, and should be pretty easy to implement.
