### ISSUE TITLE
make prod-yaml doesn't honour CLUSTER_NAME for mgmt cluster

### ISSUE THREAD

**Issue by mylesagray** [kubernetes-sigs/cluster-api-provider-vsphere#377]
/kind bug

**What steps did you take and what happened:**
Export env vars for mgmt cluster:

```sh
# K8s attributes
export CLUSTER_NAME=capv-mgmt-cluster
export KUBERNETES_VERSION=1.15.0

# vSphere attributes
export VSPHERE_USER=administrator@vsphere.local
export VSPHERE_PASSWORD=P@ssw0rd
export VSPHERE_SERVER=vc01.satm.eng.vmware.com

# VM deployment options
export VSPHERE_DATACENTER=DC01
export VSPHERE_DATASTORE=vsanDatastore
export VSPHERE_NETWORK="Cluster01-LAN-1-Routable"
export VSPHERE_RESOURCE_POOL="cluster01/Resources/CAPV"
export VSPHERE_FOLDER="/$(echo $VSPHERE_DATACENTER)/vm/Testing/K8s/$(echo $CLUSTER_NAME)"
export VSPHERE_TEMPLATE="ubuntu-18.04-kube-1.15.0"
export VSPHERE_DISK_GIB=60
export VSPHERE_NUM_CPUS="2"
export VSPHERE_MEM_MIB="2048"
```

Note `CLUSTER_NAME` is set to `capv-mgmt-cluster`.

Execute `make prod-yaml`

```sh
make prod-yaml
CAPV_MANAGER_IMAGE=gcr.io/cnx-cluster-api/vsphere-cluster-api-provider:0.3.0-beta.0 hack/generate-yaml.sh
done generating ./out/capv-mgmt-example/addons.yaml
done generating ./config/default/capv_manager_image_patch.yaml
done generating ./out/capv-mgmt-example/cluster.yaml
done generating ./out/capv-mgmt-example/machines.yaml
done generating ./out/capv-mgmt-example/machineset.yaml
Done generating ./out/capv-mgmt-example/provider-components.yaml

*** Finished creating initial example yamls in ./out/capv-mgmt-example

    The files ./out/capv-mgmt-example/cluster.yaml and ./out/capv-mgmt-example/machines.yaml need to be updated
    with information about the desired Kubernetes cluster and vSphere environment
    on which the Kubernetes cluster will be created.

Enjoy!
```

`CLUSTER_NAME` overridden by default in `generate-yaml.sh`:

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/9da65b679baf8f2b4fb57d75391be89af96f7c5e/hack/generate-yaml.sh#L29

**What did you expect to happen:**

Mgmt cluster should be created with exported `CLUSTER_NAME` and fallback to default if not defined.

**Environment:**

- Cluster-api-provider-vsphere version: 0.3.0-beta.0
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): macOS

**Comment by akutz** [comment]
We need to update docs. Users should not use the make yaml targets anymore, but the script directly

**Comment by andrewsykim** [comment]
Open a fixed here https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/378, agree with using script, though prefer post v0.3.0 since a lot of docs will need updating if we remove those targets

**Comment by codenrhoden** [comment]
I can open an issue to to cover the docs and changes to not use `make prod-yaml`. I didn't open it last night, but mentioned in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/352#issuecomment-506042576 that that was on my plate. It's something I'd like to take on as part of a bigger refresh in this whole area. =)
