### ISSUE TITLE
Design and implement a central store to track clusters created by the cluster api

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#39]
For enterprise use case, we want some central source of truth for information about clusters created with the cluster api.

1. Identity of the clusters created via vSphere console
2. Identity of the clusters created via clusterctl
3. Retrieval of the kubeconfig for the cluster

**Background:**
---
Today, the Terraform provisioner keeps information about the cluster in various places, including config maps within kubernetes and the terraform state file.  The cluster api has two mode of operations, pivot and non-pivot.  In the pivot mode, a bootstrap cluster is created, that will then be used to deploy the target cluster.  Afterwards, the bootstrap cluster is deleted, leaving information about the cluster in the target cluster itself.  If multiple users create clusters using clusterctl, there is no central way to identify all the clusters created on the vCenter.

**Options:**
---
1. Use vSphere tags to identify clusters, masters, machines
- Machine actuator can retrieve IP for the masters and pull kubeconfig from the api server of specific cluster.
2. Assume a bootstrap cluster always exist (a deployed OVA with the cluster) and keep all information in kubernetes objects in that cluster.
3. A combination of 1 and 2.  Use tags so vSphere console can quickly identify clusters.  Use the bootstrap cluster's kubernetes objects for all other information.
4. Implement a vSphere extension.  This option may not be viable as it might get deprecated.

**Comment by moshloop** [comment]
+1 for Option 3.

**Comment by akutz** [comment]
I'm not sure this is still relevant. Is the non-pivot method still valid? If so, then there is no sense of a management cluster anyway. It seems to me the answer is "If you want to keep track of clusters created by CAPV then make sure you pivot to a persistent management cluster." Otherwise everything is a one-off.

To me the source of truth is the management cluster. Beyond that, it's not a priority at the moment. That's me though. Others? @frapposelli?

**Comment by frapposelli** [comment]
As we're aligning with CAPA, the non-pivot use case, while being valid, is deprioritized at the moment.

**Comment by frapposelli** [comment]
also, this issue is particularly old and references the terraform provisioner which is long gone, we should probably close this issue altogether.

**Comment by akutz** [comment]
> also, this issue is particularly old and references the terraform provisioner which is long gone, we should probably close this issue altogether.

While true it was based on TF, the notion of a master registry of clusters isn't TF dependent.

Still, I stand by my assertion that if you want a registry, then pivot to the management cluster. Otherwise there is no registry.

**Comment by akutz** [comment]
I'm time boxing this and will close it based on the above discussion unless no one objects by next Friday.
