### ISSUE TITLE
ESXi support

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#400]
This issue is to track the discussion on whether or not CAPV should include support for deploying Kubernetes clusters directly on ESXi. PR #321 reintroduces support ESXi as it was previous part of CAPV for a short period prior to the 0.3.0 release.

| Concern | Risk |
|---------|------|
| Branching code paths | low |
| CI testing | high |
| Support costs | dependent on the previous two |

## Branching code paths
ESXi support, for the most part, should be able to use most of the CAPV codebase as it is currently designed. PR #321 isolates most of the ESXi-requirements into a single package. This is a low risk concern.

## CI testing
The primary concern is around CI. There is currently no plan in place for testing ESXi as part of the CAPV CI workflow. Any changes to ESXi code would need to be tested manually. This places a high burden on the PR author and requires a high-level of trust between the PR author and project maintainers. This is a high-risk concern.

## Support costs
The risk associated with support for ESXi depends directly on the previous two concerns. As long as branching code paths are kept to a minimum and there is CI testing that includes ESXi, the support costs for ESXi should be low to moderate.

This issue will be raised during a community meeting to solicit the opinions of community members regarding the future of ESXi support in CAPV.

**Comment by akutz** [comment]
* Testing is easier with ESXi (@moshloop)
    * This doesn't necessarily provide the same coverage as the vCenter pipeline and by definition cannot cover all of the same features available to vCenter
    * @moshloop is prepared to own this feature
* Perhaps add it back but not for public/supported consumption, but rather for use by developers
    * Gate adding to list of supported platforms until CI is available for ESXi
* Does this create a higher barrier to entry for developers new to the project?

**Comment by dougm** [comment]
The developer/resource issue that @moshloop described on the community call today isn't unique to CAPV.  Which has me wondering, what if we moved this to vcsim where in a nutshell:

* vcsim supports connecting a real ESXi host (some form of proxy)

* vcsim supports `CloneVM` in this mode using the logic/code that's currently in CAPV

There is some vCenter specific functionality already supported by vcsim that could apply to this mode (real ESXi connection), such as inventory folders, tagging, etc.  Ideally CAPV would only have to be concerned with vCenter and vcsim could support the developer/resource use cases.  Thoughts?

**Comment by akutz** [comment]
I don't want to discount the use of the Gmock library already used by CAPA to provide a lot of unit testing. It can help add coverage where it's not strictly necessary to have a true backend.

**Comment by moshloop** [comment]
I think @dougm's  idea for vcsim is brilliant 

Maybe we add ESXi back in temporarily with the goal of replacing it with vcsim once it is made available ?

**Comment by dougm** [comment]
Yes, adding back ESXi support for the short-term and possibly we can replace that functionality with the vcsim idea later on.

**Comment by mylesagray** [comment]
This is likely going to be an unpopular opinion, but I don't think we can focus on ESXi support here as CAPV matures more and more things will draw gaps between ESXi and VC that simply cannot be implemented, for example using Content Library for deployment of these images is one enhancement for longer term that cannot be added without vCenter.

Additionally the complexity involved in attempting to replicate CAPV functionality on ESXi when the simple solution is to run a vCenter with a limited number of resources assigned (or as Doug says, maybe an enhancement to vcsim) is massive from a testing, feature interop, supportability and testing point of view.

I would very heavily suggest that vcsim supporting ESXi being the primary method for this, followed by just installing a low-resource vCenter instance with your single host in it - rather than unnecessarily bloating and adding complexity to the CAPV project, in production people won't be running CAPV without vCenter and in development I don't think we should be either.

My 2c.

**Comment by sidharthsurana** [comment]
+1 to @mylesagray comment above. I share the exact same sentiment.

**Comment by moshloop** [comment]
@mylesagray If there an easily deployable OVA of a low resource (< 4GB RAM) vCenter to go along with @lamw's Nested ESXi appliance ?

@dougm could you comment on the potential timeline for vcsim support for ESXi ?

If either of the above solutions would be available/ready in a matter of weeks, then yes I would support dropping ESXi, if they are more medium-term goals then we should enable ESXi in the short-term.

ESXi is not something that needs to be focused on, when new CAPV features are implemented that don't support ESXi out of the box, then they can return unsupported errors. 

Automatic deployment of images to the content library should be opt-in, especially as many people will want to create their own images. Even if it were a required step it could just no-op for ESXi.

**Comment by lamw** [comment]
@moshloop Regarding the VCSA resources, there's definitely no VCSA that can be deployed <4GB today :( In fact, the VCSA has gotten larger over the years and today, the default "Tiny" is 10GB of memory. You can tune it down by a few GB, but you'll most likely run into issues with anything less than 6-8 (not tried 6 in latest version).

I think VCSIM + my Nested ESXi image could work out depending on what behaviors you need to simulate/mimic/test ... 

In general, we should be standing up the required infrastructure matching the customer configuration, this way we don't get any surprises as part of development/testing.

**Comment by dougm** [comment]
@moshloop I have a few other items to wrap up first (including some PTO), but could shoot for a prototype in the next few weeks.  I started to experiment this weekend and need to think about which direction to take, trying to keep it as simple as possible.  I'll share more info when I can.

**Comment by frapposelli** [comment]
Let's freeze this issue for about a month and see what progress can be made in supporting this use case with `vcsim`.

**Comment by srm09** [comment]
Seems like this one has gotten no traction for a long time. Closing this one for now, feel free to reopen in case of any new asks.
/label triage/unresolved
