### ISSUE TITLE
Getting started needs how to delete workload cluster

### ISSUE THREAD

**Issue by yktsubo** [kubernetes-sigs/cluster-api-provider-vsphere#402]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

The getting started has how to deploy workload cluster but doesn't have how to delete it.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

When deleting clusters, there seems to be manner in order.
When I deleted cluster resource first, the VMs were not cleaned up.
I guess, we need to delete control machine and worker machineset before cluster resource.

**Environment:**

- Cluster-api-provider-vsphere version: v0.3.0
- Kubernetes version: (use `kubectl version`): 
```
kubectl --kubeconfig ../yktsubo-1/kubeconfig version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:26:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.6", GitCommit:"abdda3f9fefa29172298a2e42f5102e777a8ec25", GitTreeState:"clean", BuildDate:"2019-05-08T13:46:28Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): ubuntu-1804-kube-v1.13.6 is used for management cluster and workload clusters.

**Comment by mylesagray** [comment]
In my testing if you want to destroy everything, delete the management cluster and it will cascade delete all the workload clusters, like so:

```sh
clusterctl delete cluster --bootstrap-type kind --kubeconfig capv-mgmt-example/kubeconfig -p capv-mgmt-example/provider-components.yaml
```

**Comment by yktsubo** [comment]
Thanks for comment. Actually my intention is to delete cluster created by management cluster individually.  According to getting started, kubectl is used to create workload cluster. So I assumed kubectl is also used to delete workload clusters.
Now I wonder whether to use clusterctl command to create and delete workload cluster.

**Comment by mylesagray** [comment]
Sorry for the confusion, `kubectl` indeed should be used to delete workload clusters individually - @andrewsykim may have more details on this though.

**Comment by andrewsykim** [comment]
That is correct, deleting workload clusters should involve running `kubectl delete -f` on the same manifest files you applied to create the cluster. I will follow-up with doc updates shortly. Thanks @yktsubo
