### ISSUE TITLE
Externally delete VM won't automatically heal

### ISSUE THREAD

**Issue by shawnho1018** [kubernetes-sigs/cluster-api-provider-vsphere#409]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If I use kubectl delete machine to delete a VM, clusterapi will automatically grow one back. However, if I manually delete one VM from vCenter, clusterapi won't remedy the cluster. 

**What did you expect to happen:**
clusterapi should resurrect the node. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 0.3.0 
- Kubernetes version: (use `kubectl version`): 1.13.6 
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by akutz** [comment]
Kubernetes is the author of state, not the backend platform. If you remove a machine in the backend, it *will* be reconciled eventually, but not for several cycles.

**Comment by shawnho1018** [comment]
Hi,
I actually waited for 7 hours (from 11:00AM this morning until 5:00PM this afternoon) and the deleted machine was not reconciled. I then use kubectl delete machine [machine-name] to reproduce the machine. 
If I understand correctly, the cycle you meant is 10 minutes, monitored by the pod in management cluster, right? I

I happened to have today's log:

Time zone is in UTC+0.
```
I0704 03:22:24.522938       1 cluster_controller.go:90] Running reconcile Cluster for "workload"
I0704 03:22:24.522960       1 cluster_controller.go:139] reconciling cluster object workload triggers idempotent reconcile.
I0704 03:22:25.204331       1 machine_controller.go:113] Reconciling Machine "workload-machineset-1-fvttk"
I0704 03:22:25.209430       1 machine_controller.go:207] Reconciling machine "workload-machineset-1-fvttk" triggers idempotent update
E0704 03:22:25.222108       1 machine_controller.go:214] Error updating machine "default/workload-machineset-1-fvttk": vm should already exist for "default/workload/workload-machineset-1-fvttk"
I0704 03:22:26.222336       1 machine_controller.go:113] Reconciling Machine "workload-machineset-1-fvttk"
I0704 03:22:26.226820       1 machine_controller.go:207] Reconciling machine "workload-machineset-1-fvttk" triggers idempotent update
E0704 03:22:26.239252       1 machine_controller.go:214] Error updating machine "default/workload-machineset-1-fvttk": vm should already exist for "default/workload/workload-machineset-1-fvttk"
I0704 03:22:27.239457       1 machine_controller.go:113] Reconciling Machine "workload-machineset-1-fvttk"
I0704 03:22:27.243738       1 machine_controller.go:207] Reconciling machine "workload-machineset-1-fvttk" triggers idempotent update
E0704 03:22:27.297287       1 machine_controller.go:214] Error updating machine "default/workload-machineset-1-fvttk": vm should already exist for "default/workload/workload-machineset-1-fvttk"
I0704 03:22:28.297460       1 machine_controller.go:113] Reconciling Machine "workload-machineset-1-fvttk"
I0704 03:22:28.301529       1 machine_controller.go:207] Reconciling machine "workload-machineset-1-fvttk" triggers idempotent update
~~~ Skipped middle log
I0704 10:22:22.899436       1 machine_controller.go:113] Reconciling Machine "workload-machineset-1-dlrzh"
I0704 10:22:22.903542       1 machine_controller.go:207] Reconciling machine "workload-machineset-1-dlrzh" triggers idempotent update
I0704 10:22:22.995807       1 machine_controller.go:113] Reconciling Machine "workload-machineset-1-fvttk"
I0704 10:22:23.002403       1 machine_controller.go:207] Reconciling machine "workload-machineset-1-fvttk" triggers idempotent update
E0704 10:22:23.017727       1 machine_controller.go:214] Error updating machine "default/workload-machineset-1-fvttk": vm should already exist for "default/workload/workload-machineset-1-fvttk"
I0704 10:22:24.017991       1 machine_controller.go:113] Reconciling Machine "workload-machineset-1-5x4vx"
I0704 10:22:24.085478       1 machine_controller.go:207] Reconciling machine "workload-machineset-1-5x4vx" triggers idempotent update
I0704 10:22:24.926218       1 cluster_controller.go:90] Running reconcile Cluster for "workload"
I0704 10:22:24.926241       1 cluster_controller.go:139] reconciling cluster object workload triggers idempotent reconcile.
I0704 10:30:07.999704       1 machine_controller.go:113] Reconciling Machine "workload-machineset-1-fvttk"
I0704 10:30:08.098786       1 machine_controller.go:207] Reconciling machine "workload-machineset-1-fvttk" triggers idempotent update
E0704 10:30:08.109360       1 machine_controller.go:214] Error updating machine "default/workload-machineset-1-fvttk": vm should already exist for "default/workload/workload-machineset-1-fvttk"

```

**Comment by akutz** [comment]
Hi @shawnho1018,

Thank you for these logs. There is indeed a bug here. What's happening is that the machine object in Kubernetes has the `MachineRef` set and no `TaskRef` exists for this machine, and so that asserts that the VM must exist.

What **should** happen instead is iff:

* the `MachineRef` is set
* there's no `TaskRef`
* and the VM can't be found

The `MachineRef` should be removed, causing the following reconciliation to indicate the machine does not exist, and therefore causing the `Create` workflow to occur.

Thank you for providing these logs and exposing this bug!

**Comment by akutz** [comment]
Hi @shawnho1018,

I don't suppose you have time to test the fix? If you don't, or are not sure how to test it (building a new image, etc.), then don't worry about it :)

**Comment by shawnho1018** [comment]
Dear Andrew,
Actually, I hope to learn how to fix it and then test it. I pull your modification and will try to use the current tool for a quick testing.


Sincerely,
--
Tzunghsien (Shawn) Ho

Solution Architect @ VMware
+886-920-201-322
hos@vmware.com<mailto:hos@vmware.com>
[signature_1634399214]
