### ISSUE TITLE
generate ssh key pair for VM if user does not set sshAuthorizedKeys

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/cluster-api-provider-vsphere#413]
/kind feature

**Describe the solution you'd like**
generate ssh key pair of VM if user does not set sshAuthorizedKeys, so that user can SSH to vm for debugging

**Anything else you would like to add:**
N/A

cc @akutz

**Comment by moshloop** [comment]
Why doesn't sshAuthorizedKeys solve this use case?

**Comment by frapposelli** [comment]
ref: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/416#issuecomment-511559445
