### ISSUE TITLE
Please allow for custom requeue values

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#417]
/kind feature

**Describe the solution you'd like**
Currently requeues are issued with a `20s` duration. This value should be modifiable for more rapid dev and test, but also due to varying speeds of back-end implementations.

PR #392 suggested reducing the default requeue time to `3s`:

* Three seconds is much too short based on testing [I've seen on VMC](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/392#issuecomment-507079368), and to that point
* Requeue times are very contextual and operation-specific, which is why when
* I mentioned a requeue time could be modifiable via a provider config, and there were concerns that requeue times in provider spec YAML may be too heavy-handed, I was surprised at the [suggested approach](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/392#issuecomment-507134969) of modifying the default requeue time via a CLI flag. A CLI flag for setting the default requeue time certainly must illicit the same wariness over global defaults.

I disagree that specifying a requeue time in the provider specs is objectively [a bad idea](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/392#issuecomment-507753984). The inability to parse the YAML is not something that is fixed by requeuing, so placing a value there is fine. It can be parsed, or it can't. A requeue won't fix that. And since provider specs have 1-to-1 relationships with objects, a provider spec seems like a fine location to define requeue values for specific objects.

That said, I **do** agree that ultimately requeue times should not be part of a provider's config -- it's too global. So too is a CLI arg. That's why:

* #418 allows the modification of the **sync period** -- the interval at which cluster-api objects are regularly synchronized outside of requeues. 
* This issue is to track the broader discussion that is required regarding requeues. The values probably need to be specific not just to operation *types*, but also instances of specific operations in a given workflow.

One possible solution is to define default requeue times for the various CRUD operations as part of the provider specs. Here's a super quick, not well-considered or thought-out example of what that might look like:

```golang
type VsphereClusterProviderSpec struct {
	//
	// All the other fields
	//

	DefaultRequeueOnReconcile time.Duration
	// A cluster's Delete method is not requeueable.
}

type VsphereMachineProviderSpec struct {
	//
	// All the other fields
	//

	DefaultRequeueOnCreate time.Duration
	DefaultRequeueOnUpdate time.Duration
	DefaultRequeueOnDelete time.Duration
}
```

**Anything else you would like to add:**
This is related to #392 and #418.

**Comment by moshloop** [comment]
/nit - I don't know if this perhaps adds too many configuration options

I am happy as long as we have a way to configure the requeue to reduce the feedback loop time.
