### ISSUE TITLE
Activity diagrams for central workflows

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#427]
/kind feature

# Activity diagrams

This issue tracks the creation of activity diagrams for all of the CRUD operations for the Cluster API provider for vSphere's (CAPV) cluster and machine workflows. This includes:

* Cluster
	* Reconcile
	* Delete
* Machine
	* Create
	* Update
	* Delete
	* Exist

## Requirements

The solution should:

* Use PlantUML to build plain-text, activity diagrams that may easily be exported as PNG or SVG images (example [puml](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/design/cluster-admission-machine-controller.puml), [svg](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/design/cluster-admission-machine-controller.svg))
* Adhere to a message loop architecture with the two message loops being the one for the *Cluster controller* and *Machine controller*

## Details

Understanding that Kubernetes is the author or state, and it's the job of CAPV to reconcile the backend infrastructure with that state, means CAPV's job isn't to to Create a VM, it's to reconcile the expected state with the actual state -- and if that means creating a VM, then so be it.

### Core design principles

The design of the CAPV is based on three core principles:

1. Idempotency
2. Reentrancy
3. Reconciliation

### An example machine reconciliation activity

For example, this is a basic outline of the Reconcile workflow for a `Machine`:

1. Does the `Machine` have a `TaskRef`?
	1. Yes, the `Machine` has a `TaskRef`
		1. Does the task exist?
			1. Yes, the task exists:
				1. Is the task running/pending?
					1. Yes, the task is running/pending
						1. Requeue the reconcile operation
					2. No, the task is not running/pending
						1. Remove the `TaskRef`
			2. No, the task does not exist:
				1. Remove the `TaskRef`
2. Does the `Machine` have a `MachineRef`?
	1. No, there is no `MachineRef`:
		1. Can the VM be found by the `InstanceUUID`?
			1. Yes, the VM is found by the `InstanceUUID`
				1. Assign the `MachineRef` to the `Machine`
3. Does the `Machine` have a `MachineRef`?
	1. Yes, there is a `MachineRef`
		1. Can the VM be found by the `MachineRef`?
			1. No, the VM cannot be found by the `MachineRef`
				1. Remove the `MachineRef` from the `Machine`
4. Does the `Machine` have a `DeletionTimestamp`?
	1. Yes, the `Machine` has a `DeletionTimestamp`
		1. Does the `Machine` have a `MachineRef`?
			1. Yes, there is a `MachineRef`
				1. Delete the VM
				2. Assign the delete `TaskRef` to the `Machine`
				3. Requeue the reconcile operation
	2. No, the `Machine` does not have a `DeletionTimestamp`
		1. Does the `Machine` have a `MachineRef`?
			1. Yes, there is a `MachineRef`
				1. Does the VM metadata match the calculated metadata?
					1. No, the metadata does not match
						1. Reconfigure VM with updated metadata
						2. Assign the reconfigure `TaskRef` to the `Machine`
						3. Requeue the reconcile operation
					2. Yes, the metadata matches
						1. Update the Machine status with the VM's MAC addresses
						2. Is the VM powered on?
							1. No, the VM is not powered on
								1. Power on the VM
								2. Assign the power-on `TaskRef` to the `Machine`
								3. Requeue the reconcile operation
							2. Yes, the VM is powered on
								1. Does the VM have one or more IP addresses?
									1. Yes, the VM has IP addresses
										1. Update the `Machine` status with the VM's IP addresses
									2. No, the VM does not have IP addresses
										1. Requeue the reconcile operation
				2. No, there is not a `MachineRef`
					1. Clone a template to create the VM
					2. Assign the clone `TaskRef` to the `Machine`
					3. Requeue the reconcile operation

### Representing activities in UML

The above activity could be represented in UML, from which an activity diagram might be generated ([PlantUML source](https://gist.github.com/akutz/a1decf2de925851fec10d809c529fa2d))

![machine-controller-reconcile](https://gist.githubusercontent.com/akutz/a1decf2de925851fec10d809c529fa2d/raw/ddd85ce76b3bba362f16f0bdfe2f564001c238c6/machine-controller-reconcile.svg?sanitize=true)

## Closing thoughts

Not until the VM for the `Machine` is cloned, booted, and online does CAPV consider the `Machine` ready for additional processing. And while this workflow *could* occur serially, at any junction where a *wait* might otherwise occur, the operation is instead requeued. This encourages, if not outright enforces, an idempotent and reentrant design.

**Comment by ykakarap** [comment]
@akutz Are we planning to move to CAPI v1alpha2 in the coming days? If so, is it suggested to make these diagrams after we move to v1alpha2, possibly because there will be changes?

**Comment by akutz** [comment]
Hi @ykakarap,

I opened that topic [for discussion](https://kubernetes.slack.com/archives/CKFGK3SSD/p1563560454007400) on July 19th and have yet to have any feedback from the CAPV community. @ncdc responded, and I'm inclined to agree that sooner is better. I'm currently putting together what a move to v1alpha2 means for CAPV. Still, I don't think it hurts to have diagrams of v1a1 since people may not move away from it quickly, and any patches we need to back port may fall on devs new to the project who may find diagrams helpful.

**Comment by ykakarap** [comment]
Ok. I will work on it. 

This will also help me understand what changes we might need when moving to v1a2.
