### ISSUE TITLE
Docker instructions for Workload Cluster Manifest generation have error

### ISSUE THREAD

**Issue by tkrausjr** [kubernetes-sigs/cluster-api-provider-vsphere#438]
/kind bug

**What steps did you take and what happened:**
Using Docker Instructions in GSG to generate a Workload Cluster manifests fails because` docker -v Volume bind ends up creating a directory out of envvars.txt`

**What did you expect to happen:**
I expected a generated set of manifests for a workload cluster.

**Anything else you would like to add:**
```
root@ubu01-jumphost:~/github/cluster-api-provider-vsphere/out# docker run --rm \
>   -v "$(pwd)/workload-cluster-1":/out \
>   -v "$(pwd)/envvars.txt":/out/envvars.txt:ro \
>   gcr.io/cluster-api-provider-vsphere/release/manifests:latest \
>   -c workload-cluster-1
_./hack/generate-yaml.sh: line 93: source: /out/envvars.txt: is a directory_

root@ubu01-jumphost:~/github/cluster-api-provider-vsphere/out# ls -d */
capv-33dec11d-dirty/  capv-mgmt-example/  capv-workload1/  new-capv-07-15/
capv-management/      capv-target/        envvars.txt/     workload-cluster-1/

```

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by akutz** [comment]
Hi @tkrausjr,

Was `envvars.txt` an existing file? The above command works for me:

```shell
$ docker run --rm \
   -v "$(pwd)/workload-cluster-1":/out \
   -v "$(pwd)/envvars.txt":/out/envvars.txt:ro \
   gcr.io/cluster-api-provider-vsphere/release/manifests:latest \
   -c workload-cluster-1
done generating /out/addons.yaml
done generating ./config/default/manager_image_patch.yaml
done generating /out/cluster.yaml
done generating /out/machines.yaml
done generating /out/machineset.yaml
Done generating /out/provider-components.yaml

*** Finished creating initial example yamls in /out

    The files /out/cluster.yaml and /out/machines.yaml need to be updated
    with information about the desired Kubernetes cluster and vSphere environment
    on which the Kubernetes cluster will be created.

Enjoy!
```

It will create that as a directory if there isn't a file named `envvars.txt` per [the instructions](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/getting_started.md#generating-yaml-for-the-bootstrap-cluster).

**Comment by tkrausjr** [comment]
Thanks @akutz . Worked through that but I found something else. the hack/generate-yaml.sh file in the Docker Image gcr.io/cluster-api-provider-vsphere/release/manifests:latest  needs to be updated with the changes we made in #434 to change VSPHERE_USER to VSPHERE_USERNAME

```
root@ubu01-jumphost:~/github/cluster-api-provider-vsphere/out# docker run --rm   -v "$(pwd)/management-cluster":/out -v "$(pwd)/envvars.txt":/out/envvars.txt:ro gcr.io/cluster-api-provider-vsphere/release/manifests:latest -c management-cluster
./hack/generate-yaml.sh: line 150: VSPHERE_USER: required
```

**Comment by akutz** [comment]
Hi @tkrausjr,

Can you please confirm whether or not this is still a problem?

**Comment by akutz** [comment]
I've tested it, and this is fixed.

/close
