### ISSUE TITLE
Feature: Support spreading nodes across multiple VC

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#44]
When deploying a machineset, we should support specifying a different VC in the spec that overrides the VC specified in the cluster object. This way from the infrastructure point of view, we can spread the node VMs across VCs. In doing so that assumption is that the user deploying this cluster will make sure that the VMs created across the VC will have a proper L3 connectivity to each other.

**Comment by moshloop** [comment]
What is the benefit of this? Deploying across multiple vSphere clusters I fully agree with, but that can be done with a single vCenter?

within a single VC #175 would cover that use case.

**Comment by akutz** [comment]
Hi @moshloop,

I think I agree with you. Let's allow the affinity rules cover how these are spread out. While long-term there may be benefits (cross-site redundancy) of machines across multiple vCenters, I'm not sure short-term it's necessary to prioritize this.

I'd rather push back on vSphere product group to enhance affinity rules to support cross-vCenter migration.

**Comment by dimatha** [comment]
> What is the benefit of this? Deploying across multiple vSphere clusters I fully agree with, but that can be done with a single vCenter?
> 
> within a single VC #175 would cover that use case.

We do have a use case for that. Examples:
- On-prem vCenter and VMC, different vxrail clusters deployed with its own venter (for various reasons) 
- Migration of the clusters from one vcenter to another
