### ISSUE TITLE
Add ability to log to a remote log server

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#45]
Debugging the cluster api stack is very time consuming and very complex.  If the system had the ability to log to a remote log server, it will significantly improve development productivity.  It will also be helpful for users of the cluster apis.  Not sure if glog can concurrently write to a remote server or we need another sidecar container to stream the logging to the server.

**Comment by moshloop** [comment]
Why is this an issue If you run the manager via go run it logs to stdout ?

**Comment by akutz** [comment]
This should likely be closed in favor of #200. However, @detiber and I **have** discussed something similar to this. However, in the short-term, combined with the new, standardized images, I am going to ask for lazy consensus on closing this issue in favor of the approach I outlined at https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/200#issuecomment-500064346.

If no one objects by next Friday, I will close this issue.
