### ISSUE TITLE
Failed to create management cluster

### ISSUE THREAD

**Issue by ylvmw** [kubernetes-sigs/cluster-api-provider-vsphere#465]
/kind bug

**What steps did you take and what happened:**
I failed to create the management cluster with the version v0.4.0-beta.2.

The create task failed with: unable to create control plane machine: timed out waiting for the condition

Generating YAML command:
docker run --rm \
  -v "$(pwd)":/out \
  -v "$(pwd)/envvars.txt":/envvars.txt:ro \
  gcr.io/cluster-api-provider-vsphere/release/manifests:v0.4.0-beta.2 \
  -c management-cluster

Create cluster command:
clusterctl create cluster --provider vsphere --bootstrap-type none --bootstrap-cluster-kubeconfig ~/.kube/config --cluster management-cluster/cluster.yaml --machines management-cluster/machines.yaml --provider-components management-cluster/provider-components.yaml   --addon-components management-cluster/addons.yaml --kubeconfig-out management-cluster/kubeconfig

Errors in pod vsphere-provider-controller-manager-0:
[actuator.go:217] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/management-cluster "msg"="target cluster is not ready" "error"="unable to get client for target cluster: failed to retrieve kubeconfig secret for Cluster \"management-cluster\" in namespace \"default\": secret not found"

Errors in pod cluster-api-controller-manager-0:
[noderef_controller.go:136] Failed to assign NodeRef to Machine "management-cluster-controlplane-1": cannot find a matching Node in namespace "default", retrying later

kubectl get secrets
...
management-cluster-kubeconfig   Opaque                                1      29m

**What did you expect to happen:**
Create the management cluster successfully.

**Anything else you would like to add:**
No.

**Environment:**

- Cluster-api-provider-vsphere version: v0.4.0-beta.2
- Kubernetes version: (use `kubectl version`): v1.14.3
- OS (e.g. from `/etc/os-release`):

**Comment by jpweber** [comment]
Additional information, I see this issue _only_ when I have multiple interfaces specified in my `machines.yaml` file

example
```
network:
     devices:
      - networkName: "VM Network"
         dhcp4: true
         dhcp6: false
       - networkName: "test network"
          dhcp4: false
          dhcp6: false
```

**Comment by ylvmw** [comment]
@jpweber I only have one interface, the detailed machines.yaml

apiVersion: cluster.k8s.io/v1alpha1
kind: MachineList
items:
- apiVersion: cluster.k8s.io/v1alpha1
  kind: Machine
  metadata:
    name: "management-cluster-controlplane-1"
    labels:
      cluster.k8s.io/cluster-name: "management-cluster"
  spec:
    providerSpec:
      value:
        apiVersion: vsphere.cluster.k8s.io/v1alpha1
        kind: VsphereMachineProviderSpec
        datacenter: "Datacenter"
        datastore: "nfs-ds"
        resourcePool: "rp1"
        folder: ""
        network:
          devices:
          - networkName: "VM Network"
            dhcp4: true
            dhcp6: false
        numCPUs: 2
        memoryMiB: 2048
        diskGiB: 20
        template: "ubuntu-1804-kube-v1.13.6"
    versions:
      kubelet: "1.13.6"
      controlPlane: "1.13.6"
