### ISSUE TITLE
add support  for VMC

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api-provider-vsphere#468]
/kind feature

**Describe the solution you'd like**

Machines deployed in VMC are not accessible from the public internet by default, and the ability to link an SDDC to AWS to utilize AWS services such as ELB provides a useful solution to this problem and more (e.g. HA setups).

we need to add the ability to provision an ELB  for clusters deployed to VMC on AWS

/assign

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by akutz** [comment]
Related to this [CAEP](https://docs.google.com/document/d/17Z_F_lmv4WgXaG9TaayOwwpCGRRoBxLbY070TSXDhvs/edit#heading=h.4rt1bigh1fwt)

**Comment by akutz** [comment]
Related to https://github.com/kubernetes-sigs/cluster-api/issues/1250
