### ISSUE TITLE
Typo in error message

### ISSUE THREAD

**Issue by rbankston** [kubernetes-sigs/cluster-api-provider-vsphere#473]
/kind bug

**What steps did you take and what happened:**
Creating aCAPV cluster but failed at setting the template location correctly. The error in the logs state:

 1 machine_controller.go:229] Failed to create machine "capv-mgmt-example-controlplane-1": unable to find tempate by name "ubuntu-18.04-kube-1.15.0": vm 'ubuntu-18.04-kube-1.15.0' not found

**What did you expect to happen:**

Didn't expect an error but expected the error to say:

 1 machine_controller.go:229] Failed to create machine "capv-mgmt-example-controlplane-1": unable to find template by name "ubuntu-18.04-kube-1.15.0": vm 'ubuntu-18.04-kube-1.15.0' not found

**Anything else you would like to add:**

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/c3d8e843739a86be0cd28ea265bad3af116537a6/pkg/cloud/vsphere/services/govmomi/template/template.go#L67

Is the line in question.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by akutz** [comment]
/close 

Fixed in #509
