### ISSUE TITLE
Crypto verification error when creating cloud provider secret

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/cluster-api-provider-vsphere#477]
/kind bug

**What steps did you take and what happened:**
Clusterctl errored with the following when creating a management cluster:
```
I0801 22:22:52.252326       1 cluster_controller.go:140] reconciling cluster object management-cluster triggers idempotent reconcile.
E0801 22:22:52.322736       1 actuator.go:236] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/management-cluster "msg"="unable to create cloud provider secret" "error"="Post https://192.168.3.141:6443/api/v1/namespaces/kube-system/secrets: x509: certificate signed by unknown authority (possibly because of \"crypto/rsa: verification error\" while trying to verify candidate authority certificate \"kubernetes\")"
```

This stalled the bootstrap process. I couldn't reproduce it after the first time around.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by luniHw** [comment]
Hi Andrew, i met the same issue. the error is
`actuator.go:235] [cluster-actuator]/cluster.k8s.io/v1alpha1/default/management-cluster-nimbus "msg"="unable to create cloud provider secret" "error"="Post https://172.10.0.5:6443/api/v1/namespaces/kube-system/secrets: x509: certificate is valid for 100.64.0.1, 10.161.72.227, 10.161.72.227, 10.161.72.227, not 172.10.0.5"`

environment info as below:
- Background
  Set up cluster-api+ncp env.
  Add nsx network configuration in machine.yaml, as below:
 `network:
          preferredAPIServerCidr: "172.10.0.5/24"
          devices:
          - networkName: "LS100"
            ipAddrs:
            - 172.10.0.5/24
          - networkName: "VM Network"
            dhcp4: true
            dhcp6: false`

- Cluster-api-provider-vsphere version
  v0.4.1
- Kubernetes version
   Kubernetes on VM used to execute clusterctl command is v1.14.2
   Kubernetes of cluster vm is 1.14.3
- OS
`root@sc-rdops-vm11-dhcp-92-71:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial`
