### ISSUE TITLE
unit test: write test for the govmomi provisioner

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#48]
Write unit tests for the new govmomi provisioner.

**Comment by sflxn** [comment]
Moved to release 0.3 as we've run out of time and this issue was not a `P0`.

**Comment by akutz** [comment]
Based on the model in CAPA, introduced in #307, let's look at gmock as a way to do better testing short of having a working environment. That or vc Sim.

**Comment by akutz** [comment]
Also look at how we can provide coverage with integration testing using vC Sim

**Comment by akutz** [comment]
/assign @frapposelli 

Remember RADIO? Container as place to run workload.
