### ISSUE TITLE
[CAPV] Should allow specifying more details to avoid ambiguity in the provider/machine spec

### ISSUE THREAD

**Issue by sujeet-banerjee** [kubernetes-sigs/cluster-api-provider-vsphere#481]
/kind feature

**Describe the solution you'd like**
Currently, the machine/machineset requires "ResourcePool" name/reference. However, the provider-controller fails to create a cluster if there is another vC resource-pool with the same specified name (with a different vSpere-cluster, in the same VC). The user has no option but to remove/rename the resource-pool from another cluster in his/her vCenter. This may not be a desirable scenario in existing deployments. There is no way, the user can trick/workaround the cluster-api to force create the K8s-cluster in a specific vSphere-cluster.

**Anything else you would like to add:**
Logs:
“unable to get resource pool for \“default/management-cluster/management-cluster-controlplane-1\“: path ‘k8s’ resolves to multiple resource pools”

**Environment:**
export GOVC_URL=“10.184.93.117”
export GOVC_USERNAME=“administrator@vsphere.local”
export GOVC_PASSWORD=“Admin!23”
export DC_NAME=“DC-NCP”
docker run --rm -e GOVC_URL -e GOVC_USERNAME -e GOVC_PASSWORD vmware/govc ls -k /${DC_NAME}/vm /${DC_NAME}/network /${DC_NAME}/host /${DC_NAME}/datastore
docker run -e GOVC_URL -e GOVC_USERNAME -e GOVC_PASSWORD vmware/govc ls -k /${DC_NAME}/network

- Cluster-api-provider-vsphere version: master (top-of-tree)
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`): 
Darwin banerjees-a01.vmware.com 17.7.0 Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin

**Comment by akutz** [comment]
Hi @sujeet-banerjee,

Additional specificity is already allowed. Simply specify the full path to the resource pool. Please see https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/403#issuecomment-510276822 for more information on specifying the qualified path for resource pools, folders, etc.

**Comment by sujeet-banerjee** [comment]
Thanks, Andrew. I just went through the "path". I will give it a try.

However, a related problem is the resource path specifier does not allow specifying descendants much like the convenient "Xpaths", say, "//Compute-ResourcePool" instead of "/SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool".

**Comment by akutz** [comment]
Hi @sujeet-banerjee,

This is all tied back to Govmomi. I recommend engaging @dougm in the Govmomi repository for any enhancement requests you want to make regarding descendants matching.

**Comment by dougm** [comment]
You should be able to use `Compute-ResourcePool` by name without any path structure, if the name is unique to all ResourcePool types.  Have you tried that?

**Comment by sujeet-banerjee** [comment]
> You should be able to use `Compute-ResourcePool` by name without any path structure, if the name is unique to all ResourcePool types. Have you tried that?

Yes. The bug is for the case where there may be two vc-clusters with the same resource-pool name. You may want to re-read the bug description above...

**Comment by sujeet-banerjee** [comment]
The full-path works... closing.
