### ISSUE TITLE
[CAPV][Machine Create][Cloning] Clusterctl bails out leaving an in-progress VM cloning in vSPhere, and cannot resume from where it left in the next run.

### ISSUE THREAD

**Issue by sujeet-banerjee** [kubernetes-sigs/cluster-api-provider-vsphere#488]
/kind bug

**What steps did you take and what happened:**
I ran,
>> bin/clusterctl create cluster -a ./out/management-cluster/addons.yaml -c ./out/management-cluster/cluster.yaml -m ./out/management-cluster/machines.yaml -p ./out/management-cluster/provider-components.yaml --kubeconfig-out ./out/management-cluster/kubeconfig --provider vsphere --bootstrap-type kind   -v 6

VM cloning took almost 48 minutes for my vCenter, and in the meantime, the clusterctl bailed out leaving an in-progress VM cloning. When I re-ran the clusterctl..., it did not pick the state from where it bailed out the last time - leaving a dangling VM 'management-cluster-controlplane-1' (in powered-Off state). 

Clusterctl logs:
"Waiting for Machine management-cluster-controlplane-1 to become ready..."
"Waiting for Machine management-cluster-controlplane-1 to become ready..."
...

**What did you expect to happen:**
#1. I believe, clusterctl should not bail out - and wait for the VM cloning to finish. 
#2. The next run of clusterctl should pick from where the previous one left (i.e. do not forget the VM which is still cloning from the previous CLI run)?

**Anything else you would like to add:**
export GOVC_URL="10.184.93.117"
export GOVC_USERNAME="administrator@vsphere.local"
export GOVC_PASSWORD="Admin!23"
export DC_NAME="DC-NCP"
docker run --rm -e GOVC_URL -e GOVC_USERNAME -e GOVC_PASSWORD vmware/govc ls -k /${DC_NAME}/vm /${DC_NAME}/network /${DC_NAME}/host /${DC_NAME}/datastore
docker run -e GOVC_URL -e GOVC_USERNAME -e GOVC_PASSWORD vmware/govc ls -k /${DC_NAME}/network

**Environment:**

- Cluster-api-provider-vsphere version: master (to-of-tree)
- Kubernetes version: (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:16:58Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from `/etc/os-release`): 
Darwin banerjees-a01.vmware.com 17.7.0 Darwin Kernel Version 17.7.0: Wed Feb 27 00:43:23 PST 2019; root:xnu-4570.71.35~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin

**Comment by akutz** [comment]
Is this still reproducible in v1a2? FWIW, a 48-minute long clone attempt is a problem with vCenter, not CAPV.
