### ISSUE TITLE
A mechanism to provider a query string for choosing values from cloud-init instance data

### ISSUE THREAD

**Issue by jpweber** [kubernetes-sigs/cluster-api-provider-vsphere#490]
/kind feature

**Describe the solution you'd like**
Provide an ability to provide a query string in a machine resource for choosing an interface from the cloud-init instance data. 

**Anything else you would like to add:**
Currently this value is a constant
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/a66fb0c7b77b41a07762544540802c76e37b1d4d/pkg/cloud/vsphere/services/govmomi/create.go#L37

This is related to #485 

**Environment:**

- Cluster-api-provider-vsphere version: 0.4.0
- Kubernetes version: (use `kubectl version`): NA
- OS (e.g. from `/etc/os-release`): NA

**Comment by akutz** [comment]
Hi @fabriziopandini / @chuckha,

@jpweber mentioned he might take a stab at this, and I told him that it likely makes sense to sync with you two since this part of the CAPV code base will be replaced with the kubeadm bootstrap provider. I'm hoping Jim can craft a quick fix for this issue that:

1. Is in sync with what the plan is for the bootstrap provider
2. Perhaps even ends up being the basis/starting point for a similar solution in the bootstrap provider

We were discussing a solution that looks something like:

```golang
type NotARealStruct struct {
    // LocalIPv4Lookup is the query cloud-init uses to look up a machine's local
    // IPv4 address via the cloud-init metadata service.
    //
    // This field may be set to either a JINJA query or a static IP address. For
    // example, if omitted, the field defaults to "{{ ds.meta_data.local_ipv4 }}".
    //
    // Please see https://cloudinit.readthedocs.io/en/latest/topics/instancedata.html 
    // for more information on the types of queries that can be used and the
    // data being queried.
    //
    // The field may also be assigned a static IP address to ensure the correct
    // IP address is used during the bootstrap process.
    //
    // +optional
    LocalIPv4Lookup string `json:"localIPv4Lookup,omitempty"
}
```

**Comment by chuckha** [comment]
We do want to replace this with a user-configurable value so this definitely aligns with the plan.

This value, in CAPA, was hard coded but there wasn't much from changing it to a default instead. I expect that's the path we want for right now

**Comment by akutz** [comment]
Hi @chuckha,

> I expect that's the path we want for right now

Do you mean you want to leave it static for now? If so then CAPV won't be able to use v1a2 until this is a configurable value.

**Comment by chuckha** [comment]
Let me try to rephrase:

For the kubeadm bootstrap provider we aren't forcing any values on you anymore. That value came directly from the CAPA code which can take advantage of cloud-config + jinja + metadata server. In the case of vsphere, if my understanding is correct, you don't have the metadata data server like AWS (totally reasonable) and you don't know the host name until boot (also totally reasonable). That means you have to dynamically set the kubeadm configuration file.

We have several hooks and can come up with a strategy for making this work. A PR just landed to add Pre-kubeadm commands. Either that or @detiber's idea of creating some script that exists on the image that will populate the kubeadm config file seem like that should be enough to get us through this problem. 

Let me know if you need any more clarification, happy to rephrase until I make sense

**Comment by akutz** [comment]
Hi @chuckha,

Thanks! FWIW, I'm on board with the external interpolation engine idea. I don't think it can be as simple as `envsubst` however. It should be akin to JINJA templating with a full query language. I [suggested](https://github.com/kubernetes-sigs/image-builder/pull/21#issuecomment-521805214) a data structure into a Go template, for example.

**Comment by akutz** [comment]
Hi @jpweber,

This is no longer an issue in v1a2. Would you like to continue to explore a solution for v1a1?
