### ISSUE TITLE
Intermittent crypto/rsa verification error using kubeconfig

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/cluster-api-provider-vsphere#495]
/kind bug

**What steps did you take and what happened:**
On a new cluster (using master), I'm occasionally seeing this error from kubectl using the bootstrap cluster's kubeconfig:
```
$ kubectl get machines
Unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "kubernetes")
```

It's pretty sporadic and goes away after a few retries but happens frequent enough to be a nuisance. 

Maybe related: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/477 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by akutz** [comment]
Hi @andrewsykim,

Are you still seeing this? Can you reproduce? Should we close this issue?

**Comment by andrewsykim** [comment]
I haven't seen this in a while, let's close for now and re-open if it comes up again.
