### ISSUE TITLE
update manifest generation to match centralized cloud provider configuration

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api-provider-vsphere#497]
/kind bug

**What steps did you take and what happened:** after https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/471 merged we moved from cloud provider configuration being specified on the machine config to cluster configuration.

Currently

```
docker run --rm   -v "$(pwd)":/out   -v "$(pwd)/envvars.txt":/envvars.txt:ro   gcr.io/cluster-api-provider-vsphere/release/manifests:latest   -c management-cluster
```

does not reflect that and cluster bootstrapping fails with:

```
W0812 14:38:33.977694       1 machine_controller.go:228] Failed to create machine "management-cluster-controlplane-1": unable to get datastore for "default/management-cluster/management-cluster-controlplane-1": default datastore resolves to multiple instances, please specify
```

**What did you expect to happen:**
bootstrapping the management cluster

**Anything else you would like to add:**

/assign

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
@akutz - seems like on `release/manifests:latest` templates under `/build` and `/out/cmd` are diverging

**Comment by akutz** [comment]
Hi @codenrhoden,

Do you need help looking at this? I also wonder if it's still an issue in CAPV v1alpha2.

**Comment by codenrhoden** [comment]
I can definitely look at this. With E2E tests working again, it indeed may no longer be a problem. I need to come up to speed on the changes over the last couple of weeks, but I will do so.

**Comment by yastij** [comment]
I'm no longer able to reproduce it

/close
