### ISSUE TITLE
Identify minimum set of vSphere permissions required for a functional CAPV

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#500]
/kind feature

**Describe the solution you'd like**
Identify and document the minimum set of vSphere permissions required to deploy a Kubernetes cluster.

**Comment by akutz** [comment]
@ntfrnzn is going to provide some more information on this based on some research he's done.

**Comment by akutz** [comment]
cc @moshloop

**Comment by timmycarr** [comment]
I'll start with this guide and digging into each of the values specified here: https://docs.vmware.com/en/VMware-vSphere/6.7/com.vmware.vsphere.security.doc/GUID-4D0F8E63-2961-4B71-B365-BBFA24673FDB.html

**Comment by timmycarr** [comment]
Putting together documentation here: https://hackmd.io/n-jBbLVkSsG_Dbm-eFTpIg

**Comment by yastij** [comment]
cc @maxrink

**Comment by ncdc** [comment]
@timmycarr are you still working on this?
