### ISSUE TITLE
ci/cd: create pods/containers/scripts to kick off clusterctl tests in CI/CD

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#52]
Based on what I've been told, we will likely kick off clusterctl tests by creating a pod on the existing kubernetes cluster in CI.  We need the pods/containers/scripts that kick off clusterctl tests in CI written.  The following are categories of tests we need written,

1. clusterctl create cluster
2. clusterctl delete cluster
3. clusterctl validate cluster

Note, each of these tests must be able to kick off a test to validate each commandline params.  This issue may actually be an epic as it is a large task.

**Comment by figo** [comment]
the container is uploaded to gcr.io/cnx-cluster-api/cluster-api-provider-vsphere-c
the code is currently at https://github.com/figo/cluster-api-provider-vsphere-ci but will be at main repo pretty soon.
