### ISSUE TITLE
Windows Node Support

### ISSUE THREAD

**Issue by rhockenbury** [kubernetes-sigs/cluster-api-provider-vsphere#525]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
K8s windows node support has been GA since 1.14.  Are there plans to produce a CAPV windows machine image? 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by akutz** [comment]
Hi @rhockenbury,

I'm not aware of any such immediate plans. It's something we've discussed, but this conversation should likely occur in the new machine [image-builder repository](https://github.com/kubernetes-sigs/image-builder). I will open an issue there for you.

**Comment by akutz** [comment]
/close

Closing for https://github.com/kubernetes-sigs/image-builder/issues/30
