### ISSUE TITLE
ci/cd: trigger the k8s conformance tests on the target cluster

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#54]
We need to run the k8s conformance tests on the target cluster, created by the cluster api.  Add this capability to our CI system.

**Comment by sflxn** [comment]
We should look at using Sonobuoy for this.

**Comment by timothysc** [comment]
Depending on how you want to use sonobuoy it's really easy to kick via command line, but there is also an interface library for the folks who want todo deeper CI integrations.  https://github.com/heptio/sonobuoy/blob/master/pkg/client/interfaces.go 

cc @johnSchnake

**Comment by figo** [comment]
@timothysc thank you, we will start with sonobuoy CLI

**Comment by frapposelli** [comment]
maybe considering a lower priority for this specific issue
