### ISSUE TITLE
Command line version output

### ISSUE THREAD

**Issue by rbankston** [kubernetes-sigs/cluster-api-provider-vsphere#549]
/kind feature

**Describe the solution you'd like**
Would like version, --version, or -v available to know the version of the clusterctl binary is installed on a machine.

**Anything else you would like to add:**

Would also be nice to list what provider the clusterctl is in the version output like:

```
$ clusterctl version
Client Version: version.Info{Major:"0", Minor:"5", GitVersion:"v0.5.0", GitCommit:"2da7433a4d9a74f4f1f78fcf5b1af6be06745fd9", GitTreeState:"clean", BuildDate:"2019-09-03T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Provider:"vsphere", Platform:"darwin/amd64"}
```

**Comment by akutz** [comment]
I agree this would be nice. Yes, it's definitely something with which I agree :)

**Comment by akutz** [comment]
Reassign to CAPI.
