### ISSUE TITLE
ci/cd: add some tests to validate the bootstrap and target clusters

### ISSUE THREAD

**Issue by sflxn** [kubernetes-sigs/cluster-api-provider-vsphere#55]
Add some end to end test to validate the bootstrap and target clusters are correct.  These tests can include the following as examples:

1. Clusters, Machines, MachineSet, MachineDeployment objects
2. Correct annotations

**Comment by figo** [comment]
a end to end test CI job has been configured with travis-ci to run for pull request.
https://github.com/figo/cluster-api-provider-vsphere-ci
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/.travis.yml

the foundation of end of end test is here.
we could extend for more verifications, so i would recommend to close this PR.
and open new issue for individual verification we want to add.

**Comment by frapposelli** [comment]
this is a must for v1alpha1

**Comment by sflxn** [comment]
I think we can use `clusterctl validate cluster` for this; however, it's not fully working.  This needs to be updated in the CAPI (main) repo.  Given that, I am unsure we can complete this issue for v1alpha1 since we might be punting fixing the validate command in clusterctl.

**Comment by sflxn** [comment]
Moving this issue to the next release, 0.3, since it is not a `P0` and we have run out of time.
