### ISSUE TITLE
machines and vspheremachine show up even after deleting

### ISSUE THREAD

**Issue by ykakarap** [kubernetes-sigs/cluster-api-provider-vsphere#551]
/kind bug

**What steps did you take and what happened:**
I created a management cluster and a workload cluster on vSphere.
Applied a `machinedeployment` with 1 replica on the management cluster. The VM gets created on vSphere. Then, the `machinedeployment` was deleted. 
Next, a `machinedeployment` with 2 replicas is applied on the workload cluster. After both the vm are created the `machinedeployment` is deleted. The VM get destroyed form vSphere.

At the end a `machinedeployment` with 2 replicas is applied again on the workload cluster.

Now if we run `kubectl get machines`, the machines still show up in "deleting" state and remain in the state indefinitely.
```
➜ kubectl --kubeconfig kubeconfig get machines
NAME                                       PROVIDERID                                       PHASE
management-cluster-controlplane-0          vsphere://42119170-11a2-c0f1-5522-3f10c4e8e62a   running
management-cluster-md-0-84455f76d4-r9t28   vsphere://42112a9d-3e09-1717-8c15-e60150e28481   deleting
workload-cluster-controlplane-0            vsphere://4211692f-2e55-aa58-e69c-7a7ed1914812   running
workload-cluster-md-0-59489b94fd-6zqpf     vsphere://4211cb55-7db5-34ba-a079-b1f2b81b1b16   deleting
workload-cluster-md-0-59489b94fd-8wmrj     vsphere://421196f4-d807-3c9f-db1e-1480216ac66e   running
workload-cluster-md-0-59489b94fd-h72g7     vsphere://421185b1-45c3-096b-912c-060a536b9210   running
workload-cluster-md-0-59489b94fd-m6qlw                                                      deleting
```

Similarly, if we do `kubectl get vspheremachines` the vspheremachines that were deleted still show up.
```
➜ kubectl --kubeconfig kubeconfig get vspheremachines
NAME                                AGE
management-cluster-controlplane-0   44m
management-cluster-md-0-n2cvb       41m
workload-cluster-controlplane-0     34m
workload-cluster-md-0-fdl7h         25m
workload-cluster-md-0-mcmfz         31m
workload-cluster-md-0-mmmw6         31m
workload-cluster-md-0-xwxjs         25m
```

The vspheremachines 
-`workload-cluster-md-0-mcmfz`
-`workload-cluster-md-0-mmmw6` 
belong to the deleted `machinedeployment` on the workload-cluster. 

The vspheremachine `management-cluster-md-0-n2cvb` belongs to the `machinedeployment` on he management-cluster but all of them still show up.

**What did you expect to happen:**
The deleted machines and vspheremachines should be completely removed.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
The manifests were generated using: `gcr.io/cluster-api-provider-vsphere/release/manifests@sha256:14daace258e6da4f13482eb8e3e125bb0dee787bd4666c382781ad38337cbaf1`

**Comment by akutz** [comment]
Do you think it could be related to https://github.com/kubernetes-sigs/cluster-api/issues/1377?

**Comment by ykakarap** [comment]
https://github.com/kubernetes-sigs/cluster-api/issues/1366 is an issue about the MachineSet getting automatically deleted for no reason. 
Even though this issue is not exactly the same as https://github.com/kubernetes-sigs/cluster-api/issues/1366 they might be related to a common bug (not really sure, maybe some bad reference?).

I observed the same behavior as https://github.com/kubernetes-sigs/cluster-api/issues/1366 today morning but was not able to reproduce it.
