### ISSUE TITLE
Get Start seems not working with bootstrapping 

### ISSUE THREAD

**Issue by datianshi** [kubernetes-sigs/cluster-api-provider-vsphere#554]
/kind bug

**What steps did you take and what happened:**
Follow the https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/getting_started.md

Seems a dead loop -> 
When the first control plane machine was deployed

The machine controller reports ->
Cluster infrastructure is not ready yet, requeuing machine"

And the cluster controller reports -> 
failed to get preferred IP address for VSphereMachine

**What did you expect to happen:**
The first control plane machine is provisioned and then management cluster is set to be ready

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: latest 
- Kubernetes version: (use `kubectl version`): 1.14
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by zdyxry** [comment]
`VSphereCluster.Status.Ready` will be marked  first when it is reconciled，what is the version of clusterapi controller manager?
This error `failed to get preferred IP address for VSphereMachine` should be caused by a missing field `machine.Spec.Network.PreferredAPIServerCIDR`,this error should not affect the installation of the controlplane.

**Comment by datianshi** [comment]
@zdyxry  status ready is not marked first until a recent change -> 

It used to reconcile API endpoint first

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/e086bccf0c8bef083975959fa907dd83fd2a946e#diff-f581456f74dae7eeda0f85d1f78ca0cd

I pull the latest image and worked....

**Comment by zdyxry** [comment]
I saw you env `Cluster-api-provider-vsphere version` is `latest` , so .....

**Comment by datianshi** [comment]
@zdyxry latest means pulled before this 3 days ago :)
