### ISSUE TITLE
CA Secret causes cluster to stop provisioning

### ISSUE THREAD

**Issue by rbankston** [kubernetes-sigs/cluster-api-provider-vsphere#557]
/kind bug

**What steps did you take and what happened:**
Provisioned an external etcd cluster for use with a CAPV cluster and loaded the certificate authority key and certificate used for etcd in the namespace with the <clustername>-ca secret with the same label. The controller fails to move on with the provisioning using the secret and instead outputs:

```
I0906 22:31:45.913692       1 kubeadmconfig_controller.go:557] reconciler "level"=0 "msg"="Creating secret for certificate"  "name"="external-ca"
E0906 22:31:45.918152       1 kubeadmconfig_controller.go:496] reconciler "msg"="unable to create cluster certificates" "error"="secrets \"external-ca\" already exists"
E0906 22:31:45.918244       1 kubeadmconfig_controller.go:218] reconciler "msg"="unable to lookup or create cluster certificates" "error"="secrets \"external-ca\" already exists" "kubeadmconfig"={"Namespace":"default","Name":"external-controlplane-0"} "machine-name"="external-controlplane-0"
```

**What did you expect to happen:**
Expected the secret to be used to provision the cluster

**Environment:**

- Cluster-api-provider-vsphere version: 0.5.0
- Kubernetes version: (use `kubectl version`): 1.15.1
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Note**
If this should be filed in cabpk please let me know.

**Comment by akutz** [comment]
cc @chuckha

**Comment by chuckha** [comment]
This looks entirely contained in the bootstrapper, mind if I copy paste this over there and we can close this one?

thanks for the ping @akutz

**Comment by akutz** [comment]
That sounds good to me. @rbankston?

**Comment by rbankston** [comment]
Sounds good to me @akutz

**Comment by akutz** [comment]
That didn't close it. Weird. Closing in favor of https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm/issues/217
