### ISSUE TITLE
Raise minimum, supported version of vSphere  to 6.7u3

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#561]
This issue is to discuss raising the minimum, supported version of vSphere to 6.7u3. This is to transition the default cloud provider deployed by CAPV to the external, [vSphere cloud provider](https://github.com/kubernetes/cloud-provider-vsphere). The external cloud provider relies on the new [vSphere container storage interface (CSI) driver](https://github.com/kubernetes-sigs/vsphere-csi-driver), and the vSphere CSI driver depends on the vSphere cloud native storage (CNS) feature, supported in vSphere 6.7u3+.

We definitely need to switch the default behavior of CAPV to use the external cloud provider soon, it's just a question of when. I think it makes sense to do it sooner than later since CAPV is supposed to be the bleeding edge of Kubernetes cluster lifecycle solutions.

Thoughts? Concerns?

**Comment by akutz** [comment]
cc @yastij @andrewsykim

**Comment by yastij** [comment]
@akutz - I'm strongly in favour of that. with clusterctlv2 we're going to publishing a workload cluster template as part of the release assets, so my guess is that It won't support pre 6.7u3

**Comment by andrewsykim** [comment]
The only reason we have split configuration is because the storage configuration of the cluster varies based on the vSphere version. I think ideally we should support the minimum version of vSphere that is compatible with CCM + CSI which today is 6.7u3 but tomorrow can be 6.5

**Comment by yastij** [comment]
closing this as we don't test against anything lower than 6.7u3
