### ISSUE TITLE
Print fields as columns with VSphereCluster and VSphereMachine resources

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#572]
/kind feature

**Describe the solution you'd like**
CAPI recently started annotating certain fields in the `Cluster` and `Machine` resources so that the marked fields will be printed as columns when executing `kubectl get clusters` or `kubectl get machines`. For example:

```shell
$ kubectl get clusters
NAME                 PHASE
management-cluster   provisioned
workload-cluster-1   provisioned
```

```shell
$ kubectl get machines
NAME                                       PROVIDERID                                       PHASE
management-cluster-controlplane-0          vsphere://4230e346-b34f-708f-2d7c-e680d433f868   running
workload-cluster-1-controlplane-0          vsphere://423093f7-6e8f-9fa0-f092-ebb3d3097b92   running
workload-cluster-1-md-0-689c674fc4-q26b5   vsphere://42304a73-f633-57d3-f9ae-1d020473681b   running
```

This is accomplished by adding `kubebuilder` annotations as Godocs to the resources' analogous Go types. For example:

**The CAPI [`Cluster` annotation](https://github.com/kubernetes-sigs/cluster-api/blob/5cd7261c53109d1af832c2f26eb969cfe4b8e9a0/api/v1alpha2/cluster_types.go#L151-L154)**

```golang
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase",description="Cluster status such as Pending/Provisioning/Provisioned/Deleting/Failed"

// Cluster is the Schema for the clusters API
type Cluster struct {
```

**The CAPI [`Machine` annotation](https://github.com/kubernetes-sigs/cluster-api/blob/5cd7261c53109d1af832c2f26eb969cfe4b8e9a0/api/v1alpha2/machine_types.go#L199-L204)**

```golang
// +kubebuilder:printcolumn:name="ProviderID",type="string",JSONPath=".spec.providerID",description="Provider ID"
// +kubebuilder:printcolumn:name="Phase",type="string",JSONPath=".status.phase",description="Machine status such as Terminating/Pending/Running/Failed etc"
// +kubebuilder:printcolumn:name="NodeName",type="string",JSONPath=".status.nodeRef.name",description="Node name associated with this machine",priority=1

// Machine is the Schema for the machines API
type Machine struct {
```

This issue discusses whether or not CAPV should add annotations to its `VSphereCluster` and `VSphereMachine` resources to print specific fields as columns when users execute `kubectl get vsphereclusters` and `kubectl get vspheremachines`. The questions are:

* Should we do it?
  * For `VSphereCluster`?
    * Which fields?
  * For `VSphereMachine`?
    * Which fields?

cc @andrewsykim @sidharthsurana

**Comment by voor** [comment]
I would like to see `.status.nodeRef.name` as a column or `.spec.infrastructureRef.name` I'm not sure which is more appropriate, this would allow you to quickly compare the output of your machines with the associated VMs in the vSphere UI.

**Comment by evalsocket** [comment]
Hey @outofmem0ry  Can this assign to me? If you are not working on it

**Comment by outofmem0ry** [comment]
@evalsocket sure, thanks for picking this up.

**Comment by randomvariable** [comment]
@evalsocket can you just put `/lifecycle active` when you start work on it.

**Comment by evalsocket** [comment]
@randomvariable @outofmem0ry  @voor  can you tell me the fields so that i can start

**Comment by randomvariable** [comment]
Been off CAPV for a while, so whatever might be helpful to an end user if they do `kubectl get`, and then need to do a `kubectl describe` to do an actual task. things like host names, ip addresses. there will be some limitations, because of server side printing doesn't allow full json path expressions because of CPU cost. Have a look at CAPA's for examples.

**Comment by srm09** [comment]
Implemented via https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/1204
/close
