### ISSUE TITLE
Support the vSphere CSI Driver for vSphere >= 6.7u3

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/cluster-api-provider-vsphere#575]
/kind feature

**Describe the solution you'd like**
In https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/502, we added support to use the external vSphere cloud provider for vSphere >= 6.7u3. Along with that we should also be deploying the [vSphere CSI driver](https://github.com/kubernetes-sigs/vsphere-csi-driver) for any CAPV deployment that is using the external cloud provider as well (i.e. vSphere >= 6.7u3)

**Anything else you would like to add:**
cc @divyenpatel @sandeeppissay 

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by divyenpatel** [comment]
@andrewsykim If we can provide images for `CSI controller`, `node plugin`, `external-attacher`, `external-provisioner` and `metadata syncer/full sync` containers as a parameter it would be great.

**Comment by andrewsykim** [comment]
@divyenpatel noted!
