### ISSUE TITLE
Current v1alpha2 failing to pivot cluster secrets over to newly created management cluster

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-vsphere#576]
/kind bug

**What steps did you take and what happened:**
Follow current getting started guide for `clusterctl` exactly as described on a non-NSX-t vsphere single host no-DRS or HA features turned on. (vSphere 6.7U3)
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/8aa048b1353a07a6ca296e3aba1e227fdd37707b/docs/getting_started.md#using-clusterctl

Everything works _okay_ (there's a separate issue regarding CA not being valid yet)

However, when pivoting the secrets for the cluster from kind to the new management cluster I get the following error:

```
F0915 20:23:46.032891   32463 create_cluster.go:59] unable to pivot cluster api stack to target cluster: unable to pivot cluster API objects: Failed to move cluster: default/management-cluster: failed to move Secrets for Cluster default/management-cluster to target cluster: failed to move Secret default/management-cluster-ca: error copying Secret default/management-cluster-ca to target cluster: error creating Secret default/management-cluster-ca: Secret "management-cluster-ca" is invalid: metadata.ownerReferences.uid: Invalid value: "": uid must not be empty
```

This wouldn't be that bad, except the error message comes *after* the kind cluster is destroyed, so the secrets are completely lost.

Related logs and thread on slack: https://kubernetes.slack.com/archives/CKFGK3SSD/p1568335767001600 
**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by andrewsykim** [comment]
Should be fixed with https://github.com/kubernetes-sigs/cluster-api/pull/1435

**Comment by andrewsykim** [comment]
/close

Thanks for reporting @voor
