### ISSUE TITLE
Assign some host resource in envvar.txt when creating cluster vm through cluster api

### ISSUE THREAD

**Issue by luniHw** [kubernetes-sigs/cluster-api-provider-vsphere#586]
/kind feature

**Describe the solution you'd like**
my scene is not like as usual. host in esxi cluster is added as a transport node in different transport zone in my env for different testing, so require a special exsi host. but now CAVP dose not support to assign a exsi host in envvar.txt, the vm is always cloned on the first host

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by akutz** [comment]
This is only applicable when a cluster exists without DRS.

**Comment by akutz** [comment]
There's value in supporting the initial host placement for VMs on vSphere systems sans DRS.

**Comment by randomvariable** [comment]
Closing this as we no longer use the envvar.txt in the clusterctl model in v1alpha3.

/close
