### ISSUE TITLE
manifest generation container version lacks behind quick start guide

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#587]
/kind bug

**What steps did you take and what happened:**
The Quick start documentation mentiones the -u flag for vSphere < 6.7u3.
This flag is not recognized by any published version of the container 
```text
docker run --rm \
  -v "$(pwd)":/out \
  -v "$(pwd)/envvars.txt":/envvars.txt:ro \
  gcr.io/cluster-api-provider-vsphere/release/manifests:latest \
  -c management-cluster -u
invalid option: -u
usage: /build/examples/generate.sh [FLAGS]
  Generates input manifests for the Cluster API Provider for vSphere (CAPV)

FLAGS
  -b    bootstrapper manager image (default "us.gcr.io/k8s-artifacts-prod/capi-kubeadm/cluster-api-kubeadm-controller:v0.1.0")
  -B    bootstrapper manager log level (default "4")
  -c    cluster name (default "management-cluster")
  -d    disables required environment variables
  -f    force overwrite of existing files
  -h    prints this help screen
  -i    input directory (default /build/examples)
  -m    capv manager image (default "gcr.io/cluster-api-provider-vsphere/release/manager:v0.5.1")
  -M    capv manager log level (default "4")
  -o    output directory (default )
  -p    capi manager image (default "us.gcr.io/k8s-artifacts-prod/cluster-api/cluster-api-controller:v0.2.1")
  -P    capi manager log level (default "4")
```

**What did you expect to happen:**
the -u Flag is recognized

**Anything else you would like to add:**
The script in master contains the flag tho, so i suppose somebody just forgot to push the new container or pushed the wrong one

**Environment:**

- Cluster-api-provider-vsphere version: 0.5.1
- Kubernetes version: (use `kubectl version`): na
- OS (e.g. from `/etc/os-release`): na

**Comment by shawnho1018** [comment]
Same errors for me.

**Comment by akutz** [comment]
Hi @andrewsykim,

We should use this and other issues related to manifest generation as the basis for a discussion around the long-term viability of the generator vs the CAPI quick start.

**Comment by akutz** [comment]
This has been resolved.

/close
