### ISSUE TITLE
Explore k8s image promoter to k8s.gcr.io

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/cluster-api-provider-vsphere#591]
/kind feature

**Describe the solution you'd like**
At the last subproject meeting for CAPV, it was discussed that we want to look more into the k8s [image promoter](https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io).

The idea here is that we file PRs to https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io when we want to have an image promoted to the k8s gcr.io namespace (which conveniently has us, eu, and asia domains).

The promoter process is intended to be used with the image promoter [staging repos](https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/README.md), but it doesn't actually have to be according to @dims. What this means is that we should be able to promote our GA releases straight from `gcr.io/cluster-api-provider-vsphere/release/manager` if we want to. Looking at the existing promotion configs, we would be the first to do it this way, but I think our existing build/publish infrastructure is quite streamlined and is not necessarily something we want to abandon.

But this issue is for discussion around that.

/cc @andrewsykim 
/cc @akutz 
/cc @dims

**Comment by akutz** [comment]
Ping @codenrhoden

**Comment by akutz** [comment]
Ping @codenrhoden

**Comment by akutz** [comment]
Ping @codenrhoden

**Comment by srm09** [comment]
@randomvariable @yastij This could be something that we can incorporate in the release automation process. wdyt?

**Comment by sbueringer** [comment]
/close

This will be part of #2051
