### ISSUE TITLE
Cloud provider config should not come from master config

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#60]
The cloud provider configuration to be setup for the cluster today is rendered using the machine variables used for the master node. This assumption is not correct as the machine variables are there to provide information about **where** and **what** to deploy as a master node and **_not_** to serve as the input for the cloud provider config that the target kubernetes will use.
We need to clearly abstract out the information intended to be used for generating the cloud provider configuration for the cluster.
One possible place where this cloud provider configuration information could live is in the `Cluster` object's `providerConfig`. Currently it only contains the VC endpoint and credentials. Thus we would need to expand that definition.

**Comment by andrewsykim** [comment]
ref: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/314
