### ISSUE TITLE
Allow setting LeaderID in controller manager options

### ISSUE THREAD

**Issue by Lokicity** [kubernetes-sigs/cluster-api-provider-vsphere#606]
/kind feature

Running CAPV in the same namespace with CAPI or CABPK results in leader election errors. More details kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#271

**Comment by ncdc** [comment]
@akutz if you're busy, @noamran can work on this - she did the same changes for the other repos.

**Comment by ncdc** [comment]
We decided not to expose the leader election id as a flag to end users. Instead, we are hard-coding it to a unique value per cluster api repository. I'd recommend we do the same thing in CAPV; when Shan created this issue, I was thinking that we would expose it as a flag at that time.

**Comment by akutz** [comment]
Thanks @ncdc, we'd appreciate that!

/assign @noamran
