### ISSUE TITLE
infrastructure-components.yaml shouldn't include capv-manager-bootstrap-credentials

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes-sigs/cluster-api-provider-vsphere#608]
/kind bug

**What steps did you take and what happened:**
The outputs of `make release-manifests` is what we use for the released `infrastructure-components.yaml` file. Currently `make release-manifests` includes the templated secret `capv-manager-bootstrap-credentials`, which means the infrastructure-components.yaml is no longer valid out of the box.  Creating the `capv-manager-bootstrap-credentials` Secret should be an extra step that users are required since it involves storing the vCenter credentials in a Kubernetes Secret, as a result we should remove it entirely from the outputted manifests of `make release-manifests`. 

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
@akutz @andrewsykim - this means that it should be added to `provider-components.yaml` by user in order to be able to pivot to the management cluster, right ?

**Comment by andrewsykim** [comment]
`infrastructure-components.yaml` is generated separate from the bootstrap/pivot process. So `provider-components.yaml` shouldn't change.

**Comment by akutz** [comment]
Hi @yastij,

Here's how to visualize it.

* Running `kustomize build config/default` creates the _infrastructure components_
* Running `examples/generate.sh` creates the _provider components_
* _Infrastructure components_ is defined as only the components related to CAPV
* _Provider components_ is defined as both the _infrastructure components_ for CAPV and the _infrastructure components_ for everything on which CAPV depends, such as: CAPI controllers, CABPK controllers, etc.
