### ISSUE TITLE
publish latest stable version of capv using a stable.txt file

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api-provider-vsphere#620]
**Describe the solution you'd like**

It would be convenient to publish the latest stable version of capv as `stable.txt` file. This would enable us for example to generate manifests with the latest version, and help build various automation scripts

/assign @yastij @codenrhoden 
/kind feature

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by akutz** [comment]
Ping @yastij

**Comment by randomvariable** [comment]
This is more or less completed by clusterctl v2? Safe to close?
