### ISSUE TITLE
VSphereMachineTemplate determines node name and hostname but MachineDeployment determines VM name in vSphere

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-vsphere#623]
/kind feature

**Describe the solution you'd like**
Right now when you create new nodes for a cluster you are typically configuring a `MachineDeployment` and a `VSphereMachineTemplate`.  The `VSphereMachineTemplate` determines the name of the hostname and then the resulting node, so you're left with something that is a little tough to compare across UIs and APIs.  For example, I created a cluster with 8 nodes and get the following from `kubectl get nodes`:
```
NAME                          STATUS   ROLES    AGE   VERSION
small-workloads-58q77         Ready    <none>   12m   v1.15.4
small-workloads-pjc6c         Ready    <none>   18m   v1.15.4
small-workloads-wzf8c         Ready    <none>   12m   v1.15.4
small-workloads-zll7d         Ready    <none>   18m   v1.15.4
toiling-slug-controlplane-0   Ready    master   45h   v1.15.4
toiling-slug-md-0-rlkx4       Ready    <none>   45h   v1.15.4
toiling-slug-md-2-rhfnb       Ready    <none>   30m   v1.15.4
toiling-slug-md-2-w4lgg       Ready    <none>   32m   v1.15.4
```
Then in my management cluster I will get an entirely different response from `kubectl get machines -l 'cluster.x-k8s.io/cluster-name= toiling-slug'` 
```
NAME                                                    PROVIDERID                                       PHASE
dog-wearing-shoes-machine-deployment-65b8bd58d6-jgjdl   vsphere://4223def8-58c2-f606-f814-746a73cec2a6   running
dog-wearing-shoes-machine-deployment-65b8bd58d6-l4vf7   vsphere://42238bda-f6a4-f96b-f3bf-01e3a5034cd7   running
small-workloads-65b8bd58d6-ppvjk                        vsphere://4223e59a-6501-eaa2-d93f-20aa9426cea5   running
small-workloads-65b8bd58d6-zpw8g                        vsphere://4223f384-15a6-7d6f-b215-6b094ff86b36   running
toiling-slug-controlplane-0                             vsphere://4223bfdd-79b5-06e7-6fd4-16d8950137f5   running
toiling-slug-md-0-5f6769c55f-bbfps                      vsphere://4223d2f4-186d-488c-e57b-378c74cdd326   running
toiling-slug-md-1-db976d98f-5tzz5                       vsphere://4223a08d-1946-e541-d213-8806b4145337   running
toiling-slug-md-1-db976d98f-lxglj                       vsphere://4223f39c-6c4f-f2db-018b-5a833b004d98   running
```

**Anything else you would like to add:**
I might be just confusing the behavior of the sample `KubeadmConfigTemplate` which is setting hte hostname to the `ds.meta_data.hostname`, in which case maybe this is a feature request to change the default behavior to instead find out what the MachineDeployment name is, or to pass that information to the guest VM userdata.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by akutz** [comment]
Hi @voor,

This is really a CAPI issue, not a vSphere issue. It's the CAPI controller that determines the name of the machine and thus host. @vincepri, should @voor file this with the CAPI repo?

**Comment by vincepri** [comment]
This is definitely a CAPI issue, I'm not sure if it's an actual bug, but more expected behavior

**Comment by voor** [comment]
Yes, this wasn't filed as a bug, it's just a little confusing at first, I'm wondering if maybe a way to cut down that confusion is to add a default column to the `machines.cluster.x-k8s.io` that would allow better comparison.

**Comment by vincepri** [comment]
@voor Is the column you're looking for the corresponding node name?

**Comment by voor** [comment]
I accidentally made the comment over in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/572#issuecomment-541901304 since I'm still getting used to which CRD is owned by which group, I see now that `machines.cluster.x-k8s.io` is a CAPI owned CRD instead.

Repeated here:

I would like to see .status.nodeRef.name as a column or .spec.infrastructureRef.name I'm not sure which is more appropriate, this would allow you to quickly compare the output of your machines with the associated VMs in the vSphere UI.

**Comment by andrewsykim** [comment]
> This is definitely a CAPI issue, I'm not sure if it's an actual bug, but more expected behavior

@vincepri what was the justification for having machine controller use different names for node name and VM names?

**Comment by vincepri** [comment]
There is no justification, it's more like how `generate-name` functionality works in Kubernetes

**Comment by andrewsykim** [comment]
Right, but why not set the hostname based on the MachineDeployment generated name instead of a separate generated name for both?

**Comment by andrewsykim** [comment]
So I had a chance to dig into this issue a bit more. I don't think there's much we can do because of the existing assumptions around `generate-name` in CAPI as @vincepri mentioned. However, I think setting the VM name to match the `Machine` generated name, instead of the `VSphereMachine` generated name is better since we want the hostnames matching the VM names in vSphere.

**Comment by andrewsykim** [comment]
Opened https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/630 -- which at the very least consolidates the VM name and hostname (hence the Kubernetes node name) to match the name of the Machine. There will still be a mismatch between Machines and VSphereMachines  but not much we can do about that. Still investigating why we didn't use the Machine name for this in the first place, there may be a reason I'm not seeing yet.

**Comment by vincepri** [comment]
The patch looks good to me, although seems very vSphere specific, in other environment you cannot override the VMname or hostnames

**Comment by andrewsykim** [comment]
> in other environment you cannot override the VMname or hostnames

I know in some cloud providers, you can't override the hostname (AWS comes to mind) but the hostname is still determined based on the VM name. I think in general we should try to make the VM name match the Machine name at the very least. Though I admit AWS is a special case where the VM name itself is sometimes not configurable so not much that can be done there :) 

Fwiw, we may not merge the PR above until we migrate to v1alpha3 since it breaks compatibility for deleting machines.
