### ISSUE TITLE
Creation of workload cluster machines stuck at provisioned status. Cloud-init preflight failing to fetch the ConfigMap

### ISSUE THREAD

**Issue by KeithRichardLee** [kubernetes-sigs/cluster-api-provider-vsphere#624]
/kind bug

**What steps did you take and what happened:**
- Successfully created management cluster. 
- Successfully created workload cluster control plane. 
- Not successful in creating workload cluster workers
- Workload cluster machines don't progress from provisioned state to running state if there are 3 replicas. 
- Sometimes, one worker machine will progress to a running state but remaining two stay in a provisioned state.
- No issues if only 1 replica and then scale to 3. Have not tried 2 replicas, or 4+

**What did you expect to happen:**
All three machines to go to a running state

**Anything else you would like to add:**
```
# kubectl get machines -o wide
NAME                                                 PROVIDERID                                       PHASE         NODENAME
keithlee-capi-mgmt-cluster-controlplane-0            vsphere://42055c30-7f18-6d98-d8a5-cd00de95fd77   running       keithlee-capi-mgmt-cluster-controlplane-0
keithlee-workload-cluster-01-controlplane-0          vsphere://42052918-be7a-9e96-0f4a-555150de0f13   running       keithlee-workload-cluster-01-controlplane-0
keithlee-workload-cluster-01-md-0-759c657695-2899z   vsphere://4205ebe7-2636-d0a4-694e-08b19de37f98   provisioned
keithlee-workload-cluster-01-md-0-759c657695-97c7c   vsphere://420577c1-10a5-ea5f-8e94-5b21a318b0bf   provisioned
keithlee-workload-cluster-01-md-0-759c657695-p2vsg   vsphere://4205288a-5565-5a1f-82a9-d67e2d89235c   provisioned
```

**Environment:**
- capi manifest: v0.5.2-beta.0
- clusterctl: v0.2.5
- kind: v0.5.1
- docker: 19.0.3
- vSphere: 6.7U3
- ova: ubuntu-1804-kube-v1.15.4.ova

[capi.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/3725106/capi.log)
[capv.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/3725107/capv.log)

**Comment by KeithRichardLee** [comment]
Found the following in cloud-init-output.log from a machine 'stuck" in provisioned state..

```
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 running 'modules:config' at Thu, 17 Oct 2019 09:06:59 +0000. Up 24.37 seconds.
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
error execution phase preflight: unable to fetch the kubeadm-config ConfigMap: failed to get config map: Unauthorized
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 running 'modules:final' at Thu, 17 Oct 2019 09:07:07 +0000. Up 32.09 seconds.
2019-10-17 09:07:10,576 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/runcmd [1]
2019-10-17 09:07:10,587 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2019-10-17 09:07:10,587 - util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) failed
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 finished at Thu, 17 Oct 2019 09:07:10 +0000. Datasource DataSourceVMwareGuestInfo.  Up 35.55 seconds
```
compared to a machine that was sucessfull in same cluster progressing on to a running state...
```
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 running 'modules:config' at Thu, 17 Oct 2019 09:02:39 +0000. Up 38.53 seconds.
[preflight] Running pre-flight checks
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
[kubelet-start] Downloading configuration for the kubelet from the "kubelet-config-1.15" ConfigMap in the kube-system namespace
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Activating the kubelet service
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...

This node has joined the cluster:
* Certificate signing request was sent to apiserver and a response was received.
* The Kubelet was informed of the new secure connection details.

Run 'kubectl get nodes' on the control-plane to see this node join the cluster.

Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 running 'modules:final' at Thu, 17 Oct 2019 09:02:51 +0000. Up 50.49 seconds.
Cloud-init v. 19.2-36-g059d049c-0ubuntu1~18.04.1 finished at Thu, 17 Oct 2019 09:03:26 +0000. Datasource DataSourceVMwareGuestInfo.  Up 85.28 seconds
```

**Comment by yastij** [comment]
FYI @fabriziopandini

**Comment by fabriziopandini** [comment]
> unable to fetch the kubeadm-config ConfigMap: failed to get config map: Unauthorized

this is a problem we encountered sometime in kubeadm. It is not fully clear why the API server answers Unauthorized (all the required RBAC rules are created at init time).

However, as a temporary workaround, we implemented a retry logic in kubeadm in v1.15. 
As a temporary fix we can increase a little this timeout, but for a long term solution sig machinery support is required

**Comment by yastij** [comment]
I'll try and reproduce it, but increasing the timeout for now sounds reasonable for now. cc @neolit123

**Comment by andrewsykim** [comment]
This happened in 3 machines, is the problem known to happen that often?

**Comment by fabriziopandini** [comment]
@andrewsykim this problem happened when trying to setup kubeadm e2e with aggressive parallel join. no reports from users afaik

**Comment by neolit123** [comment]
the 1.15 signal is clean and uses the same join code path for workers:
https://k8s-testgrid.appspot.com/sig-cluster-lifecycle-kubeadm#kubeadm-kind-1-15

^ also this is an HA cluster.

is CAPV waiting to join workers after the `kubeadm init` node has fully finished?

**Comment by andrewsykim** [comment]
> this problem happened when trying to setup kubeadm e2e with aggressive parallel join

Sounds like what CAPV is doing now when you create a machine deployment with replicas=3. 

> is CAPV waiting to join workers after the kubeadm init node has fully finished?

IIRC, CAPV will only join workers once the first control plane is fully up so it seems unlikely.

**Comment by neolit123** [comment]
>> his problem happened when trying to setup kubeadm e2e with aggressive parallel join

> Sounds like what CAPV is doing now when you create a machine deployment with replicas=3.

a couple of points:
- if workers are currently being joined in parallel please experiment with serial join.
- the kubeadm e2e is doing serial join for CPs and then serial for workers.
we have plans to extend that to parallel, yet i saw flakes that are hard to explain and reproduce:
https://gist.github.com/neolit123/4ecd657175f17df0a8207e7ffb2c0ec4
we can potentially extend the retry logic as it's currently using the default k8s exponential backoff, which is quite short.

ideally CAP* should also have e2e tests, so that we can better catch similar problems on the different providers.

**Comment by andrewsykim** [comment]
Doing serial join at the CAPV level means we have to do serial creates, should be a last resort IMO.

**Comment by akutz** [comment]
This issue should be reassigned to the Kubeadm Bootstrap Provider IMO. cc @chuckha

**Comment by akutz** [comment]
/close 

Refiled as https://github.com/kubernetes-sigs/cluster-api/issues/1626
