### ISSUE TITLE
Unable to ssh to machines using key pair provided during creation

### ISSUE THREAD

**Issue by KeithRichardLee** [kubernetes-sigs/cluster-api-provider-vsphere#626]
/kind bug

**What steps did you take and what happened:**
After machines (mgmt or workload) are created, unable to ssh to them using private key of key pair specified during creation by the SSH_AUTHORIZED_KEY variable. Confirmed key is correct in the yamls under spec -> users -> sshAuthorizedKeys

```
export SSH_AUTHORIZED_KEY='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDGkxUnvuEQS4MDMmn4TrDsjDY8xae0tM8AvF8Iq2I2OrnieVS91RxcUVUuSl401fWm3ak0OxX6y19vPDksO57pcGhORxnqNJALXjXwbrUFbZlJ/yfZnmZ5I3iJae10AQ5h/5Va4nPtSMr9Vpo57zEfL7GNj2n+keSJ6pFB3edXnU9bhdchltqTGDNcgptPnWtNYxOTpoJ8tlt4znoJJpQ/Or2iVgV4LlmlAvhfy8fg/uvOt1lCxBGFdJzkKvYb84z5Gb4iB9L3VG30cULNmeX7b4vF/FcmmGp4ZAIGbP+/pKk/q1WkcXaenAqhS77BghyUbl/5Lylz+9aBHzuZTfxl root@ubuntu-jump'
```

```
root@ubuntu-jump:~/CAPI# ssh -i /root/.ssh/id_rsa ubuntu@10.0.10.216
ubuntu@10.0.10.216's password:
```

```
root@ubuntu-jump:~# ssh -V
OpenSSH_7.2p2 Ubuntu-4ubuntu2.8, OpenSSL 1.0.2g  1 Mar 2016
```

**What did you expect to happen:**
Able to ssh to any machine created using the key specified

**Environment:**
- capi manifest: v0.5.2-beta.0
- clusterctl: v0.2.5
- kind: v0.5.1
- docker: 19.0.3
- vSphere: 6.7U3
- ova: ubuntu-1804-kube-v1.15.4.ova

**Comment by andrewsykim** [comment]
@KeithRichardLee the default user is `capv` not `ubuntu`. Can you confirm `capv` works?

**Comment by andrewsykim** [comment]
(we should document this better)

**Comment by KeithRichardLee** [comment]
> @KeithRichardLee the default user is `capv` not `ubuntu`. Can you confirm `capv` works?

confirm `capv` works!

**Comment by andrewsykim** [comment]
Great, thanks for confirming. Btw the user is configurable in the kubeadm config (see [here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/examples/default/controlplane/controlplane.yaml#L61-L64)). We don't expose this knob on the manifest generator though so you have to update it yourself if you want a different user.
