### ISSUE TITLE
Version check against vCenter doesn't check ESXI hosts

### ISSUE THREAD

**Issue by voor** [kubernetes-sigs/cluster-api-provider-vsphere#639]
/kind bug

**What steps did you take and what happened:**

There is a new process with the example manifests where, if you have `VSPHERE_` variables configured, will check the version of your vCenter to see if it is 6.7U3 (or better).  This _may be_ a little confusing, since the interaction is hidden from the user.  More importantly, it *does not* check the versions of the ESXI hosts, *which also* must be running 6.7U3 (or better) for the CSI vSphere provider to properly work.

**What did you expect to happen:**

I *do want* the ability to toggle to 6.7U3 or older, but I would like this to be more explicit with guardrails, so that if I know my vSphere infrastructure cannot yet support 6.7U3 I am able to properly override this.

* Maybe a big warning banner similar to `WARNING: ./out/junk/provider-components.yaml includes vSphere credentials` that alerts you to whether CSI is turned on or not?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: `gcr.io/cluster-api-provider-vsphere/release/manifests:latest`
- Kubernetes version: (use `kubectl version`): N/A
- OS (e.g. from `/etc/os-release`):  N/A

**Comment by akutz** [comment]
/assign @andrewsykim 

We need to investigate whether the ESX host version impacts the features currently leveraged by CAPV, such as CNS.

**Comment by akutz** [comment]
@andrewsykim is on PTO, assigning this to myself.

/assign

**Comment by akutz** [comment]
Hey, @dougm, thoughts?

**Comment by dougm** [comment]
Yeah, I suppose the CNS driver should check the host version too.  There is a `HostSystem.Config.Product` field, which is the same structure as `Client.ServiceContent.About` currently used here:
https://github.com/kubernetes-sigs/vsphere-csi-driver/blob/5b197c4ca5079ea0ad4274e649f40f16c489120a/pkg/csi/service/cns/controller.go#L96

**Comment by akutz** [comment]
Blocked by #718

**Comment by voor** [comment]
For reference this is because CAPV requires 6.7U3 or more to function now.
