### ISSUE TITLE
Update calico version to support K8s 1.16 API's

### ISSUE THREAD

**Issue by nvpnathan** [kubernetes-sigs/cluster-api-provider-vsphere#653]
/kind bug

**What steps did you take and what happened:**
Because of some breaking API changes in 1.16 I had to modify a few things in the addons.yaml related to the calico deployment and daemonset in order for the management cluster to deploy and pivot properly. For the deployment and daemonset I changed extensions/v1beta1 to apps/v1 and also add a selector to the calico controller deployment.
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
vSphere 6.7u3
- Cluster-api-provider-vsphere version: 0.5.2
- Kubernetes version: (use `kubectl version`): 1.16
- OS (e.g. from `/etc/os-release`):

**Comment by andrewsykim** [comment]
Hi @nvpnathan I think this was fixed in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/579, is it possible you're using a stale addons.yaml file?

**Comment by akutz** [comment]
Hi @nvpnathan,

Ping.

**Comment by akutz** [comment]
Hi @nvpnathan,

We've not been able to reproduce this issue, and I am going to time box the closing of this issue to this Friday (2019/11/08) at 5pm CST. Please let us know before then if this is still a problem. Thank you!

**Comment by nvpnathan** [comment]
Hi @akutz I had a outdated image of the docker file to prep the cluster yamls. Fixed by pulling the latest.
