### ISSUE TITLE
Disable auto-approve for PRs

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#657]
/kind feature

**Describe the solution you'd like**
Disable auto-approval of PRs. Currently when an individual with approver status submits a PR, the PR is automatically approved. This results in a lot of explicit holds since we try to prevent drive-by lgtms from merging a PR before it's deemed ready.

@andrewsykim and I think disabling auto-approve will reduce the need for explicit holds in many to perhaps even most cases. We also want to be clear, approving your own PR shouldn't necessarily be frowned upon as it's the current behavior as auto-approve is enabled. However, this change would at least make the approval an explicit action.

cc @sidharthsurana @ncdc @codenrhoden @yastij Thoughts?

/assign @andrewsykim

**Comment by codenrhoden** [comment]
I don't have approver status in this repo, but in other repos where I *do* have it, I've generally not been a fan of auto-approve. I was surprised it is the default. 

So I would be +1 for this, but it's definitely up to the OWNERS here. :)

**Comment by andrewsykim** [comment]
+1 from me. It's disabled in https://github.com/kubernetes/cloud-provider-vsphere and I prefer it over holding PRs all the time.

**Comment by akutz** [comment]
I also have no issue with this. @andrewsykim, can you please go ahead and file a PR while we wait to see if any other feedback is received? Thanks!

**Comment by sidharthsurana** [comment]
+1

**Comment by ncdc** [comment]
No objections here

**Comment by srm09** [comment]
Unsure if this warrants any change right now. Is everyone in favor of closing this?

**Comment by sbueringer** [comment]
As far as I can tell this is disabled now (looking at recent PRs)

/close
