### ISSUE TITLE
Refactor 'services/cloudprovider' to a utility/components package

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#659]
/kind feature

**Describe the solution you'd like**
The package `pkg/cloud/vsphere/services/cloudprovider` is not really a service, it's more of a utility repository for creating the components necessary to deploy the external vSphere cloud provider to a target cluster. This package should be refactored/relocated to a utility or components package to indicate the purpose.

cc @andrewsykim 

**Environment:**

- Cluster-api-provider-vsphere version: v0.5.3

**Comment by randomvariable** [comment]
/close

This code has been removed.
