### ISSUE TITLE
Migrate to Kubebuilder

### ISSUE THREAD

**Issue by frodenas** [kubernetes-sigs/cluster-api-provider-vsphere#66]
Cluster-API has migrated to kubebuilder and CRDs (PR https://github.com/kubernetes-sigs/cluster-api/pull/494). We need to sync the vsphere cluster-api provider with the upstream changes.

**Comment by sflxn** [comment]
This was completed.  https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/105
