### ISSUE TITLE
Add warning to Getting Started Guide about ova suffix

### ISSUE THREAD

**Issue by shivaani0505** [kubernetes-sigs/cluster-api-provider-vsphere#671]
/kind feature

**Describe the solution you'd like**
When deploying OVA template via Vsphere using URL method, we get template with .ova suffix.
The name of template should comply with VSPHERE_TEMPLATE value in envvars.txt

It will be a good idea to add warning to getting started guide to carefully handle the .ova suffix

**Comment by akutz** [comment]
Hi @shivaani0505,

Do you think you'll have time to file a PR for this?

**Comment by shivaani0505** [comment]
Yes @akutz , I will be able to file a PR for this.
