### ISSUE TITLE
After capv pod was deleted, the reconciled pod keeps producing "msg"="Waiting for Machine Controller to set OwnerRef on VSphereMachine"

### ISSUE THREAD

**Issue by shawnho1018** [kubernetes-sigs/cluster-api-provider-vsphere#676]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I was using clusterapi to produce clusters earlier and everything worked fine. After 10 days, I tried to create a new guest cluster but I found I can only create control-plane machine not worker nodes. There are errors in pods in capv-system. I tried to delete the pod and let kubernetes's reconciled capability to re-run the pod. 
However, since then, I see this message every 20 seconds in the reconciled pod:

controllers/VSphereMachine/vspherecluster-controller/namespace=default/vsphereMachine=andrea-md-0-rq8dc/infrastructure.cluster.x-k8s.io/v1alpha2 "level"=0 "msg"="Waiting for Machine Controller to set OwnerRef on VSphereMachine"

Also, the newly create control-plane machine will always stuck in provisioning (under kubectl  get machines) while the VM is produced successfully. 
**What did you expect to happen:**
1. The control-plane VM can be provisioned successfully.
2. CapV pod could set OwnerRef on VSphereMachine successfully.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 0.4
- Kubernetes version: (use `kubectl version`): 1.15-5
- OS (e.g. from `/etc/os-release`): ubnutu-16.04

**Comment by akutz** [comment]
Is this still an issue or did #681 fix it?

**Comment by shawnho1018** [comment]
@akutz  thanks for your reply. I apologized that I don't know how I could apply this patch. Is there any new clusterctl being released or I need to change version in yaml file? I could not find the instruction in either this or #681 issue.

**Comment by akutz** [comment]
Hi @shawnho1018,

This should be fixed in v0.5.4, and I saw you're using 0.4. Can you please try with 0.5.4 and verify this has been fixed? If so, you may close this issue. Since I've seen this as fixed, if you're unable to verify this by the next CAPV bi-weekly call, we'll close this issue during triage.

**Comment by akutz** [comment]
FYI, we know this is fixed in v1alpha3, as well as v0.5.4, just waiting for @shawnho1018 to confirm.

**Comment by shawnho1018** [comment]
I'll check on my lab next week and reply here. Thanks for all team's efforts.

**Comment by yastij** [comment]
closing this as this was fixed
