### ISSUE TITLE
Not able to generate YAML for the Bootstrap Cluster

### ISSUE THREAD

**Issue by akashpatel2** [kubernetes-sigs/cluster-api-provider-vsphere#677]
Follow this guide: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/getting_started.md

run this command: $ docker run --rm \
  -v "$(pwd)":/out \
  -v "$(pwd)/envvars.txt":/envvars.txt:ro \
  gcr.io/cluster-api-provider-vsphere/release/manifests:latest \
  -c management-cluster

and it will generate:

cluster.yaml | The cluster resource for the target cluster
controlplane.yaml | The machine resource for target cluster's control plane nodes
machinedeployment.yaml | The machine resource for target cluster's worker nodes
provider-components.yaml | The CAPI and CAPV reources for the target cluster
addons.yaml | Additional add-ons to apply to the management cluster (ex. CNI)

but my command is failing:

[`````````````````````````````]# docker run --rm \
>   -v "$(pwd)":/out \
>   -v "$(pwd)/envvars.txt":/envvars.txt:ro \
>   gcr.io/cluster-api-provider-vsphere/release/manifests:latest \
>   -c management-cluster
Checking 172.18.200.65 for vSphere version
Detected vSphere version 6.5
Generated ./out/management-cluster/addons.yaml
Generated ./out/management-cluster/cluster.yaml
Generated ./out/management-cluster/controlplane.yaml
Generated ./out/management-cluster/machinedeployment.yaml
Error: trouble fetching v0.2.7: exit status 128

**Comment by akutz** [comment]
Hi @akashpatel2,

It works for me:

```shell
$ docker run --rm \
> -v "$(pwd)":/out \
> -v "$(pwd)/envvars.txt":/envvars.txt:ro \
> gcr.io/cluster-api-provider-vsphere/release/manifests:latest \
> -c management-cluster
Generated ./out/management-cluster/addons.yaml
Generated ./out/management-cluster/cluster.yaml
Generated ./out/management-cluster/controlplane.yaml
Generated ./out/management-cluster/machinedeployment.yaml
Generated /build/examples/provider-components/provider-components-cluster-api.yaml
Generated /build/examples/provider-components/provider-components-kubeadm.yaml
Generated /build/examples/provider-components/provider-components-vsphere.yaml
Generated ./out/management-cluster/provider-components.yaml
WARNING: ./out/management-cluster/provider-components.yaml includes vSphere credentials
```

I imagine it's your network connectivity. The line with the error is trying to fetch the CAPI and CABPK components from GitHub. Please make sure your container runtime can access GitHub and try again.

**Comment by akashpatel2** [comment]
It was proxy issue, after passing proxy details with --env to docker run, it's working fine.

Thank you @akutz
