### ISSUE TITLE
How to pass http_proxy and https_proxy details to management cluster which is created by kind on vSphere infra

### ISSUE THREAD

**Issue by akashpatel2** [kubernetes-sigs/cluster-api-provider-vsphere#680]
How to pass http_proxy and https_proxy details to management cluster which is created by kind [ny clusterctl] on vSphere infra ?

I was able to create management cluster by creating management-controlplane node / VM on vSphere infra / vCenter server through clusterctl. [Followed the get_started guide.]

Most of the pods were under pending state in management cluster; i was suspecting it because of ImagePullBack error; and it's because my vSphere infra / vCenter server is under corporate proxy.

Looks like i am blocked because of this, I could not find any way to pass proxy in management-controlpane VM.

Can i get any kind of help here to proceed ahead ? 

Thanks,
Akash

**Comment by akutz** [comment]
/kind feature

Hi @akashpatel2,

Where would the requested settings need to be applied?

**Comment by akutz** [comment]
ping @akashpatel2

**Comment by akashpatel2** [comment]
Hi @akutz 

We can set the http/https proxy details by cloud init way.

1] set env proxy
2] set apt-get proxy [to download any packages, i am assuming the OS is ubuntu]
3] set docker proxy

Thanks,
Akash

**Comment by MnrGreg** [comment]
@akutz this is another example where we could capture the proxy key-value variables in a clustervars.txt as discussed here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/675#issuecomment-581157898

and then use Kustomize varReference to Patch in the below content to **KubeadmConfig/spec/files/path: /etc/systemd/system/containerd.service.d/http-proxy.conf** with **KubeadmConfig/spec/files/content:**
```ini  
[Service]    
Environment="HTTP_PROXY=$(HTTP_PROXY)"    
Environment="HTTPS_PROXY=$(HTTPS_PROXY)"    
Environment="NO_PROXY=$(NO_PROXY)"    
```


Alternatively, even if not catered for upfront in the clustervar.txt key-value file, if we're using Kustomized enabled CAPV Provider templates, end users can easily create and drop in their own Overlay for this, with their proxy values hardcoded.
