### ISSUE TITLE
How does the bootstrap work

### ISSUE THREAD

**Issue by mooperd** [kubernetes-sigs/cluster-api-provider-vsphere#687]
Hi,

Could someone explain how the bootstrap works? Does the provider inject a bootstrap which connects to the master IP address? Does the provider and the new node need to be able to talk to each other when the new node is booting or does it just connect directly to the K8s api?

Cheers,

Andrew

**Comment by akutz** [comment]
Hi @mooperd,

Somehow I whiffed on this. I can explain it when I get a minute. In the meantime there are [docs in the cluster-api book](https://cluster-api.sigs.k8s.io/architecture/controllers/bootstrap.html) that might be helpful.

Hey @ncdc / @chuckha, any idea of where else we can point Andrew?

**Comment by ncdc** [comment]
If you're looking for generic info on Cluster API & bootstrap providers, see https://cluster-api.sigs.k8s.io/architecture/controllers/bootstrap.html and https://master.cluster-api.sigs.k8s.io/providers/bootstrap.html.

If you're looking for information as to specifically what the kubeadm bootstrap provider is doing, I'm not sure we have that written down anywhere. If this is what you want, I would recommend opening an issue in the cluster-api repository.

**Comment by akutz** [comment]
Hi @mooperd,

Do you have any other questions? Or may I close this issue? Thanks!

**Comment by mooperd** [comment]
@ncdc I am very interested in what the kubeadm bootstrap provider is doing thanks! 

I am also trying to find the minimum set of vsphere permissions that I need to make this work. Should I open a new ticket for that?

**Comment by randomvariable** [comment]
A new issue was created for the permissions, and https://cluster-api.sigs.k8s.io/developer/architecture/controllers/bootstrap.html has details on how bootstrap works.

/close
