### ISSUE TITLE
Update pre-submit e2e job to use VPN

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#695]
/kind feature

**Describe the solution you'd like**
The [pre-submit e2e job for CAPV](https://github.com/kubernetes/test-infra/blob/2125a004bd89e422dcb639feb3d4d54907a6a3c4/config/jobs/kubernetes-sigs/cluster-api-provider-vsphere/cluster-api-provider-vsphere-presubmits.yaml#L199-L227) should use the VPN to perform testing with the e2e framework directly from the Prow cluster. 

/assign

**Comment by akutz** [comment]
I'm leaving myself assigned as well until the SA is created.

**Comment by yastij** [comment]
@akutz - sounds good

**Comment by yastij** [comment]
fixed by https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/709
/close
