### ISSUE TITLE
envatrs.txt is a directory when generating with docker

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#703]
/kind bug

**What steps did you take and what happened:**

When attempting to generate release manifests, the envars.txt is reported as a directory.

**What did you expect to happen:**

manifests would generate, and envars.txt would end up being a file.

**Anything else you would like to add:**

Very little context, first time trying CAP-v

**Environment:**

running from the docker image on master/latest as of dec 19, 2019.

```➜  clusterapi git:(master) ✗ docker run --rm \
  -v "$(pwd)":/out \
  -v "$(pwd)/envvars.txt":/envvars.txt:ro \
  gcr.io/cluster-api-provider-vsphere/release/manifests:latest \
  -c management-cluster
Unable to find image 'gcr.io/cluster-api-provider-vsphere/release/manifests:latest' locally
latest: Pulling from cluster-api-provider-vsphere/release/manifests
fc7181108d40: Pull complete 
869df5e15cd7: Pull complete 
f9485c4e0620: Pull complete 
1d959594fb73: Pull complete 
ecbcb5c3ee03: Pull complete 
d54144cee33b: Pull complete 
67e982c8e4c9: Pull complete 
5d03a15ed239: Pull complete 
fb52fed35322: Pull complete 
Digest: sha256:61254ceb3f36ff11699df82f3304504801942cdcead073ec55d391c35f5d5abe
Status: Downloaded newer image for gcr.io/cluster-api-provider-vsphere/release/manifests:latest
/build/examples/generate.sh: line 121: source: /envvars.txt: is a directory
```

**Comment by akutz** [comment]
Hi @jayunit100,

Did you ever confirm this happened due to our conversation on Slack? That the `envvars.txt` file was missing and thus Docker bind mounted an empty directory? Thanks!
