### ISSUE TITLE
failed to reconcile VM: error getting network specs

### ISSUE THREAD

**Issue by sheriefhammam** [kubernetes-sigs/cluster-api-provider-vsphere#710]
/kind bug

**What steps did you take and what happened:**
After following https://blah.cloud/kubernetes/clusterapi-for-vsphere-now-with-cns-support/

**i get the following Error:**
```shell
I0107 13:18:34.957906   13139 clusterclient.go:878] Waiting for Machine management-cluster-controlplane-0 to become ready...
```

**using while** 
```shell
! kubectl --kubeconfig=$(kind get kubeconfig-path --name management-cluster) -n capv-system logs   $(kubectl get pods -n capv-system | tail -n1 | awk '{print $1}')  -f ||   true; do sleep 5; done
 **i can see that:**
E0103 11:30:54.500791       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile VM: error getting network specs for \"infrastructure.cluster.x-k8s.io/v1alpha2, Kind=VSphereCluster default/management-cluster/management-cluster-controlplane-0\": unable to create new ethernet card backing info for network \"ds146\" on \"infrastructure.cluster.x-k8s.io/v1alpha2, Kind=VSphereCluster default/management-cluster/management-cluster-controlplane-0\": no System.Read privilege on: DistributedVirtualPortgroup:dvportgroup-2960.config.distributedVirtualSwitch"  "controller"="vspheremachine" "request"={"Namespace":"default","Name":"management-cluster-controlplane-0"}
```

**envvars.txt:**
```shell
#vCenter config/credentials
export VSPHERE_SERVER='*************'
export VSPHERE_USERNAME='*************'
export VSPHERE_PASSWORD=’************’
#vSphere deployment configs
export VSPHERE_DATACENTER='NIC-Darmstadt'
export VSPHERE_DATASTORE='Storage.a4'
export VSPHERE_NETWORK='ds146'
export VSPHERE_RESOURCE_POOL='Cluster_Intel-E5_SUT/Resources/rpA4'
export VSPHERE_FOLDER='/NIC-Darmstadt/vm/1_Projects/A4/Team SPF/1_Dev'
export VSPHERE_TEMPLATE='T_centos-7-kube-v1.16.3.a4'
export VSPHERE_DISK_GIB='20'
export VSPHERE_NUM_CPUS='2'
export VSPHERE_MEM_MIB='2048'
#Kubernetes configs
export KUBERNETES_VERSION='1.16.3'
export SERVICE_CIDR='192.168.10.0/24'
export CLUSTER_CIDR='10.240.16.0/24'
export SERVICE_DOMAIN='cluster.local'
```

**What did you expect to happen:**

**Anything else you would like to add:**
i cannot create VM using the same specs from the GUI and using Terraform as well

**Environment:**

- Cluster-api-provider-vsphere version: 
- OS (e.g. from `/etc/os-release`):  CentOS7
- kind v0.6.1 go1.13 linux/amd64
-  kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by sheriefhammam** [comment]
for a better clarification:
I0107 12:31:26.569379       1 vspheremachine_controller.go:176] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0 "level"=4 "msg"="VSphereMachine.Status.TaskRef OnEntry"  "task-ref"=""
I0107 12:31:26.572681       1 clone.go:43] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0/vcenter "level"=4 "msg"="starting clone process"
I0107 12:31:26.794716       1 util.go:159] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0 "level"=4 "msg"="skipping reconcile VSphereMachine on task completion"  "reason"="no-task"
I0107 12:31:26.795045       1 vspheremachine_controller.go:249] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0 "level"=0 "msg"="resource patch was not required"  "local-resource-version"="645" "remote-resource-version"="645"
I0107 12:31:26.795079       1 vspheremachine_controller.go:180] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0 "level"=4 "msg"="VSphereMachine.Status.TaskRef OnExit"  "task-ref"=""
E0107 12:31:26.795195       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile VM: error getting network specs for \"infrastructure.cluster.x-k8s.io/v1alpha2, Kind=VSphereCluster default/management-cluster/management-cluster-controlplane-0\": unable to create new ethernet card backing info for network \"ds146\" on \"infrastructure.cluster.x-k8s.io/v1alpha2, Kind=VSphereCluster default/management-cluster/management-cluster-controlplane-0\": no System.Read privilege on: DistributedVirtualPortgroup:dvportgroup-2960.config.distributedVirtualSwitch"  "controller"="vspheremachine" "request"={"Namespace":"default","Name":"management-cluster-controlplane-0"}
I0107 12:31:27.921115       1 vspheremachine_controller.go:176] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0 "level"=4 "msg"="VSphereMachine.Status.TaskRef OnEntry"  "task-ref"=""
I0107 12:31:27.924473       1 clone.go:43] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0/vcenter "level"=4 "msg"="starting clone process"
I0107 12:31:28.159732       1 util.go:159] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0 "level"=4 "msg"="skipping reconcile VSphereMachine on task completion"  "reason"="no-task"
I0107 12:31:28.160057       1 vspheremachine_controller.go:249] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0 "level"=0 "msg"="resource patch was not required"  "local-resource-version"="645" "remote-resource-version"="645"
I0107 12:31:28.160094       1 vspheremachine_controller.go:180] capv-controller-manager/vspheremachine-controller/default/management-cluster-controlplane-0 "level"=4 "msg"="VSphereMachine.Status.TaskRef OnExit"  "task-ref"=""
E0107 12:31:28.160175       1 controller.go:218] controller-runtime/controller "msg"="Reconciler error" "error"="failed to reconcile VM: error getting network specs for \"infrastructure.cluster.x-k8s.io/v1alpha2, Kind=VSphereCluster default/management-cluster/management-cluster-controlplane-0\": unable to create new ethernet card backing info for network \"ds146\" on \"infrastructure.cluster.x-k8s.io/v1alpha2, Kind=VSphereCluster default/management-cluster/management-cluster-controlplane-0\": no System.Read privilege on: DistributedVirtualPortgroup:dvportgroup-2960.config.distributedVirtualSwitch"  "controller"="vspheremachine" "request"={"Namespace":"default","Name":"management-cluster-controlplane-0"}

**Comment by akutz** [comment]
Hi @sheriefhammam,

I'm aware that you said this works manually and/or with Terraform, but the logs are pretty clear that it's a permissions issue:

```
 unable to create new ethernet card backing info for network \"ds146\" on \"infrastructure.cluster.x-k8s.io/v1alpha2, Kind=VSphereCluster default/management-cluster/management-cluster-controlplane-0\": no System.Read privilege on: DistributedVirtualPortgroup:dvportgroup-2960.config.distributedVirtualSwitch"
```

Specifically:

```
no System.Read privilege on: DistributedVirtualPortgroup:dvportgroup-2960.config.distributedVirtualSwitch
```

This seems related to https://github.com/vmware/govmomi/issues/1517. @dougm, was there ever any resolution on that issue? It appears to be the same one that @sheriefhammam is encountering here. Thanks!

**Comment by sheriefhammam** [comment]
@akutz my bad i corrected it. i can not deploy using terraform or manually.

i get that the error is pretty clear but what's confusing that i have the right clone other templates to vm but not the published one here 

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/README.md#kubernetes-versions-with-published-ovas 

thanks a lot for following up with me.

**Comment by akutz** [comment]
Hi @sheriefhammam,

> thanks a lot for following up with me.

Of course!

Hmmm, it sure seems like a permissions issue. I would start by using `govc` to list the permissions for a template that works and one that doesn't:

```shell
govc permissions.ls PATH_TO_OBJ
```

That will list all of the principals (users) that have rights to an object, and the role to which the principal belongs. From there you can use `govc role.ls` and `govc role.usage` to discover what permissions a role has on objects.

**Comment by sheriefhammam** [comment]
@akutz Both of them are exactly identical in terms of principals and the right to objects

**Comment by sidharthsurana** [comment]
@sheriefhammam I think the issue is more related to the read permission on the distributed port group `DistributedVirtualPortgroup:dvportgroup-2960` and not on the template. Please make sure that the networks you are trying to use have proper access to your user.

**Comment by sheriefhammam** [comment]
@sidharthsurana  that's exactly what confuses me as i have the proper access for it.
what makes me think it's more related to the template is that deploying any other template for the same specs everything works fine but not the three official centOS7 templates for cluster API

**Comment by dougm** [comment]
> This seems related to [vmware/govmomi#1517](https://github.com/vmware/govmomi/issues/1517). @dougm, was there ever any resolution on that issue?

No resolution, I'll take another look and let you know what I find.

**Comment by dougm** [comment]
govmomi is trying to collect the DistributedVirtualPortgroup's `config.distributedVirtualSwitch` property.  According the [docs]:(https://code.vmware.com/apis/196/vsphere/doc/vim.dvs.DistributedVirtualPortgroup.ConfigInfo.html)

> This property should always be set unless the user's setting does not have System.Read privilege on the object referred to by this property.

Note that "the object" in this case is the Switch, not the Portgroup.

@sheriefhammam  are you able to read the Switch properties using govc and the same credentials used with CAPV? Can you try this to check?
```console
% govc object.collect -type DistributedVirtualSwitch / portgroup | grep dvportgroup-2960
```

btw, it looks like Terraform uses the same method (EthernetCardBackingInfo) as CAPV:

https://github.com/terraform-providers/terraform-provider-vsphere/blob/ea68cb99b1c30a6f1b155e532a806d078a0cbad3/vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go#L594

https://github.com/terraform-providers/terraform-provider-vsphere/blob/ea68cb99b1c30a6f1b155e532a806d078a0cbad3/vsphere/internal/virtualdevice/virtual_machine_network_interface_subresource.go#L798

**Comment by sheriefhammam** [comment]
Hi @akutz @dougm you are perfectly correct it's all about the read privilege on Virtual switches and currently searching why i was able to clone the first template with the same spec and virtual switch but not the cluster API CentOS7 templates but generally speaking this solves my problem here and you can gladly close this bug.


ps:
- i didn't work till the end but at least i get rid of this problem and will see with some debugging what i am encountering at the moment
- govc working normally cloning the template but Terraform not because some customization of the template error

thanks a lot for your support

**Comment by sheriefhammam** [comment]
everything works fine at the moment and the control plane cluster is deployed at the moment
