### ISSUE TITLE
deploy CSI with ClusterResourceSet

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#718]
/kind feature

**Describe the solution you'd like**
This is to discuss whether or not CSI should be installed as an add-on, and not reconciled as part of CAPV when deploying workload clusters.

cc @voor @mylesagray

**Comment by mylesagray** [comment]
@akutz is there more context for this? A meeting recording or such that I missed? Is the proposal to remove CSI as part of the default installation when using CAPV?

**Comment by akutz** [comment]
Per my discussion with @mylesagray we decided a good cutline for what is an external add-on should be whether the platform leveraged by the "add-on" is built into vSphere. Since CSI depends on container network storage (CNS), and it **is** built into vSphere, CSI can be deployed by CAPV. 

On the other hand, the NSX container plug-in (NCP), a container network interface (CNI) solution, should be deployed as an add-on since NSX is not built into vSphere.

**Comment by akutz** [comment]
I will leave this issue open until someone files a PR that adds documentation to the effect of the above.

/help wanted

**Comment by yastij** [comment]
@akutz - I think we should re-visit this assumption, as any fix to CSI implies cutting a new release of CAPV.

**Comment by voor** [comment]
Since everything is manifest based (i.e., you're not putting static pods in anywhere) this also makes a lot more sense now, especially with the post-cluster apply stuff getting more fleshed out.

Referencing https://github.com/kubernetes-sigs/cluster-api/issues/2395

**Comment by MaxRink** [comment]
We honestly would also prefer it to be an add-on, as we have instances where we cant run the csi provider but would still like to provision clusters via CAPV

**Comment by yastij** [comment]
@MaxRink - this is definitely happening
