### ISSUE TITLE
No event metadata for workload cluster VMs which are Pending / Deleting / Running

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#723]
/kind bug

(might be a broader CAPI feature request - to add status conditions as a norm to machines?) .... 

**What steps did you take and what happened:**

After creating a VSphere cluster, i see all machines in the 'pending state' but i don't see any status updates to them, and i don't see any `describe` metadata to explain why they are pending.  i.e. there are no `events` records.

I tried to create a workload cluster, and noticed that when i had problems maintaining it, there were no events that i could look at to determine what was wrong, or *when* the machines state changed.

What I saw: 

- There are no Events/Status conditions for Running machines
- There are no Events/Status conditions for Pending machines
- There are no Events/Status conditions for Deleting machines

In contrast, for example with pods, you get 

```
status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2020-01-13T22:26:58Z"
      status: "True"
      type: Initialized
```

**What did you expect to happen:**

I would expec that there would be some events for CAPV `machine`s which i can use to determine why their status is infintely pending.

**Anything else you would like to add:**
 
im n00b still so could be missing something, or misfiling - maybe this is a CAPI issue.

```
Name:         workload-cluster-2-md-0-5f77f47487-2c4sq
Namespace:    default
Labels:       cluster.x-k8s.io/cluster-name=workload-cluster-2
              machine-template-hash=1933903043
Annotations:  <none>
API Version:  cluster.x-k8s.io/v1alpha2
Kind:         Machine
Metadata:
  Creation Timestamp:  2020-01-14T20:57:36Z
  Finalizers:
    machine.cluster.x-k8s.io
  Generate Name:  workload-cluster-2-md-0-5f77f47487-
  Generation:     1
  Owner References:
    API Version:           cluster.x-k8s.io/v1alpha2
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  MachineSet
    Name:                  workload-cluster-2-md-0-5f77f47487
    UID:                   2b110cb3-cc8d-4209-a93b-7f2cd9d92e8c
  Resource Version:        254408
  Self Link:               /apis/cluster.x-k8s.io/v1alpha2/namespaces/default/machines/workload-cluster-2-md-0-5f77f47487-2c4sq
  UID:                     4264bd91-4206-4db9-9e93-f476c4528f7b
Spec:
  Bootstrap:
    Config Ref:
      API Version:  bootstrap.cluster.x-k8s.io/v1alpha2
      Kind:         KubeadmConfig
      Name:         workload-cluster-2-md-0-ckwhz
      Namespace:    default
  Infrastructure Ref:
    API Version:  infrastructure.cluster.x-k8s.io/v1alpha2
    Kind:         VSphereMachine
    Name:         workload-cluster-2-md-0-jjsnb
    Namespace:    default
  Metadata:
  Version:  1.16.2
Status:
  Phase:  pending
Events:   <none>
 
```
**Environment:**

- Cluster-api-provider-vsphere version: cluster.x-k8s.io/v1alpha2 
- Kubernetes version: (use `kubectl version`): 1.16
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by akutz** [comment]
Hi @jayunit100,

Once upstream CAPI decided on a standard for events, CAPV will either adopt them or the instructions will be to query `machines`, not the infrastructure provider machines.

For questions like this, it's okay to start with Slack (cluster-api or cluster-api-vsphere) as this isn't a bug, but just an inquiry. Thanks!

cc @ncdc, if you agree with the above regarding CAPI events, please feel free to close this issue, or let me know, and I will. Thanks!

**Comment by jayunit100** [comment]
per @fabriziopandini  ... 'there is an ongoing effort to add events in CAPI" ... so, wi suppose i should link this to some upstream issues at some point.

**Comment by jayunit100** [comment]
thanks @akutz  ! will do that from now on.  feel free to close, if not ill leave this open... gotcha !

**Comment by akutz** [comment]
Hi @jayunit100,

I raised this issue in the upstream Cluster API call today, and @ncdc pointed me to https://github.com/kubernetes-sigs/cluster-api/issues/1658. Maybe it's something at which you'd like to take a look?

**Comment by jayunit100** [comment]
thanks , will follow up ther
