### ISSUE TITLE
Static IP pool mechanism

### ISSUE THREAD

**Issue by chipzoller** [kubernetes-sigs/cluster-api-provider-vsphere#728]
More of a general inquiry about how/if static IP pools can be assigned/consumed by CAPV. Currently, it appears to be DHCP only. As this project matures and is consumed by various automations, the desire to either pull from a vCenter static IP pool or external IPAM integration will be required. Wondering if this is being thought about.

**Comment by ncdc** [comment]
Hi @chipzoller, please take a look at https://github.com/kubernetes-sigs/cluster-api/issues/1740 for some additional information that is relevant here.

**Comment by jzhoucliqr** [comment]
@yastij Is this being worked on? I'm interested in this and am glad to help.

**Comment by jzhoucliqr** [comment]
Will put up a proposal with https://github.com/metal3-io/ip-address-manager

**Comment by ncdc** [comment]
One thing that I'd recommend including: modify CAPV so that if both dhcp4 and dhcp6 are disabled, and there are no IP addresses in the VSphereMachine, have the reconciler wait until at least one of those 3 fields is true/populated. This way, we can have CAPV wait until some external IPAM controller sets an IP on the VSphereMachine.

**Comment by jzhoucliqr** [comment]
Thanks @ncdc . That's exactly what I'm going to do!

**Comment by jzhoucliqr** [comment]
Proposal draft :  https://docs.google.com/document/d/10I-HH67_xBk73pazhNmbJjOvtPgq9Uk6ZrD3vj06srs/edit?usp=sharing

Please help take a look. @ncdc @yastij

**Comment by omniproc** [comment]
@jzhoucliqr was that draft ever finalized and implemented? I'm unable to find any issue or commit for it. There is a patch for CAPV here that had IPAM added already by modifying the controllers. https://github.com/omniproc/cluster-api-provider-vsphere-static-ip

This is quite old and I'm wondering if IPAM is yet integrated at all. Maybe you can clearify the status?

**Comment by jzhoucliqr** [comment]
@omniproc yes it is there:  https://github.com/spectrocloud/cluster-api-provider-vsphere-static-ip

And changes for v1alpha4 will be merged soon.

**Comment by omniproc** [comment]
in that case check out #1228 - those guys seem to be working on the same thing

**Comment by omniproc** [comment]
@jzhoucliqr merge only with v1alpha4 or do you plan adding v1beta1 support as well?
