### ISSUE TITLE
dump logs from CAPI and CAPV components into the artifacts directory

### ISSUE THREAD

**Issue by yastij** [kubernetes-sigs/cluster-api-provider-vsphere#734]
/kind feature

**Describe the solution you'd like**
Currently our e2e test do not dump logs from CAPI and CAPV, this makes hard to debug things while running on CI. 
We should invoke `kubectl  cluster-info dump` and add the content to the artifacts directory before garbage collecting the kind cluster 

**Anything else you would like to add:**

/assign @yastij 
/priority important-soon

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
cc @akutz

**Comment by ncdc** [comment]
FWIW, this is what CAPA dumps: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/24b2057904692380d419db6e8ab56ec35779993c/hack/ci/e2e-conformance.sh#L31-L93

**Comment by yastij** [comment]
@ncdc - we'll probably dump the same thing, Thanks !

**Comment by fabriziopandini** [comment]
/lifecycle frozen
The CAPI e2e frameworks now support exporting logs from machines before deletion, but this requires to provide a log collector for CAPV.
This is an example from CAPZ https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/976
