### ISSUE TITLE
Getting started guide for v1alpha3

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#745]
/kind feature

**Describe the solution you'd like**

We need an updated getting started guide

**Anything else you would like to add:**

There are differences with clusterctl that need to be explained, like the original cluster creation part, which v1alpha2 did *for* you.

cc @yastij @fabriziopandini

**Comment by fabriziopandini** [comment]
rif getting started guide in cluster API book for clusterctl https://master.cluster-api.sigs.k8s.io/clusterctl/overview.html
Not sure if this is going to merge with https://master.cluster-api.sigs.k8s.io/user/quick-start.html or not

**Comment by yastij** [comment]
closing this as the docs are you now relying on v1alpha3
