### ISSUE TITLE
Default credentials for pre-built images

### ISSUE THREAD

**Issue by chipzoller** [kubernetes-sigs/cluster-api-provider-vsphere#755]
I don't see anywhere where the default credentials are published for the pre-built machine images in OVA format. Is this written some place?

**Comment by yastij** [comment]
@codenrhoden - IIRC for AMIs we're disabling login/password, I guess we are doing the same for OVAs

**Comment by codenrhoden** [comment]
@yastij Correct, there are no default credentials. An account/user/credentials has to be configured via cloud-init.

There are a couple of _sample_ scripts of how to do this at https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi/hack. Namely the `govc-cloudinit` script for talking to vSphere, or the `post-create-config` script if playing around with Fusion or Workstation.

Obviously those aren't necessary if deploying the image with CAPV. :)

**Comment by MnrGreg** [comment]
It would be interesting to see how far one could get nowadays, without having to set credentials within the OS. If one treats the OS as a stripped down, immutable, Kubernetes appliance, is `cluster-admin` level authentication not sufficient? In our test environments we’re not adding any accounts and have gone so far as to disable SSH through `preKubeadmCommands`.

@codenrhoden there could be an argument to disable SSH by default in `Image-Builder` and have those that need it, explicitly turn it on. Photon Minimal is already very small. We're aiming to get rid of all OS agents and only rollout new OVA versions when there is a kernel patch and/or kubernetes/containerd updates.

For the odd troubleshooting one can use kubectl with `cluster-admin` role to execute tools such as [node-shell](https://github.com/kvaps/kubectl-node-shell), [node-restart](https://github.com/MnrGreg/kubectl-node-restart) and even [trace](https://github.com/iovisor/kubectl-trace) within the root namespace. Also, the benefit of CAPV is that it’s often quicker to evict and blow away the machine, than it is to troubleshoot.

I would be interested to hear what use-cases do still require local accounts and remote access outside of Kubernetes APIs. @chipzoller what was your requirement here?

**Comment by chipzoller** [comment]
Sorry for late reply. Use case here is to troubleshoot cloud-init scripts to see what payload is being passed as well as for other bring-up troubleshooting purposes where the logs on the K8s management cluster side are insufficient.

**Comment by chipzoller** [comment]
See also issue https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/854

**Comment by chipzoller** [comment]
Disregard. SSH key auth with `capv` username does work at this time.
