### ISSUE TITLE
Fail to assign static ipv4 address to centos

### ISSUE THREAD

**Issue by luniHw** [kubernetes-sigs/cluster-api-provider-vsphere#756]
/kind bug

**What steps did you take and what happened:**
Fail to create Centos k8s cluster with static ip, static ip is not assigned to virtual machine.

**What did you expect to happen:**
successfully create centos k8s cluster with static ipv4 address

**Anything else you would like to add:**
Check the cluster vm, find that id0 network file is created, which shows that the value of dhcp is yes, no static ipv4 address info.
Additionally, Photon template has the same issue.

**Environment:**
- Cluster-api-provider-vsphere version: 
   capv 0.4.2
- Kubernetes version: (use `kubectl version`): 
   v1.15.6
- OS 
   http://storage.googleapis.com/capv-images/release/v1.15.6/centos-7-kube-v1.15.6.ova

**Comment by MnrGreg** [comment]
@luniHw 0.5.5 released with fix https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/707

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/releases/tag/v0.5.5

**Comment by yastij** [comment]
closing since this was fixed in v0.5.5
