### ISSUE TITLE
Support standalone ESXi server when deploying a cluster

### ISSUE THREAD

**Issue by frapposelli** [kubernetes-sigs/cluster-api-provider-vsphere#76]
Right now the only supported endpoint to deploy a cluster is vCenter, deployment should be supported even on standalone ESXi servers.

**Comment by moshloop** [comment]
Duplicate of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/177

**Comment by frapposelli** [comment]
This was implemented with #264 
/close
