### ISSUE TITLE
capv controller crashes with invalid memory warning

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#779]
/kind bug

**What steps did you take and what happened:**
Im deploying CAPV to a cluster to deploy another cluster and capv ends up in a crashloopbackoff

**What did you expect to happen:**
CAPV doesnt crash and starts deployment of new vms

**Environment:**

- Cluster-api-provider-vsphere version: 0.5.5
- Kubernetes version: (use `kubectl version`): 1.16.3
- OS (e.g. from `/etc/os-release`): ubuntu ova fom capv

[crashdump-26.02.2020.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4256730/crashdump-26.02.2020.log)
[provider-components.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4256732/provider-components.txt)

**Comment by yastij** [comment]
@MaxRink - can you attach the resources used to create your cluster ?

**Comment by MaxRink** [comment]
Sure

[cluster.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4256764/cluster.txt)
[controlplane.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4256765/controlplane.txt)

**Comment by yastij** [comment]
adding `awaiting-more-evidence` as we'll need resources from the apiserver using `kubectl get`

**Comment by MaxRink** [comment]
here are all the resources related capi from when i could reproduce it.
[describe.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4257467/describe.txt)
[get.txt](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4257468/get.txt)

**Comment by yastij** [comment]
closing this, If someone sees this back, please open an issue and link this
