### ISSUE TITLE
The name of vm contains  numbers

### ISSUE THREAD

**Issue by luniHw** [kubernetes-sigs/cluster-api-provider-vsphere#790]
/kind bug

**What steps did you take and what happened:**
Use capv 0.5.4 to create vm, the name of vm is work-node-2-6fc4cbb677-vgthz, not work-node-2

**What did you expect to happen:**
Hope the vm name is completely customized, not with internal stuff.
At present, in DHCP scenario, get vm's ip by vm's name,  need consider how to match the vm name.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
   v0.5.4

**Comment by yastij** [comment]
This is expected. worker nodes are generated from machineSets, we need to append an uid to ensure uniqueness.

**Comment by rhockenbury** [comment]
Somewhat related -https://github.com/kubernetes-sigs/cluster-api/issues/2217

**Comment by luniHw** [comment]
> This is expected. worker nodes are generated from machineSets, we need to append an uid to ensure uniqueness.

I see it is userful in internal,  can we build the relation rule between vm name and uuid? not directly add uuid in the end of name
