### ISSUE TITLE
Unable to create VsphereCluster without loadBalancerRef

### ISSUE THREAD

**Issue by sedefsavas** [kubernetes-sigs/cluster-api-provider-vsphere#794]
/kind bug

**What steps did you take and what happened:**
Applied this [yaml](https://gist.github.com/sedefsavas/653d05b7191f4ed7d17f3a0a73e153a3) to a bootstrap kind cluster. Only created Cluster, VsphereCluster, VSphereMachineTemplate, and KubeadmControlPlane. Getting this error:

`"msg"="Reconciler error" "error"="unexpected error while reconciling control plane endpoint for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster default/mgmt-cluster: unable to determine control plane endpoint for infrastructure.cluster.x-k8s.io/v1alpha3 `

**What did you expect to happen:**
I expected it to create a control-plane machine on vsphere.

**Environment:**

- Cluster-api-provider-vsphere version: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/a56e9b5b78d5139b59b6708bd039b1c714f6404a

**Comment by yastij** [comment]
@sedefsavas - having an `HAProxyLoadBalancer` and a `LoadBalancerRef` is mandatory If you want to use `kubeadmControlPlane`

**Comment by yastij** [comment]
closing this, as it's behaving as expected
