### ISSUE TITLE
Release management parity with CAPA

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#795]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Adopt image promoter and release notes process as is done for CAPA, to make releases easier.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by sbueringer** [comment]
Let's close this in favor of #2051

(I wanted to provide more context in the issue description)
