### ISSUE TITLE
kubeadmcontrolplane without loadbalancer

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#796]
/kind bug

Reported via Slack by @sedefsavas 

When I don’t provide loadBalancerRef in VSphereCluster, my management cluster does not come up. Keep getting this error: unable to determine control plane endpoint for infrastructure.cluster.x-k8s.io/v1alpha3, Kind=VSphereCluster default/sedef-cluster"

/assign

- Cluster-api-provider-vsphere version: 0.6.0-rc.1
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
@sedefsavas - were you using `kubeadmControlPlane` ?

**Comment by yastij** [comment]
closing this as a dup of https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/794
