### ISSUE TITLE
kubeadm-controlplane upgrade does not delete old control plane pods

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#797]
/kind bug

reported on slack by @sedefsavas 

**What steps did you take and what happened:**
After triggering kubeadm-controlplane upgrade, I see some errors. Is this a supported workflow: I only changed version in KubeadmControlPlane but not the VSphereMachineTemplate. It actually creates another machine and starts controlplane, but it does not delete old control plane pods.

**Environment:**

- Cluster-api-provider-vsphere version: 0.6.0-rc.1
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
@sedefsavas - I don't think it's supported to use the same `VSphereMachineTemplate`. Can you try using a new one ? (the old one is needed for existing nodes)
