### ISSUE TITLE
Predefined Mac-Adresses for MachineDeployments

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#799]
/kind feature

**Describe the solution you'd like**
In some of our environments we need predefined Mac-Adresses for DHCP to work.
For the controlplane this currently works fine, as i can just populate the MacAddr-Filed in the VSphereMachine with the "correct" Mac. 
However, for MachineDeployments and VSphereMachineTemplates this currently doesnt work, as i cant preselect a mac there.
Thus i would propose a feature where i can add a predefined Range of Mac-Adresses that get used by CAPV when creating the actual Machines from the VSphereMachineTemplate.

**Comment by detiber** [comment]
Unfortunately, this approach will not work with the KubeadmControlPlane introduced in v1alpha3, it will behave a bit more like MachineDeployments in that a template is used for stamping out the Machines that comprise the control plane.

**Comment by yastij** [comment]
@detiber - we might want some sort of IPAM when you want to use a pre-defined subnet for machines

**Comment by detiber** [comment]
> @detiber - we might want some sort of IPAM when you want to use a pre-defined subnet for machines

+1, I think IPAM is probably a better approach here, since it is likely to work in a wider range of environments

**Comment by ncdc** [comment]
#728 is a feature request for an out-of-band static IP mechanism, and it's being implemented in #957. This is external IPAM integration, but not specifically MAC addresses. Would that work for you @MaxRink (you'd have to find/implement an IPAM controller)?

**Comment by randomvariable** [comment]
/close

I think this is obsoleted by the IPAM provider.

@MaxRink , reopen if you think you still need this.
