### ISSUE TITLE
Calico Manifest assumes Service IP range

### ISSUE THREAD

**Issue by roberthbailey** [kubernetes-sigs/cluster-api-provider-vsphere#8]
_From @krousey on June 11, 2018 16:57_

A Calico manifest has a hard-coded service IP that makes an assumption that it falls within the cluster's service cidr. This assumption is made https://github.com/kubernetes-sigs/cluster-api/blob/7fdecc5cc4b4174ab5c540a027fcfccc7183f66f/cloud/vsphere/templates.go#L372 and https://github.com/kubernetes-sigs/cluster-api/blob/7fdecc5cc4b4174ab5c540a027fcfccc7183f66f/cloud/vsphere/templates.go#L492

This needs to be an address that falls withing the cluster's [Service CIDR](https://github.com/kubernetes-sigs/cluster-api/blob/7fdecc5cc4b4174ab5c540a027fcfccc7183f66f/cloud/vsphere/templates.go#L271) because it can be changed by the end-user [here](https://github.com/kubernetes-sigs/cluster-api/blob/7fdecc5cc4b4174ab5c540a027fcfccc7183f66f/clusterctl/examples/vsphere/cluster.yaml.template#L8)

/kind cluster-api-vsphere
/cc @karan 

_Copied from original issue: kubernetes-sigs/cluster-api#324_

**Comment by roberthbailey** [comment]
_From @karan on June 11, 2018 16:59_

/assign @satyasm

**Comment by roberthbailey** [comment]
_From @k8s-ci-robot on June 11, 2018 16:59_

@karan: GitHub didn't allow me to assign the following users: satyasm.

Note that only [kubernetes-sigs members](https://github.com/orgs/kubernetes-sigs/people) and repo collaborators can be assigned.

<details>

In response to [this](https://github.com/kubernetes-sigs/cluster-api/issues/324#issuecomment-396312749):

>/assign @satyasm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by roberthbailey** [comment]
_From @karan on June 11, 2018 16:59_

/cc @cadmuxe @satyasm

**Comment by roberthbailey** [comment]
_From @cadmuxe on June 11, 2018 18:28_

Thanks, I will create a patch.

**Comment by roberthbailey** [comment]
@sflxn - feel free to close if you aren't going to fix, but since this was a vsphere specific issue I moved it out of the cluster-api repo.

**Comment by sflxn** [comment]
We're currently using weave.  However, I am keeping this issue around in case users want to use calico in the future.
