### ISSUE TITLE
Deleting a VM from a cluster ends up in a continual Loop and fails to recreate the VM

### ISSUE THREAD

**Issue by kacole2** [kubernetes-sigs/cluster-api-provider-vsphere#805]
/kind bug

**What steps did you take and what happened:**
When a VM is deleted from vCenter, CAPI/CAPV should clone a new VM from template and add it back to the cluster to account for the VM that was removed from the cluster. Instead, it ends up in a continual loop unable to create the VM.

Turn Off the VM
![Screen Shot 2020-03-05 at 5 18 29 PM](https://user-images.githubusercontent.com/4482386/76032220-64df7f80-5f07-11ea-9b56-666eb1fb9d80.png)

Delete the VM. 
![Screen Shot 2020-03-05 at 5 18 38 PM](https://user-images.githubusercontent.com/4482386/76032227-6ad56080-5f07-11ea-930b-108f3f9a7071.png)

Wait upwards of 10 minutes for the watch to see the VM is no longer in the vCenter inventory.
CAPI/CAPV will attempt to clone and recreate the VM and add it back to the cluster
The VM fails because there is a continual process trying to recreate the VM and it says there is already one with a duplicate name
![Screen Shot 2020-03-05 at 5 32 23 PM](https://user-images.githubusercontent.com/4482386/76032250-77f24f80-5f07-11ea-84be-6a9a8cc725bd.png)

The only way to get this to stop was I had to completely delete the cluster using the Local Control Plane with `kubectl delete cluster workload-cluster`
![Screen Shot 2020-03-05 at 5 32 30 PM](https://user-images.githubusercontent.com/4482386/76032259-7f195d80-5f07-11ea-9d1e-964d59b6a171.png)

**What did you expect to happen:**
The VM to be cloned and added back to the cluster with no errors.

**Anything else you would like to add:**

**Environment:**

- Cluster-api-provider-vsphere version: v0.3.0-rc.2
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by xgao3** [comment]
I'm running into something similar issue except i can't delete the cluster in question.  cluster stuck in deleting status.  
root@ubuntu:/home/ubuntu# kubectl delete cluster xgao-cluster
cluster.cluster.x-k8s.io "xgao-cluster" deleted

I tried to power down and delete from VC, but VMs stuck in the never ending clone cycle.

<img width="1624" alt="Screen Shot 2020-03-11 at 4 05 36 PM" src="https://user-images.githubusercontent.com/6633018/76459250-37388180-63b2-11ea-832c-df7ef1733495.png">

**Comment by randomvariable** [comment]
The correct behaviour should be to fail the machine completely if it has been deleted from vCenter. There should be a 1:1 correspondance between a machine and its manifestation on the provider, like pods. MachineSets can then replace the machine.

**Comment by randomvariable** [comment]
cc @detiber

**Comment by ncdc** [comment]
Fail the machine, yes. But that doesn't mean delete the machine. You'd still need MachineHealthCheck configured for that.

**Comment by ncdc** [comment]
I am curious about users' expectations with deleted VMs in CAPV. In most/all the other Cluster API providers, if a VM goes missing, we do as you wrote @randomvariable and mark the machine as failed. That, combined with MachineHealthCheck, allows for automated remediation of Machines managed by MachineSets (and MachineDeployments, by extension) (we are still working on automated remediation for KubeadmControlPlane).

While this would be a behavioral change in CAPV, to mark the machine as failed instead of recreating a VM, it would move CAPV to be in line with Cluster API. I am in favor of making this change but do want to give people some time to comment.

**Comment by randomvariable** [comment]
/assign
/lifecycle active

I've speculatively made a start on matching the other providers. Noticed that VSphereVM doesn't have the Failure* fields, so we miss some possible state transitions.
