### ISSUE TITLE
HAProxy image: make datasource and dataplaneapi URLs configurable

### ISSUE THREAD

**Issue by ncdc** [kubernetes-sigs/cluster-api-provider-vsphere#817]
/kind feature

**Describe the solution you'd like**
I'd like the following 2 URLs to be configurable, so I can pull them from a different source (e.g. if air-gapped):

- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/379582ce23584b217af2b319a2af7421b9a9efd6/hack/tools/haproxy/ansible/roles/cloudinit/tasks/main.yml#L20 
- https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/379582ce23584b217af2b319a2af7421b9a9efd6/hack/tools/haproxy/ansible/roles/haproxy/tasks/main.yml#L17

**Comment by yastij** [comment]
fixed by https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/820
