### ISSUE TITLE
Internal Load Balancer for ControlPlane HA (other types)

### ISSUE THREAD

**Issue by moonek** [kubernetes-sigs/cluster-api-provider-vsphere#819]
/kind feature

**Describe the solution you'd like**
I fount it difficult to controlplane HA because the built-in load balancer is not in vsphere.
And I also found some attempts to solve this.
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/705 (a separate LB)
https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/pull/722 (nsx-t LB)

However, a separate LB do not guarantee HA for LB(haproxy vm failure) and need additional resource for this.
And nsx-t LB can only be configured in certain supported environments.

I want a load balancer with no SPOF due to LB failure, no additional resources and no environmental dependencies.

**Anything else you would like to add:**
This is for reference and it's actually the way I'm using it on-prem.
Run `haproxy` and `keepalived` on the controlplane to make internal LB.
It only requires to allocate `vip` that can be routed on all cluster nodes.
The concept architecture is shown below and has been tested for node failure.

![architecture-1](https://user-images.githubusercontent.com/7972724/76390655-21768c80-63b1-11ea-8d78-30d12b80a608.png)
![architecture-2](https://user-images.githubusercontent.com/7972724/76390690-33582f80-63b1-11ea-91e6-43b412256b97.png)

In my on-prem, I wrote static ip manually in `haproxy.cfg` and `keepalived.conf` and then deployed  the `haproxy+keepalived` container with this file mounted as docker. (with --restart=always)
The `haproxy+keepalived` container internally monitors the process for each module.

I install the control planes after installing the architecture described above.

I don't know much about capv, but I think it's possible to automate it using capv.

**Comment by ncdc** [comment]
#965 shows an example for how to use kube-vip with CAPV to get a VIP for all the control plane machines. It removes the HAProxy VM. All traffic for the control plane goes to the VIP, which is bound to a single VM at a time. There is no load balancing in this approach - all requests go to whatever VM has ownership of the VIP. Would that be sufficient for you @moonek?

**Comment by moonek** [comment]
I am very happy with the removal of LB VM resource and SPOF.
The first request is sent to the VM with VIP ownership, but since then it isn't load balancing to each apiserver?

**Comment by dhawal55** [comment]
Once traffic flow to the VIP, can kube-vip redirect it to kubernetes service IP? If so, then kube-proxy will spread it to all apiserver instances.

**Comment by ncdc** [comment]
@dhawal55 I imagine you could configure iptables to do that. I don't think kube-vip does that by default. You could file an issue there if you wanted?
