### ISSUE TITLE
Move e2e to use only KubeadmControlPlane

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#825]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
e2e tests still create control plane instances manually, should switch over to HAProxyLoadbalancer and KCP.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
closing as #922 removed non KCP tests
