### ISSUE TITLE
Use only the types from the v1alpha1 version

### ISSUE THREAD

**Issue by sidharthsurana** [kubernetes-sigs/cluster-api-provider-vsphere#85]
Currently our code uses a mix of "v1alpha1" versioned resource and the release versioned resource present under the parent directory of the "v1alpha1".  Since currently the project is in "v1alpha1" release we should only be using the types from "v1alpha1" release.

Ideally we should remove the duplicate type information currently present under the parent directory  of the "v1alpha1" folder.

**Comment by frapposelli** [comment]
/priority critical-urgent
/assign @sidharthsurana 

@sidharthsurana this is just an initial assignment, feel free to comment or reassign

**Comment by sidharthsurana** [comment]
This issue is fixed after we moved to CRDs
