### ISSUE TITLE
Static IPs in VSphereMachineTemplate not reserved if referenced in KubeadmControlPlane and MachineDeployment

### ISSUE THREAD

**Issue by chipzoller** [kubernetes-sigs/cluster-api-provider-vsphere#857]
***Unknown if bug or feature request.**

**What steps did you take and what happened:**

1. Create a VSphereMachineTemplate resource with multiple static IPs
2. Reference said resource in both a KubeadmControlPlane resource and a MachineDeployment resource.
3. Deploy manifest with, for example, one control plane and one worker.
4. Observe that the first static IP in the list is assigned to both the control plane and worker. (EDIT: *ALL* IPs seem to be assigned to the first machine.)

**What did you expect to happen:**

1. IPs are allocated sequentially starting from the top of the array of strings in order.
2. IP, once allocated for a machine, is marked as reserved.
3. No duplication of IPs happens.
4. Validation occurs prior to API server accepting the resource that sum of replicas referencing the VSphereMachineTemplate does not exceed the number of static IPs defined.

**Anything else you would like to add:**

Re-use of VSphereMachineTemplate with separate requests should perform the same validation that there are enough free static IPs to handle the requested replicas. For any that exceed the number, an error should be delivered to this effect.

**Environment:**

- Cluster-api-provider-vsphere version: 0.6.2
- Kubernetes version: (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T21:03:42Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by chipzoller** [comment]
After studying this a little more, it appears that this object is only designed to be mapped in a 1:1 fashion to either a KubeadmControlPlane or MachineDeployment. It's not a one-to-many "template" of a class of machine. If specifying multiple IPs in the VSphereMachineTemplate, **all** of those IPs get assigned to the VM(s) referenced by it. This consequently makes deploying a cluster with static IPs extremely cumbersome if a VSphereMachineTemplate spec has to be created for each and every VM that gets cloned out.

I feel like I may be missing something in the larger design plan of CAPV and this ability to not use DHCP. Commentary welcome.

**Comment by MnrGreg** [comment]
You're quite right @chipzoller. If using Static IPs, for every machine, one needs a separate single replica MachineDeployment referencing a VSphereMachineTemplate with the static IP definition.

We're in need of an IPAM Controller + Mutating Admission Controller to handle static IP assignment for machines with a MachineDeployment.

https://github.com/kubernetes-sigs/cluster-api/issues/1740
