### ISSUE TITLE
Images specification

### ISSUE THREAD

**Issue by adrianriobo** [kubernetes-sigs/cluster-api-provider-vsphere#872]
/kind feature

**Describe the solution you'd like**
I can not find any documentation regarding to images specification, as you point in the documentation: .*..it is highly recommended to build and use your own custom images*, but I assume there are some requirements regarding the image.

Amazon EKS will include a [project](https://github.com/awslabs/amazon-eks-ami) with Packer scripts to create the images (so they can be inspected).

It would be great to have some specification to try to create a image based on RHEL and even better have any kind of automation scripts like packer to facilitate any kind of image extension .

**Comment by randomvariable** [comment]
Btw @adrianRiobo , whilst we should add the docs here, the relevant packer bits and pieces are in https://github.com/kubernetes-sigs/image-builder for the CAPV images and in https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/tree/master/hack/tools/haproxy for HAProxy
