### ISSUE TITLE
HAProxy server cert generated before time is synced and has wrong validity

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#875]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
If ESXi doesn't have NTP running, HAProxy can boot with the wrong time. Although systemd-timesyncd is active, the time doesn't sync before the serving certificate is generated, and therefore the certificate can have the incorrect validity.

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
HAProxyLoadBalancer should allow NTP configuration
To get this working, systemd-timesyncd will need to be swapped out for ntpd, and then the cloud-init module enabled.

We should also find a way to get ntp to have time synced prior to the certificate generation. @akutz suggests:

1. Verify that ntpd does not WANT cloud-init-final, which is the stage where the runcmd module runs
2. Put a `while ! ntpstat >/dev/null 2>&1; do sleep 1;` done in front of the new-cert command - https://linux.die.net/man/8/ntpstat. The ntpstat program returns a zero exit code only if time is synced.

**Environment:**

- Cluster-api-provider-vsphere version: 0.6.2
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`): Photon 3

**Comment by detiber** [comment]
If systemd-timesyncd is configured, can you leverage `timedatectl status` to determine when time is sync'd prior to generating the certificate rather than looping on ntpstat?

**Comment by randomvariable** [comment]
Yup. Going to be a problem if there's no connectivity to time.google.com.

Going to hold off on this, and instead provide guidance that you must have ESXi time synchronised.

**Comment by akutz** [comment]
> If systemd-timesyncd is configured, can you leverage `timedatectl status` to determine when time is sync'd prior to generating the certificate rather than looping on ntpstat?

Hi @detiber,

I think the point was to *wait* for time-sync. Whether that is with `ntpstat` or `timedatactl status`, both need to be in a loop and serve the same purpose. Not sure there is value in one over the other here. Although at least on CentOS the [`ntpd` package](https://rpmfind.net/linux/RPM/centos/7.7.1908/x86_64/Packages/ntp-4.2.6p5-29.el7.centos.x86_64.html) includes `ntpstat` and not `timedatactl`.

**Comment by randomvariable** [comment]
I.e. it's going to end up being distro specific:
timedatectl for photon
ntpstat where ntpd is available 
whatever the equivalent for chronyd is for centos

**Comment by detiber** [comment]
If I'm not mistaken, `timedatectl` should work for all cases, at least it does on my local Fedora 31 system running `chronyd`:
```sh
> timedatectl status
               Local time: Mon 2020-03-30 10:25:54 EDT
           Universal time: Mon 2020-03-30 14:25:54 UTC
                 RTC time: Mon 2020-03-30 14:25:54
                Time zone: America/New_York (EDT, -0400)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

```

**Comment by randomvariable** [comment]
oh, that's good. me being over-cynical for once.

**Comment by detiber** [comment]
Probably need to also validate on an Ubuntu and Amazon Linux 2 image just to be on the safe side.

**Comment by ncdc** [comment]
We have decided to deprecate HAProxy support because it is a single point of failure (i.e. it's not actually highly available with multiple HAProxy instances), and it's difficult or impossible to upgrade by creating a replacement HAProxy VM (it has to retain the IP address and that isn't a guarantee).

The replacement is to use something like kube-vip - see #965 for details.

/close
