### ISSUE TITLE
Print controller version on startup

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#877]
/kind feature

**Describe the solution you'd like**
Would be great to to see the controller version in the logs, makes debugging issues for end users much simpler.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 0.6.2

**Comment by ncdc** [comment]
Here's what CAPI does:

https://github.com/kubernetes-sigs/cluster-api/blob/60147823dc2131b822125598a73b2ad34e55b050/main.go#L181

The version package: https://github.com/kubernetes-sigs/cluster-api/blob/60147823dc2131b822125598a73b2ad34e55b050/cmd/version/version.go

https://github.com/kubernetes-sigs/cluster-api/blob/60147823dc2131b822125598a73b2ad34e55b050/Makefile#L105

https://github.com/kubernetes-sigs/cluster-api/blob/60147823dc2131b822125598a73b2ad34e55b050/Makefile#L135

https://github.com/kubernetes-sigs/cluster-api/blob/60147823dc2131b822125598a73b2ad34e55b050/Makefile#L340
