### ISSUE TITLE
Move the HAProxy build tooling over to image-builder project

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/cluster-api-provider-vsphere#884]
/kind feature

**Describe the solution you'd like**
With v1alpha3, CAPV started requiring a load-balancer image.  This repo contains code/tooling to build an OVA using the HAProxy dataplane API. The code to build this image was strongly modeled after the sigs.k8s.io/image-builder project. However, improves made to `image-builder` were not reflected here.

I propose that the HAProxy image be built using `image-builder` instead for consistency. This is development work I volunteer to take on.

The argument could be made that since the OVA is vSphere specific, it belongs here and not in `image-builder`. My counter argument is that `image-builder` has the express charter of building **images** for CAPI on multiple cloud providers. If vSphere needs an HAProxy OVA, then vSphere needs it and it should be the `image-builder` that is responsible for building **all** images necessary to deploy a cluster with CAPV.

**Anything else you would like to add:**
none

**Environment:**

- Cluster-api-provider-vsphere version: v0.6.3

**Comment by randomvariable** [comment]
No debate here if image-builder wants to own it. Would dedupe work here significantly.

**Comment by yastij** [comment]
strong +1

**Comment by codenrhoden** [comment]
This topic was discussed in yesterday's image-builder office hours and there were no objections, so I will work on this.

/assign

**Comment by frapposelli** [comment]
+1 on deduplicating, since this is specific to CAPV, some guardrails should be implemented to make sure changes are driven by CAPV owners (separate OWNERS file maybe?)
