### ISSUE TITLE
Environment variables override the config file in getting started guide

### ISSUE THREAD

**Issue by akutz** [kubernetes-sigs/cluster-api-provider-vsphere#888]
/kind bug

**What steps did you take and what happened:**
When following [the getting started guide](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/getting_started.md#configuring-and-installing-cluster-api-provider-vsphere-in-a-management-cluster), I created the file `$HOME/.cluster-api/clusterctl.yaml` with the appropriate configuration values. However, when I ran `clusterctl init --infrastructure vsphere`, the VMs never showed up.

It turns out the VMs were created on another vCenter -- the system defined by the environment variables of the same name.

I am not sure if this is:

* by design
* a code bug
* a doc error

**What did you expect to happen:**
For `clusterctl` to use the configuration properties from the file `$HOME/.cluster-api/clusterctl.yaml` if set and not the equivalent environment variables.

**Anything else you would like to add:**
Nope

**Environment:**

- Cluster-api-provider-vsphere version: 0.6.3 w CAPI v0.3.4
- Kubernetes version: (use `kubectl version`): 1.17.3
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by randomvariable** [comment]
Doc error. It's a combination of clusterctl and how viper works that means that environment variables take precedence.
