### ISSUE TITLE
setup periodic job to run e2e test

### ISSUE THREAD

**Issue by figo** [kubernetes-sigs/cluster-api-provider-vsphere#90]
this job is run at post-commit, publish test result to testgrid

**Comment by sflxn** [comment]
Set this up in prow, once we have moved to prow.  Update test-grid with results.

**Comment by figo** [comment]
@frapposelli  just updated the comment to remove the travis-ci part, the issue still valid, we will setup period job for expanded coverage.

**Comment by figo** [comment]
the periodic job been configured, and we need a fix on test-infra: https://github.com/kubernetes/test-infra/pull/11527

**Comment by sflxn** [comment]
Pushing this to next milestone as there is uncertainty around whether the test-infra issue will be resolved in time and whether @figo will have the bandwidth to work on it.
