### ISSUE TITLE
Move e2e tests to clusterctl framework

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-vsphere#903]
With the introduction of the new clusterctl test framework, we should draw a plan of action and publish a gap-analysis of the current e2e tests CAPV has today, and how we can port them to the new framework.

/kind cleanup
/assign @sedefsavas 
/cc @fabriziopandini @yastij

**Comment by yastij** [comment]
@vincepri - that's on my plate of things to do this week.

**Comment by sedefsavas** [comment]
This CAPV config is working with the new e2e, may be useful: https://github.com/kubernetes-sigs/cluster-api/pull/2950

**Comment by fabriziopandini** [comment]
happy to help if required!
