### ISSUE TITLE
Replace LDAP server in test infrastructure with AWS Simple Active Directory

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#914]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Intermittently, the LDAP server that provides authentication for the vSphere infrastructure for e2e tests falls over.

We should replace it with AWS Simple Directory so we don't have to be LDAP server admins, because whomst wants to be an LDAP administrator?

AWS Simple AD is a managed Samba 4 instance, so should work fine.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
fyi @akutz

**Comment by akutz** [comment]
Agree, but this should be closed and tracked internally.

**Comment by akutz** [comment]
> We should replace it with AWS Simple Directory so we don't have to be LDAP server admins, because whomst wants to be an LDAP administrator?

Let's be positive. LDAP is fine, it's an issue of time and resources.
