### ISSUE TITLE
Node hostname gets reset during reboot

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#920]
/kind bug

**What steps did you take and what happened:**
We have a few nodes that dont survice a reboot without manual intervention.
The Issue is, that the Hostname gets reset to localhost during boot, altough /etc/hostname was correct before reboot.
Because of that i need to set the hostname manually aftewr reboot via ssh and restart kubelet, so the node becomes ready again.
The Node name reset happens within cloud-init:
https://pastebin.com/wMDU0eVr

**What did you expect to happen:**
Hostnames persist reboots

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
@MaxRink - are you still seeing this issue ?

**Comment by MaxRink** [comment]
no, looking back to this i think this was related to the way how we initially botstrapped cni via shellscripts and files, which broke some parts of cloud-init
