### ISSUE TITLE
VMs that are long in "Provisioning" state get stuck in that state even after all provisioning is completed

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#942]
/kind bug

**What steps did you take and what happened:**

I did some debugging around running the ccm externally nad had a cluster which master nodes were stuck in provisioning within the master cluster.
Once CCM ran those never got ready, altough the cluster being ready and new nodes getting joined just fine.

**What did you expect to happen:**
Nodes become "provisioned"

**Anything else you would like to add:**
Logs and Objects are attached
[external-ccm-timeouts.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4814383/external-ccm-timeouts.log)
[external-ccm-timeouts-capi.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4814384/external-ccm-timeouts-capi.log)
[external-ccm-timeouts-capv.log](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/files/4814385/external-ccm-timeouts-capv.log)
**Environment:**

- Cluster-api-provider-vsphere version: latest
- Kubernetes version: (use `kubectl version`): 1.18.2

- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
Probably worth exploring a limit for exp. backoff

**Comment by ubhide** [comment]
/reopen

This is happening for me with v1.0.2, using k8s 1.20.1

The nodes come up, everything looks good, but describing the Machines shows that they are stuck in `Provisioned`

```
    Last Transition Time:  2021-12-21T20:00:59Z
    Reason:                NodeProvisioning
    Severity:              Warning
    Status:                False
    Type:                  NodeHealthy
```

`clusterctl describe` also shows that they are stuck in `NodeProvisioning`
