### ISSUE TITLE
CAPV crashes if govmomi cant read uuid

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#944]
/kind bug

**What steps did you take and what happened:**
If govmomi cant read the uuid of an VM CAPV crashes because the error never gets caught.

**What did you expect to happen:**
CAPV doesnt crash and cathes the error

**Anything else you would like to add:**
Slack-thread regarding that issue: https://app.slack.com/client/T09NY5SBT/CKFGK3SSD/thread/CKFGK3SSD-1593457166.343000
Log:
https://gist.github.com/MaxRink/239e4fde6894ff102913d550647a3c93

**Environment:**

- Cluster-api-provider-vsphere version: 0.6.5
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
ref https://github.com/vmware/govmomi/blob/ffbd963c889d82c914cc2fc44524a2cf56a69c04/object/virtual_machine.go#L858-L859

**Comment by yastij** [comment]
this specifically comes from govmomi [here](https://github.com/vmware/govmomi/blob/1ddd1feea83c0d554b1434eec37c5307a8183fea/object/virtual_machine.go#L858-L859)
