### ISSUE TITLE
Change default branch to "main"

### ISSUE THREAD

**Issue by vincepri** [kubernetes-sigs/cluster-api-provider-vsphere#949]
Once the community agrees on the naming, we need to change our default development branch to `main`, and check that any tools or references to it are changed as well.

This includes the container image tag used in development.

/kind cleanup
/wg naming
/milestone Next

**Comment by randomvariable** [comment]
/milestone v0.8.0

This work should be ready to go. There are docs for the process at https://www.kubernetes.dev/resources/rename/

**Comment by srm09** [comment]
We are waiting on the outstanding PRs against the current `default` branch to get merged before picking this up.

**Comment by aartij17** [comment]
More details here - https://www.kubernetes.dev/resources/rename/

**Comment by srm09** [comment]
@aartij17 It might help to create a list of tasks necessary to make the switch seamlessly.

**Comment by aartij17** [comment]
Sure @srm09, I will add a list of the tasks!

**Comment by aartij17** [comment]
Tasks to be completed - 

Pre-Rename, non-disruptive tasks:
- [ ] Prep the Prow jobs to run against `main` branch
PR Raised: https://github.com/kubernetes/test-infra/pull/25463 

Disruptive tasks:
- [ ] For periodic prowjobs, or any prowjob that mentions the master branch in base_ref, update them to the main branch. Ensure that these changes happen in lock-step with the branch rename (jobs triggered in between landing these changes and renaming the branch will fail).
- [ ] If a prowjob mentions master in its name, rename the job to not include the branch name, e.g. pull-repo-verify-master -> pull-repo-verify. [status-reconciler](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/status-reconciler) should automatically migrate PR status contexts to the new job name, and retrigger accordingly, but we have anecdotally found it sometimes misses changes.
- [ ] If a prowjob calls scripts or code in your repo that explicitly reference master, update all references to use main, or auto-detect the remote branch
- [ ] Once all non-disruptive tasks have been completed and disruptive tasks have been identified, assign the GitHub Management team ([@kubernetes/owners](https://github.com/orgs/kubernetes/teams/owners)) for approval.
- [ ] Rename the default branch from master to main using the GitHub UI by following the [official instructions](https://github.com/github/renaming#renaming-existing-branches).
