### ISSUE TITLE
tkg during cluster creation pass cluster name, alternative vCenter.

### ISSUE THREAD

**Issue by spyroot** [kubernetes-sigs/cluster-api-provider-vsphere#951]
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

tkg cli to pass a cluster name during creation process or even better entire data center details.
For example you pass detail for another vCenter, so manager cluster de-coupled from vCenter.

Note for template VM,  we can always use vCenter library feature.  Where vCenter b subscribe to library A
so images in sync.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

it not an issue but generally you want to be able to indicate different clusters / data-center name and vCenters.
Imagine vCenter dedicated only for Mgmt from where you bootstrap all other clusters.

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by yastij** [comment]
closing this as it's not specific to CAPV, but rather to a distro using CAPV
