### ISSUE TITLE
Support for UEFI boot OVAs

### ISSUE THREAD

**Issue by moonek** [kubernetes-sigs/cluster-api-provider-vsphere#954]
/kind feature

**Describe the solution you'd like**
I may have gone ahead.
I believe GPU nodes will be supported in cluster api someday.
But I want to manually configure the GPU pass-through to the node created via the current state of CAPV.
GPU pass-through is only supported in UEFI boot mode.
All current CAPV OVAs are considered BIOS boot mode.
Can someone make a UEFI boot mode OVA?

**Comment by yastij** [comment]
closing as dupe of #968 which has context and milestone
