### ISSUE TITLE
Support Storage Pools not only datastores

### ISSUE THREAD

**Issue by MaxRink** [kubernetes-sigs/cluster-api-provider-vsphere#956]
/kind feature

**Describe the solution you'd like**
vSphere has Storage Pools with Storage DRS to cluster datastores.
Currently CAPV cant consume those, but as StorageDRS automates VM Disk placement this is desired.
Edit: I think the correct name for them is Storage Cluster, not Storage Pool
**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by MaxRink** [comment]
We have had a small discussion here: https://kubernetes.slack.com/archives/CKFGK3SSD/p1594115208399600?thread_ts=1594113406.395200&cid=CKFGK3SSD

**Comment by yastij** [comment]
closing since this comes with storage policy support
