### ISSUE TITLE
Review presubmit jobs against files and directories

### ISSUE THREAD

**Issue by randomvariable** [kubernetes-sigs/cluster-api-provider-vsphere#967]
Some files and directories in this repo don't trigger the correct presubmits.

**Comment by ncdc** [comment]
CAPV’s Prow config uses run_if_changed on a bunch of jobs. We do not use this anywhere for CAPI or CAPA. I’d recommend removing this from CAPV

**Comment by ncdc** [comment]
Or we need to add go.mod/go.sum to the right places
