### ISSUE TITLE
Abillity to run conformance tests with different CNIs

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/cluster-api-provider-vsphere#969]
/kind feature

**Describe the solution you'd like**

Analogous to https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/1745 .  If we can start pumping out brioader CNI test coverage.

**Anything else you would like to add:**

Specifically probably start with adding antrea to the test matrix

**Environment:**

- Cluster-api-provider-vsphere version: all
- Kubernetes version: (use `kubectl version`): all
- OS (e.g. from `/etc/os-release`):

**Comment by randomvariable** [comment]
Depends on https://github.com/kubernetes-sigs/cluster-api/pull/3593
