### ISSUE TITLE
Config parameters should be linted/sanity checked prior to deployment

### ISSUE THREAD

**Issue by mylesagray** [kubernetes-sigs/cluster-api-provider-vsphere#984]
/kind bug

**What steps did you take and what happened:**
Following the docs to install a new cluster with v0.6.6 - I messed up and put in the wrong folder as the target folder, installation hangs indefinitely with no indication of an error - looking at the logs however, an error is seen:

```
"msg"="Reconciler error" "error"="failed to reconcile VM: unable to get folder for default/vsphere-quickstart-lb: folder 'Testing/k8s' not found" "controller"="vspherevm" "name"="vsphere-quickstart-lb" "namespace"="default"
```

We should either test the vars or expose the error messages up to the CRD objects, as it's not obvious why the operation was hanging.

**What did you expect to happen:**

An error to be generated so I could take action on my config.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version:  v0.6.6
- Kubernetes version: (use `kubectl version`):  1.18.2
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

/assign @yastij

**Comment by ncdc** [comment]
@yastij would you have interest in trying to do this in a validating webhook, i.e. a live lookup against vCenter to validate things like this?

**Comment by yastij** [comment]
closing this, as we have now conditions that surface these issues
