### ISSUE TITLE
docs - Getting Started Page

### ISSUE THREAD

**Issue by mkbhanda** [kubernetes-sigs/cluster-api-provider-vsphere#990]
/kind feature

Newbie questions/comments!! 

**Describe the solution you'd like**
1) What is PV? as in "To use PVs, "  persistent volumes?

2) govc -- need to tell folks what it is and how to download
https://starkandwayne.com/blog/newly-discovered-tool-vsphere-cli-govc/

3) typo s/provisiong/provisioning

4) would be more appropriate to call the cluster "managed cluster" versus "management cluster"
The latter implies the cluster will manage something else
Am I correct in understanding we need a vCenter cluster on which we deploy a Kubernetes cluster using the Cluster API?

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api-provider-vsphere version: 
- Kubernetes version: (use `kubectl version`): 
- OS (e.g. from `/etc/os-release`):

**Comment by fabriziopandini** [comment]
/assign
/lifecycle active

going to address everything except 4, because "management cluster" is the right term (it is the place where you can manage "workload clusters).
