### ISSUE TITLE
Cluster with custom YAML fails to create cluster

### ISSUE THREAD

**Issue by spiegela** [kubernetes-sigs/cluster-api-provider-vsphere#995]
/kind bug

**What steps did you take and what happened:**

- Create new 0.7.0 management cluster with kind and `clusterctl init --infrastructure vsphere`
- For each version (1.17.5 and 1.18.2):
    - Create cluster.yaml with `clusterctl config cluster`
    - Patch cluster and machine templates (patch script attached)
    - apply cluster to management cluster

The 1.18.2 cluster was created normally within about 10 minutes.
The 1.17.5 cluster created the first controlplane node.  The local boot messages of this node showed this error:

```
[FAILED] Failed to start Execute cloud user/final scripts.
```

No subsequent controlplane nodes were created after running for 20 minutes.

**What did you expect to happen:**

The cluster creation should have proceeded with each controlplane and MD host created.

**Anything else you would like to add:**

As mentioned above, I do customize the machine  template, and cluster (just the pod CIDR), so it is possible that the 1.17.5 image doesn't work with my customization. I also install the CAPV environment via Concourse-CI addressing a Kind cluster.  While the Kind cluster is persistent, the container in which I run `kubectl apply -f` is ephemeral -- not the same node.  I'm not sure if that would have any bearing

The logs will show both `jonquil` and `gamboge` clusters.  `gamboge` is `v1.17.5` and `jonquil` is `1.18.2`

https://gist.github.com/spiegela/7a318ccd685f6d23e0ffcdf3f6e4ef47

**Environment:**

- Cluster-api-provider-vsphere version: 0.7.0
- Kubernetes version: (use `kubectl version`): 1.17.5
- OS (e.g. from `/etc/os-release`): ubuntu-1804

Also, vCenter 7.0 with vSphere 6.7u1.

**Comment by spiegela** [comment]
This appears to be an intermittent issue.  I just ran the CI job again with the same cluster and configuration, and it ran to completion in about 10 minutes.  That failed boot message did not appear this time.

**Comment by randomvariable** [comment]
Worth getting the results of `/var/log/cloud-init-output.log`

Also, for your kubeadmcontrolplane and kubeadmconfigtemplates, particularly in a vSphere environment, you will want to use `UseExperimentalRetryJoin: true`, as this makes kubeadm retries much more consistent.

**Comment by spiegela** [comment]
I've updated the gist with the cloud-init and cloud-init-output logs (the latter was in there, but mis-named).  I'll add a patch to enable `useExperiementalRetryJoin`.  I've re-run the cluster creation a couple times since yesterday, and the issue didn't resurface, so if you don't see anything obvious in the logs, its OK with me to close.

**Comment by randomvariable** [comment]
Can't see anything obvious.
I'll close it for now, but feel free to reopen if you encounter it again.
/close
