### ISSUE TITLE
CAPV OVAs at HW image 15?

### ISSUE THREAD

**Issue by codenrhoden** [kubernetes-sigs/cluster-api-provider-vsphere#998]
/kind bug

**What steps did you take and what happened:**
Before we make the change in `image-builder`, I wanted to confirm something first. CAPV always deploys vSphere CSI, correct? If it does, the documented required version for vSphere CSI is [hardware version 15](https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/prerequisites.html), but `image-builder` is currently setting the hardware version to 13.

Are there any use cases where we don't want the hardware image version to be 15? I can't think of any if CAPV is *always* deploying vSphere CSI. I can picture scenarios were vSphere CSI isn't used (say, deploying a cluster on vSphere but using another storage solution), but in that case, I think it is likely that there will be some customization happening at both the CAPV manifest layer, and potentially the OVAs coming from `image-builder`. The hardware version is easily cusomizable in `image-builder`, but the default behavior should most likely support the documented needs of CNS, which is deployed by default with CAPV. Any objections around this?

**Comment by randomvariable** [comment]
Version 15 would mandate ESXi 6.7 U2 minimum, as per https://kb.vmware.com/s/article/1003746 where as version 13 allows ESXi 6.5 to be used. We don't have a formal support statement for CAPV so may need to be discussed with a wider audience.

**Comment by ncdc** [comment]
I don't know what's been discussed or declared previously with the CAPV community, but the only thing I've ever heard is that you need 6.7u3 minimum, and I think that's for CSI (?). Let's wait for @yastij to chime in tomorrow.

**Comment by yastij** [comment]
@mylesagray - did introduce the requirement of a HW version 13 for CSI[here](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/commit/78ba2a6fcd17b137bfda1766537217b8b1aecb60) but this probably changed given the docs @codenrhoden is pointing to. 

Also @ncdc is correct, officially the project only support 6.7u3 and above.

**Comment by randomvariable** [comment]
Just a note that this isn't formally documented, so as a follow up, this needs to be made clear somewhere in the repo.

**Comment by yastij** [comment]
we dropped 6.5 a while ago, this should have been documented somewhere. Let's use this issue to track the changes/docs to raise the bar to >=6.7u3

**Comment by mylesagray** [comment]
Confirmed that @SandeepPissay has said internally HW15 is required for CSI, as was noticed by Robbie Jerrom when he was testing it.

The doc update was based on early internal research - that has since been updated to HW15.

**Comment by codenrhoden** [comment]
image-builder [set this to 13](https://github.com/kubernetes-sigs/image-builder/pull/60) back when it was 6.5 and up, but hasn't been updated since. I figured this was a good opportunity to update everything across the board if that was what was needed. And it sounds like it is!

**Comment by codenrhoden** [comment]
> Just a note that this isn't formally documented, so as a follow up, this needs to be made clear somewhere in the repo.

It is mentioned in the [getting started guide](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/docs/getting_started.md) specifically calling out version 13 and needing to upgrade to that if using older images. So that will need to be updated to.

As a side-note, anyone know how to link to a specific line in a markdown file in GitHub? 😆  I've never figured that out since GitHub always renders the markdown when viewing...

**Comment by randomvariable** [comment]
> As a side-note, anyone know how to link to a specific line in a markdown file in GitHub? laughing I've never figured that out since GitHub always renders the markdown when viewing...

Click on the file, and then choose "Show source blob"
![image](https://user-images.githubusercontent.com/1441070/90530089-637bd980-e16c-11ea-95f3-d80c7f4fa704.png)

**Comment by codenrhoden** [comment]
The getting started has this blurb in it:

> To use PersistentVolumes (PV), your cluster needs support for Cloud Native Storage (CNS), which is available in vSphere 6.7 Update 3 and later. CNS relies on a shared datastore, such as VSAN.

So I think this is good now.

/close
